var sparkConfig={gateway:null,servers:null,users:null,config:function(b,c,a,d,e,f){b=b+"/CONF?type="+c+"&action="+a;f&&(b+=f);(c=document.getElementById("gwPwd").value)&&(b+="&gwPwd="+encodeURIComponent(c));hi5.tool.openWebSocket(b,e,d)},formatDate:function(b){if(!b)return"";b=new Date(b);return b.getFullYear()+"-"+(b.getMonth()+1)+"-"+b.getDate()+" "+b.getHours()+":"+b.getMinutes()},parseDate:function(b){var c=b.split(" ");b=c[0].split("-");c=c[1].split(":");if(3!=b.length||2!=c.length)throw"Date format must be yyyy-MM-dd hh:mm";
return new Date(b[0],b[1]-1,b[2],c[0],c[1])},showMessage:function(b){document.getElementById("message").innerHTML=b},checkError:function(b){if(b.error){var c=__svi18n.errorCode["S"+b.name];b.message&&(c+=b.message);setTimeout(function(){alert(c)},0);return!0}return!1},refreshServers:function(){function b(d){d=sparkConfig.servers.getValue(0);sparkConfig.config(sparkConfig.getGatewayAddr(),"servers","remove",a,null,"&id="+d)}function c(a){a=this.getValue(0);sparkConfig.editServer(a)}function a(a){sparkConfig.servers=
a;var e=new hi5.DataTable(a),f=new hi5.DataGrid(document.getElementById("servers.rows"));f.dataTable=e;f.open();document.getElementById("servers.type").value=a.type;document.getElementById("servers.display").checked=a.display;f.onrowclick=function(a){a=a.target;(a=a["data-action"]||a.name)&&e.perform(a)};e.addEvent("beforeremove",b);e.addEvent("onaction",c)}sparkConfig.config(sparkConfig.getGatewayAddr(),"servers","get",a)},refreshUsers:function(){function b(d){d=sparkConfig.users.getValue(0);sparkConfig.config(sparkConfig.getGatewayAddr(),
"users","remove",a,null,"&name="+d)}function c(a){a=this.getValue(0);sparkConfig.editUser(a)}function a(a){sparkConfig.users=a;var e=new hi5.DataTable(a);a=new hi5.DataGrid(document.getElementById("users.rows"));a.dataTable=e;a.open();a.onrowclick=function(a){a=a.target;(a=a["data-action"]||a.name)&&e.perform(a)};e.addEvent("beforeremove",b);e.addEvent("onaction",c)}sparkConfig.config(sparkConfig.getGatewayAddr(),"users","get",a)},refreshSessions:function(){function b(d){d=sparkConfig.sessions.getValue(0);
sparkConfig.config(sparkConfig.getGatewayAddr(),"sessions","remove",a,null,"&id="+d)}function c(a){a=this.getValue(0);var c=this.getValue(9),b="join";switch(c){case "RFB":b="joinvnc";break;case "SSH":b="joinssh";break;case "TELNET":b="jointelnet"}a=location.protocol+"//"+document.getElementById("gateway").value+"/"+b+".html?id="+a;window.open(a)}function a(a){sparkConfig.sessions=a;var e=new hi5.DataTable(a),f=new hi5.DataGrid(document.getElementById("sessions.rows"));e.beforeGetValue=function(a,
d){var c=e.cols[a].name;return"thumbnail"==c?'<img src="'+d+'">':d};f.dataTable=e;f.open();f.onrowclick=function(a){a=a.target;(a=a["data-action"]||a.name)&&e.perform(a)};e.addEvent("beforeremove",b);e.addEvent("onaction",c);f=document.getElementById("sessions.size");f.innerHTML=a.rows.length}sparkConfig.config(sparkConfig.getGatewayAddr(),"sessions","get",a)},updateSymlink:function(){var b=document.getElementById("symlinkAccess"),c=document.getElementById("symlink.id"),a=document.getElementById("symlink.password"),
d=document.getElementById("symlink.server"),e=document.getElementById("gateway").value,c=location.protocol+"//"+e+"/rdpdirect.html?symlink="+c.value+"&gateway="+e;a.value&&(c+="&pwd="+a.value);d.value&&(a=sparkConfig.servers.find(0,d.value))&&a[3]&&(c+="&startProgram=app");b.href=c},refreshSymlinks:function(){function b(d){d=sparkConfig.symlinks.getValue(0);sparkConfig.config(sparkConfig.getGatewayAddr(),"symlinks","remove",a,null,"&id="+d)}function c(a){a=this.getValue(0);sparkConfig.editSymlink(a)}
function a(a){sparkConfig.symlinks=a;var e=new hi5.DataTable(a);a=new hi5.DataGrid(document.getElementById("symlinks.rows"));a.dataTable=e;e.beforeGetValue=function(a,d){var c=e.cols[a].name;return"validFrom"==c||"validTo"==c?hi5.DateUtils.formatDate(d):d};e.beforeSetValue=function(a,d){var c=e.cols[a].name;return"validFrom"==c||"validTo"==c?hi5.DateUtils.parseDate(d).getTime():d};a.onrowclick=function(a){a=a.target;(a=a["data-action"]||a.name)&&e.perform(a)};a.open();e.addEvent("beforeremove",b);
e.addEvent("onaction",c);a=document.getElementById("symlink.id");var f=document.getElementById("symlink.password"),g=document.getElementById("symlink.server");f.onchange=a.onchange=g.onchange=sparkConfig.updateSymlink}sparkConfig.config(sparkConfig.getGatewayAddr(),"symlinks","get",a)},initUI:function(){function b(){function c(){}var b="&sType="+a.value+"&display="+d.checked;sparkConfig.config(sparkConfig.getGatewayAddr(),"servers_h","put",c,null,b)}function c(a){sparkConfig.gateway.prop.webfeed&&
(document.getElementById("servers.add").style.disabled=!0,document.getElementById("users.add").style.disabled=!0);switch(a){case 1:if(sparkConfig.servers)break;sparkConfig.refreshServers();break;case 2:if(sparkConfig.users)break;sparkConfig.refreshUsers();break;case 3:sparkConfig.servers||sparkConfig.refreshServers();if(sparkConfig.symlinks)break;sparkConfig.refreshSymlinks();break;case 4:if(sparkConfig.sessions)break;sparkConfig.refreshSessions()}}var a=document.getElementById("servers.type"),d=
document.getElementById("servers.display");a.onchange=b;d.onchange=b;var e=document.getElementById("conf3");e.addEvent("ontabchange",c);var f=hi5.tool.queryToObj(),e=f.port,g=f.expect;if(e){var f=window.location.host,k=location.protocol;f||(f="localhost");document.getElementById("gateway").value=f;f=k+"//"+f;g&&(g=f+":"+g,document.getElementById("expectAddr").innerHTML=g,document.getElementById("expect").style.display="inline");if("http:"==k&&"80"!=e||"https:"==k&&"443"!=e)f+=":"+e;f="<a href='"+
f+"'>"+f+"</a>";e=document.getElementById("sparkAddr");e.innerHTML=f;document.getElementById("conf1").style.display="block"}else document.getElementById("gateway").value=location.host,document.getElementById("conf0").style.display="block";if(e=document.getElementById("rfxOpt"))e.onchange=function(a){a.target.checked&&(document.getElementById("colorOpt").selectedIndex=3)}},getGatewayAddr:function(){return("http:"==location.protocol?"ws:":"wss:")+"//"+document.getElementById("gateway").value},getAll:function(){function b(c){if(!sparkConfig.checkError(c)){sparkConfig.gateway=
c;c=c.prop;var a,d=document.getElementById("frmGateway").elements,b;for(b in c)if(a=d[b]){var f=a.type,g=c[b];"checkbox"==f?a.checked="true"===g:"file"!=f&&(a.value=g)}document.getElementById("conf3").style.display="block"}}sparkConfig.config(sparkConfig.getGatewayAddr(),"gateway","get",b)},saveGateway:function(){function b(a,c,b){a=a.elements;for(var f=0,g=a.length;f<g;f++){var k=a[f];if(k){var m=k.value;if(""!==m&&!k.readonly){var l=k.type;if("button"!=l&&"submit"!=l&&"file"!=l){var n=k.name;c[n]=
"checkbox"==l?k.checked+"":m}}}}a=document.getElementById("licenseFile").files;0<a.length?hi5.file.readAsArrayBuffer(a[0],function(a){c.licenseFile=hi5.Base64.enc(a);b()}):b()}function c(a){var c;a.error?(c=__svi18n.errorCode["S"+a.name],a.message&&(c+=a.message)):c=__svi18n.info.restart;setTimeout(function(){alert(c)},0)}b(document.getElementById("frmGateway"),sparkConfig.gateway.prop,function(){sparkConfig.config(sparkConfig.getGatewayAddr(),"gateway","put",c,JSON.stringify(sparkConfig.gateway))})},
editServer:function(b,c){function a(a){if(a.id){var b=a.rdp;b||(b={});b.isRDP=!!a.rdp;b.id=a.id;b.displayName=a.displayName;a.server&&(b.server=a.server);a.icon&&(b.icon=a.icon);if(b.mapDisk&&b.disks){for(var g=b.disks,k,p=Math.min(3,g.length),h=0;h<p;h++)b["dosName"+h]=g[h].dosName,b["devicePath"+h]=g[h].devicePath,k=g[h].actions,b["actRedirect"+h]=0!=(k&1),b["actDownload"+h]=0!=(k&2),b["actUpload"+h]=0!=(k&4);delete b.disks}if(a.vnc){g=a.vnc;b["vnc.port"]="";b["vnc.password"]="";b.UseCopyRect=!1;
b.share=!1;b["vnc.mapClipboard"]=!1;b["vnc.recording"]=0;for(h in g)"port"==h||"password"==h||"mapClipboard"==h||"color"==h||"sessionRecord"==h?b["vnc."+h]=g[h]:b[h]=g[h];b.isVNC=!0}if(a.ssh){g=a.ssh;b["ssh.mapClipboard"]=!1;b["ssh.fontSize"]="";b["ssh.port"]="";b["ssh.username"]="";b["ssh.recording"]=0;for(h in g)b["ssh."+h]=g[h];b.isSSH=!0}if(a.telnet){a=a.telnet;b["telnet.mapClipboard"]=!1;b["telnet.fontSize"]="";b["telnet.port"]="";b["telnet.recording"]=0;for(h in a)b["telnet."+h]=a[h];b.isTELNET=
!0}e=hi5.$("server.id").value;f=hi5.$("server.displayName").value;d.reset();hi5.browser.objToForm(b,d);c||(d._dataAction="put");e&&(hi5.$("server.id").value=e);f&&(hi5.$("server.displayName").value=f)}}var d=document.getElementById("servers.view"),e="",f="";c||d.reset();var g=d.visible?d:new hi5.Lightbox(d);g.onclose=function(){sparkConfig.refreshServers()};sparkConfig.showMessage("");g.visible()||g.show();d._dataAction="post";b&&sparkConfig.config(sparkConfig.getGatewayAddr(),"server","get",a,null,
"&id="+b);var k=hi5.$("server.server");k.hide||new hi5.Select(k);k.beforedropdown=function(){for(var a=k.options,b=sparkConfig.servers,b=b.rows,c=a.length=0,d=b.length;c<d;c++)a[c]=new Option(b[c][1],b[c][0])};k.onchange=function(){var b=k.value;sparkConfig.config(sparkConfig.getGatewayAddr(),"server","get",a,null,"&id="+b)}},initServerList:function(b){b=b.options;var c=sparkConfig.servers;if(c)for(var c=c.rows,a=b.length=0,d=c.length;a<d;a++)b[a]=new Option(c[a][1],c[a][0])},editUser:function(b){var c=
document.getElementById("users.view");c.reset();var a=hi5.$("user.server"),d=new hi5.Lightbox(c);d.onclose=function(){a.hide();sparkConfig.refreshUsers()};sparkConfig.showMessage("");d.show();c._dataAction="post";b&&(c._dataAction="put",b={name:b,password:sparkConfig.users.getValue(1),servers:sparkConfig.users.getValue(2),isDomainUser:sparkConfig.users.getValue(3),domainServer:sparkConfig.users.getValue(4),transferCredential:sparkConfig.users.getValue(5)},hi5.browser.objToForm(b,c));a.hide||new hi5.Select(a,
!0);sparkConfig.servers||sparkConfig.refreshServers();a.beforedropdown=function(){sparkConfig.initServerList(a)}},importUsers:function(){function b(a){sparkConfig.checkError(a)||sparkConfig.refreshUsers()}var c=hi5.$("adUser").value,a=hi5.$("adPwd").value,d=hi5.$("adDomain").value,e=hi5.$("adServer").value,f=hi5.$("adOU").value;c&&a?sparkConfig.config(sparkConfig.getGatewayAddr(),"users","import",b,null,"&user="+c+"&pwd="+a+"&domain="+d+"&server="+e+"&ou="+f):alert("Please enter credentials.")},saveServer:function(){function b(a){a.error?
sparkConfig.showMessage(a.message):(c.reset(),c._dataAction="post",sparkConfig.gateway.server||sparkConfig.getAll())}var c=document.getElementById("servers.view");sparkConfig.showMessage("");var a=hi5.browser.formToObj(c);if(a.mapDisk){var d=0,e=[];a.dosName0&&(a.actRedirect0&&(d|=1),a.actDownload0&&(d|=2),a.actUpload0&&(d|=4),e.push({dosName:a.dosName0,devicePath:a.devicePath0,actions:d}),delete a.dosName0,delete a.devicePath0);a.dosName1&&(d=0,a.actRedirect1&&(d|=1),e.push({dosName:a.dosName1,devicePath:a.devicePath1,
actions:d}),delete a.dosName1,delete a.devicePath1);a.dosName2&&(d=0,a.actRedirect2&&(d|=1),e.push({dosName:a.dosName2,devicePath:a.devicePath2,actions:d}),delete a.dosName2,delete a.devicePath2);0<e.length&&(a.disks=e)}d={};d.id=a.id;d.displayName=a.displayName;a.server&&(d.server=a.server);a.icon&&(d.icon=a.icon);a.isRDP&&(d.rdp=a);a.isVNC&&(d.vnc={port:a["vnc.port"],password:a["vnc.password"],encoding:a.encoding,quality:a.quality,compression:a.compression,color:a["vnc.color"],UseCopyRect:a.UseCopyRect,
share:a.share,sessionRecord:a["vnc.sessionRecord"],mapClipboard:a["vnc.mapClipboard"]});a.isSSH&&(d.ssh={mapClipboard:a["ssh.mapClipboard"],fontSize:a["ssh.fontSize"],port:a["ssh.port"],username:a["ssh.username"],sessionRecord:a["ssh.sessionRecord"],password:a["ssh.password"]});a.isTELNET&&(d.telnet={mapClipboard:a["telnet.mapClipboard"],fontSize:a["telnet.fontSize"],sessionRecord:a["telnet.sessionRecord"],port:a["telnet.port"]});sparkConfig.config(sparkConfig.getGatewayAddr(),"server",c._dataAction||
"put",b,JSON.stringify(d));return!1},saveUser:function(){function b(a){a.error?sparkConfig.showMessage(a.message):(c.reset(),c._dataAction="post",sparkConfig.gateway.user||sparkConfig.getAll())}var c=document.getElementById("users.view");sparkConfig.showMessage("");var a=hi5.browser.formToObj(c);if(a.servers){for(var d=a.servers.split(","),e=d.length,f=0;f<e;f++)d[f]=d[f].trim();a.servers=d}sparkConfig.config(sparkConfig.getGatewayAddr(),"user",c._dataAction||"put",b,JSON.stringify(a));return!1},
editSymlink:function(b){var c=document.getElementById("symlinks.view");c.reset();var a=new hi5.Lightbox(c);a.onclose=function(){sparkConfig.refreshSymlinks()};sparkConfig.showMessage("");a.show();c._dataAction="post";b?(c._dataAction="put",hi5.browser.objToForm(sparkConfig.symlinks.getObject(),c)):document.getElementById("symlink.id").value=hi5.tool.uuid();document.getElementById("symlink.id").onchange();var d=hi5.$("symlink.server");d.hide||new hi5.Select(d);sparkConfig.servers||sparkConfig.refreshServers();
d.beforedropdown=function(){sparkConfig.initServerList(d)};sparkConfig.updateSymlink()},saveSymlink:function(){function b(a){a.error?sparkConfig.showMessage(a.message):(c.reset(),c._dataAction="post",document.getElementById("symlink.id").value=hi5.tool.uuid())}var c=document.getElementById("symlinks.view");sparkConfig.showMessage("");var a=hi5.browser.formToObj(c);a.validFrom&&(a.validFrom=hi5.DateUtils.parseDate(a.validFrom).getTime());a.validTo&&(a.validTo=hi5.DateUtils.parseDate(a.validTo).getTime());
sparkConfig.config(sparkConfig.getGatewayAddr(),"symlink",c._dataAction||"put",b,JSON.stringify(a));return!1},notify:function(b,c){sparkConfig.config(sparkConfig.getGatewayAddr(),"sessions","notify",null,null,"&msg="+b+"&sendTo="+(c||[]).join(","))}};window.addEventListener("load",sparkConfig.initUI,!1);
