var sparkConfig={gateway:null,servers:null,users:null,config:function(c,a,b,e,d,f){c=c+"/CONF?type="+a+"&action="+b;f&&(c+=f);(a=document.getElementById("gwPwd").value)&&(c+="&gwPwd="+encodeURIComponent(a));hi5.tool.openWebSocket(c,d,e)},formatDate:function(c){if(!c)return"";c=new Date(c);return c.getFullYear()+"-"+(c.getMonth()+1)+"-"+c.getDate()+" "+c.getHours()+":"+c.getMinutes()},parseDate:function(c){var a=c.split(" ");c=a[0].split("-");a=a[1].split(":");if(3!=c.length||2!=a.length)throw"Date format must be yyyy-MM-dd hh:mm";
return new Date(c[0],c[1]-1,c[2],a[0],a[1])},showMessage:function(c){document.getElementById("message").innerHTML=c},checkError:function(c){if(c.error){var a=__svi18n.errorCode["S"+c.name];c.message&&(a+=c.message);setTimeout(function(){alert(a)},0);return!0}return!1},refreshServers:function(){function c(a){a=sparkConfig.servers.getValue(0);sparkConfig.config(sparkConfig.getGatewayAddr(),"servers","remove",b,null,"&id="+a)}function a(a){a=this.getValue(0);sparkConfig.editServer(a)}function b(e){sparkConfig.servers=
e;var b=new hi5.DataTable(e),f=new hi5.DataGrid(document.getElementById("servers.rows"));f.dataTable=b;f.open();document.getElementById("servers.type").value=e.type;document.getElementById("servers.display").checked=e.display;f.onrowclick=function(a){a=a.target;(a=a["data-action"]||a.name)&&b.perform(a)};b.addEvent("beforeremove",c);b.addEvent("onaction",a)}sparkConfig.config(sparkConfig.getGatewayAddr(),"servers","get",b)},refreshUsers:function(){function c(a){a=sparkConfig.users.getValue(0);sparkConfig.config(sparkConfig.getGatewayAddr(),
"users","remove",b,null,"&name="+a)}function a(a){a=this.getValue(0);sparkConfig.editUser(a)}function b(b){sparkConfig.users=b;var d=new hi5.DataTable(b);b=new hi5.DataGrid(document.getElementById("users.rows"));b.dataTable=d;b.open();b.onrowclick=function(a){a=a.target;(a=a["data-action"]||a.name)&&d.perform(a)};d.addEvent("beforeremove",c);d.addEvent("onaction",a)}sparkConfig.config(sparkConfig.getGatewayAddr(),"users","get",b)},refreshSessions:function(){function c(a){a=sparkConfig.sessions.getValue(0);
sparkConfig.config(sparkConfig.getGatewayAddr(),"sessions","remove",b,null,"&id="+a)}function a(a){a=this.getValue(0);var b="join";switch(this.getValue(9)){case "RFB":b="joinvnc";break;case "SSH":b="joinssh";break;case "TELNET":b="jointelnet"}a=location.protocol+"//"+document.getElementById("gateway").value+"/"+b+".html?id="+a;window.open(a)}function b(b){sparkConfig.sessions=b;var d=new hi5.DataTable(b),f=new hi5.DataGrid(document.getElementById("sessions.rows"));d.beforeGetValue=function(a,b){return"thumbnail"==
d.cols[a].name?'<img src="'+b+'">':b};f.dataTable=d;f.open();f.onrowclick=function(a){a=a.target;(a=a["data-action"]||a.name)&&d.perform(a)};d.addEvent("beforeremove",c);d.addEvent("onaction",a);document.getElementById("sessions.size").innerHTML=b.rows.length}sparkConfig.config(sparkConfig.getGatewayAddr(),"sessions","get",b)},updateSymlink:function(){var c=document.getElementById("symlinkAccess"),a=document.getElementById("symlink.id"),b=document.getElementById("symlink.password"),e=document.getElementById("symlink.server"),
d=document.getElementById("gateway").value,a=location.protocol+"//"+d+"/rdpdirect.html?symlink="+a.value+"&gateway="+d;b.value&&(a+="&pwd="+b.value);e.value&&(b=sparkConfig.servers.find(0,e.value))&&b[3]&&(a+="&startProgram=app");c.href=a},refreshSymlinks:function(){function c(a){a=sparkConfig.symlinks.getValue(0);sparkConfig.config(sparkConfig.getGatewayAddr(),"symlinks","remove",b,null,"&id="+a)}function a(a){a=this.getValue(0);sparkConfig.editSymlink(a)}function b(b){sparkConfig.symlinks=b;var d=
new hi5.DataTable(b);b=new hi5.DataGrid(document.getElementById("symlinks.rows"));b.dataTable=d;d.beforeGetValue=function(a,b){var c=d.cols[a].name;return"validFrom"==c||"validTo"==c?hi5.DateUtils.formatDate(b):b};d.beforeSetValue=function(a,b){var c=d.cols[a].name;return"validFrom"==c||"validTo"==c?hi5.DateUtils.parseDate(b).getTime():b};b.onrowclick=function(a){a=a.target;(a=a["data-action"]||a.name)&&d.perform(a)};b.open();d.addEvent("beforeremove",c);d.addEvent("onaction",a);b=document.getElementById("symlink.id");
var f=document.getElementById("symlink.password"),g=document.getElementById("symlink.server");f.onchange=b.onchange=g.onchange=sparkConfig.updateSymlink}sparkConfig.config(sparkConfig.getGatewayAddr(),"symlinks","get",b)},initUI:function(){function c(){var c="&sType="+a.value+"&display="+b.checked;sparkConfig.config(sparkConfig.getGatewayAddr(),"servers_h","put",function(){},null,c)}var a=document.getElementById("servers.type"),b=document.getElementById("servers.display");a.onchange=c;b.onchange=
c;document.getElementById("conf3").addEvent("ontabchange",function(a){sparkConfig.gateway.prop.webfeed&&(document.getElementById("servers.add").style.disabled=!0,document.getElementById("users.add").style.disabled=!0);switch(a){case 1:if(sparkConfig.servers)break;sparkConfig.refreshServers();break;case 2:if(sparkConfig.users)break;sparkConfig.refreshUsers();break;case 3:sparkConfig.servers||sparkConfig.refreshServers();if(sparkConfig.symlinks)break;sparkConfig.refreshSymlinks();break;case 4:if(sparkConfig.sessions)break;
sparkConfig.refreshSessions()}});var e=hi5.tool.queryToObj(),d=e.port,e=e.expect;if(d){var f=window.location.host,g=location.protocol;f||(f="localhost");document.getElementById("gateway").value=f;f=g+"//"+f;e&&(e=f+":"+e,document.getElementById("expectAddr").innerHTML=e,document.getElementById("expect").style.display="inline");if("http:"==g&&"80"!=d||"https:"==g&&"443"!=d)f+=":"+d;f="<a href='"+f+"'>"+f+"</a>";document.getElementById("sparkAddr").innerHTML=f;document.getElementById("conf1").style.display=
"block"}else document.getElementById("gateway").value=location.host,document.getElementById("conf0").style.display="block";if(d=document.getElementById("rfxOpt"))d.onchange=function(a){a.target.checked&&(document.getElementById("colorOpt").selectedIndex=3)}},getGatewayAddr:function(){return("http:"==location.protocol?"ws:":"wss:")+"//"+document.getElementById("gateway").value},getAll:function(){sparkConfig.config(sparkConfig.getGatewayAddr(),"gateway","get",function(c){if(!sparkConfig.checkError(c)){sparkConfig.gateway=
c;c=c.prop;var a,b=document.getElementById("frmGateway").elements,e;for(e in c)if(a=b[e]){var d=a.type,f=c[e];"checkbox"==d?a.checked="true"===f:"file"!=d&&(a.value=f)}document.getElementById("conf3").style.display="block"}})},saveGateway:function(){function c(a){var b;a.error?(b=__svi18n.errorCode["S"+a.name],a.message&&(b+=a.message)):b=__svi18n.info.restart;setTimeout(function(){alert(b)},0)}(function(a,b,c){a=a.elements;for(var d=0,f=a.length;d<f;d++){var g=a[d];if(g){var k=g.value;if(""!==k&&
!g.readonly){var l=g.type;"button"!=l&&"submit"!=l&&"file"!=l&&(b[g.name]="checkbox"==l?g.checked+"":k)}}}a=document.getElementById("licenseFile").files;0<a.length?hi5.file.readAsArrayBuffer(a[0],function(a){b.licenseFile=hi5.Base64.enc(a);c()}):c()})(document.getElementById("frmGateway"),sparkConfig.gateway.prop,function(){sparkConfig.config(sparkConfig.getGatewayAddr(),"gateway","put",c,JSON.stringify(sparkConfig.gateway))})},editServer:function(c,a){function b(b){if(b.id){var c=b.rdp;c||(c={});
c.isRDP=!!b.rdp;c.id=b.id;c.displayName=b.displayName;b.server&&(c.server=b.server);b.icon&&(c.icon=b.icon);if(c.mapDisk&&c.disks){for(var g=c.disks,k,m=Math.min(3,g.length),h=0;h<m;h++)c["dosName"+h]=g[h].dosName,c["devicePath"+h]=g[h].devicePath,k=g[h].actions,c["actRedirect"+h]=0!=(k&1),c["actDownload"+h]=0!=(k&2),c["actUpload"+h]=0!=(k&4);delete c.disks}if(b.vnc){g=b.vnc;c["vnc.port"]="";c["vnc.password"]="";c.UseCopyRect=!1;c.share=!1;c["vnc.mapClipboard"]=!1;c["vnc.recording"]=0;for(h in g)"port"==
h||"password"==h||"mapClipboard"==h||"color"==h||"sessionRecord"==h?c["vnc."+h]=g[h]:c[h]=g[h];c.isVNC=!0}if(b.ssh){g=b.ssh;c["ssh.mapClipboard"]=!1;c["ssh.fontSize"]="";c["ssh.port"]="";c["ssh.username"]="";c["ssh.recording"]=0;for(h in g)c["ssh."+h]=g[h];c.isSSH=!0}if(b.telnet){b=b.telnet;c["telnet.mapClipboard"]=!1;c["telnet.fontSize"]="";c["telnet.port"]="";c["telnet.recording"]=0;for(h in b)c["telnet."+h]=b[h];c.isTELNET=!0}e.reset();hi5.browser.objToForm(c,e);a?(hi5.$("server.id").value=d,hi5.$("server.displayName").value=
f):e._dataAction="put"}}var e=document.getElementById("servers.view"),d="",f="";a&&(d=hi5.$("server.id").value,f=hi5.$("server.displayName").value);a||e.reset();var g=e.visible?e:new hi5.Lightbox(e);g.onclose=function(){sparkConfig.refreshServers()};sparkConfig.showMessage("");g.visible()||g.show();e._dataAction="post";c&&sparkConfig.config(sparkConfig.getGatewayAddr(),"server","get",b,null,"&id="+c);var k=hi5.$("server.server");k.hide||new hi5.Select(k);k.beforedropdown=function(){for(var a=k.options,
b=sparkConfig.servers.rows,c=a.length=0,d=b.length;c<d;c++)a[c]=new Option(b[c][1],b[c][0])};k.onchange=function(){sparkConfig.editServer(k.value,!0)}},initServerList:function(c){c=c.options;var a=sparkConfig.servers;if(a)for(var a=a.rows,b=c.length=0,e=a.length;b<e;b++)c[b]=new Option(a[b][1],a[b][0])},editUser:function(c){var a=document.getElementById("users.view");a.reset();var b=hi5.$("user.server"),e=new hi5.Lightbox(a);e.onclose=function(){b.hide();sparkConfig.refreshUsers()};sparkConfig.showMessage("");
e.show();a._dataAction="post";c&&(a._dataAction="put",c={name:c,password:sparkConfig.users.getValue(1),servers:sparkConfig.users.getValue(2),isDomainUser:sparkConfig.users.getValue(3),domainServer:sparkConfig.users.getValue(4),transferCredential:sparkConfig.users.getValue(5)},hi5.browser.objToForm(c,a));b.hide||new hi5.Select(b,!0);sparkConfig.servers||sparkConfig.refreshServers();b.beforedropdown=function(){sparkConfig.initServerList(b)}},importUsers:function(){function c(a){sparkConfig.checkError(a)||
sparkConfig.refreshUsers()}var a=hi5.$("adUser").value,b=hi5.$("adPwd").value,e=hi5.$("adDomain").value,d=hi5.$("adServer").value,f=hi5.$("adOU").value;a&&b?sparkConfig.config(sparkConfig.getGatewayAddr(),"users","import",c,null,"&user="+a+"&pwd="+b+"&domain="+e+"&server="+d+"&ou="+f):alert("Please enter credentials.")},saveServer:function(){var c=document.getElementById("servers.view");sparkConfig.showMessage("");var a=hi5.browser.formToObj(c);if(a.mapDisk){var b=0,e=[];a.dosName0&&(a.actRedirect0&&
(b|=1),a.actDownload0&&(b|=2),a.actUpload0&&(b|=4),e.push({dosName:a.dosName0,devicePath:a.devicePath0,actions:b}),delete a.dosName0,delete a.devicePath0);a.dosName1&&(b=0,a.actRedirect1&&(b|=1),e.push({dosName:a.dosName1,devicePath:a.devicePath1,actions:b}),delete a.dosName1,delete a.devicePath1);a.dosName2&&(b=0,a.actRedirect2&&(b|=1),e.push({dosName:a.dosName2,devicePath:a.devicePath2,actions:b}),delete a.dosName2,delete a.devicePath2);0<e.length&&(a.disks=e)}b={};b.id=a.id;b.displayName=a.displayName;
a.server&&(b.server=a.server);a.icon&&(b.icon=a.icon);a.isRDP&&(b.rdp=a);a.isVNC&&(b.vnc={port:a["vnc.port"],password:a["vnc.password"],encoding:a.encoding,quality:a.quality,compression:a.compression,color:a["vnc.color"],UseCopyRect:a.UseCopyRect,share:a.share,sessionRecord:a["vnc.sessionRecord"],mapClipboard:a["vnc.mapClipboard"]});a.isSSH&&(b.ssh={mapClipboard:a["ssh.mapClipboard"],fontSize:a["ssh.fontSize"],port:a["ssh.port"],username:a["ssh.username"],sessionRecord:a["ssh.sessionRecord"],password:a["ssh.password"]});
a.isTELNET&&(b.telnet={mapClipboard:a["telnet.mapClipboard"],fontSize:a["telnet.fontSize"],sessionRecord:a["telnet.sessionRecord"],port:a["telnet.port"]});sparkConfig.config(sparkConfig.getGatewayAddr(),"server",c._dataAction||"put",function(a){a.error?sparkConfig.showMessage(a.message):(c.reset(),c._dataAction="post",sparkConfig.gateway.server||sparkConfig.getAll())},JSON.stringify(b));return!1},saveUser:function(){var c=document.getElementById("users.view");sparkConfig.showMessage("");var a=hi5.browser.formToObj(c);
if(a.servers){for(var b=a.servers.split(","),e=b.length,d=0;d<e;d++)b[d]=b[d].trim();a.servers=b}sparkConfig.config(sparkConfig.getGatewayAddr(),"user",c._dataAction||"put",function(a){a.error?sparkConfig.showMessage(a.message):(c.reset(),c._dataAction="post",sparkConfig.gateway.user||sparkConfig.getAll())},JSON.stringify(a));return!1},editSymlink:function(c){var a=document.getElementById("symlinks.view");a.reset();var b=new hi5.Lightbox(a);b.onclose=function(){sparkConfig.refreshSymlinks()};sparkConfig.showMessage("");
b.show();a._dataAction="post";c?(a._dataAction="put",hi5.browser.objToForm(sparkConfig.symlinks.getObject(),a)):document.getElementById("symlink.id").value=hi5.tool.uuid();document.getElementById("symlink.id").onchange();var e=hi5.$("symlink.server");e.hide||new hi5.Select(e);sparkConfig.servers||sparkConfig.refreshServers();e.beforedropdown=function(){sparkConfig.initServerList(e)};sparkConfig.updateSymlink()},saveSymlink:function(){var c=document.getElementById("symlinks.view");sparkConfig.showMessage("");
var a=hi5.browser.formToObj(c);a.validFrom&&(a.validFrom=hi5.DateUtils.parseDate(a.validFrom).getTime());a.validTo&&(a.validTo=hi5.DateUtils.parseDate(a.validTo).getTime());sparkConfig.config(sparkConfig.getGatewayAddr(),"symlink",c._dataAction||"put",function(a){a.error?sparkConfig.showMessage(a.message):(c.reset(),c._dataAction="post",document.getElementById("symlink.id").value=hi5.tool.uuid())},JSON.stringify(a));return!1},notify:function(c,a){sparkConfig.config(sparkConfig.getGatewayAddr(),"sessions",
"notify",null,null,"&msg="+c+"&sendTo="+(a||[]).join(","))}};window.addEventListener("load",sparkConfig.initUI,!1);
