var hi5=hi5||{};hi5.init={inited:false,funcs:[],push:function(a){hi5.init.funcs.push(a)},start:function(a){if(hi5.init.inited)return;hi5.browser.innerHeight=window.innerHeight;hi5.init.inited=true;var b=hi5.init.funcs;var d=0;for(var e=b.length;d<e;d++)b[d]();hi5.init.release()},release:function(){document.removeEventListener("DOMContentLoaded",hi5.init.start,false)}};
if(!window.requestAnimationFrame)window.requestAnimationFrame=window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,30,Date.now())};window.URL=window.URL||window.webkitURL;window.WebSocket=window.WebSocket||window.MozWebSocket;hi5.WebSocket=window.WebSocket;hi5.$=function(a){return document.getElementById(a)};
hi5.html={hasClass:function(a,b){return a.className.match(new RegExp("(\\s|^)"+b+"(\\s|$)"))},addClass:function(a,b){if(!hi5.html.hasClass(a,b))a.className+=" "+b},removeClass:function(a,b){if(hi5.html.hasClass(a,b)){var d=new RegExp("(\\s|^)"+b+"(\\s|$)");a.className=a.className.replace(d," ")}}};
hi5.browser=new function(){var a=navigator.userAgent;this.innerHeight=0;this.isEdge=a.indexOf("Edge")!=-1;var b=a.indexOf("MSIE")!=-1||a.indexOf("Trident")!=-1||this.isEdge;this.isIE=b;this.isTouch="ontouchstart"in window||"createTouch"in document||"DocumentTouch"in window&&window.document instanceof window.DocumentTouch||!!navigator.msMaxTouchPoints||navigator.maxTouchPoints>1||a.indexOf("Mobile")!=-1;this.isFirefox=a.indexOf("Firefox")!=-1&&!b;this.isOpera=a.indexOf("Opera")!=-1;this.isRIM=a.indexOf(" RIM ")!=
-1;this.isChrome=a.indexOf("Chrome")!=-1&&!b;this.isMacOS=a.indexOf("Mac OS")!=-1;this.isWindows=a.indexOf("Windows ")!=-1;this.isiOS=navigator.userAgent.match(/(iPad|iPhone|iPod)/i)?true:false;this.isSafari=a.indexOf("Chrome")==-1&&a.indexOf("Safari")!=-1&&!b;this.isWebKit=a.indexOf("WebKit")!=-1;this.isCrOS=a.indexOf("CrOS")!=-1;this.isOperaNext=a.indexOf("Edition Next")!=-1;this.isAndroid=a.indexOf("Android")!=-1;this.isChromeApp="chrome"in window&&"app"in chrome&&"window"in chrome.app;this.isDesktop=
!a.match(/(iPhone|iPod|iPad|Android|BlackBerry|Mobile)/);this.isLinux=a.indexOf("Linux")!=-1;var d=window.outerHeight-window.innerHeight;this.isMetro=window.screenY==0&&(window.screenX==0||window.screenX+window.outerWidth==screen.width)&&d>3&&d<31;this.isMultitask=!(this.isiOS&&this.isSafari&&a.indexOf("Version/5")>0);this.binaryWS=function(){return hi5.browser.isChrome?true:hi5.tool.hasProperty(WebSocket,"binaryType")};this.cookie2Obj=function(){var a=document.cookie;var c={};var g;var b;if(a=="")return c;
var d=a.split(";");var e=0;for(var h=d.length;e<h;e++){for(var n=d[e];n.charAt(0)==" ";)n=n.substring(1,n.length);g=n.indexOf("=");if(g>0){b=decodeURIComponent(n.substring(g+1).replace(/\+/g," "));if(hi5.tool.isNumber(b)&&b[0]!="0"&&parseFloat(b)==b)b=parseFloat(b);if(b=="true"||b=="on")b=true;else if(b=="false"||b=="off")b=false;c[n.substring(0,g)]=b}}return c};this.getLibPath=function(a){var c=document.getElementsByTagName("script");var g;var b;var d="";var e=c.length;for(var h=0;h<e;h++){b=c[h].src;
g=b.indexOf(a);if(g>-1){d=b.substring(0,g);break}}if(d.indexOf(location.origin)==0)d=d.substring(location.origin.length);return d};this.loadJS=function(a,c){if(a.indexOf("/")<0)a=hi5.libPath+a;if(hi5.browser.getLibPath(a))return;var g=document.createElement("script");g.type="text/javascript";g.src=a;if(c){g.onload=c;g.onreadystatechange=function(){if(this.readyState=="complete")c()}}var b=document.body||document.getElementsByTagName("script")[0].parentNode;b.appendChild(g)};this.formToObj=function(a,
c){var g=a.elements;var b;var d;var e;var h;var n=g.length;if(!c)c={};for(var p=0;p<n;p++){b=g[p];e=b.name;if(!e)continue;d=b.type;switch(d){case "submit":case "button":case "reset":continue;case "checkbox":h=b.checked;break;case "radio":if(!b.checked)continue;h=b.value;break;case "number":h=parseFloat(b.value);default:h=b.value}if(h=="")continue;c[e]=h}return c};this.objToForm=function(a,c){var b;var d;var e=c.elements;for(var m in a){b=e[m];if(!b)continue;d=a[m];var h=typeof d;if(h=="boolean")b.checked=
d;else b.value=d}};this.objToCookie=function(a){for(var c in a){if(a[c]=="")continue;document.cookie=c+"="+a[c]}};this.getScale=function(){return document.documentElement.clientWidth/window.innerWidth};this.httpGet=function(a,c){var b=new XMLHttpRequest;b.open("GET",a,c);b.setRequestHeader("Content-Type","text/plain;charset=UTF-8");b.send(null);return b.responseText};this.selectEditable=function(a){try{var c=document.createRange();c.selectNodeContents(a);var b=window.getSelection();b.removeAllRanges();
b.addRange(c)}catch(d){console.log(d)}};this.setOrientaionHandler=function(a){if("onorientationchange"in screen)screen.onorientationchange=a;else if("onmozorientationchange"in screen)screen.onmozorientationchange=a;else if("onmsorientationchange"in screen)screen.onmsorientationchange=a;else window.addEventListener("orientationchange",a,false)};var e={x:0,y:0};this.getMousePos=function(a,c){var b=(c||a.target).getBoundingClientRect();e.x=a.clientX-b.left;e.y=a.clientY-b.top;return e};this.calMousePos=
function(a,c,b){var d=b.getBoundingClientRect();e.x=a-d.left;e.y=c-d.top;return e};this.getHost=function(){var a=hi5.tool.queryToObj().gateway;if(!a&&!hi5.browser.isChromeApp){a=location.host;if(!a)a="localhost";else{var c=location.pathname;var b=c.indexOf("://");if(b>0)a+=c.substring(0,c.indexOf("/",b+3))}}return a};this.html2text=function(a){var c=document.createElement("div");c.innerHTML=a.replace(/<br>|<\/p>/gi,"\n</p>");return c.textContent.replace(/\r?\n/g,"\r\n").replace(new RegExp("\u00a0",
"g")," ")};this.dataURLtoBlob=function(a){var c=a.indexOf(",");var b=a.substring(0,c++);var d=b.indexOf(":");var e=b.indexOf(";",d);var m=e>d?b.substring(d+1,e):"text/plain";var h=b.indexOf("base64",d)>0?hi5.Base64.dec(a,c,true):a.substring(c);return new Blob([h],{type:m})};this.loadFlash=function(a,c,b,d,e){d=d||8;e=e||8;b=b||"__sv_flash_plugin";c=c||document.body;var m=document.getElementById(b);if(m)return m;var h=document.createElement("div");var n=h.style;n["position"]="fixed";n["width"]=n["height"]=
d+"px";n["bottom"]=n["left"]=e+"px";n["overflow"]="hidden";h.innerHTML='<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" type="application/x-shockwave-flash" data="'+a+'" width="'+d+'" height="'+e+'" id="'+b+'"><param name="allowScriptAccess" value="always" /></object>';c.appendChild(h);return h.childNodes[0]}};
if(!hi5.libPath){hi5.libPath=hi5.browser.getLibPath("hi5core.js")||hi5.browser.getLibPath("hi5.js");if(hi5.libPath)hi5.libMin=false;else{hi5.libPath=hi5.browser.getLibPath("hi5core_min.js")||hi5.browser.getLibPath("hi5_min.js");if(hi5.libPath)hi5.libMin=true}}
hi5.storage=new function(){function a(a,b){this._state=b||0;this._value=a}function b(a){if(a&&a.indexOf("{")==0){var b=JSON.parse(a);if(b&&"_state"in b&&"_value"in b)return b}return null}var d="chrome"in window&&!!chrome.storage;var e="localStorage"in window;if(e)try{localStorage.setItem("_t_s_t","1");localStorage.removeItem("_t_s_t")}catch(c){this.isAvailable=false;e=false}this.isAvailable=!!d||e;var f=d||!this.isAvailable?{}:localStorage;if(d)chrome.storage.local.get(null,function(a){for(var b in a)f[b]=
a[b]});this.set=function(b,d){f[b]=JSON.stringify(new a(d,1))};this.get=function(a){var d=f[a];var e=b(d);return e?e._value:d};this.clear=function(a){f={};if(d)chrome.storage.local.clear(a||function(){});else if(e)localStorage.clear()};this.remove=function(a){if(f.removeItem)f.removeItem(a);else{var d=b(f[a]);if(d){d._state=2;f[a]=JSON.stringify(d)}}};this.commit=function(a){a=a||function(){};if(d){var e={};var k=[];var l=false;for(var m in f){var h=b(f[m]);if(!h)continue;if(h._state==1){e[m]=h._value;
l=true}else if(h._state==2)k.push(m)}if(k.length>0){var n=function(){var b=0;for(var d=k.length;b<d;b++)delete f[k[b]];a&&a()};chrome.storage.local.remove(k,n)}if(l)chrome.storage.local.set(e,a)}else a()}};
hi5.tool={isNumber:function(a){return!isNaN(parseFloat(a))&&isFinite(a)},cumulativePos:function(a){var b=0;var d=0;do{b+=a.offsetTop||0;d+=a.offsetLeft||0;b+=parseInt(a.style.borderLeftWidth)||0;d+=parseInt(a.style.borderTopWidth)||0;b-=a.scrollTop;d-=a.scrollLeft;a=a.offsetParent;if(a==document.body)break}while(a);return{x:d,y:b}},getPos:function(a,b){var d=0;var e=0;do{if(b&&getComputedStyle(a).getPropertyValue("position")!="static")break;d+=a.offsetLeft;e+=a.offsetTop}while(a=a.offsetParent);return{x:d,
y:e}},bytesToSize:function(a){if(isNaN(a))return"";var b=[" bytes"," KB"," MB"," GB"," TB"," PB"," EB"," ZB"," YB"];var d=Math.floor(Math.log(+a)/Math.log(2));if(d<1)d=0;var e=Math.floor(d/10);a=+a/Math.pow(2,10*e);if(a.toString().length>a.toFixed(3).toString().length)a=a.toFixed(2);return a+b[e]},queryToObj:hi5.string.queryToObj,replaceQuery:function(a,b,d){var e=a.indexOf(b+"=");var f=false;if(e>0){var c=a.charAt(e-1);if(c=="&"||c=="?")f=true}if(!f)return a+="&"+b+"="+encodeURIComponent(d);var g=
new RegExp("[\\?&]"+b+"=([^&#]*)");return a.replace(g,function(a){return a.charAt(0)+b+"="+encodeURIComponent(d)})},disableInput:function(){var a=document.createElement("div");a.style.position="fixed";a.style.left=0;a.style.top=0;a.style.width="100%";a.style.height="100%";a.style.zIndex=99999;a.style.background="url("+hi5.libPath+"spinner.gif) no-repeat center center";document.body.appendChild(a);window.__hi5_bk=a},enableInput:function(){if(window.__hi5_bk){document.body.removeChild(window.__hi5_bk);
window.__hi5_bk=null}},scale:function(a,b,d,e,f){var c=e===undefined?"left top":e+" "+f;if(!d)d=b;a.style.transformOrigin=c;a.style.MozTransformOrigin=c;a.style.webkitTransformOrigin=c;a.style.msTransformOrigin=c;a.style.OTransformOrigin=c;b="scale("+b+","+d+")";a.style.transform=b;a.style.MozTransform=b;a.style.webkitTransform=b;a.style.msTransform=b;a.style.OTransform=b},openWebSocket:function(a,b,d){var e=false;if(d){var f=hi5.callback.put(d);a+="&callback="+f}var c=new WebSocket(a,"ctrl");c.onopen=
function(a){e=true;if(b)c.send(b)};c.onclose=function(a){if(!e)alert("Failed to connect")};c.onmessage=function(a){var b=JSON.parse(a.data);c.close();if(b.callback)hi5.callback.get(b.callback)(b);else console.log(b)};return c},getChildNodesByTag:function(a,b){var d=a.childNodes;var e=[];var f=0;for(var c=d.length;f<c;f++){if(d[f].nodeName.toLowerCase()!=b)continue;e.push(d[f])}return e},hasProperty:function(a,b){var d=b in a||b in a.prototype;if(d)return true;var e=a.__proto__||a.constructor.prototype;
return b in e},isCapslock:function(a){var b=String.fromCharCode(a.keyCode||a.which);if(b.toUpperCase()==b&&b.toLowerCase()!=b&&!a.shiftKey)return true;return false},getImage:function(a,b){if(b&&b.indexOf("/")!=0)b=hi5.libPath+b;return hi5&&hi5.appcfg&&hi5.appcfg.img?hi5.appcfg.img[a]||b:b},uuid:function(){var a="";var b=new Array(16);var d="";for(var e=0;e<16;e++){b[e]=Math.random()*255|0;d=b[e].toString(16);if(d.length==1)d="0"+d;switch(e){case 3:case 5:case 7:case 9:a+=d;a+="-";break;case 6:a+=
"4"+d[1];break;case 8:a+=(parseInt(d[0],16)&3|8).toString(16)+d[1];break;default:a+=d}}return a},text2html:function(a){return a.replace(/\n/g,"<br>")},Profiler:function(){function a(){this.count=0;this.totalTime=0}var b={};var d=0;var e=null;var f=false;this.begin=function(c){if(f){e=c;var k=b[c];if(k===undefined){k=new a;b[c]=k}d=(new Date).getTime();return k}};this.end=function(a){if(f){var c=b[a||e];var l=(new Date).getTime()-d;c.totalTime=c.totalTime+l;c.count++;return c}};var c=function(){b=
{};d=0;e=null};this.start=function(){if(!f){f=true;c()}};this.stop=function(){if(f)f=false};this.isStarted=function(){return f};this.print=function(){console.log(this.getResult())};this.getResult=function(a){var c={};var d=typeof a==="undefined"?0:a.length;for(var e in b){if(d>0)if(e.substring(0,d)!==a)continue;c[e]=b[e]}return c}},ResponseMonitor:function(a,b){function d(){if(b)b()}function e(){if(c){a();if(g)f=setTimeout(b,g)}}var f=0;var c=0;var g;this.tag=0;this.check=function(a){if(c){clearTimeout(f);
f=setTimeout(e,a||c)}};this.setInterval=function(a,b){c=a*1E3|0;g=b*1E3|0};this.stop=function(){clearTimeout(f);c=0}}};navigator.getUserMedia=navigator.getUserMedia||navigator.webkitGetUserMedia||navigator.mozGetUserMedia||navigator.msGetUserMedia;
hi5.audio={recordable:!!navigator.getUserMedia,getAudioContext:function(){var a=window;var b=window.AudioContext||window.webkitAudioContext;if(!b)return null;try{if(window.parent!=window)_golbal=window.parent}catch(d){}if(a.__audioCtx&&a.__audioCtx.state&&a.__audioCtx.state!="running"){if(a.__audioCtx.close)a.__audioCtx.close();a.__audioCtx=null}if(!a.__audioCtx)a.__audioCtx=new b;a.__audioCtx.__refCount=!a.__audioCtx.__refCount?1:a.__audioCtx.__refCount+1;return a.__audioCtx},releaseAudioContext:function(){var a=
window;try{if(window.parent!=window)_golbal=window.parent}catch(b){}if(a.__audioCtx){if(a.__audioCtx.__refCount)a.__audioCtx.__refCount--;if(!a.__audioCtx.__refCount||a.__audioCtx.__refCount<1){if(a.__audioCtx.close)a.__audioCtx.close();a.__audioCtx=null}}}};if(hi5.audio.recordable)if(hi5.browser.isChrome&&"https:"!=document.location.protocol)hi5.audio.recordable=false;
hi5.EventControl=function(a){a.addEvent=function(b,d){if(!a[b]||!a[b]._evt_listeners){a[b]=function(){a.fireEvent(b,arguments)};a[b]._evt_listeners=[]}a[b]._evt_listeners.push(d)};a.removeEvent=function(b,d){if(!a[b]&&!a[b]._evt_listeners)return false;var e=a[b]._evt_listeners;var f=e.indexOf(d);if(f>-1){e.removeElm(f);return true}return false};a.fireEvent=function(b,d){if(!a[b]||!a[b]._evt_listeners)return;var e=a[b]._evt_listeners;if(!d)d=[];var f=0;for(var c=e.length;f<c;f++)e[f].apply(a,d)};return a};
hi5.ui=hi5.ui||{};hi5.ui.initAs=function(a,b){var d=a["data-h5-ui"];if(!d){a["data-h5-ui"]=b;return true}if(hi5.string.seperatedStr.indexOf(d,b)!=-1)return false;else{a["data-h5-ui"]=d+","+b;return true}};hi5.ui.clean=function(a){if(a["data-h5-ui"])a["data-h5-ui"]=""};hi5.ui.confirm=function(a){return hi5.browser.isChromeApp?true:confirm(a)};
hi5.chromeapp={convertLink:function(a){var b=0;for(var d=a.length;b<d;b++)a[b].onclick=function(a){var b=a.target.href;var c=b.lastIndexOf("/");if(c!=-1)b=b.substring(c+1);chrome.app.window.create(b,{left:window.screenLeft+20,top:window.screenTop+20,width:window.innerWidth,height:window.innerHeight});return false}}};
hi5.Draggable=function(a,b){function d(b){var c=b.touchs||b.changedTouches;if(c){if(c.length!=1){g.dragging=false;return}b=c[0]}else if(b.button!=0)return;b.stopPropagation();b.preventDefault();g.pos=hi5.tool.getPos(a);g.x=b.pageX;g.y=b.pageY;g.dragging=true;g.moved=false}function e(b){if(b.touchs)b=b.touchs[0];else if(b.changedTouches)b=b.changedTouches[0];var c=g.pos.x+b.pageX-g.x;var d=g.pos.y+b.pageY-g.y;if(c<0)c=0;if(c>window.innerWidth-a.offsetWidth)c=window.innerWidth-a.offsetWidth;if(d<0)d=
0;if(d>window.innerHeight-a.offsetHeight)d=window.innerHeight-a.offsetHeight;a.style.left=c+"px";a.style.top=d+"px"}function f(a){if(!g.dragging)return;if(!g.moved)g.moved=true;e(a);a.stopPropagation();a.preventDefault()}function c(a){if(g.dragging){a.preventDefault();a.stopPropagation();g.dragging=false;g.moved=false}}b=b||a;b.draggable=false;if(!hi5.ui.initAs(b,"Draggable"))return b;var g={pos:null,x:0,y:0,dragging:false,moved:false};var k=hi5.browser.isTouch;b.addEventListener(k?"touchstart":"mousedown",
d,false);document.addEventListener(k?"touchmove":"mousemove",f,false);b.addEventListener(k?"touchmove":"mousemove",f,false);document.addEventListener(k?"touchend":"mouseup",c,false);b.addEventListener(k?"touchend":"mouseup",c,false);if(k){document.addEventListener("touchcancel",c,false);b.addEventListener("touchcancel",c,false)}return a};
hi5.Fadable=function(a,b,d,e){function f(){if(document.activeElement==a||document.activeElement==a.activeObj)setTimeout(f,m);else a.style.display="none"}function c(){if(h)clearTimeout(h);h=setTimeout(function(){if(a.beforeDisplay)a.beforeDisplay();a.style.display=e;if(!n)return;if(h)clearTimeout(h);h=setTimeout(f,m)},88);return false}function g(a){if(h)clearTimeout(h)}function k(a){c()}if(!hi5.ui.initAs(a,"Fadable"))return a;if(a.tabIndex<0)a.tabIndex=999;var l=d||document;e=e||"block";var m=b||3E3;
var h=0;var n=true;a.setFadable=function(b){n=b;if(b){var d="mouseup";if(navigator.pointerEnabled)d="pointerup";else if(navigator.msPointerEnabled)d="MSPointerUp";else if(hi5.browser.isTouch)d="touchend";l.addEventListener(d,c,false);if(d="touchend")l.addEventListener("mouseup",c,false);a.addEventListener("mouseenter",g,false);a.addEventListener("mouseleave",k,false)}else{a.style.display=e;a.removeEventListener("mouseenter",g,false);a.removeEventListener("mouseleave",k,false)}};a.startFade=c;return a};
hi5.cancelDefault=function(a){if(a.preventDefault)a.preventDefault();if(a.stopPropagation)a.stopPropagation();return false};
hi5.Toolbar=function(a,b,d){if(b){var e=a.querySelector("#svImgHandle");var f=e||document.createElement("img");if(!e){f.style.cursor="move";f.style.width="11px";f.src=d;f.id="svImgHandle";a.appendChild(f)}hi5.Draggable(a,f)}a.addButton=function(b,c,d){var e=document.createElement("img");e.src=b;if(hi5.browser.isTouch){if(!navigator.msMaxTouchPoints)e.addEventListener("touchend",c,false)}else e.addEventListener("click",c,false);e.className="h5-img-btn";a.appendChild(e);if(d)e.id=d;return e};a.getButton=
function(b){var c=a.getElementsByTagName("img");var d=c.length;for(var e=0;e<d;e++)if(c[e].id==b)return c[e];return null};a.removeButton=function(b){var c=a.getElementsByTagName("img");var d=c.length;for(var e=0;e<d;e++)if(c[e].id==b){a.removeChild(c[e]);break}};var c=a.getElementsByTagName("img");var g=c.length;for(var k=0;k<g;k++)c[k].className="h5-img-btn";return a};
hi5.ProgressBar=function(a){a.progress=0;a.maxValue=0;var b=a.getElementsByTagName("div")[0];a.setProgress=function(d){var e=Math.floor(d/a.maxValue*100);if(e==a.progress)return;a.progress=e;b.style.width=e/100*a.offsetWidth+"px"};return a};
hi5.Lightbox=function(a,b,d){function e(){var b=f.clientWidth;var c=f.clientHeight;var d=a.offsetWidth;var e=a.offsetHeight;if(d>b*.96){d=b*.96;a.style.width=d+"px"}if(e>c*.96){e=c*.96;a.style.height=e+"px";a.style.width=a.offsetWidth+22+"px"}var h=(b-d)/2;var n=(c-e)/3;a.style.left=h+"px";a.style.top=n+"px"}var f=document.createElement("div");f.id="divBackground";f.style.position="fixed";f.style.left=0;f.style.top=0;f.style.width="100%";f.style.height="100%";f.style.zIndex=999;f.style.backgroundColor=
d?d:"#222";if(!b)b=.4;if(b<1)f.style.opacity=b;a.style.position="absolute";a.style.zIndex=1E3;a.style.visibility="hidden";var c=document.createElement("img");c.width=25;c.height=25;c.src=hi5.tool.getImage("del","del.png");c.className="h5-img-btn";c.style.cursor="pointer";c.align="top";c.style.position="absolute";c.style.top=0;c.style.right=0;a.resize=e;a.show=function(){var b=document.body;b.appendChild(f);a.appendChild(c);a.style.display="block";a.style.visibility="visible";e();if(a.onopen)a.onopen(a)};
a.visible=function(){return a&&a.style.visibility=="visible"};a.dismiss=function(b){function d(){var b=document.body;b.removeChild(f);a.removeChild(c);a.style.display="none";a.style.visibility="hidden";if(a.onclose)a.onclose()}if(typeof b=="number")setTimeout(d,b);else d()};a.background=f;c.addEventListener("click",a.dismiss,false);return a};
hi5.DataTable=function(a){if(hi5.ui.initAs(a,"DataTable")){hi5.EventControl(a);var b=typeof a;if(b=="string")a=JSON.parse(a);var d=a.rows;var e=a.cols;a.rowNo=-1;a.beforeGetValue=null;a.moveTo=function(b){a.rowNo=b};a.getColNo=function(a){var b=0;for(var d=e.length;b<d;b++)if(e[b].name==a)return b;return-1};a.getValue=function(b){var c=d[a.rowNo][b];return!a.beforeGetValue?c:a.beforeGetValue(b,c)};a.setValue=function(b,c){if(a.beforeSetValue)c=a.beforeSetValue(b,c);d[a.rowNo][b]=c;a.fireEvent("onchange",
[b,a.rowNo,c])};a.first=function(){a.moveTo(0)};a.next=function(){a.moveTo(a.rowNo+1)};a.last=function(){a.moveTo(d.length-1)};a.hasNext=function(){return a.rowNo<d.length-1};a.remove=function(b){if(!b)b=a.rowNo;var c=[b];a.fireEvent("beforeremove",c);d.splice(b,1);a.fireEvent("onremove",c)};a.perform=function(b){if(typeof a[b]=="function")a[b].apply(a);else a.fireEvent("onaction",[b])};a.getObject=function(){var b=new Object;var c=0;for(var d=e.length;c<d;c++)b[e[c].name]=a.getValue(c);return b};
a.find=function(a,b){var e=0;for(var k=d.length;e<k;e++)if(d[e][a]==b)return d[e];return null}}a.fireEvent("onopen");return a};
hi5.DataGrid=function(a){function b(b){var c=this.rowIndex;if(typeof c=="number"){c=c-a.tHead.rows.length;e=c;a.dataTable.moveTo(c)}if(a.onrowclick)a.onrowclick(b)}function d(){if(!a._rowTemp){var b=a.tBodies[0].rows[0];a._rowTemp=b.cloneNode(true)}return a._rowTemp}if(!hi5.ui.initAs(a,"DataGrid"))return a;if("TABLE"!=a.nodeName)throw"Not HTML Table";a.dataTable=null;a.onrowclick=null;var e=-1;a.getValue=function(b){var c=a.dataTable;c.moveTo(e);return c.getValue(c.getColNo(b))};a.fillData=function(f){var c=
f.rows;var g=f.cols;var k=a.tBodies[0];var l;var m;var h;var n;var p=d();var u=p.cells.length;var q;var t=k.cloneNode(false);var r;h=c.length;for(m=0;m<h;m++){q=p.cloneNode(true);r=q.cells;f.moveTo(m);for(l=0;l<u;l++)if(!r[l].innerHTML){n=f.getValue(l);if(a.beforeDisplayValue)n=a.beforeDisplayValue(l,n);r[l].innerHTML=n}e=m;q.addEventListener("click",b,false);if(a.beforeAppendRow)a.beforeAppendRow(q);t.appendChild(q)}a.removeChild(k);a.appendChild(t)};a.open=function(){function b(c){var d=a.tBodies[0];
var e=d.rows[c];if(e)d.removeChild(e)}if(!a.dataTable)return;a.fillData(a.dataTable);a.dataTable.addEvent("onremove",b)};return a};
hi5.Select=function(a,b,d){if(!hi5.ui.initAs(a,"Select"))return a;var e=a.parentNode;var f=document.createElement("div");f.style.padding="0";f.style.display="inline";e.insertBefore(f,a);var c=document.createElement("img");c.src=hi5.tool.getImage("select","select.png");c.height=a.offsetHeight;c.style.verticalAlign="-6px";f.appendChild(a);f.appendChild(c);var g=document.createElement("select");if(b){g.multiple=true;if(!d)d=","}var k=a.getAttribute("hi5_size");g.size=k?k:10;var l=a.getAttribute("hi5_list");
if(l){var m=l.split(";");var h=m.length;if(h>0){var n=g.options;for(var p=0;p<h;p++)n[p]=new Option(m[p])}}g.style.position="absolute";g.style.zIndex=99999;g.style.display="none";document.body.appendChild(g);a.show=function(){if(a.beforedropdown)a.beforedropdown(a);g.style.display="";g.focus()};a.hide=function(){g.style.display="none";a.focus()};c.onclick=function(){if(g.style.display=="none"){if(g.options.length==0){var b=a.getAttribute("onfetchlist");if(b)eval(b)}var d=hi5.tool.getPos(a,false);
g.style.left=d.x+"px";g.style.top=d.y+a.offsetHeight+"px";g.style.width=a.offsetWidth+c.width+3+"px";a.show()}else a.hide()};g.onchange=function(){if(!b){a.value=g.value;g.style.display="none"}else{var c=[];var e;var f=g.options;var h=0;for(var l=f.length;h<l;h++){e=f[h];if(e.selected)c.push(e.value)}a.value=c.join(d)}if(a.onchange)a.onchange()};a.options=g.options;return a};hi5.init.push(function(){var a=document.getElementsByClassName("Hi5Select");var b=a.length;for(var d=0;d<b;d++)new hi5.Select(a[d])});
hi5.Tab=function(a){function b(b){var d=c;if(c!=b){g[c].className="tab_back";k[c].className="tab_hide";c=b}g[b].className="tab_front";k[b].className="tab_show";g[b].focus();if(d!=b)a.fireEvent("ontabchange",[b,d])}function d(a){var c=g.indexOf(a.target);if(c==-1)return;b(c)}if(!hi5.ui.initAs(a,"Tab"))return a;hi5.EventControl(a);var e=a.getElementsByClassName("tab")[0].getElementsByClassName("tab_title")[0].childNodes;var f=e.length;var c=0;var g=new Array(0);var k=new Array(0);for(var l=0;l<f;l++){var m=
e[l];if(m.nodeName.toUpperCase()!="SPAN")continue;m.className="tab_back";m.onclick=d;m.onfocus=d;g[g.length]=m}var h=a.getElementsByClassName("tab_body")[0].childNodes;f=h.length;for(l=0;l<f;l++){var n=h[l];if(n.nodeName.toUpperCase()!="DIV")continue;k[k.length]=n;n.className="tab_hide"}b(c);a.setSelected=b;a.getSelected=function(){return c};return a};hi5.init.push(function(){var a=document.getElementsByClassName("tab_all");var b=a.length;for(var d=0;d<b;d++)new hi5.Tab(a[d])});
hi5.notifications=new function(){function a(a){var f=new b(a);d.getElement().appendChild(f);if(a.select){var c=f.getElementsByClassName("hi5_notifer_msg")[0];if(c.nodeName=="TEXTAREA")c.select();else hi5.browser.selectEditable(c)}}function b(b){function f(a,b){var d=document.createElement("span");d.className=b;d.onclick=function(b){a.apply(c,[b])};return d}var c=document.createElement("div");c.className="hi5_notifer slideUp";c.title=b.title;c.message=b.msg;c.msgCount=1;var g=document.createElement("div");
g.className="hi5_notifer_title";var k=document.createElement("span");k.className="hi5_notifer_icon";g.appendChild(k);g.appendChild(document.createTextNode(c.title));c.appendChild(g);var l=document.createElement("div");var m=b.format=="text/plain";var h=m?document.createElement("textarea"):document.createElement("div");h.className="hi5_notifer_msg";h.style.width="100%";h.innerHTML=b.msg;l.appendChild(h);if(!d.disableCounter){var n=document.createElement("span");n.className="hi5_notifer_count";c.addCount=
function(a){a=a||1;c.msgCount+=a;n.innerHTML="("+c.msgCount+")"};if(b.count&&b.count>1)c.addCount(b.count-1);l.appendChild(n)}if(b.cbNo)l.appendChild(f(b.cbNo,"hi5_notifer_button_no"));if(b.cbYes)l.appendChild(f(b.cbYes,"hi5_notifer_button_yes"));c.appendChild(l);c.destroy=function(){if(c.parentNode){c.parentNode.removeChild(c);var f=d.notifyPool.shift();if(f)a(f);else if(d.onempty&&d.notifySize()==0)d.onempty();if(b.cbClose)b.cbClose()}};if(b.timeout){var p=setTimeout(function(){c.destroy()},b.timeout);
c.addEventListener("mouseover",function(){clearTimeout(p)},false)}if(!b.cbYes&&!b.cbNo)c.onclick=c.destroy;return c}this.notifyPool=[];this.disableCounter=false;this.getElement=function(){var a=hi5.$("hi5_notifer_all");if(!a){a=document.createElement("div");a.id="hi5_notifer_all";document.body.appendChild(a)}return a};var d=this;this.notify=function(b){var f=typeof b=="string"?{msg:b,title:"",count:1}:b;if(!f.title)f.title="";if(!f.count)f.count=1;if(d.onnotify&&d.onnotify(f))return;var c=hi5.tool.getChildNodesByTag(d.getElement(),
"div");var g=c.length;if(!d.disableCounter&&g>0){var k=c[g-1];if(k.title==f.title&&k.message==f.msg){k.addCount();return}}if(g<3)a(f);else{var l=d.notifyPool;if(!d.disableCounter&&l.length>0){var m=l[l.length-1];if(m.title==f.title&&m.msg==f.msg){m.count++;return}}l.push(f)}};this.notifySize=function(){return hi5.tool.getChildNodesByTag(d.getElement(),"div").length};this.clearAll=function(){d.notifyPool.length=0;for(var a=d.getElement();a.hasChildNodes();)a.removeChild(a.firstChild)}};
hi5.file={readAsArrayBuffer:function(a,b){var d=new FileReader;d.onloadend=function(a){b(new Uint8Array(a.target.result))};d.readAsArrayBuffer(a)},getEntries:function(a){var b=a.target&&(a.target.webkitEntries||a.target.entries||[]);if(!b.length){var d=a.dataTransfer&&a.dataTransfer.items;if(d){var e=0;for(var f;f=d[e];++e){if(f.kind!="file")continue;if(!f.webkitGetAsEntry&&!f.getAsEntry)break;var c=f.webkitGetAsEntry()||f.getAsEntry();if(!c)break;b.push(c)}}}return b},getFilesFromEntries:function(a,
b){function d(){c--;if(!c)b(g)}function e(a){return function(b){b.fullPath=a;g.push(b);d()}}function f(a){var b=a.length;c+=b;for(var g=0;g<b;g++){var h=a[g];if(h.isFile)h.file(e(h.fullPath),function(a){console.log(a);d()});else if(h.isDirectory){var n=h.createReader();n.readEntries(function(a){if(a.length)f(a);d()},function(){d()})}}}var c=0;var g=[];f(a)},DirectoryReader:function(a){function b(a){return Array.prototype.slice.call(a||[],0)}function d(a,d){var e=a.createReader();var f=[];var m=function(){e.readEntries(function(a){if(!a.length)d(f);
else{f=f.concat(b(a));m()}})};m()}function e(a){var b=0;for(var k=a.length;b<k;b++){var l=a[b];if(l.isFile){var m=function(a){return function(b){f.onfile(b,a)}};l.file(m(l.fullPath))}else if(l.isDirectory)d(l,function(a){e(a)})}}var f=this;this.start=function(){e(a)}}};
hi5.Chat=function(a,b){function d(a,b,d){var c=document.createElement("span");c.className=b;c.innerHTML=a;d.appendChild(c);return c}function e(){var a=c.value;k.add(a,b);c.value="";if(k.onchat)k.onchat(a,b)}var f=hi5.$("chatHistory");var c=hi5.$("chatText");var g=hi5.$("chatSend");var k=this;this.add=function(c,e){var g=document.createElement("div");d((e||b)+":","chatFrom",g);d(c,"chatMsg",g);var k=new Date;d(k.getHours()+":"+k.getMinutes()+":"+k.getSeconds(),"chatTime",g);if(a.style.display!="block")a.style.display=
"block";f.appendChild(g);f.scrollTop=f.scrollHeight};c.addEventListener("keydown",function(a){if(a.keyCode==13)e()},false);g.addEventListener("click",e,false)};document.addEventListener("DOMContentLoaded",hi5.init.start,false);
