var hi5=hi5||{};if(!String.prototype.trim)String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")};if(!Number.prototype.toByte)Number.prototype.toByte=function(){var a=this&255;return a>127?a-256:a};if(!Date.now)Date.now=function b(){return(new Date).getTime()};
if(!String.prototype.applyArgs)String.prototype.applyArgs=function(a){var b=this.split("%");var d;var c;var e=b[0];var f=1;for(var l=b.length;f<l;f++){d=b[f];var m=parseInt(d,10);if(isNaN(m))e+=d;else{c=d.substring((m+"").length);d=a[m-1];if(d)e+=d;e+=c}}return e};if(!String.prototype.hashCode)String.prototype.hashCode=function(){var a=0|0;var b=0;var d=this.length;for(var c=0;c<d;c++){b=this.charCodeAt(c);a=(a<<5)-a+b|0}return a};
if(!Array.prototype.removeElm)Array.prototype.removeElm=function(a){var b=this.indexOf(a);if(b==-1)return;this.splice(b,1)};if(!Date.prototype.getStdTimezoneOffset)Date.prototype.getStdTimezoneOffset=function(){var a=new Date(this.getFullYear(),0,1);var b=new Date(this.getFullYear(),6,1);return Math.max(a.getTimezoneOffset(),b.getTimezoneOffset())};
hi5.DateUtils={formatNum:function(a){return a<10?"0"+a:""+a},formatDate:function(a,b){if(!a)return"";var d=new Date(a);var c=d.getFullYear()+"-"+hi5.DateUtils.formatNum(d.getMonth()+1)+"-"+hi5.DateUtils.formatNum(d.getDate());if(b)c+=+" "+d.getHours()+":"+d.getMinutes();return c},parseDate:function(a){var b=a.split(" ");var d=b[0].split("-");if(d.length!=3)return null;if(b.length>1){var c=b[1].split(":");if(c.length!=2)return null;return new Date(d[0],d[1]-1,d[2],c[0],c[1])}else return new Date(d[0],
d[1]-1,d[2])}};hi5.NumUtils={toBytes:function(a,b){var d=a.toString(16);var c=d.length/2;var e=c|0;var f=0;if(!b)b=new Uint8Array(8);for(;f<e;f++)b[f]=parseInt(d.substr(-(f+1)*2,2),16);if(c>e)b[f]=parseInt(d[0],16);return b}};
hi5.Arrays={fill:function(a,b,d,c){if(a.fill)a.fill(c,b,d);else for(var e=b;e<d;e++)a[e]=c},arraycopy:function(a,b,d,c,e){if(d.set&&a.subarray)d.set(a.subarray(b,b+e),c);else for(var f=0;f<e;f++)d[c+f]=a[b+f]},equals:function(a,b){if(a==b)return true;if(!a||!b)return false;var d=a.length;if(d!=b.length)return false;for(var c=0;c<d;c++)if(a[c]!=b[c])return false;return true},startWidth:function(a,b){var d=0;for(var c=b.length;d<c;d++)if(a[d]!=b[d])return false;return true},__sortNumber:function(a,
b){return a-b},sortNumber:function(a){return a.sort(hi5.Arrays.__sortNumber)},hashCode:function(a){var b=1|0;var d=0;for(var c=a.length;d<c;d++)b=31*b+a[d]|0;return b},release:function(a){if(a){var b=0;for(var d=a.length;b<d;b++)a[b]=null;a=null}}};hi5.callback={callbacks:{},no:0,put:function(a){var b="CB"+this.no++;this.callbacks[b]=a;return b},get:function(a){var b=this.callbacks[a];if(b)delete this.callbacks[a];return b}};
hi5.string={seperatedStr:{indexOf:function(a,b,d){var c=0;var e=a.indexOf(b,c);var f=b.length;var l=a.length;d=d||",";if(e==-1)return-1;if(e==0&&(f==a.length||a.charAt(f)==d))return 0;for(;a.charAt(e-1)!=d||a.charAt(e+f)!=d&&e+f!=l;){c=e+1;e=a.indexOf(b,c);if(e==-1)return-1}return e}},queryToObj:function(a,b){if(!a)a=location.search.substring(1);var d=b||{};if(!!a){var c=a.split("&");var e=c.length;for(var f=0;f<e;f++){var l=c[f].split("=");d[l[0]]=decodeURIComponent(l[1])}}return d}};
hi5.graphic={};hi5.graphic.Line=function(a,b,d,c){this.x1=a||0;this.y1=b||0;this.x2=d||0;this.y2=c||0};hi5.graphic.Line.prototype.set=function(a,b,d,c){this.x1=a;this.y1=b;this.x2=d;this.y2=c};hi5.graphic.Line.prototype.intersection=function(a,b,d,c){var e=this.x1;var f=this.y1;var l=this.x2;var m=this.y2;var q=(c-b)*(l-e)-(d-a)*(m-f);if(q==0)return null;var k=((d-a)*(f-b)-(c-b)*(e-a))/q;var h=((l-e)*(f-b)-(m-f)*(e-a))/q;if(k>=0&&k<=1&&h>=0&&h<=1)return{x:e+(k*(l-e)|0),y:f+(k*(m-f)|0)};return null};
hi5.graphic.Rectangle=function(a,b,d,c){this.x=a;this.y=b;this.width=d;this.height=c;var e=this;this.union=function(a,c,b,d){var k=e.width;var h=e.height;if((k|h)<0){e.x=a;e.y=c;e.width=b;e.height=d;return}var g=b;var p=d;if((g|p)<0)return;var n=e.x;var r=e.y;k+=n;h+=r;var t=a;var u=c;g+=t;p+=u;if(n>t)n=t;if(r>u)r=u;if(k<g)k=g;if(h<p)h=p;k-=n;h-=r;e.x=n;e.y=r;e.width=k;e.height=h};this.intersection=function(a,c,b,d,k){var h=e.x;var g=e.y;var p=h;p+=e.width;var n=g;n+=e.height;var r=a;r+=b;var t=c;
t+=d;if(h<a)h=a;if(g<c)g=c;if(p>r)p=r;if(n>t)n=t;p-=h;n-=g;if(k){k.x=h;k.y=g;k.width=p;k.height=n;return k}return new hi5.graphic.Rectangle(h,g,p,n)};this.isEmpty=function(){return e.width<=0||e.height<=0}};
hi5.graphic.Bitmap=function(a,b,d){var c=d==32;var e=d/8;var f=(4-a*e%4)%4;var l=c?108:40;var m=14+l;var q=(a*e+f)*b;var k=m+q;var h=new Uint8Array(k);var g=new hi5.DataBuffer(h,0,k);g.setByte(66);g.setByte(77);g.setLittleEndian32(k);g.skipPosition(4);g.setLittleEndian32(m);g.setLittleEndian32(l);g.setLittleEndian32(a);g.setLittleEndian32(b);g.setLittleEndian16(1);g.setLittleEndian16(d);g.setLittleEndian32(c?3:0);g.setLittleEndian32(q);g.setLittleEndian32(2835);g.setLittleEndian32(2835);g.skipPosition(8);
if(c){g.setLittleEndian32(16711680);g.setLittleEndian32(65280);g.setLittleEndian32(255);g.setLittleEndian32(4278190080);g.setLittleEndian32(1466527264);g.skipPosition(36);g.skipPosition(12)}this.getWidth=function(){return a};this.getHeight=function(){return b};this.getColor=function(){return d};this.getPaddingSize=function(){return f};this.putPixels=function(c,b,d){if(!f)g.setBytes(c,b,d);else{var m=0;for(var k=a*e;b<d;){m=b+k;if(m>d)m=d;g.setBytes(c,b,m);b=m;g.skipPosition(f)}}};this.getDataURL=
function(){return"data:image/bmp;base64,"+hi5.Base64.enc(g.getData())};this.getData=function(){return g.getData()}};
hi5.Base64={table:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".split(""),enc:function(a,b,d){var c="";var e=this.table;if(!b)b=a.length;if(!d)d=0;var f=d;var l=d+b-2;for(var m=b%3;f<l;f+=3){c+=e[a[f]>>2];c+=e[((a[f]&3)<<4)+(a[f+1]>>4)];c+=e[((a[f+1]&15)<<2)+(a[f+2]>>6)];c+=e[a[f+2]&63]}if(m==2){f=d+b-2;c+=e[a[f]>>2];c+=e[((a[f]&3)<<4)+(a[f+1]>>4)];c+=e[(a[f+1]&15)<<2];c+="="}else if(m==1){f=d+b-1;c+=e[a[f]>>2];c+=e[(a[f]&3)<<4];c+="=="}return c},binaries:[-1,-1,-1,-1,-1,-1,-1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,62,-1,-1,-1,63,52,53,54,55,56,57,58,59,60,61,-1,-1,-1,0,-1,-1,-1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,-1,-1,-1,-1,-1,-1,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,-1,-1,-1,-1,-1],dec:function(a,b,d){var c=this.binaries;var e;var f;var l;var m;var q;var k;var h=0;var g=0;var p=a.indexOf("=")-b;var n=a.length;if(p<0)p=n-b;f=(p>>
2)*3+Math.floor(p%4/1.5);e=d?new Uint8Array(f):new Array(f);e[0]=0;for(l=0,m=b;m<n;m++){q=c[a.charCodeAt(m)&127];k=a.charAt(m)=="=";if(q==-1){console.log("Illegal character '"+a.charCodeAt(m)+"'");continue}g=g<<6|q;h+=6;if(h>=8){h-=8;if(!k)e[l++]=g>>h&255;g&=(1<<h)-1}}return e}};
hi5.DataBuffer=function(a,b,d){if(!b)b=0;if(!d)d=a.length;this.size=d;var c=b;var e=b+d;var f=hi5.Arrays.arraycopy;var l=this;this.attach=function(b,d,f){if(a)a=null;a=b;c=d;l.size=f;e=d+f};this.reset=function(a){c=0;l.size=e=a};this.markEnd=function(a){e=a||l.getPosition()};this.getEnd=function(){return e};this.has=function(a){return e-c>=a};this.getByte=function(){return a[c++]};this.getBytes=function(b){var d;if(a.slice)d=a.slice(c,c+b);else if(a.buffer&&a.buffer.slice)d=new Uint8Array(a.buffer.slice(c,
c+b));else{d=!!Uint8Array?new Uint8Array(b):new Array(b);if(d.set&&a.subarray)d.set(a.subarray(c,c+b));else for(var e=0;e<b;e++)d[e]=a[c+e]}c+=b;return d};this.getArrayBuffer=function(b){return a.buffer.slice(c,c+b)};this.cloneBytes=function(b){return new Uint8Array(a.buffer.slice(c,c+b))};this.copyToByteArray=function(c,b,d,e){f(a,d,c,b,e)};this.getCapacity=function(){return a.length};this.getPosition=function(){return c};this.getLittleEndian16=function(){var b=a[c+1]<<8|a[c];c+=2;return b};this.getBigEndian16=
function(){var b=a[c]<<8|a[c+1];c+=2;return b};this.getLittleEndian32=function(){var b=a[c+3]<<24|a[c+2]<<16|a[c+1]<<8|a[c];c+=4;return b};this.getLittleEndian64=function(){var b=a[c+7]<<56|a[c+6]<<48|a[c+5]<<40|a[c+4]<<32|a[c+3]<<24|a[c+2]<<16|a[c+1]<<8|a[c];c+=8;return b};this.getBigEndian32=function(){var b=a[c]<<24|a[c+1]<<16|a[c+2]<<8|a[c+3];c+=4;return b};this.getUnicodeString=function(a,b){var c=Math.floor(a/2);var d="";for(var e=0;e<c;e++){var f=this.getLittleEndian16();if(b&&f==0){this.skipPosition((c-
e-1)*2);break}d+=String.fromCharCode(f)}return d};this.getAscllString=function(b,d){var f="";var h=b||e;if(a.subarray&&b&&d===false){var g=c;c+=h;return String.fromCharCode.apply(null,a.subarray(g,g+h))}for(var l=0;l<h;l++){var n=this.getByte();if(n==0){if(b)this.skipPosition(b-l-1);break}f+=String.fromCharCode(n)}return f};this.setAscllString=function(b){var d=0;for(var e=b.length;d<e;d++)a[c++]=b.charCodeAt(d)};this.setUnicodeString=function(a){var b=a.length;for(var c=0;c<b;c++)this.setLittleEndian16(a.charCodeAt(c))};
this.skipPosition=function(a){c+=a};this.setPosition=function(a){c=a};this.getData=function(){return a};this.setByte=function(b){a[c++]=b};this.setBytes=function(b,d,e){if(a.set)if(!d&&!e){a.set(b,c);c+=b.length;return}else if(b.subarray){a.set(b.subarray(d,e),c);c+=e-d;return}if(!e)e=b.length;if(!d)d=0;for(var f=d;f<e;f++)a[c++]=b[f]};this.setLittleEndian16=function(b){a[c++]=b&255;a[c++]=b>>8&255};this.setLittleEndian32=function(b){a[c++]=b&255;a[c++]=b>>8&255;a[c++]=b>>16&255;a[c++]=b>>24&255}};
hi5.Logger=function(){var a=1;this.setLevel=function(b){a=b};this.debug=function(b){if(a>2)console.log(b)};this.info=function(b){if(a>1)console.log(b)};this.warn=function(b){if(a>0)console.log(b)}};
hi5.httpGet=function(a,b){function d(a){b(false,a.target.responseText)}function c(a){b(true)}var e=b?true:false;var f=new XMLHttpRequest;if(e){f.addEventListener("load",d);f.addEventListener("error",c);f.addEventListener("abort",c)}f.open("GET",a,e);f.setRequestHeader("Content-Type","text/plain;charset=UTF-8");f.send(null);return e?"":f.responseText};var svGlobal={logger:new hi5.Logger,util:{}};
