svGlobal.auth=new function(){var g=this;this.login=function(l){function p(e,a){window.__sparkUser=null;if(!g.beforelogin||!g.beforelogin(e)){var b=new WebSocket(e.substring(0,e.indexOf("?"))+"?_METHOD=post");b.onclose=function(a){g.afterlogin&&g.afterlogin(m);m=!1};b.onopen=function(a){m=!0};b.onmessage=function(c){0==c.data.indexOf("00")?b.send("00"+e.substring(e.indexOf("?")+1)):(c=JSON.parse(c.data),c.error||b.send("A1"+navigator.userAgent),a(c),b.close())}}}var m=!1,e=hi5.browser.cookie2Obj();
e.svSession&&e.svEmail&&(l+="&svSession="+e.svSession+"&svEmail="+encodeURIComponent(e.svEmail));setTimeout(function(){p(l,svGlobal.onloggedin)},5);return!1}};function startExitingApp(g){function l(e){p.addSurface(e);p.startExitingApp(g)}var p=svManager.getInstance();window.svOnSurfaceReady=l;window.open("rail.html").svOnSurfaceReady=l;var m=hi5.$(g),e=m.parentNode;e.removeChild(m);e=e.parentNode;0==e.getElementsByTagName("input").length&&(e.dismiss(),p.checkRemaining(2E3))}
function getLoginURL(){return("https:"==location.protocol?"wss://":"ws://")+hi5.$("gateway").value+"/LOGIN?"}
window.addEventListener("load",function(g){function l(){g.preventDefault();var a=hi5.$("frmLogin").elements,b=a.user.value,a=a.pwd.value,b=getLoginURL()+"user="+encodeURIComponent(b)+"&pwd="+encodeURIComponent(a);return svGlobal.auth.login(b)}function p(){window.__sparkUser=null;var a=hi5.$("frmLogin");a.elements.pwd.value="";a.style.display="block";hi5.$("frmConn").style.display="none";(a=svManager.getInstance())&&a.running()&&a.close()}function m(a){var b=a.target;b.onclick=null;setTimeout(function(){b.onclick=
m},300);r(b.id)}function e(){function a(a){c.addSurface(a);c.running()?c.startApp(b.exe,b.args,""):c.run()}var b=window.__sparkUser.server,c=svManager.getInstance();null==c&&(c=new svGlobal.Rdp2(b),c.sessionTimeout=9E5);window.svOnSurfaceReady=a;window.open("rail.html").svOnSurfaceReady=a}function r(a,b,c){var f=window.__sparkUser,h=f.servers,q=h.length;f.server=null;window.sparkGateway=f.gateway;for(var n=0;n<q;n++){var d=h[n];if(a==d.id){d=connvertServer(d);d.gateway=f.gateway;d.session=f.session;
d.account=f.account;f.server=d;q=d.server_bpp;a=window.innerWidth;h=window.innerHeight;d.width=a;d.height=h;q||(q=16);d.width=a;d.height=h;d.color=q;break}}if(f.server){console.log("connecting to:"+f.server.id);(d=hi5.$("touchpad"))&&d.checked&&(f.server.touchpad=!0);if(d=hi5.$("keyboard"))d=parseInt(d.options[d.selectedIndex].value),0<d&&(f.server.keyboard=d);"undefined"==typeof b&&(b=(d=hi5.$("sameWindow"))&&d.checked);if("app"==f.server.startProgram&&hi5.browser.isMultitask&&!b)e();else if(b){var k=
new Rdp2(f.server);hi5.$("login").style.display="none";k.addSurface(new svGlobal.LocalInterface);k.run();k.onclose=function(){if(c){window.__sparkUser=null;var a=hi5.$("frmLogin");a.elements.pwd.value="";a.style.display="block";hi5.$("frmConn").style.display="none"}else k.hide(),hi5.$("login").style.display="block"}}else window.open("rdpdirect.html")}else hi5.notifications.notify("Not a valid server")}svGlobal.auth.beforelogin=function(){hi5.tool.disableInput()};svGlobal.auth.afterlogin=function(a){a||
(hi5.notifications.notify(__svi18n.errorCode.connection),p());hi5.tool.enableInput()};svGlobal.onloggedin=function(a){hi5.tool.enableInput();if(a.error)hi5.notifications.notify(__svi18n.errorCode["S"+a.name]);else{hi5.$("frmLogin").style.display="none";hi5.$("frmConn").style.display="block";if(!0===a.isDomainUser){var b=hi5.$("settings");b&&b.parentNode.removeChild(b)}for(b=hi5.$("programs");b.hasChildNodes();)b.removeChild(b.firstChild);var c=a.servers;if(!a.accessNotInList){var f=hi5.$("anyconn");
f&&(f.style.display="none")}window.__sparkUser={session:a.session,account:hi5.$("user").value,gateway:hi5.$("gateway").value,servers:c};a=c.length;if(!(1>a)){for(var f="",h=0;h<a;h++){var e=c[h].server,n=c[h].id,e=c[h].displayName||n||e,d=c[h].icon;d||(d="rdp32.png");var k=document.createElement("div");k.className="icon";var g=document.createElement("img");g.src=d;g.id=n;g.alt=n;g.title=e;g.style.cursor="pointer";g.onclick=m;k.appendChild(g);k.appendChild(document.createElement("br"));k.appendChild(document.createTextNode(e));
b.appendChild(k);hi5.appcfg.startup&&n===hi5.appcfg.startup.server&&(f=n)}!f&&hi5.appcfg.startup&&(console.log("start up:"+hi5.appcfg.startup.server+" not found, use the first instead"),f=c[0].id);f&&r(f,!hi5.appcfg.startup.newWindow,!0)}}};(function(){hi5.$("user").focus();hi5.$("frmLogin").onsubmit=l;var a=hi5.$("anyconn");a&&(a.onclick=function(){window.open("rdp.html?gateway="+hi5.$("gateway").value)});if(a=document.querySelector('input[name="showlogin"]'))a.onclick=p;a=hi5.browser.cookie2Obj();
if(a.svEmail){var b=hi5.$("frmLogin").elements;b.user.value=a.svEmail;b.pwd.value=a.svSession?"fake":a.pwd;setTimeout(l,1E3)}var a=hi5.$("settings"),c=hi5.$("settingsDiv");a&&(a.onclick=function(){c&&((new hi5.Lightbox(c)).show(),hi5.$("currPwd").focus())});if(a=hi5.$("frmSettings"))a.onsubmit=function(a){a.preventDefault();var b=a.target.elements;if(b.newPwd1.value!=b.newPwd2.value)hi5.notifications.notify(__svi18n.errorCode.pwdmatch);else{a=getLoginURL()+"_METHOD=post&action=put";var e=new WebSocket(a);
e.onmessage=function(a){0==a.data.indexOf("00")?(e.send("00currPwd="+b.currPwd.value+"&newPwd="+b.newPwd1.value+"&user="+hi5.$("user").value),hi5.$("frmSettings").reset()):(a=JSON.parse(a.data),a.error&&hi5.notifications.notify(__svi18n.errorCode["S"+a.name]),e.close())};c.dismiss&&c.dismiss();return!1}};(a=hi5.$("sameWindow"))&&(hi5.browser.isiOS||hi5.browser.isIE||hi5.browser.isChromeApp)&&(a.checked=!0);a=hi5.$("gateway");(b=a.value)||(b=hi5.appcfg.defaultPort?window.location.hostname+":"+hi5.appcfg.defaultPort:
window.location.host);0==b.length&&(b="localhost");a.value=b;a=hi5.$("touchpadmode");hi5.browser.isTouch&&(a.style.display="");(a=hi5.$("user"))&&!a.value&&hi5.appcfg&&hi5.appcfg.domain&&(a.value=hi5.appcfg.domain+"\\");(function(){var a=!1,b="";try{document.createElement("canvas").getContext("2d"),a=!0}catch(e){b="This browser does not support Canvas.\n\n"}var c=!("WebSocket"in window)&&!("MozWebSocket"in window),d=navigator.userAgent,g=-1!=d.indexOf("Firefox");c&&(b+="This browser doesn't support WebSocket.\n\n",
g?b+="Please update to Firefox 6 or later.\n\n":-1!=d.indexOf("Opera")?b+="Please open 'opera:config#Enable WebSockets' (type it in the link field) make 'Enable WebSockets' selected and restart Opera.\n\n":-1!=d.indexOf("MSIE")&&(b+="Please install Google Chrome Frame.\n\n"));0<b.length&&hi5.notifications.notify(b);return!c&&a})();(a=hi5.$("defPort"))&&hi5.appcfg.defaultPort&&(a.innerHTML=hi5.appcfg.defaultPort)})()},!1);
