svGlobal.auth=new function(){var k=this;this.login=function(g){function n(c,a){window.__sparkUser=null;if(!k.beforelogin||!k.beforelogin(c)){var b=new WebSocket(c.substring(0,c.indexOf("?"))+"?_METHOD=post","login");b.onclose=function(a){k.afterlogin&&k.afterlogin(h);h=!1};b.onopen=function(a){h=!0};b.onmessage=function(e){var f=e.data;0==f.indexOf("00")?b.send("00"+c.substring(c.indexOf("?")+1)):(e=JSON.parse(e.data),e.error||b.send("A1"+navigator.userAgent),a(e),b.close())}}}var h=!1,c=hi5.browser.cookie2Obj();
c.svSession&&c.svEmail&&(g+="&svSession="+c.svSession+"&svEmail="+encodeURIComponent(c.svEmail));setTimeout(function(){n(g,svGlobal.onloggedin)},5);return!1}};function startExitingApp(k){function g(c){n.addSurface(c);n.startExitingApp(k)}var n=svManager.getInstance();window.svOnSurfaceReady=g;var h=window.open("rail.html");h.svOnSurfaceReady=g;var h=hi5.$(k),c=h.parentNode;c.removeChild(h);c=c.parentNode;0==c.getElementsByTagName("input").length&&(c.dismiss(),n.checkRemaining(2E3))}
function getLoginURL(){return("https:"==location.protocol?"wss://":"ws://")+hi5.$("gateway").value+"/LOGIN?"}
window.addEventListener("load",function(k){function g(){k.preventDefault();var a=hi5.$("frmLogin").elements,b=a.user.value,e=a.pwd.value,b=getLoginURL()+"user="+encodeURIComponent(b)+"&pwd="+encodeURIComponent(e);(a=a.sharedSecret)&&a.value&&(b+="&sharedSecret="+encodeURIComponent(a.value));return svGlobal.auth.login(b)}function n(){window.__sparkUser=null;var a=hi5.$("frmLogin");a.elements.pwd.value="";a.style.display="block";hi5.$("frmConn").style.display="none";(a=svManager.getInstance())&&a.running()&&
a.close()}function h(a){var b=a.target;b.onclick=null;setTimeout(function(){b.onclick=h},300);q(b.id)}function c(){function a(a){e.addSurface(a);e.running()?e.startApp(b.exe,b.args,""):e.run()}var b=window.__sparkUser.server,e=svManager.getInstance();null==e&&(e=new svGlobal.Rdp2(b),e.sessionTimeout=9E5);window.svOnSurfaceReady=a;var f=window.open("rail.html");f.svOnSurfaceReady=a}function q(a,b,e){var f=window.__sparkUser,l=f.servers,p=l.length;f.server=null;window.sparkGateway=f.gateway;for(var m=
0;m<p;m++){var d=l[m];if(a==d.id){d=connvertServer(d);d.gateway=f.gateway;d.session=f.session;d.account=f.account;f.server=d;p=d.server_bpp;a=window.innerWidth;l=window.innerHeight;d.width=a;d.height=l;p||(p=16);d.width=a;d.height=l;d.color=p;break}}if(f.server){console.log("connecting to:"+f.server.id);(d=hi5.$("touchpad"))&&d.checked&&(f.server.touchpad=!0);if(d=hi5.$("keyboard"))d=parseInt(d.options[d.selectedIndex].value),0<d&&(f.server.keyboard=d);"undefined"==typeof b&&(b=(d=hi5.$("sameWindow"))&&
d.checked);if((d="app"==f.server.startProgram)&&hi5.browser.isMultitask&&!b)c();else if(b){var h=new Rdp2(f.server);hi5.$("login").style.display="none";h.addSurface(new svGlobal.LocalInterface);h.run();h.onclose=function(){if(e){window.__sparkUser=null;var a=hi5.$("frmLogin");a.elements.pwd.value="";a.style.display="block";hi5.$("frmConn").style.display="none"}else h.hide(),hi5.$("login").style.display="block"}}else window.open("rdpdirect.html")}else hi5.notifications.notify("Not a valid server")}
svGlobal.auth.beforelogin=function(){hi5.tool.disableInput()};svGlobal.auth.afterlogin=function(a){a||(hi5.notifications.notify(__svi18n.errorCode.connection),n());hi5.tool.enableInput()};svGlobal.onloggedin=function(a){hi5.tool.enableInput();if(a.error)hi5.notifications.notify(__svi18n.errorCode["S"+a.name]);else{hi5.$("frmLogin").style.display="none";hi5.$("frmConn").style.display="block";if(!0===a.isDomainUser){var b=hi5.$("settings");b&&b.parentNode.removeChild(b)}for(b=hi5.$("programs");b.hasChildNodes();)b.removeChild(b.firstChild);
var e=a.servers;if(!a.accessNotInList){var f=hi5.$("anyconn");f&&(f.style.display="none")}window.__sparkUser={session:a.session,account:hi5.$("user").value,gateway:hi5.$("gateway").value,servers:e};a=e.length;if(!(1>a)){for(var f="",l=0;l<a;l++){var c=e[l].server,m=e[l].id,c=e[l].displayName||m||c,d=e[l].icon;d||(d="rdp32.png");var k=document.createElement("div");k.className="icon";var g=document.createElement("img");g.src=d;g.id=m;g.alt=m;g.title=c;g.style.cursor="pointer";g.onclick=h;k.appendChild(g);
k.appendChild(document.createElement("br"));k.appendChild(document.createTextNode(c));b.appendChild(k);hi5.appcfg.startup&&m===hi5.appcfg.startup.server&&(f=m)}!f&&hi5.appcfg.startup&&(console.log("start up:"+hi5.appcfg.startup.server+" not found, use the first instead"),f=e[0].id);f&&q(f,!hi5.appcfg.startup.newWindow,!0)}}};(function(){hi5.$("user").focus();hi5.$("frmLogin").onsubmit=g;var a=hi5.$("anyconn");a&&(a.onclick=function(){window.open("rdp.html?gateway="+hi5.$("gateway").value)});if(a=
document.querySelector('input[name="showlogin"]'))a.onclick=n;a=hi5.browser.cookie2Obj();a.svEmail||(a=hi5.tool.queryToObj());if(a.svEmail||a.user){var b=hi5.$("frmLogin").elements;b.user.value=a.svEmail||a.user;b.pwd.value=(a.svSession?"fake":a.pwd)||"";a.gateway&&(b.gateway.value=a.gateway);(b.gateway.value&&b.user.value&&b.pwd.value||a.autoLogin)&&setTimeout(g,300)}var a=hi5.$("settings"),e=hi5.$("settingsDiv");a&&(a.onclick=function(){if(e){var a=new hi5.Lightbox(e);a.show();hi5.$("currPwd").focus()}});
if(a=hi5.$("frmSettings"))a.onsubmit=function(a){a.preventDefault();var b=a.target.elements;if(b.newPwd1.value!=b.newPwd2.value)hi5.notifications.notify(__svi18n.errorCode.pwdmatch);else{a=getLoginURL()+"_METHOD=post&action=put";var c=new WebSocket(a,"login");c.onmessage=function(a){var d=a.data;0==d.indexOf("00")?(c.send("00currPwd="+b.currPwd.value+"&newPwd="+b.newPwd1.value+"&user="+hi5.$("user").value),hi5.$("frmSettings").reset()):(a=JSON.parse(a.data),a.error&&hi5.notifications.notify(__svi18n.errorCode["S"+
a.name]),c.close())};e.dismiss&&e.dismiss();return!1}};(a=hi5.$("sameWindow"))&&(hi5.browser.isiOS||hi5.browser.isIE||hi5.browser.isChromeApp)&&(a.checked=!0);a=hi5.$("gateway");(b=a.value)||(b=hi5.appcfg.defaultPort?window.location.hostname+":"+hi5.appcfg.defaultPort:window.location.host);0==b.length&&(b="localhost");a.value=b;a=hi5.$("touchpadmode");hi5.browser.isTouch&&(a.style.display="");(a=hi5.$("user"))&&!a.value&&hi5.appcfg&&hi5.appcfg.domain&&(a.value=hi5.appcfg.domain+"\\");(function(){var a=
!1,b="";try{document.createElement("canvas").getContext("2d"),a=!0}catch(e){b="This browser does not support Canvas.\n\n"}var c=!("WebSocket"in window)&&!("MozWebSocket"in window),g=navigator.userAgent,d=-1!=g.indexOf("Firefox");c&&(b+="This browser doesn't support WebSocket.\n\n",d?b+="Please update to Firefox 6 or later.\n\n":-1!=g.indexOf("Opera")?b+="Please open 'opera:config#Enable WebSockets' (type it in the link field) make 'Enable WebSockets' selected and restart Opera.\n\n":-1!=g.indexOf("MSIE")&&
(b+="Please install Google Chrome Frame.\n\n"));0<b.length&&hi5.notifications.notify(b);return!c&&a})();(a=hi5.$("defPort"))&&hi5.appcfg.defaultPort&&(a.innerHTML=hi5.appcfg.defaultPort)})()},!1);
