var wsRdp=null;
function websocketData(a){var b=a.data;switch(b.type){case 0:switch(b.cmd){case 0:initialize(b.data);break;case 1:setBpp(b.data);break;case 2:setResolution(b.data);break;case 3:restoreVar();break;case 4:if(wsRdp)wsRdp.close();setTimeout(function(){close()},50);break;case 5:wsRdp.setAudioFormat(b.data);break;case 6:if(b.start)wsRdp.onSlowPath=wsRdp.onFastPath=function(){_dataReceived.id=1;self.postMessage(_dataReceived)};else wsRdp.onSlowPath=wsRdp.onFastPath=null;break;default:console.log("invalid cmd:"+b.cmd);
console.log(b)}break;case 5:wsRdp.writeRawInput(b.data);break;case 6:localFilePlayer.onmessage(b);break;default:console.log("Invalid msg type: "+b.type);console.log(b)}}function FilePlayerProxy(){this.onmessage=function(){};this.onclose=function(){};this.onopen=function(){}}var localFilePlayer=new FilePlayerProxy;self.addEventListener("message",websocketData,false);var _cursorMov={type:1,event:6,x:0,y:0};
var _cursor={type:9,cache_idx:0,rawData:null,none:false,hotX:0,hotY:0,width:0,height:0,xorSize:0,andSize:0,result:"",distance:0,bpp:0,system:""};var _msgData={type:10,data:null};var _altSecData={type:11,data:null,size:0};var _dataReceived={type:1,event:8,id:0};
function initialize(a){var b=a.libPath;var g=a.libMin!==false?"_min.js":".js";importScripts(b+"hi5core"+g);importScripts(b+"rdpcore"+g);if(a.addr)wsRdp=new RdpGeneral(a.addr,a.width,a.height,a.server_bpp,new DisplayBufferWrapper,true,a.wsPost);else wsRdp=new RdpGeneral(localFilePlayer,a.width,a.height,a.server_bpp,new DisplayBufferWrapper,true,false);if(a.updateFix)wsRdp.enableUpdateFix();wsRdp.onopen=function(){self.postMessage({type:1,event:0})};wsRdp.onclose=function(a){self.postMessage({type:1,
event:1,"expected":a})};wsRdp.onerror=function(a){self.postMessage({type:1,event:2,"code":a})};wsRdp.oninfo=function(a){self.postMessage({type:1,event:3,"code":a})};wsRdp.onloggedin=function(a){self.postMessage({type:1,event:4})};wsRdp.onHistoryReceived=function(){_dataReceived.id=0;self.postMessage(_dataReceived)};wsRdp.onReqHistory=function(){_dataReceived.id=3;self.postMessage(_dataReceived)};wsRdp.onresolutionchange=function(a,b){self.postMessage({type:1,event:5,"w":a,"h":b})};wsRdp.onMoveCursor=
function(a,b){_cursorMov.x=a;_cursorMov.y=b;self.postMessage(_cursorMov)};wsRdp.onCloseSurface=function(a,b){self.postMessage({type:1,event:6})};wsRdp.onColorChange=function(a){self.postMessage({type:1,event:9,color:a})};wsRdp.onAltSecWindows=function(a,b){_altSecData.data=a.getBytes(b);_altSecData.size=b;self.postMessage(_altSecData,[_altSecData.data.buffer])};wsRdp.onmessage=function(a){_msgData.data=a.data;if(typeof _msgData.data!="string")self.postMessage(_msgData,[_msgData.data]);else self.postMessage(_msgData)};
wsRdp.run()}function setResolution(a){if(wsRdp)wsRdp.setResolution(a.w,a.h)}function setBpp(a){if(wsRdp)wsRdp.setColor(a)}function restoreVar(){if(wsRdp)wsRdp.resetStatus()}
function DisplayBufferWrapper(){var a={type:2,x:0,y:0,w:0,h:0,pixel:null,offset:0,scansize:0};var b={type:3,srcx:0,srcy:0,cx:0,cy:0,dx:0,dy:0};var g={type:5,l:0,t:0,w:0,h:0,color:0};var l={type:6,x1:0,y1:0,x2:0,y2:0,color:0};var e={type:7,opcode:0,dstwidth:0,x:0,y:0,cx:0,cy:0,src:0,srcwidth:0,srcx:0,srcy:0};var m={type:8,x1:0,y1:0,x2:0,y2:0,color:0,opcode:0};var c={type:12,font:0,flags:0,mixmode:0,foregroundColor:0,backgroundColor:0,clipLeft:0,clipTop:0,clipcx:0,clipcy:0,boxLeft:0,boxTop:0,boxcx:0,
boxcy:0,x:0,y:0,length:0,text:null,_left:0,_top:0,_right:0,_bottom:0};var k={type:13,cacheID:0,cacheIDX:0,x:0,y:0,cx:0,cy:0,srcx:0,srcy:0,opcode:0};var d={type:14,x:0,y:0,cx:0,cy:0,offset:0};var p={type:16,font:0,character:0,glyph:null};var h={type:17,idx:0,cursor:null};var n={type:20,order:0,data:null,off:0};var q={type:21,id:0,idx:0,bitmap:null};this.setRGBs=function(b,r,t,c,f,d,e){a.x=b;a.y=r;a.w=t;a.h=c;a.pixel=f;a.offset=d;a.scansize=e;self.postMessage(a,[f.buffer])};this.moveArea=function(a,
r,t,c,f,d){b.srcx=a;b.srcy=r;b.cx=t;b.cy=c;b.dx=f;b.dy=d;self.postMessage(b)};this.fillRect=function(a,b,c,d,f){g.l=a;g.t=b;g.w=c;g.h=d;g.color=f;self.postMessage(g)};this.drawLine=function(a,b,c,d,f){l.x1=a;l.y1=b;l.x2=c;l.y2=d;l.color=f;self.postMessage(l)};this.bitBlt=function(a,b,c,d,f,k,g,h,l,m){e.opcode=a;e.dstwidth=b;e.x=c;e.y=d;e.cx=f;e.cy=k;e.src=g;e.srcwidth=h;e.srcx=l;e.srcy=m;self.postMessage(e)};this.drawLineExt=function(a,b,c,d,f,e){m.opcode=e;m.x1=a;m.y1=b;m.x2=c;m.y2=d;m.color=f};
this.drawText=function(a,b,d,e,f,k,g,h,l,m,n,p,q,u,v,w,x,y,z,A,B){c.font=a;c.flags=b;c.mixmode=d;c.foregroundColor=e;c.backgroundColor=f;c.clipLeft=k;c.clipTop=g;c.clipcx=h;c.clipcy=l;c.boxLeft=m;c.boxTop=n;c.boxcx=p;c.boxcy=q;c.x=u;c.y=v;c.length=w;c.text=x;c._left=y;c._top=z;c._right=A;c._bottom=B;self.postMessage(c)};this.drawBitmap=function(a,b,c,d,f,e,g,h,l){k.cacheID=a;k.cacheIDX=b;k.x=c;k.y=d;k.cx=f;k.cy=e;k.srcx=g;k.srcy=h;k.opcode=l;self.postMessage(k)};this.saveDesktop=function(a,b,c,e,
f){d.type=14;d.x=a;d.y=b;d.cx=c;d.cy=e;d.offset=f;self.postMessage(d)};this.restoreDesktop=function(a,b,c,e,f){d.type=15;d.x=a;d.y=b;d.cx=c;d.cy=e;d.offset=f;self.postMessage(d)};this.putFont=function(a,b,c){p.font=a;p.character=b;p.glyph=c;self.postMessage(p,[c.fontData.buffer])};this.putCursor=function(a,b){h.type=17;h.idx=a;h.cursor=b;if(b.rawData)self.postMessage(h,[b.rawData.buffer]);else self.postMessage(h)};this.setCursor=function(a){h.type=18;h.idx=a;h.cursor=null;self.postMessage(h)};this.getHistory=
function(){self.postMessage({type:19})};this.setHistory=function(a,b){n.order=a;n.data=b.getData();n.off=b.getPosition();self.postMessage(n,[n.data.buffer])};this.putBitmap=function(a,b,c){q.id=a;q.idx=b;q.bitmap=c;self.postMessage(q,[c.data.buffer])}};
