var svManager={getInstance:function(){var c=window.$ssh;return c&&c.running&&c.running()?c:null}};function connvertServer(c){var u={};u.id=c.id;u.server=c.id;u.displayName=c.displayName||c.id;if(c=c.ssh){for(var w in c)u[w]=c[w];u.user=c.username||"";u.pwd=c.password||""}return u}
svGlobal.SSH=function(c,u,w,v){function va(b,a){var y=[],e=null,g=new hi5.graphic.Rectangle(0,0,0,0),d="Uint8ClampedArray"in window;this.width=b;this.height=a;var c=!1,f=this;this.pause=function(a){c=a};this.release=function(){y=e=f=null};this.isPaused=function(){return c};this.setContext=function(a){a!=e&&(e||!a||a.createImageData(1,1).data.buffer||(d=!1),e=a)};this.getContext=function(){return e};this.resize=function(e,g){for(var d=0;d<g;d++)y[d]=new Uint32Array(e);f.width=b=e;f.height=a=g};f.resize(b,
a);this.getBuffer=function(){return y};this.setRGB=function(a,b,e){y[b][a]=e|4278190080};this.getRGB=function(a,b){return y[b][a]};this.setRGBs=function(a,b,e,g,d,c,f){var k=0,r=0;e=a+e;g=b+g;for(var h=y,l=b;l<g;l++,c+=f)for(r=c,b=h[l],k=a;k<e;k++)b[k]=d[r++]};this.moveArea=function(a,b,e,g,d,c){if(0<c){d=a+d;c=b+c;var f=y,k,r,h;for(k=g-1;0<=k;k--)for(r=f[c+k],h=f[b+k],g=0;g<e;g++)r[d+g]=h[a+g]}else if(0>c){d=a+d;c=b+c;var f=y,l;for(r=0;r<g;r++)for(h=f[c+r],l=f[b+r],k=0;k<e;k++)h[d+k]=l[a+k]}else if(0<
d)for(d=a+d,c=b+c,f=y,--e;0<=e;e--)for(r=d+e,h=a+e,k=0;k<g;k++)f[c+k][r]=f[b+k][h];else for(d=a+d,c=b+c,f=y,k=0;k<e;k++)for(h=d+k,l=a+k,r=0;r<g;r++)f[c+r][h]=f[b+r][l]};this.getRGBs=function(a,b,e,d){var g=_Uint32Array(e*d);g[0]=0;var k=y;e=a+e;d=b+d;for(var c=0,f=b;f<d;f++)for(b=a;b<e;b++)g[c++]=k[f][b];return g};this.repaint=function(g,c,f,r){if(e){0>g&&(f+=g,g=0);0>c&&(r+=c,c=0);g+f>b&&(f=b-g);c+r>a&&(r=a-c);var h=e.createImageData(f,r),l=h.data;f=g+f;r=c+r;var n=0,q=y;if(d)for(var l=new Uint32Array(l.buffer),
m,p=c;p<r;p++)for(m=g;m<f;m++)l[n++]=q[p][m];else for(var t,u,p=c;p<r;p++)for(m=g;m<f;m++)t=q[p][m],u=n<<2,l[u]=t&255,l[u+1]=t>>8&255,l[u+2]=t>>16&255,l[u+3]=255,n++;e.putImageData(h,g,c)}};this.postPaint=function(a,b,e,d){0<g.width?g.union(a,b,e,d):(g.x=a,g.y=b,g.width=e,g.height=d)};this.commitPaint=function(){0<g.width&&(this.repaint(g.x,g.y,g.width,g.height),g.width=0)};this.fillRect=function(a,b,e,g,d){var c=y;e=a+e;g=b+g;for(var f=b;f<g;f++)for(b=a;b<e;b++)c[f][b]=d}}function ma(b,a){F?F.resize(b,
a):F=new va(b,a);return F}function na(){var b=c.indexOf("://"),a=c.substring(b+3),b=a.indexOf("/");0<b&&(a=a.substring(0,b));return location.protocol+"//"+a}function wa(b){return sessionId?hi5.browser.httpGet(na()+"/CLIP?s="+sessionId+"&t="+(new Date).getTime(),!1):""}function da(b,a){var c=b-z,e=a-z,g=Math.floor(e/f),k=Math.floor(c/p),r=null;if(A)var r=Math.min(k*p+z,B*p+z),m=Math.min(g*f+z,V*f+z),r=h.getImageData(0,0,r,m);u=c;w=e;C.setSize(b,a);h.font=l.fontSize+"px Courier New";oa();r&&h.putImageData(r,
0,0);V=g;B=k;H=Math.floor(w/f);if(d.onresolutionchange)d.onresolutionchange(u,w)}function xa(){this.ws=null;this.setJoinMode=d.setJoinMode;this.requestControl=d.requestControl;this.writeKeyComb=d.writeKeyComb;this.getAppMode=function(){return d.mode};this.send=function(a){"891"!=a&&A&&this.ws.send(a)};this.sendInput=function(a){d.writeRawInput(a);if(d.onactivity)d.onactivity(a)};var b=null;this.getAppInfo=function(){return d.sessionInfo.appInfo};this.onresize=function(a){if(a=a.target.svSurface){a=
a.getFreeSpace();var d=a.width,e=a.height;hi5.browser.isTouch||hi5.browser.isOpera||!A||(a=function(){da(d,e);var a=u,b=w,c=0,h=0,c=parseInt(a/p),h=parseInt(b/f);q.send("ED"+c+"\t"+h+"\t"+a+"\t"+b)},b&&(clearTimeout(b),b=null),b=setTimeout(a,200))}};this.onorientationchange=function(a){};this.getClipData=wa;this.onfocus=function(a){};this.fileCallback=[];this.getShareFiles=function(a,b){loggedin&&(this.ws.send("3A5"+a),this.fileCallback.push(b))};this.notifyFiles=function(a){for(var b=this.fileCallback,
e=0,g=b.length;e<g;e++)b[e](a)};this.getFile=function(a){window.open(d.getFileUrl(a))};this.removeFile=function(a){uploadMgr&&uploadMgr.fileService.remove(a)};this.getFileLink=function(a){return na()+"/DOWNLOAD?s="+sessionId+"&f="+a};this.getGateway=function(){return c};this.reconnect=function(a,b,e){}}function ea(b){return"on"==b||"true"==b}function pa(b,a,d){this.need=b;this.handler=a;this.repeat=d||1}function ya(b){var a=0,d=0,e=new Uint8Array(b),g=this,c=new pa(0,null,0);this.release=function(){g=
e=c=null};this.getHandler=function(){return c};this.getData=function(){return e};this.getPosition=function(){return a};this.setPosition=function(b){a=b};this.getEnd=function(){return d};this.set=function(b,g,c){e=b;a=g;d=c};this.handle=function(){c.handler(g,c)};this.setHandler=function(b){b&&1>b.need&&svGlobal.logger.warn("need < 1");(c=b)&&d-a>=b.need&&b.handler(g,b)};this.getByte=function(){return e[a++]};this.peekByte=function(){return e[a]};this.getBE32=function(){return e[a++]<<24|e[a++]<<16|
e[a++]<<8|e[a++]};this.getBE16=function(){return e[a++]<<8|e[a++]};this.skip=function(b){a+=b};this.skipBack=function(b){a-=b};this.getBytes=function(b,d){if(d)for(var g=0;g<b;g++)d[g]=e[a++];else return g=a,a+=b,e.subarray(g,a)};this.copyToByteArray=function(a,b,g,d){hi5.Arrays.arraycopy(e,g,a,b,d)}}function za(){if(!A){if(fa)q=fa,ga();else{qa();var b=c+="&cols="+B+"&rows="+V,a=hi5.browser.binaryWS();a&&(b+="&binary=on");var h=window.opener;if(h){a=null;try{a=h.__sparkUser}catch(e){}a&&(h=a.account,
a=a.session,h&&(b+="&account="+h),a&&(b+="&session="+a))}a=hi5.browser.isChrome&&hi5.browser.isDesktop;c=b+("&pasteCap="+(a?3:0));b=0==d.mode&&hi5.appcfg.wsPost?c.substring(0,c.indexOf("?"))+"?_METHOD=post":c;q=new WebSocket(b,"ssh");q.binaryType="arraybuffer"}ha.ws=q;svGlobal.logger.info(c);q.onopen=Aa;void 0!=l.recording&&"on"==l.recording&&Ba(l);q.onmessage=function(a){a=a.data;if("string"!=typeof a){var b=new Uint8Array(a);null!=K&&K.add(new RecordingObj(b,0,a.byteLength));S.set(b,0,a.byteLength);
S.handle()}else{var b=parseInt(a.substring(0,2),16),k=a.substring(2);switch(b){case 0:a=c.substring(c.indexOf("?")+1);q.send("00"+a);q.send("87"+navigator.userAgent);break;case 15:if(d.onready)d.onready();if(d.onloggedin)d.onloggedin();break;case 26:b=k;a=JSON.parse(b);if(a.name){svGlobal.logger.info("msg="+b);if(d.onerror)d.onerror(a);b=__svi18n.errorCode["S"+a.name]||"";b+=a.message;d.showMessage(b)}else 0<svGlobal.log&&console.erro("No error code for message:"+b);break;case 27:0!=hi5.appcfg.drawLicense&&
C.drawLicense(k);break;case 56:b=a=JSON.parse(k);sessionId=a.session;b.server=d.server;if(k=hi5.$("joinSelect"))k.value=b.joinMode;if(k=hi5.$("requestControl"))k.disabled=b.hasControl;var k=hi5.appcfg.page&&hi5.appcfg.page.joinssh||"joinssh.html",k=location.protocol+"//"+location.host+"/"+k+"?id="+a.numericId,h=a.webAddress;if(h&&0<h.length){var y=h.indexOf("://"),h=h.substring(y+3),y=h.indexOf("/");0<y&&(h=h.substring(0,y));h.toLowerCase()!=location.host.toLowerCase()&&(k+="&gateway="+h)}b.joinLink=
k;d.sessionInfo.appInfo=b;a.ver&&a.ver!=svGlobal.version&&svGlobal.logger.warn("Client:"+svGlobal.version+" server:"+a.ver);ga();if(d.onsessionstart)d.onsessionstart(d.sessionInfo);break;case 59:break;case 61:a=JSON.parse(k);switch(a.type){case 0:l.fontSize=parseInt(a.fontSize);u=a.width;w=a.height;ga();C.setAutoScale(!0);da(u+z,w+z);if(b=a.server)d.server=a.server,d.setTitle&&(document.title=l.displayName||d.server);ra=a.length;if(d.onopened)d.onopened(a);break;case 1:a=a.duration;if(d.onprogress)d.onprogress(a,
ra);break;case 2:2==a.status?A=!0:(b=0==a.status,F.pause(b),a.warn&&d.showMessage(b?__svi18n.info.sessionPaused:__svi18n.info.sessionResumed))}break;case 62:Ca(k);break;case 91:W(__svi18n.info.user||k);N=!0;break;case 93:m+=f;n=t;W(__svi18n.info.password||k);X=!0;break;default:svGlobal.logger.warn("@TODO:"+a+"\n")}}};q.onclose=ba;q.onerror=Da}}function Ba(b){K=new RecordingManager;var a=0<b.user.length?b.server+"_"+b.user:b.server;b={name:a,width:b.width,height:b.height,color:b.fontSize,namesuffix:".sshv",
filetag:"SSHV",duration:0};K.setHeader(b)}function Ca(b){var a=parseInt(b.substring(0,1),16),c,e;c=b.substring(1);b=!1;var g=d.sessionInfo.appInfo;switch(a){case 1:e=JSON.parse(c);d.onsessionjoin&&(b=d.onsessionjoin(e));if(b)break;d.showMessage(__svi18n.info.joinsession.applyArgs([e.numericId,e.__ip,e.name]));break;case 2:e=JSON.parse(c);d.onsessionexit&&(b=d.onsessionexit(e));if(b)break;d.showMessage(__svi18n.info.exitsession.applyArgs([e.numericId,e.__ip,e.name]));break;case 3:e=JSON.parse(c);g.joinMode!=
e.mode&&(g.joinMode=e.mode,c=hi5.$("joinSelect"))&&(c.value=e.mode);if(g.hasControl)break;C.setReadOnly(!1);if(c=hi5.$("requestControl"))c.disabled=!0;d.ongivecontrol&&(b=d.ongivecontrol());if(b)break;d.showMessage(__svi18n.info.givecontrol);break;case 4:C.setReadOnly(!0);g.hasControl=!1;if(c=hi5.$("requestControl"))c.disabled=!1;d.ontakebackcontrol&&(b=d.ontakebackcontrol());if(b)break;d.showMessage(__svi18n.info.nocontrol);break;case 5:a=function(){d.refuseControl(e.numericId);this.destroy()};g=
function(){d.giveControl(e.numericId);this.destroy()};e=JSON.parse(c);d.onrequirecontrol&&(b=d.onrequirecontrol(e));if(b)break;b=__svi18n.info.title.applyArgs([e.name,e.numericId,e.__ip]);hi5.notifications.notify({title:b,msg:__svi18n.info.recontrol,cbYes:g,cbNo:a});break;case 6:C.setTouchRemoting(!0);break;case 7:e=JSON.parse(c);e.width&&e.height&&(F=ma(e.width,e.height),da(e.width+z,e.height+z));break;case 8:e=JSON.parse(c);if(d.onrequestcredential&&d.onrequestcredential(e))break;C.requestCredential(e);
break;case 11:a=function(){d.allowJoin(e.numericId,!1);this.destroy()};g=function(){d.allowJoin(e.numericId,!0);this.destroy()};e=JSON.parse(c);d.onrequirejoin&&(b=d.onrequirejoin(e));if(b)break;b=__svi18n.info.title.applyArgs([e.name,e.numericId,e.__ip]);hi5.notifications.notify({title:b,msg:__svi18n.info.reqjoin,cbYes:g,cbNo:a})}}function Aa(b){svGlobal.logger.info("opened...");A=!0;q.send("87"+navigator.userAgent);if(d.onopen)d.onopen()}function Da(b){svGlobal.logger.warn(b)}function ba(b){svGlobal.logger.warn("closed ...");
P.style.display="none";A=!1;if(d&&d.onclose)d.onclose();try{null!=K&&(K.exit(),K=null),C&&C.close(),I&&I.visible()&&(I.dismiss(),I=null)}catch(a){}S&&(S.release(),S=null);h=null;q&&(q.onopen=null,q.onmessage=null,q.onclose=null,q=q.onerror=null);C=ha=null;F&&(F.release(),F=null);d&&(d=null);window&&window.$ssh&&(window.$ssh=null);null!=K&&(K.exit(),K=null)}function qa(){10>l.fontSize&&(l.fontSize=10);12>=l.fontSize?(f=l.fontSize+6,Y=2):13<=l.fontSize&&18>l.fontSize?(f=l.fontSize+8,Y=2):19<=l.fontSize&&
25>l.fontSize?(f=l.fontSize+12,Y=3):25<=l.fontSize&&(f=l.fontSize+16,Y=4);h.font=l.fontSize+"px Courier New";p=h.measureText("X").width;H=parseInt(w/f);V=parseInt(w/f);B=parseInt(u/p)}function ga(){oa();n=t;m=D;qa();remotectrl.style.cursor="text";null==P&&(P=document.getElementById("cursorID"),P.style.display="block",P.style.width=p+"px",P.style.height=f+"px")}function ia(){n-=p;n<t&&(n=t);L()}function T(b){sa=b;h.fillStyle=ja[b]}function oa(){h.fillStyle="black";h.fillRect(0,0,h.canvas.width,h.canvas.height);
h.fillStyle="white"}function L(){P.style.top=m+"px";P.style.left=n+"px"}function W(b){U=b.length;h.fillStyle=ja[Q];h.fillRect(n,m,p*U,f);h.fillStyle=ja[sa];h.fillText(b,n,m+f-3*Y);n+=U*p;n>t+(B-1)*p&&(n=t+(B-1)*p);I&&(J+=b);L()}function Ea(b){if(A)return(b=b.getData("text/plain"))?(b=b.replace(/\r\n/g,"\n"),M(!1,b,3),!0):!1}function Fa(){I&&Z&&!I.visible()&&(Z.value=J,I.show(),setTimeout(function(){Z.scrollTop=Z.scrollHeight},10))}function M(b,a,c){29==aa&&68==a&&b?d.close():N||X?(b=a,28==b?(q.send((N?
"5B":"5D")+R),R="",N?N=!1:(X=!1,m+=f,n=t)):14==b&&0<R.length&&(R=R.substring(0,R.length-1),N&&(ia(),W(" "),ia()))):q.send("8B"+c+"\t"+a);aa=a}sessionStorage&&sessionStorage.clear();hi5.appcfg.copyDialog=!0;var Z=document.getElementById("copytextarea"),I=Z?new hi5.Lightbox(document.getElementById("copydialog")):null,J="";this.displayMsg=!0;this.reconnectTimes=0;this.setTitle=this.openLink=!0;this.mode=0;var fa="object"==typeof c?c:null,ta="object"==typeof c||0<c.indexOf("/PLAY?");ta?(this.mode=1,fa&&
(c=""),c+="&touchpad=on"):0<c.indexOf("/JOIN?")&&(this.mode=2,this.reconnectOnResize=!1);var l=hi5.tool.queryToObj(c.substring(c.indexOf("?")+1));l.color||(l.color=32);this.server=l.server;this.port=parseInt(l.port,10);this.sessionInfo={major:0,minor:0,width:0,height:0,bpp:0,bigEndian:!0,trueColor:!0};var C=null,A=!1,z=5,E=0,x=[],O=0,t=z,D=z,n=0,m=0,p=0,f=18,Y=0,sa=7,Q=0,ua=8,G=1,H=24,P=null,V=0,B=0,U=0,aa=0,ka=!1,la=!1,K=null;window.$ssh=this;var S=new ya(4194304);this.__que=S;this.running=function(){return A};
var d=this,q=null;u||(u=window.innerWidth);u-=z;l.width=u;c+="&width="+u;w||(w=window.innerHeight);w-=z;l.height=w;c+="&height="+w;l.fontSize?l.fontSize=parseInt(l.fontSize,10):(v||(v=13),l.fontSize=v,c+="&fontSize="+v);var ja="black red green yellow blue magenta cyan white".split(" "),F=ma(u,w),h=F.getContext(),ha=new xa;if(hi5.appcfg){v=hi5.appcfg;var ca="undefined";typeof v.displayMsg!=ca&&(this.displayMsg=v.displayMsg);typeof v.reconnectTimes!=ca&&(this.reconnectTimes=v.reconnectTimes);typeof v.openLink!=
ca&&(this.openLink=v.openLink);typeof v.setTitle!=ca&&(this.setTitle=v.setTitle);"boolean"==typeof v.useWSS&&(c=(hi5.appcfg.useWSS?"wss":"ws")+c.substring(c.indexOf("://")))}this.getURL=function(){return c};var Ga=parseInt(l.server_bpp||l.color||24);this.getColor=function(){return Ga};this.setJoinMode=function(b){A&&q.send("8E1"+b)};this.refuseControl=function(b){A&&q.send("8E3"+b)};this.giveControl=function(b){A&&q.send("8E4"+b)};this.requestControl=function(){A&&q.send("8E2")};this.play=function(){q.send("F3")};
this.pause=function(){q.send("F2")};this.scan=function(b){q.send("F4"+(b?"1":"0"))};this.seek=function(b){C&&A&&(q.send("F4"+(b?"1":"0")+"\t"+(b/C.getScale()|0)),F.pause(!0))};var N=!1,X=!1,R="",ra=0;this.run=function(){za()};this.hide=function(){C&&("block"==document.getElementById("cursorID").style.display&&(document.getElementById("cursorID").style.display="none"),C.hide())};this.showMessage=function(b){d.displayMsg&&b&&hi5.notifications.notify({msg:b})};this.close=function(){if(q&&A)try{q.send("85"),
q.close()}catch(b){}else ba()};hi5.browser.isChromeApp?chrome.runtime.onSuspend.addListener(ba):window.addEventListener("unload",ba,!1);v=new pa(1024,function(b){for(var a,c=!0;c;)if(a=b.getByte(),void 0==a)c=!1;else if(0!=a)if(13==a)n=t,m>D+(H-1)*f&&(m=D+(H-1)*f),L();else if(27==a)if(a=b.getByte(),77==a)a=h.getImageData(t,D+(G-1)*f,B*p,(H-G)*f),h.fillStyle="black",h.fillRect(0,D+(G-1)*f,B*p,f),h.putImageData(a,t,D+G*f),h.fillStyle="white";else if(68==a)a=h.getImageData(t,G*f+D,B*p,(H-G)*f),h.fillStyle=
"black",h.fillRect(t,H*f-f+D,B*p,f),h.putImageData(a,t,(G-1)*f+D),h.fillStyle="white";else{if(55!=a){if(40==a)if(a=b.getByte(),66==a)if(a=b.getByte(),27==a)if(a=b.getByte(),41==a)if(a=b.getByte(),48==a)continue;else b.skipBack(1);else b.skipBack(1);else b.skipBack(1);else b.skipBack(1);if("0x5b"==a){E=0;for(O=x[E]=0;;)if(a=b.getByte(),59==a)0<O&&(E++,O=x[E]=0);else if(48<=a&&57>=a)x[E]=10*x[E]+(a-48),O++;else{b.skipBack(1);break}a=b.getByte();if(109==a)if(0==O&&0==E)a=b.getByte(),15==a?(T(7),Q=0):
(T(7),Q=0,b.skipBack(1));else for(a=0;a<=E;a++)switch(x[a]){case 0:0==E?(T(7),Q=0):0==a?T(0):Q=0;break;case 7:0==E?(T(7),Q=0):0==a?T(7):Q=7;continue;case 30:case 31:case 32:case 33:case 34:case 35:case 36:case 37:T(x[a]-30);break;case 40:case 41:case 42:case 43:case 44:case 45:case 46:case 47:Q=x[a]-40}else if(114==a)a=x[1],G=x[0],H=a;else if(72==a)0==O&&0==E&&(x[0]=x[1]=1),a=x[0],n=(x[1]-1)*p+t,n<t&&(n=t),m=(a-1)*f+D,L();else if(66==a)m+=x[0]*f,I&&(J+="\n"),L();else if(68==a)n-=x[0]*p,L();else if(67==
a)0==O&&0==E&&(x[0]=1),n+=x[0]*p,L();else if(65==a)0==O&&0==E&&(x[0]=1),m-=x[0]*f,L();else{if(63==a)if(a=b.getByte(),49==a)if(a=b.getByte(),108==a||104==a){if(a=b.getByte(),27==a&&(a=b.getByte(),">"==a||"="==a))continue}else{if(104==a&&(a=b.getByte(),27==a&&(a=b.getByte(),61==a)))continue}else if(55==a){a=b.getByte();if(104==a)continue;else if(49==a)continue;b.skipBack(1);a=55}75==a?(0==O&&0==E?(h.fillStyle="black",h.fillRect(n,m,B*p-n+t,f)):(h.fillStyle="black",h.fillRect(t,m,n,f)),h.fillStyle="white"):
74==a&&(h.fillStyle="black",h.fillRect(n,m,B*p-n+t,V*f-m+D),h.fillStyle="white")}}}}else if(7!=a)if(9==a)a=(n-t)/p/ua,a*=1,a=parseInt(a)+1,n=a*ua*p+t,n>=B*p&&(n=t,m+=f,I&&(J+="\n")),L();else if(15!=a)if(8==a)ia();else if(10==a){if(m+=f,I&&(J+="\n"),n>=B*p&&(n=t,m+=f,I&&(J+="\n")),m>(H-1)*f+D){for(;m>(H-1)*f+D;)m-=f;L();a=h.getImageData(t,D+(G-0)*f,B*p,(H-G)*f);h.fillStyle="black";h.fillRect(t,D+(G-1)*f,B*p,(H-G+1)*f);h.putImageData(a,t,D+(G-1)*f);h.fillStyle="white"}}else{if(void 0!=a&&10!=a){b.skipBack(1);
a=b;var e="",d=a.getPosition(),k=void 0;U=0;for(var l=[];d<a.getEnd();)if(k=a.getByte(),32<=k&&255>=k)e+=String.fromCharCode(k),d++,l[U++]=k;else{13!=k&&27!=k&&8!=k&&9!=k||a.skipBack(1);break}if(0<U)for(a=l,e="",k=c1=c2=d=0;d<a.length;)k=a[d],128>k?(e+=String.fromCharCode(k),d++):191<k&&224>k?(c2=a[d+1],e+=String.fromCharCode((k&31)<<6|c2&63),d+=2):(c2=a[d+1],c3=a[d+2],e+=String.fromCharCode((k&15)<<12|(c2&63)<<6|c3&63),d+=3,U--);a=e;W(a)}b.getPosition()>=b.getEnd()&&(c=!1)}});S.setHandler(v);this.addSurface=
function(b){C=b;ta&&b.setPlayerMode();F.setContext(C.context);h=F.getContext();b.alwaysPaste=!0;b.setAutoScale(0<d.mode);b.setSize(u+z,w+z);b.setController(ha);b.setFastCopy(ea(l.fastCopy));b.setTouchpad(ea(l.touchpad));b.setClipboard(ea(l.mapClipboard));b.run(99997);b.onclipdata=Ea};v=new Uint8Array(6);v[0]=5;v=new Uint8Array(8);v[0]=4;this.writeRawInput=function(b){if(A){var a=parseInt(b.substring(0,2),16);b=b.substring(2).split("\t");var c=0,e=!1;switch(a){case 128:a=b[2];2==a&&Fa();return;case 129:return;
case 130:return;case 131:M(!0,0==b[2]?200:208,0);return;case 132:e=0==b[0];c=parseInt(b[1]);29==c&&(ka=e);56==c&&(la=e);if(0==b[0]){if(69==c)return;M(e,c,0)}else 42==b[1]?M(!1,42,2):29==b[1]&&M(!1,29,2);return;case 139:if(0==b[0]){if(ka&&la)return;c=parseInt(b[1]);N||X?29==aa&&68==c&&d.close():(ka&&29!=aa&&M(!0,29,0),la&&56!=aa&&M(!0,56,0),M(!0,c,1))}return;case 134:c=b[0].charCodeAt(0);N||X?(a=String.fromCharCode(c),R+=a,N&&W(a)):47==c?M(!0,191,1):(160==c&&(b[0]=" "),M(!1,b[0],3));return}svGlobal.logger.warn("Unknowncode: "+
b[1]+" type:"+a)}}};
