var svManager={getInstance:function(){var c=window.$ssh;return c&&c.running&&c.running()?c:null}};function connvertServer(c){var t={};t.id=c.id;t.server=c.id;t.displayName=c.displayName||c.id;if(c=c.ssh){for(var v in c)t[v]=c[v];t.user=c.username||"";t.pwd=c.password||""}return t}
svGlobal.SSH=function(c,t,v,y){function qa(b,a){var f=[],d=null,g=new hi5.graphic.Rectangle(0,0,0,0),r="Uint8ClampedArray"in window;this.width=b;this.height=a;var c=!1,e=this;this.pause=function(a){c=a};this.isPaused=function(){return c};this.setContext=function(a){a!=d&&(d||!a||a.createImageData(1,1).data.buffer||(r=!1),d=a)};this.getContext=function(){return d};this.resize=function(g,d){for(var r=0;r<d;r++)f[r]=new Uint32Array(g);e.width=b=g;e.height=a=d};e.resize(b,a);this.getBuffer=function(){return f};
this.setRGB=function(a,b,g){f[b][a]=g|4278190080};this.getRGB=function(a,b){return f[b][a]};this.setRGBs=function(a,b,g,d,r,c,u){if(r){var e=0,m=0;g=a+g;d=b+d;for(var k=b;k<d;k++,c+=u)for(m=c,b=f[k],e=a;e<g;e++)b[e]=r[m++]}else console.log("pixel null")};this.moveArea=function(a,b,g,d,r,c){if(0<c){r=a+r;c=b+c;var e,u,m;for(e=d-1;0<=e;e--)for(u=f[c+e],m=f[b+e],d=0;d<g;d++)u[r+d]=m[a+d]}else if(0>c){r=a+r;c=b+c;var k;for(u=0;u<d;u++)for(m=f[c+u],k=f[b+u],e=0;e<g;e++)m[r+e]=k[a+e]}else if(0<r)for(r=
a+r,c=b+c,--g;0<=g;g--)for(u=r+g,m=a+g,e=0;e<d;e++)f[c+e][u]=f[b+e][m];else for(r=a+r,c=b+c,e=0;e<g;e++)for(m=r+e,k=a+e,u=0;u<d;u++)f[c+u][m]=f[b+u][k]};this.getRGBs=function(a,b,g,d){var r=_Uint32Array(g*d);r[0]=0;g=a+g;d=b+d;for(var e=0,c=b;c<d;c++)for(b=a;b<g;b++)r[e++]=f[c][b];return r};this.repaint=function(g,e,c,m){if(d){0>g&&(c+=g,g=0);0>e&&(m+=e,e=0);g+c>b&&(c=b-g);e+m>a&&(m=a-e);var k=d.createImageData(c,m),h=k.data;c=g+c;m=e+m;var n=0;if(r)for(var h=new Uint32Array(h.buffer),l,p=e;p<m;p++)for(l=
g;l<c;l++)h[n++]=f[p][l];else for(var q,t,p=e;p<m;p++)for(l=g;l<c;l++)q=f[p][l],t=n<<2,h[t]=q&255,h[t+1]=q>>8&255,h[t+2]=q>>16&255,h[t+3]=255,n++;d.putImageData(k,g,e)}};this.postPaint=function(a,b,f,d){0<g.width?g.union(a,b,f,d):(g.x=a,g.y=b,g.width=f,g.height=d)};this.commitPaint=function(){0<g.width&&(this.repaint(g.x,g.y,g.width,g.height),g.width=0)};this.fillRect=function(a,b,g,d,e){g=a+g;d=b+d;for(var c=b;c<d;c++)for(b=a;b<g;b++)f[c][b]=e}}function ha(b,a){G?G.resize(b,a):G=new qa(b,a);return G}
function ia(){var b=c.indexOf("://"),a=c.substring(b+3),b=a.indexOf("/");0<b&&(a=a.substring(0,b));return location.protocol+"//"+a}function ra(b){return sessionId?hi5.browser.httpGet(ia()+"/CLIP?s="+sessionId+"&t="+(new Date).getTime(),!1):""}function Y(b,a){var f=b-5,c=a-5,g=Math.floor(c/e),r=Math.floor(f/p),m=null;if(x)var m=Math.min(r*p+5,z*p+5),l=Math.min(g*e+5,R*e+5),m=k.getImageData(0,0,m,l);t=f;v=c;A.setSize(b,a);k.font=h.fontSize+"px Courier New";ja();m&&k.putImageData(m,0,0);R=g;z=r;D=Math.floor(v/
e);if(d.onresolutionchange)d.onresolutionchange(t,v)}function Z(b){return"on"==b||"true"==b}function ka(b,a,d){this.need=b;this.handler=a;this.repeat=d||1}function sa(){if(!x){if(aa)q=aa,ba();else{la();var b=c+="&cols="+z+"&rows="+R;hi5.browser.binaryWS()&&(b+="&binary=on");var a=window.opener;if(a){var f=null;try{f=a.__sparkUser}catch(u){}f&&(a=f.account,f=f.session,a&&(b+="&account="+a),f&&(b+="&session="+f))}c=b+="&pasteCap="+(hi5.browser.isChrome&&hi5.browser.isDesktop?3:0);b=0==d.mode&&hi5.appcfg.wsPost?
c.substring(0,c.indexOf("?"))+"?_METHOD=post":c;q=new WebSocket(b,[]);q.binaryType="arraybuffer"}ma.ws=q;svGlobal.logger.info(c);q.onopen=ta;void 0!=h.recording&&"on"==h.recording&&ua(h);q.onmessage=function(a){a=a.data;if("string"!=typeof a){var b=new Uint8Array(a);null!=H&&H.add(new RecordingObj(b,0,a.byteLength));S.set(b,0,a.byteLength);S.handle()}else{var f=parseInt(a.substring(0,2),16),b=a.substring(2);switch(f){case 0:a=c.substring(c.indexOf("?")+1);q.send("00"+a);q.send("87"+navigator.userAgent);
break;case 15:if(d.onready)d.onready();if(d.onloggedin)d.onloggedin();break;case 26:a=JSON.parse(b);if(a.name){svGlobal.logger.info("msg="+b);if(d.onerror)d.onerror(a);b=__svi18n.errorCode["S"+a.name]||"";b+=a.message;d.showMessage(b)}else 0<svGlobal.log&&console.erro("No error code for message:"+b);break;case 27:0!=hi5.appcfg.drawLicense&&A.drawLicense(b);break;case 56:a=JSON.parse(b);sessionId=a.session;a.server=d.server;if(b=hi5.$("joinSelect"))b.value=a.joinMode;if(b=hi5.$("requestControl"))b.disabled=
a.hasControl;var b=hi5.appcfg.page&&hi5.appcfg.page.joinssh||"joinssh.html",b=location.protocol+"//"+location.host+"/"+b+"?id="+a.numericId,u=a.webAddress;u&&0<u.length&&(f=u.indexOf("://"),u=u.substring(f+3),f=u.indexOf("/"),0<f&&(u=u.substring(0,f)),u.toLowerCase()!=location.host.toLowerCase()&&(b+="&gateway="+u));a.joinLink=b;d.sessionInfo.appInfo=a;a.ver&&a.ver!=svGlobal.version&&console.log("Client:"+svGlobal.version+" server:"+a.ver);ba();if(d.onsessionstart)d.onsessionstart(d.sessionInfo);
break;case 59:break;case 61:a=JSON.parse(b);switch(a.type){case 0:h.fontSize=parseInt(a.fontSize);t=a.width;v=a.height;ba();A.setAutoScale(!0);Y(t+5,v+5);a.server&&(d.server=a.server,d.setTitle&&(document.title=h.displayName||d.server));na=a.length;if(d.onopened)d.onopened(a);break;case 1:a=a.duration;if(d.onprogress)d.onprogress(a,na);break;case 2:2==a.status?x=!0:(b=0==a.status,G.pause(b),a.warn&&d.showMessage(b?__svi18n.info.sessionPaused:__svi18n.info.sessionResumed))}break;case 62:va(b);break;
case 91:T(__svi18n.info.user||b);K=!0;break;case 93:l+=e;n=5;T(__svi18n.info.password||b);U=!0;break;default:svGlobal.logger.warn("@TODO:"+a+"\n")}}};q.onclose=function(a){svGlobal.logger.warn("closed, code="+a.code+" reason="+a.reason);M.style.display="none";if(!x&&0==d.mode){(a=__svi18n.errorCode.connection)||(a="error connection");if(d.onerror)d.onerror({name:"connection",message:a});d.displayMsg&&hi5.notifications.notify({msg:a});0<svGlobal.log&&console.error(a)}x=!1;try{null!=H&&(H.exit(),H=
null),A&&A.close(),E&&E.visible()&&E.dismiss()}catch(b){}window&&window.$ssh&&(window.$ssh=null);if(d&&d.onclose)d.onclose()};q.onerror=wa}}function ua(b){H=new RecordingManager;H.setHeader({name:0<b.user.length?b.server+"_"+b.user:b.server,width:b.width,height:b.height,color:b.fontSize,namesuffix:".sshv",filetag:"SSHV",duration:0})}function va(b){var a=parseInt(b.substring(0,1),16),f,c=b.substring(1);b=!1;var e=d.sessionInfo.appInfo;switch(a){case 1:f=JSON.parse(c);d.onsessionjoin&&(b=d.onsessionjoin(f));
if(b)break;d.showMessage(__svi18n.info.joinsession.applyArgs([f.numericId,f.__ip,f.name]));break;case 2:f=JSON.parse(c);d.onsessionexit&&(b=d.onsessionexit(f));if(b)break;d.showMessage(__svi18n.info.exitsession.applyArgs([f.numericId,f.__ip,f.name]));break;case 3:f=JSON.parse(c);e.joinMode!=f.mode&&(e.joinMode=f.mode,a=hi5.$("joinSelect"))&&(a.value=f.mode);if(e.hasControl)break;A.setReadOnly(!1);if(a=hi5.$("requestControl"))a.disabled=!0;d.ongivecontrol&&(b=d.ongivecontrol());if(b)break;d.showMessage(__svi18n.info.givecontrol);
break;case 4:A.setReadOnly(!0);e.hasControl=!1;if(a=hi5.$("requestControl"))a.disabled=!1;d.ontakebackcontrol&&(b=d.ontakebackcontrol());if(b)break;d.showMessage(__svi18n.info.nocontrol);break;case 5:f=JSON.parse(c);d.onrequirecontrol&&(b=d.onrequirecontrol(f));if(b)break;b=__svi18n.info.title.applyArgs([f.name,f.numericId,f.__ip]);hi5.notifications.notify({title:b,msg:__svi18n.info.recontrol,cbYes:function(){d.giveControl(f.numericId);this.destroy()},cbNo:function(){d.refuseControl(f.numericId);
this.destroy()}});break;case 6:A.setTouchRemoting(!0);break;case 7:f=JSON.parse(c);f.width&&f.height&&(G=ha(f.width,f.height),Y(f.width+5,f.height+5));break;case 8:f=JSON.parse(c);if(d.onrequestcredential&&d.onrequestcredential(f))break;A.requestCredential(f);break;case 11:f=JSON.parse(c);d.onrequirejoin&&(b=d.onrequirejoin(f));if(b)break;b=__svi18n.info.title.applyArgs([f.name,f.numericId,f.__ip]);hi5.notifications.notify({title:b,msg:__svi18n.info.reqjoin,cbYes:function(){d.allowJoin(f.numericId,
!0);this.destroy()},cbNo:function(){d.allowJoin(f.numericId,!1);this.destroy()}})}}function ta(b){svGlobal.logger.info("opened...");x=!0;q.send("87"+navigator.userAgent);if(d.onopen)d.onopen()}function wa(b){svGlobal.logger.warn(b)}function ca(b){S.setHandler(null);if(q&&x){q.onmessage=null;try{q.send("85"),q.close()}catch(a){}}window&&window.$ssh&&(window.$ssh=null);null!=H&&(H.exit(),H=null)}function la(){10>h.fontSize&&(h.fontSize=10);12>=h.fontSize?(e=h.fontSize+6,V=2):13<=h.fontSize&&18>h.fontSize?
(e=h.fontSize+8,V=2):19<=h.fontSize&&25>h.fontSize?(e=h.fontSize+12,V=3):25<=h.fontSize&&(e=h.fontSize+16,V=4);k.font=h.fontSize+"px Courier New";p=k.measureText("X").width;D=parseInt(v/e);R=parseInt(v/e);z=parseInt(t/p)}function ba(){ja();l=n=5;la();remotectrl.style.cursor="text";null==M&&(M=document.getElementById("cursorID"),M.style.display="block",M.style.width=p+"px",M.style.height=e+"px")}function da(){n-=p;5>n&&(n=5);I()}function P(b){oa=b;k.fillStyle=ea[b]}function ja(){k.fillStyle="black";
k.fillRect(0,0,k.canvas.width,k.canvas.height);k.fillStyle="white"}function I(){M.style.top=l+"px";M.style.left=n+"px"}function T(b){Q=b.length;k.fillStyle=ea[N];k.fillRect(n,l,p*Q,e);k.fillStyle=ea[oa];k.fillText(b,n,l+e-3*V);n+=Q*p;n>5+(z-1)*p&&(n=5+(z-1)*p);E&&(F+=b);I()}function xa(b){if(x)return(b=b.getData("text/plain"))?(b=b.replace(/\r\n/g,"\n"),J(!1,b,3),!0):!1}function ya(){E&&W&&!E.visible()&&(W.value=F,E.show(),setTimeout(function(){W.scrollTop=W.scrollHeight},10))}function J(b,a,f){29==
X&&68==a&&b?d.close():K||U?28==a?(q.send((K?"5B":"5D")+O),O="",K?K=!1:(U=!1,l+=e,n=5)):14==a&&0<O.length&&(O=O.substring(0,O.length-1),K&&(da(),T(" "),da())):q.send("8B"+f+"\t"+a);X=a}sessionStorage&&sessionStorage.clear();hi5.appcfg.copyDialog=!0;var W=document.getElementById("copytextarea"),E=W?new hi5.Lightbox(document.getElementById("copydialog")):null,F="";this.displayMsg=!0;this.reconnectTimes=0;this.setTitle=this.openLink=!0;this.mode=0;var aa="object"==typeof c?c:null,pa="object"==typeof c||
0<c.indexOf("/PLAY?");pa?(this.mode=1,aa&&(c=""),c+="&touchpad=on"):0<c.indexOf("/JOIN?")&&(this.mode=2,this.reconnectOnResize=!1);var h=hi5.tool.queryToObj(c.substring(c.indexOf("?")+1));h.color||(h.color=32);this.server=h.server;this.port=parseInt(h.port,10);this.sessionInfo={major:0,minor:0,width:0,height:0,bpp:0,bigEndian:!0,trueColor:!0};var A=null,x=!1,B=0,w=[],L=0,n=0,l=0,p=0,e=18,V=0,oa=7,N=0,C=1,D=24,M=null,R=0,z=0,Q=0,X=0,fa=!1,ga=!1,H=null;window.$ssh=this;var S=new function(b){var a=0,
f=0,d=new Uint8Array(b),c=this,e=new ka(0,null,0);this.getHandler=function(){return e};this.getData=function(){return d};this.getPosition=function(){return a};this.setPosition=function(b){a=b};this.getEnd=function(){return f};this.set=function(b,c,e){d=b;a=c;f=e};this.handle=function(){e.handler(c,e)};this.setHandler=function(b){b&&1>b.need&&console.log("need < 1");(e=b)&&f-a>=b.need&&b.handler(c,b)};this.getByte=function(){return d[a++]};this.peekByte=function(){return d[a]};this.getBE32=function(){return d[a++]<<
24|d[a++]<<16|d[a++]<<8|d[a++]};this.getBE16=function(){return d[a++]<<8|d[a++]};this.skip=function(b){a+=b};this.skipBack=function(b){a-=b};this.getBytes=function(b,f){if(f)for(var c=0;c<b;c++)f[c]=d[a++];else return c=a,a+=b,d.subarray(c,a)};this.copyToByteArray=function(a,b,f,c){hi5.Arrays.arraycopy(d,f,a,b,c)}}(4194304);this.__que=S;this.running=function(){return x};var d=this,q=null;t||(t=window.innerWidth);t-=5;h.width=t;c+="&width="+t;v||(v=window.innerHeight);v-=5;h.height=v;c+="&height="+
v;h.fontSize?h.fontSize=parseInt(h.fontSize,10):(y||(y=13),h.fontSize=y,c+="&fontSize="+y);var ea="black red green yellow blue magenta cyan white".split(" "),G=ha(t,v),k=G.getContext(),ma=new function(){this.ws=null;this.setJoinMode=d.setJoinMode;this.requestControl=d.requestControl;this.writeKeyComb=d.writeKeyComb;this.getAppMode=function(){return d.mode};this.send=function(a){"891"!=a&&x&&this.ws.send(a)};this.sendInput=function(a){d.writeRawInput(a);if(d.onactivity)d.onactivity(a)};var b=null;
this.getAppInfo=function(){return d.sessionInfo.appInfo};this.onresize=function(a){if(a=a.target.svSurface){a=a.getFreeSpace();var d=a.width,c=a.height;hi5.browser.isTouch||hi5.browser.isOpera||!x||(b&&(clearTimeout(b),b=null),b=setTimeout(function(){Y(d,c);var a=t,b=v,k=0,h=0,k=parseInt(a/p),h=parseInt(b/e);q.send("ED"+k+"\t"+h+"\t"+a+"\t"+b)},200))}};this.onorientationchange=function(a){};this.getClipData=ra;this.onfocus=function(a){};this.fileCallback=[];this.getShareFiles=function(a,b){loggedin&&
(this.ws.send("3A5"+a),this.fileCallback.push(b))};this.notifyFiles=function(a){for(var b=this.fileCallback,d=0,c=b.length;d<c;d++)b[d](a)};this.getFile=function(a){window.open(d.getFileUrl(a))};this.removeFile=function(a){uploadMgr&&uploadMgr.fileService.remove(a)};this.getFileLink=function(a){return ia()+"/DOWNLOAD?s="+sessionId+"&f="+a};this.getGateway=function(){return c};this.reconnect=function(a,b,d){}};hi5.appcfg&&(y=hi5.appcfg,"undefined"!=typeof y.displayMsg&&(this.displayMsg=y.displayMsg),
"undefined"!=typeof y.reconnectTimes&&(this.reconnectTimes=y.reconnectTimes),"undefined"!=typeof y.openLink&&(this.openLink=y.openLink),"undefined"!=typeof y.setTitle&&(this.setTitle=y.setTitle),"boolean"==typeof y.useWSS&&(c=(hi5.appcfg.useWSS?"wss":"ws")+c.substring(c.indexOf("://"))));this.getURL=function(){return c};var za=parseInt(h.server_bpp||h.color||24);this.getColor=function(){return za};window.onerror=function(b,a,d){console.log("Uncatched error, msg: "+b+" url: "+a+" line: "+d)};this.setJoinMode=
function(b){x&&q.send("8E1"+b)};this.refuseControl=function(b){x&&q.send("8E3"+b)};this.giveControl=function(b){x&&q.send("8E4"+b)};this.requestControl=function(){x&&q.send("8E2")};this.play=function(){q.send("F3")};this.pause=function(){q.send("F2")};this.scan=function(b){q.send("F4"+(b?"1":"0"))};this.seek=function(b){A&&x&&(q.send("F4"+(b?"1":"0")+"\t"+(b/A.getScale()|0)),G.pause(!0))};var K=!1,U=!1,O="",na=0;this.run=function(){setTimeout(sa,5)};this.hide=function(){A&&("block"==document.getElementById("cursorID").style.display&&
(document.getElementById("cursorID").style.display="none"),A.hide())};this.showMessage=function(b){d.displayMsg&&b&&hi5.notifications.notify({msg:b})};this.close=ca;hi5.browser.isChromeApp?chrome.runtime.onSuspend.addListener(ca):window.addEventListener("unload",ca,!1);y=new ka(1024,function(b){for(var a,d=!0;d;)if(a=b.getByte(),void 0==a)d=!1;else if(0!=a)if(13==a)n=5,l>5+(D-1)*e&&(l=5+(D-1)*e),I();else if(27==a)if(a=b.getByte(),77==a)a=k.getImageData(5,5+(C-1)*e,z*p,(D-C)*e),k.fillStyle="black",
k.fillRect(0,5+(C-1)*e,z*p,e),k.putImageData(a,5,5+C*e),k.fillStyle="white";else if(68==a)a=k.getImageData(5,C*e+5,z*p,(D-C)*e),k.fillStyle="black",k.fillRect(5,D*e-e+5,z*p,e),k.putImageData(a,5,(C-1)*e+5),k.fillStyle="white";else{if(55!=a){if(40==a)if(a=b.getByte(),66==a)if(a=b.getByte(),27==a)if(a=b.getByte(),41==a)if(a=b.getByte(),48==a)continue;else b.skipBack(1);else b.skipBack(1);else b.skipBack(1);else b.skipBack(1);if("0x5b"==a){B=0;for(L=w[B]=0;;)if(a=b.getByte(),59==a)0<L&&(B++,L=w[B]=0);
else if(48<=a&&57>=a)w[B]=10*w[B]+(a-48),L++;else{b.skipBack(1);break}a=b.getByte();if(109==a)if(0==L&&0==B)a=b.getByte(),15==a?(P(7),N=0):(P(7),N=0,b.skipBack(1));else for(a=0;a<=B;a++)switch(w[a]){case 0:0==B?(P(7),N=0):0==a?P(0):N=0;break;case 7:0==B?(P(7),N=0):0==a?P(7):N=7;continue;case 30:case 31:case 32:case 33:case 34:case 35:case 36:case 37:P(w[a]-30);break;case 40:case 41:case 42:case 43:case 44:case 45:case 46:case 47:N=w[a]-40}else if(114==a)a=w[1],C=w[0],D=a;else if(72==a)0==L&&0==B&&
(w[0]=w[1]=1),a=w[0],n=(w[1]-1)*p+5,5>n&&(n=5),l=(a-1)*e+5,I();else if(66==a)l+=w[0]*e,E&&(F+="\n"),I();else if(68==a)n-=w[0]*p,I();else if(67==a)0==L&&0==B&&(w[0]=1),n+=w[0]*p,I();else if(65==a)0==L&&0==B&&(w[0]=1),l-=w[0]*e,I();else{if(63==a)if(a=b.getByte(),49==a)if(a=b.getByte(),108==a||104==a){if(a=b.getByte(),27==a&&(a=b.getByte(),">"==a||"="==a))continue}else{if(104==a&&(a=b.getByte(),27==a&&(a=b.getByte(),61==a)))continue}else if(55==a){a=b.getByte();if(104==a)continue;else if(49==a)continue;
b.skipBack(1);a=55}75==a?(0==L&&0==B?(k.fillStyle="black",k.fillRect(n,l,z*p-n+5,e)):(k.fillStyle="black",k.fillRect(5,l,n,e)),k.fillStyle="white"):74==a&&(k.fillStyle="black",k.fillRect(n,l,z*p-n+5,R*e-l+5),k.fillStyle="white")}}}}else if(7!=a)if(9==a)a=(n-5)/p/8,a*=1,a=parseInt(a)+1,n=8*a*p+5,n>=z*p&&(n=5,l+=e,E&&(F+="\n")),I();else if(15!=a)if(8==a)da();else if(10==a){if(l+=e,E&&(F+="\n"),n>=z*p&&(n=5,l+=e,E&&(F+="\n")),l>(D-1)*e+5){for(;l>(D-1)*e+5;)l-=e;I();a=k.getImageData(5,5+(C-0)*e,z*p,(D-
C)*e);k.fillStyle="black";k.fillRect(5,5+(C-1)*e,z*p,(D-C+1)*e);k.putImageData(a,5,5+(C-1)*e);k.fillStyle="white"}}else{if(void 0!=a&&10!=a){b.skipBack(1);var c=b,g="",h=c.getPosition(),m=void 0;Q=0;for(a=[];h<c.getEnd();)if(m=c.getByte(),32<=m&&255>=m)g+=String.fromCharCode(m),h++,a[Q++]=m;else{13!=m&&27!=m&&8!=m&&9!=m||c.skipBack(1);break}if(0<Q){c="";for(h=c1=c2=g=0;g<a.length;)h=a[g],128>h?(c+=String.fromCharCode(h),g++):191<h&&224>h?(c2=a[g+1],c+=String.fromCharCode((h&31)<<6|c2&63),g+=2):(c2=
a[g+1],c3=a[g+2],c+=String.fromCharCode((h&15)<<12|(c2&63)<<6|c3&63),g+=3,Q--);g=c}T(g)}b.getPosition()>=b.getEnd()&&(d=!1)}});S.setHandler(y);this.addSurface=function(b){A=b;pa&&b.setPlayerMode();G.setContext(A.context);k=G.getContext();b.alwaysPaste=!0;b.setAutoScale(0<d.mode);b.setSize(t+5,v+5);b.setController(ma);b.setFastCopy(Z(h.fastCopy));b.setTouchpad(Z(h.touchpad));b.setClipboard(Z(h.mapClipboard));b.run(99997);b.onclipdata=xa};(new Uint8Array(6))[0]=5;(new Uint8Array(8))[0]=4;this.writeRawInput=
function(b){if(x){var a=parseInt(b.substring(0,2),16);b=b.substring(2).split("\t");var c=0,e=!1;switch(a){case 128:2==b[2]&&ya();return;case 129:return;case 130:return;case 131:J(!0,0==b[2]?200:208,0);return;case 132:e=0==b[0];c=parseInt(b[1]);29==c&&(fa=e);56==c&&(ga=e);if(0==b[0]){if(69==c)return;J(e,c,0)}else 42==b[1]?J(!1,42,2):29==b[1]&&J(!1,29,2);return;case 139:if(0==b[0]){if(fa&&ga)return;c=parseInt(b[1]);K||U?29==X&&68==c&&d.close():(fa&&29!=X&&J(!0,29,0),ga&&56!=X&&J(!0,56,0),J(!0,c,1))}return;
case 134:c=b[0].charCodeAt(0);K||U?(a=String.fromCharCode(c),O+=a,K&&T(a)):47==c?J(!0,191,1):(160==c&&(b[0]=" "),J(!1,b[0],3));return}console.log("Unknowncode: "+b[1]+" type:"+a)}}};
