var svManager={getInstance:function(){var f=window.$ssh;if(f&&f.running&&f.running())return f;return null}};function connvertServer(f){var q=new Object;q.id=f.id;q.server=f.id;q.displayName=f.displayName||f.id;var t=f.ssh;if(t){for(var H in t)q[H]=t[H];q.user=t.username||"";q.pwd=t.password||""}return q}
svGlobal.SSH=function(f,q,t,H){function zb(){I=g.fgColor||U[7];J=g.bgColor||U[0]}function Da(a,c){function d(a,b,c,d,e,h){var r=a+e;var l=b+h;var k=x;var g;var f;var v;var w;for(f=0;f<d;f++){v=k[l+f];w=k[b+f];for(g=0;g<c;g++)v[r+g]=w[a+g]}}function b(a,b,c,d,e,h){var r=a+e;var g=b+h;var f=x;var k;var l;var v;var w;for(l=d-1;l>=0;l--){v=f[g+l];w=f[b+l];for(k=0;k<c;k++)v[r+k]=w[a+k]}}function e(a,b,c,d,h,r){var k=a+h;var l=b+r;var f=x;var g;var v;var w;var m;for(g=c-1;g>=0;g--){w=k+g;m=a+g;for(v=0;v<
d;v++)f[l+v][w]=f[b+v][m]}}function r(a,b,c,d,e,h){var g=a+e;var r=b+h;var k=x;var f;var l;var v;var w;for(f=0;f<c;f++){v=g+f;w=a+f;for(l=0;l<d;l++)k[r+l][v]=k[b+l][w]}}var x=[];var h=null;var l=new hi5.graphic.Rectangle(0,0,0,0);var k="Uint8ClampedArray"in window;this.width=a;this.height=c;var g=false;var f=this;this.pause=function(a){g=a};this.release=function(){f=null;h=null;x=null};this.isPaused=function(){return g};this.setContext=function(a){if(a==h)return;if(!h&&a&&!a.createImageData(1,1).data.buffer)k=
false;h=a};this.getContext=function(){return h};this.resize=function(b,d){for(var e=0;e<d;e++)x[e]=new Uint32Array(b);f.width=a=b;f.height=c=d};f.resize(a,c);this.getBuffer=function(){return x};this.setRGB=function(a,b,c){x[b][a]=c|4278190080};this.getRGB=function(a,b){return x[b][a]};this.setRGBs=function(a,b,c,d,e,h,f){var l=h;var g=0;var k=0;var r=a+c;var v=b+d;var w=x;var m;for(var n=b;n<v;n++,l+=f){k=l;m=w[n];for(g=a;g<r;g++)m[g]=e[k++]}};this.moveArea=function(a,c,h,g,l,f){if(f>0)b(a,c,h,g,
l,f);else if(f<0)d(a,c,h,g,l,f);else if(l>0)e(a,c,h,g,l,f);else r(a,c,h,g,l,f)};this.getRGBs=function(a,b,c,d){var e=c*d;var h=_Uint32Array(e);h[0]=0;var f=x;var g=a+c;var l=b+d;var k=0;var r;for(var v=b;v<l;v++)for(r=a;r<g;r++)h[k++]=f[v][r];return h};this.repaint=function(b,d,e,f){if(!h)return;if(b<0){e+=b;b=0}if(d<0){f+=d;d=0}if(b+e>a)e=a-b;if(d+f>c)f=c-d;var g=h.createImageData(e,f);var l=g.data;var r=b+e;var v=d+f;var w=0;var m=x;if(k){var n=new Uint32Array(l.buffer);var p;for(var q=d;q<v;q++)for(p=
b;p<r;p++)n[w++]=m[q][p]}else{var t;var u;for(q=d;q<v;q++)for(p=b;p<r;p++){t=m[q][p];u=w<<2;l[u]=t&255;l[u+1]=t>>8&255;l[u+2]=t>>16&255;l[u+3]=255;w++}}h.putImageData(g,b,d);g=null};this.postPaint=function(a,b,c,d){if(l.width>0)l.union(a,b,c,d);else{l.x=a;l.y=b;l.width=c;l.height=d}};this.commitPaint=function(){if(l.width>0){this.repaint(l.x,l.y,l.width,l.height);l.width=0}};this.fillRect=function(a,b,c,d,e){var f=x;var l=a+c;var g=b+d;var h;for(var r=b;r<g;r++)for(h=a;h<l;h++)f[r][h]=e}}function ra(a,
c){if(G)G.resize(a,c);else G=new Da(a,c);return G}function sa(){var a=f.indexOf("://");var c=f.substring(a+3);a=c.indexOf("/");if(a>0)c=c.substring(0,a);return location.protocol+"//"+c}function Ea(a){if(!ba)return"";return hi5.browser.httpGet(sa()+"/CLIP?s="+ba+"&t="+(new Date).getTime(),false)}function ha(a,c){if(c)C=c;if(a){K=a;ca=(K-1)*h}ta=C==1&&K==Math.floor(t/h)}function ia(a,c){var d=a-D;var b=c-D;var f=Math.floor(b/h);var r=Math.floor(d/p);var x=null;if(A){var m=Math.min(r*p+D,E*p+D);var l=
Math.min(f*h+D,X*h+D);x=k.getImageData(0,0,m,l)}q=d;t=b;y.setSize(a,c);k.font=g.fontSize+"px Courier New";ua();if(x)k.putImageData(x,0,0);X=f;E=r;ha(Math.floor(t/h));if(e.onresolutionchange)e.onresolutionchange(q,t)}function Fa(){this.ws=null;this.setJoinMode=e.setJoinMode;this.requestControl=e.requestControl;this.writeKeyComb=e.writeKeyComb;this.getAppMode=function(){return e.mode};this.send=function(a){if(a=="891")return;if(!A)return;this.ws.send(a)};this.sendInput=function(a){e.writeRawInput(a);
if(e.onactivity)e.onactivity(a)};var a=null;this.getAppInfo=function(){return e.sessionInfo.appInfo};this.onresize=function(c){var d=c.target.svSurface;if(!d)return;var b=d.getFreeSpace();var e=b.width;var f=b.height;if(hi5.browser.isTouch||hi5.browser.isOpera)return;if(A){var h=function(){ia(e,f);Ga(q,t)};if(a){clearTimeout(a);a=null}a=setTimeout(h,200)}};this.onorientationchange=function(a){};this.getClipData=Ea;this.onfocus=function(a){};this.fileCallback=[];this.getShareFiles=function(a,d){if(loggedin){this.ws.send("3A5"+
a);this.fileCallback.push(d)}};this.notifyFiles=function(a){var d=this.fileCallback;var b=0;for(var e=d.length;b<e;b++)d[b](a)};this.getFile=function(a){window.open(e.getFileUrl(a))};this.removeFile=function(a){if(uploadMgr)uploadMgr.fileService.remove(a)};this.getFileLink=function(a){return sa()+"/DOWNLOAD?s="+ba+"&f="+a};this.getGateway=function(){return f};this.reconnect=function(a,d,b){}}function da(a){return a=="on"||a=="true"}function Ha(){return g.displayName||e.server}function Ia(a){if(e.setTitle)document.title=
a}function va(a,c,d){this.need=a;this.handler=c;this.repeat=d||1}function Ja(a){var c=0;var d=0;var b=new Uint8Array(a);var e=this;var f=new va(0,null,0);this.release=function(){f=null;b=null;e=null};this.getHandler=function(){return f};this.getData=function(){return b};this.getPosition=function(){return c};this.setPosition=function(a){c=a};this.getEnd=function(){return d};this.set=function(a,e,f){b=a;c=e;d=f};this.handle=function(){f.handler(e,f)};this.setHandler=function(a){if(a&&a.need<1)svGlobal.logger.warn("need < 1");
f=a;if(a&&d-c>=a.need)a.handler(e,a)};this.getByte=function(){return b[c++]};this.peekByte=function(){return b[c]};this.getBE32=function(){return b[c++]<<24|b[c++]<<16|b[c++]<<8|b[c++]};this.getBE16=function(){return b[c++]<<8|b[c++]};this.skip=function(a){c+=a};this.skipBack=function(a){c-=a};this.getBytes=function(a,d){if(!d){var e=c;c+=a;return b.subarray(e,c)}else for(var f=0;f<a;f++)d[f]=b[c++]};this.copyToByteArray=function(a,c,d,e){hi5.Arrays.arraycopy(b,d,a,c,e)}}function Ka(){if(A)return;
if(ja){m=ja;ka()}else{wa();f+="&cols="+E+"&rows="+X;var a=f;var c=hi5.browser.binaryWS();if(c)a+="&binary=on";var d=window.opener;if(d){var b=null;try{b=d.__sparkUser}catch(h){}if(b){var k=b.account;var r=b.session;if(k)a+="&account="+k;if(r)a+="&session="+r}}var x=hi5.browser.isChrome&&hi5.browser.isDesktop;a+="&pasteCap="+(x?3:0);f=a;a=e.mode==0&&B.wsPost?f.substring(0,f.indexOf("?"))+"?_METHOD=post":f;m=new WebSocket(a,"ssh");m.binaryType="arraybuffer"}la.ws=m;svGlobal.logger.info(f);m.onopen=
La;if(g["recording"]!=undefined&&g["recording"]=="on")Ma(g);m.onmessage=function(a){var b=a.data;if(typeof b!="string"){var c=new Uint8Array(b);if(L!=null)L.add(new RecordingObj(c,0,b.byteLength));Q.set(c,0,b.byteLength);Q.handle()}else{var d=parseInt(b.substring(0,2),16);var e=b.substring(2);switch(d){case 0:Na();break;case 15:Oa(e);break;case 26:Pa(e);break;case 27:Qa(e);break;case 56:Ra(e);break;case 59:Sa(e);break;case 61:Ta(e);break;case 62:Ua(e);break;case 91:Va(e);break;case 93:Wa(e);break;
default:svGlobal.logger.warn("@TODO:"+b+"\n")}}};m.onclose=ea;m.onerror=Xa}function Na(){var a=f.substring(f.indexOf("?")+1);m.send("00"+a);m.send("87"+navigator.userAgent)}function Ma(a){L=new RecordingManager;var c=a.user.length>0?a.server+"_"+a.user:a.server;var d={name:c,width:a.width,height:a.height,color:a.fontSize,namesuffix:".sshv",filetag:"SSHV",duration:0};L.setHeader(d)}function Qa(a){if(B.drawLicense!=false)y.drawLicense(a)}function Oa(a){if(e.onready)e.onready();if(e.onloggedin)e.onloggedin();
m.send("8D")}function Sa(a){}function Ta(a){var c=JSON.parse(a);switch(c.type){case 0:g.fontSize=parseInt(c.fontSize);q=c.width;t=c.height;ka();y.setAutoScale(true);ia(q+D,t+D);var d=c.server;if(d){e.server=c.server;Ia(Ha())}xa=c.length;if(e.onopened)e.onopened(c);break;case 1:var b=c.duration;if(e.onprogress)e.onprogress(b,xa);break;case 2:if(c.status==2){Ya();A=true}else{var f=c.status==0;G.pause(f);if(c.warn)e.showMessage(f?__svi18n.info.sessionPaused:__svi18n.info.sessionResumed)}}}function Ya(){}
function Wa(a){u+=h;n=0;V(__svi18n.info.password||a);ma=true}function Va(a){na=true;V(__svi18n.info.user||a);R=true}function Ua(a){var c=parseInt(a.substring(0,1),16);var d;var b;var f=a.substring(1);var h=false;var g=e.sessionInfo.appInfo;switch(c){case 1:b=JSON.parse(f);if(e.onsessionjoin)h=e.onsessionjoin(b);if(h)break;e.showMessage(__svi18n.info.joinsession.applyArgs([b.numericId,b.__ip,b.name]));break;case 2:b=JSON.parse(f);if(e.onsessionexit)h=e.onsessionexit(b);if(h)break;e.showMessage(__svi18n.info.exitsession.applyArgs([b.numericId,
b.__ip,b.name]));break;case 3:b=JSON.parse(f);if(g.joinMode!=b.mode){g.joinMode=b.mode;var k=hi5.$("joinSelect");if(k)k.value=b.mode}if(g.hasControl)return;y.setReadOnly(false);d=hi5.$("requestControl");if(d)d.disabled=true;if(e.ongivecontrol)h=e.ongivecontrol();if(h)break;e.showMessage(__svi18n.info.givecontrol);break;case 4:y.setReadOnly(true);g.hasControl=false;d=hi5.$("requestControl");if(d)d.disabled=false;if(e.ontakebackcontrol)h=e.ontakebackcontrol();if(h)break;e.showMessage(__svi18n.info.nocontrol);
break;case 5:var l=function(){e.refuseControl(b.numericId);this.destroy()};var m=function(){e.giveControl(b.numericId);this.destroy()};b=JSON.parse(f);if(e.onrequirecontrol)h=e.onrequirecontrol(b);if(h)break;var w=__svi18n.info.title.applyArgs([b.name,b.numericId,b.__ip]);hi5.notifications.notify({"title":w,"msg":__svi18n.info.recontrol,"cbYes":m,"cbNo":l});break;case 6:y.setTouchRemoting(true);break;case 7:b=JSON.parse(f);if(b.width&&b.height){G=ra(b.width,b.height);ia(b.width+D,b.height+D)}break;
case 8:b=JSON.parse(f);if(e.onrequestcredential&&e.onrequestcredential(b))return;y.requestCredential(b);break;case 9:break;case 11:var n=function(){e.allowJoin(b.numericId,false);this.destroy()};var p=function(){e.allowJoin(b.numericId,true);this.destroy()};b=JSON.parse(f);if(e.onrequirejoin)h=e.onrequirejoin(b);if(h)break;w=__svi18n.info.title.applyArgs([b.name,b.numericId,b.__ip]);hi5.notifications.notify({"title":w,"msg":__svi18n.info.reqjoin,"cbYes":p,"cbNo":n})}}function Ra(a){var c=JSON.parse(a);
var d=c;ba=c.session;d.server=e.server;var b=hi5.$("joinSelect");if(b)b.value=d.joinMode;b=hi5.$("requestControl");if(b)b.disabled=d.hasControl;var f=B.page&&B.page.joinssh||"joinssh.html";f=location.protocol+"//"+location.host+"/"+f+"?id="+c.numericId;var h=c.webAddress;if(h&&h.length>0){var g=h.indexOf("://");var k=h.substring(g+3);g=k.indexOf("/");if(g>0)k=k.substring(0,g);if(k.toLowerCase()!=location.host.toLowerCase())f+="&gateway="+k}d.joinLink=f;e.sessionInfo.appInfo=d;if(c.ver&&c.ver!=svGlobal.version)svGlobal.logger.warn("Client:"+
svGlobal.version+" server:"+c.ver);ka();if(e.onsessionstart)e.onsessionstart(e.sessionInfo)}function Ab(a){var c=__svi18n.errorCode[a];if(!c)c="error "+a;if(e.onerror)e.onerror({name:a,message:c});if(e.displayMsg)hi5.notifications.notify({"msg":c});if(svGlobal.log>0)console.error(c)}function Pa(a){var c=JSON.parse(a);if(!c.name){if(svGlobal.log>0)console.erro("No error code for message:"+a);return}svGlobal.logger.info("msg="+a);if(e.onerror)e.onerror(c);var d=__svi18n.errorCode["S"+c.name]||"";d+=
c.message;e.showMessage(d)}function La(a){svGlobal.logger.info("opened...");A=true;m.send("87"+navigator.userAgent);if(e.onopen)e.onopen()}function Xa(a){svGlobal.logger.warn(a)}function ea(a){svGlobal.logger.warn("closed ...");O.style.display="none";A=false;na=false;if(e&&e.onclose)e.onclose();try{if(L!=null){L.exit();L=null}if(y)y.close()}catch(c){}if(Q){Q.release();Q=null}k=null;Y=null;if(m){m.onopen=null;m.onmessage=null;m.onclose=null;m.onerror=null;m=null}la=null;y=null;if(G){G.release();G=
null}if(e)e=null;if(window&&window.$ssh)window.$ssh=null;if(L!=null){L.exit();L=null}}function wa(){if(g.fontSize<10)g.fontSize=10;if(g.fontSize<=12){h=g.fontSize+6;Z=2}else if(g.fontSize>=13&&g.fontSize<18){h=g.fontSize+8;Z=2}else if(g.fontSize>=19&&g.fontSize<25){h=g.fontSize+12;Z=3}else if(g.fontSize>=25){h=g.fontSize+16;Z=4}ya=h-3*Z;k.font=g.fontSize+"px Courier New";p=k.measureText("X").width;X=parseInt(t/h);E=parseInt(q/p);ha(parseInt(t/h))}function ka(){ua();n=0;u=0;wa();remotectrl.style.cursor=
"text";if(O==null){O=document.getElementById("cursorID");O.style.display="block";O.style.width=p+"px";O.style.height=h+"px"}na=true}function Za(){var a=k.getImageData(0,0+(C-1)*h,E*p,(K-C)*h);k.fillStyle=J;k.fillRect(0,(C-1)*h,E*p,h);k.putImageData(a,0,C*h);k.fillStyle=I}function $a(){var a=k.getImageData(0,C*h,E*p,(K-C)*h);k.fillStyle=J;k.fillRect(0,K*h-h,E*p,h);k.putImageData(a,0,(C-1)*h);k.fillStyle=I}function ab(){}function bb(){var a=n/p/za;a=a*1;a=parseInt(a)+1;n=a*za*p;if(n>=E*p){n=0;u+=h;
fa("\n")}M()}function cb(){}function db(){u+=h;fa("\n");Aa()}function Aa(){if(n>=E*p){n=0;u+=h}if(u>ca){for(;u>ca;)u-=h;M();if(ta){k.drawImage(Y,0,-h);k.fillStyle=J;k.fillRect(0,ca,q,h)}else{var a=k.getImageData(0,0+(C-0)*h,E*p,(K-C)*h);k.fillStyle=J;k.fillRect(0,(C-1)*h,E*p,(K-C+1)*h);k.putImageData(a,0,0+(C-1)*h)}k.fillStyle=I}}function oa(){n=n-p;if(n<0)n=0;M()}function eb(a){n+=a*p;M()}function fb(a){u+=a*h;fa("\n");M()}function gb(a){n-=a*p;M()}function hb(a){u-=a*h;M()}function ib(a,c){n=(c-
1)*p;if(n<0)n=0;u=(a-1)*h;M()}function jb(a,c){ha(c,a)}function S(a){J=U[a]||g.bgColor||"black"}function T(a){I=U[a]||g.bgColor||"white";k.fillStyle=I}function kb(){k.fillStyle=J;k.fillRect(n,u,E*p-n,h);k.fillStyle=I}function lb(){k.fillStyle=J;k.fillRect(0,u,n,h);k.fillStyle=I}function mb(){k.fillStyle=J;k.fillRect(n,u,E*p-n,X*h-u);k.fillStyle=I}function ua(){k.fillStyle=J;k.fillRect(0,0,Y.width,Y.height);k.fillStyle=I}function M(){O.style.top=u+"px";O.style.left=n+"px"}function Bb(a,c,d){for(var b=
c;b<d;)if(a.charCodeAt(b++)<32){b--;break}V(a.substring(c,b));return b}function nb(a){V(ob(a))}function V(a){pa=a.length;k.fillStyle=J;k.fillRect(n,u,p*pa,h);k.fillStyle=I;k.fillText(a,n,u+ya);n=n+pa*p;Aa();fa(a);M()}function ob(a){var c=a.getPosition();var d=0;var b=0;var e=0;var f=0;var h="";var g=a.getEnd();for(var k=a.getData();c<g;){d=k[c++];if(d>=32)switch(d>>4){case 0:case 1:case 2:case 3:case 4:case 5:case 6:case 7:h+=String.fromCharCode(d);break;case 12:case 13:h+=String.fromCharCode((d&
31)<<6|k[c++]&63);break;case 14:h+=String.fromCharCode((d&15)<<12|(k[c++]&63)<<6|(k[c++]&63)<<0)}else{if(d==13||d==27||d==8||d==9)c--;break}}a.setPosition(c);return h}function Cb(a){var c=String.fromCharCode(a);P=P+c;if(R)V(c)}function Db(a,c,d){var b=c/h;if(a==0)pb[b]=d}function qb(){n=0;if(u>(K-1)*h)u=(K-1)*h;M()}function Eb(a){if(!e.openLink)return false;var c=a;a=a.toLowerCase();var d=a.indexOf("http://")==0||a.indexOf("https://")==0||a.indexOf("ftp://")==0||a.indexOf("mailto:")==0||a.indexOf("tel:")==
0||a.indexOf("callto:")==0;if(!d)if(a.indexOf("www.")==0){d=true;a="http://"+a}else if(a.indexOf("ftp.")==0){d=true;a="ftp://"+a}if(d){if(a.indexOf("\r")>0||a.indexOf("\n")>0)return false;if(e.onurlredirection&&e.onurlredirection(d))return true;y.processLink(c);return true}return false}function rb(a){if(!A)return;var c=a.getData("text/plain");if(c){c=c.replace(/\r\n/g,"\n");Ba(false,c,3);return true}return false}function sb(){if(!aa)return;aa.value=W;var a=new hi5.Lightbox(document.getElementById("copydialog"));
a.show();if(y)y.setIgnorePaste(false);setTimeout(function(){aa.scrollTop=aa.scrollHeight},10)}function fa(a,c){if(aa){W=W+a;if(W.length>1E5)W=W.substring(4E4)}if(e.onoutput)e.onoutput(a)}function tb(a){if(a==28){m.send((R?"5B":"5D")+P);P="";if(R)R=false;else{ma=false;u+=h;n=0}}else if(a==14)if(P.length>0){P=P.substring(0,P.length-1);if(R){oa();V(" ");oa()}}}function Ba(a,c,d){if(R||ma)tb(c);else m.send("8B"+d+"\t"+c);ub=c}function Ga(a,c){var d=0;var b=0;d=parseInt(a/p);b=parseInt(c/h);m.send("ED"+
d+"\t"+b+"\t"+a+"\t"+c)}function ga(a){if(!a)return;var c=a.length+1;var d=new Uint8Array(c);d[0]=147;for(var b=1;b<c;b++)d[b]=a.charCodeAt(b-1);m.send(d.buffer)}if(sessionStorage)sessionStorage.clear();var W="";this.displayMsg=true;this.reconnectTimes=0;this.openLink=true;this.setTitle=true;this.mode=0;var ja=typeof f=="object"?f:null;var Ca=typeof f=="object"||f.indexOf("/PLAY?")>0;if(Ca){this.mode=1;if(ja)f="";f+="&touchpad=on"}else if(f.indexOf("/JOIN?")>0){this.mode=2;this.reconnectOnResize=
false}var B=hi5.appcfg||{img:{},toolbar:{fadable:true}};var g=hi5.tool.queryToObj(f.substring(f.indexOf("?")+1));if(!g.color)g.color=32;var aa=da(g["mapClipboard"])?document.getElementById("copytextarea"):null;this.server=g["server"];this.port=parseInt(g["port"],10);this.sessionInfo={major:0,minor:0,width:0,height:0,bpp:0,bigEndian:true,trueColor:true};var y=null;var A=false;var na=false;var ba="";B.copyDialog=true;var D=0;var F=0;var z=new Array;var N=0;var n=0;var u=0;var p=0;var h=18;var Z=0;var ya=
0;var U=["black","red","green","yellow","blue","magenta","cyan","white"];var I=g.fgColor||U[7];var J=g.bgColor||U[0];var za=8;var C=1;var K=24;var ca=0;var ta=true;var O=null;var X=0;var E=0;var pa=0;var ub=0;var Fb=false;var Gb=false;var L=null;window.$ssh=this;var Q=new Ja(4194304);this.__que=Q;this.running=function(){return A};var e=this;var m=null;if(!q)q=window.innerWidth;q-=D;g.width=q;f+="&width="+q;if(!t)t=window.innerHeight;t-=D;g.height=t;f+="&height="+t;H=H||g.fontSize;H=H?parseInt(H):
13;if(!g.fontSize){g.fontSize=H;f+="&fontSize="+H}else{H=parseInt(g.fontSize,10);g.fontSize=H}var G=ra(q,t);var k=G.getContext();var Y;var la=new Fa;if(B.displayMsg!=undefined)this.displayMsg=B.displayMsg;if(B.reconnectTimes!=undefined)this.reconnectTimes=B.reconnectTimes;if(B.openLink!=undefined)this.openLink=B.openLink;if(B.setTitle!=undefined)this.setTitle=B.setTitle;if(typeof B.useWSS=="boolean")f=(B.useWSS?"wss":"ws")+f.substring(f.indexOf("://"));this.getURL=function(){return f};var vb=parseInt(g.server_bpp||
g.color||24);this.getColor=function(){return vb};this.setJoinMode=function(a){if(!A)return;m.send("8E1"+a)};this.refuseControl=function(a){if(!A)return;m.send("8E3"+a)};this.giveControl=function(a){if(!A)return;m.send("8E4"+a)};this.requestControl=function(){if(!A)return;m.send("8E2")};this.play=function(){m.send("F3")};this.pause=function(){m.send("F2")};this.scan=function(a){m.send("F4"+(a?"1":"0"))};this.seek=function(a){if(y&&A){m.send("F4"+(a?"1":"0")+"\t"+(a/y.getScale()|0));G.pause(true)}};
var R=false;var ma=false;var P="";var xa=0;this.run=function(){Ka()};this.hide=function(){if(!y)return;if(document.getElementById("cursorID").style.display=="block")document.getElementById("cursorID").style.display="none";y.hide()};this.showMessage=function(a){if(!e.displayMsg||!a)return;hi5.notifications.notify({"msg":a})};this.close=function(){if(m&&A)try{m.send("85");m.close()}catch(a){}else ea()};if(!hi5.browser.isChromeApp)window.addEventListener("unload",ea,false);else chrome.runtime.onSuspend.addListener(ea);
var wb=new va(1024,function c(d){var b;for(var e=true;e;){b=d.getByte();if(b==undefined)break;switch(b){case 0:break;case 13:qb();break;case 27:b=d.getByte();if(b==77){Za();continue}if(b==68){$a();continue}if(b==55){ab();continue}if(b==40){b=d.getByte();if(b==66){b=d.getByte();if(b==27){b=d.getByte();if(b==41){b=d.getByte();if(b==48)continue;else d.skipBack(1)}else d.skipBack(1)}else d.skipBack(1)}else d.skipBack(1)}if(b!="0x5b")continue;F=0;z[F]=0;for(N=0;true;){b=d.getByte();if(b==59){if(N>0){F++;
z[F]=0;N=0}continue}if(48<=b&&b<=57){z[F]=z[F]*10+(b-48);N++;continue}d.skipBack(1);break}b=d.getByte();if(b==109){if(N==0&&F==0){b=d.getByte();if(b==15){T(7);S(0);continue}else{T(7);S(0);d.skipBack(1);continue}}for(var f=0;f<=F;f++)switch(z[f]){case 0:if(F==0){T(7);S(0)}else if(f==0)T(0);else S(0);break;case 1:break;case 2:break;case 4:break;case 5:case 8:break;case 7:if(F==0){T(7);S(0)}else if(f==0)T(7);else S(7);continue;case 30:case 31:case 32:case 33:case 34:case 35:case 36:case 37:T(z[f]-30);
break;case 40:case 41:case 42:case 43:case 44:case 45:case 46:case 47:S(z[f]-40);default:}continue}if(b==114){jb(z[0],z[1]);continue}if(b==72){if(N==0&&F==0)z[0]=z[1]=1;ib(z[0],z[1]);continue}if(b==66){fb(z[0]);continue}if(b==68){gb(z[0]);continue}if(b==67){if(N==0&&F==0)z[0]=1;eb(z[0]);continue}if(b==65){if(N==0&&F==0)z[0]=1;hb(z[0]);continue}if(b==63){b=d.getByte();if(b==49){b=d.getByte();if(b==108||b==104){b=d.getByte();if(b==27){b=d.getByte();if(b==">"||b=="=")continue}}else if(b==104){b=d.getByte();
if(b==27){b=d.getByte();if(b==61)continue}}}else if(b==55){b=d.getByte();if(b==104)continue;else if(b==49)continue;d.skipBack(1);b=55}else;}if(b==75){if(N==0&&F==0)kb();else lb();continue}if(b==74){mb();continue}break;case 7:break;case 9:bb();break;case 15:cb();break;case 8:oa();break;case 10:db();break;default:d.skipBack(1);nb(d)}}});Q.setHandler(wb);var pb=new Array;this.addSurface=function(c){y=c;if(Ca)c.setPlayerMode();G.setContext(y.context);k=G.getContext();Y=k.canvas;c.forceTextArea=true;c.alwaysPaste=
true;c.setAutoScale(e.mode>0);c.setSize(q+D,t+D);c.setController(la);c.setFastCopy(da(g["fastCopy"]));c.setTouchpad(da(g["touchpad"]));c.setClipboard(da(g["mapClipboard"]));c.run(99997,false,true);c.onclipdata=rb};var xb=new Uint8Array(6);xb[0]=5;var yb=new Uint8Array(8);yb[0]=4;this.writeText=ga;this.writeRawInput=function(c){if(!A)return;var d=parseInt(c.substring(0,2),16);var b=c.substring(2).split("\t");var f=0;var e=false;switch(d){case 128:var h=b[2];if(h==2)sb();return;case 129:return;case 130:return;
case 131:Ba(true,b[2]==0?200:208,0);return;case 132:e=b[0]==0;f=parseInt(b[1]);ga(qa.process(e,f,0));return;case 139:f=parseInt(b[1]);e=b[0]==0;ga(qa.process(e,f,1));return;case 134:ga(qa.process(true,b[0],3));return}svGlobal.logger.warn("Unknowncode: "+b[1]+" type:"+d)};var qa=new function(c,d,b){var f=false;var e=false;var h=false;this.process=function(b,c,d){if(d==3)return c;if(d==0){switch(c){case 29:case 157:f=b;return"";case 56:case 56|128:e=b;return"";case 42:case 54:h=b;return""}if(b){var g=
"";switch(c){case 28:g="\r";break;case 200:g="\u001bOA";break;case 208:g="\u001bOB";break;case 205:g="\u001bOC";break;case 203:g="\u001bOD";break;case 59:g="\u001bOP";break;case 60:g="\u001bOQ";break;case 61:g="\u001bOR";break;case 62:g="\u001bOS";break;case 63:g="\u001bOt";break;case 64:g="\u001bOu";break;case 65:g="\u001bOv";break;case 66:g="\u001bOI";break;case 67:g="\u001bOw";break;case 68:g="\u001bOx";break;case 15:g="\t";break;case 209:g="\u001b[6~";break;case 201:g="\u001b[5~";break;case 199:g=
"\u0001";break;case 207:g="\u0005";break;case 14:g=h?"\b":"\u007f";break;case 211:g="\u001b[3~";break;case 197:g="\u00ff\u00f3";break;case 210:g="\u001b[2~";break;case 1:g="\u001b";break;default:console.log("Invalid code:"+c);return""}if(e)g="\u001b"+g;return g}else return""}if(d==1)if(f)if(c>64&&c<91)return String.fromCharCode(c-64);else switch(c){case 54:return"\u001e";case 219:return"\u001b";case 220:return"\u001c";case 221:return"\u001d";case 32:return"\x00";case 192:return"\u001e";case 191:return"\u001f";
default:console.log("Invalid key code:"+c);return""}if(e)return"\u001b"+String.fromCharCode(c).toLowerCase()}}};
