var svGlobal={version:"4.7",log:1,isMultitask:hi5.browser.isMultitask,util:{},logger:{debug:function(e){2<svGlobal.log&&console.log(e)},info:function(e){1<svGlobal.log&&console.log(e)},warn:function(e){0<svGlobal.log&&console.log(e)}}};function cancelDefault(e){e.preventDefault&&e.preventDefault();e.stopPropagation&&e.stopPropagation();return!1}
function LocalInterface(e){function v(a){var b=0,d=0,c=a.offsetParent;c&&c.offsetParent&&(c=c.offsetParent,b=c.scrollTop,d=c.scrollLeft);a.focus();b&&(c.scrollTop=b);d&&(c.scrollLeft=d)}function p(){var a=[];this.sent=!1;this.types=[];var b=this;this.datas=a;this.setData=function(d,c){if("text/plain"==d||"text/html"==d)2<c.length&&"`\t`"==c.substring(0,3)&&(c=c.substring(3)),c=c.replace(/\r?\n/g,"\r\n");b.types.push(d);a.push(c)};this.getData=function(d){return a[b.types.indexOf(d)]};this.equals=
function(a){if(!a||!hi5.Arrays.equals(b.types,a.types))return!1;for(var c,f,q=b.types,m=0,y=q.length;m<y;m++)if(c=q[m],f=b.getData(c),c=a.getData(c),f!=c)return!1;return!0}}function F(a){function b(){var b=h?a.value:a.innerText||a.textContent;B&&!h&&b.charAt(0)!=n.PLACE_HOLDER&&(b=n.PLACE_HOLDER+b);return b}function d(){var b=B?n.PLACE_HOLDER:"";k=b;n.setValue(b);if(B)if(h)a.setSelectionRange&&a.setSelectionRange(a.value.length,a.value.length);else if(a.focus(),"undefined"!=typeof window.getSelection&&
"undefined"!=typeof document.createRange){b=document.createRange();b.selectNodeContents(a);b.collapse(!1);var c=window.getSelection();c.removeAllRanges();c.addRange(b)}else"undefined"!=typeof document.body.createTextRange&&(b=document.body.createTextRange(),b.moveToElementText(a),b.collapse(!1),b.select())}function c(a){G=8==a.keyCode;if(n.onkeydown)n.onkeydown(a);return!0}function f(b){if(n.onkeyup)n.onkeyup(b);b=b.keyCode;1!=(h?a.value:a.innerText||a.textContent).length&&13!=b&&32!=b||setTimeout(d,
100);return!0}function q(a){if(n.onbackspace)for(var b=0;b<a;b++)n.onbackspace()}function m(c){if(!n.disableTextInput){c.stopPropagation();c=b();var f=c.length;1<f&&c.charAt(0)!=n.PLACE_HOLDER&&c.charAt(f-1)==n.PLACE_HOLDER&&(c=n.PLACE_HOLDER+c.substring(0,f-1),n.setValue(c));if(c!=k){var m=k.length,y=c.indexOf(k);if(c&&0===y){if(c=c.substring(m),0<c.length&&e&&n.ontextinput&&(n.ontextinput({data:c,target:a}),"."==c)){d();return}}else if(y=k.indexOf(c),0===y)G||q(m-f);else if(e&&(B&&(m--,c=c.substring(1)),
q(m),0<c.length&&n.ontextinput))n.ontextinput({data:c,target:a});""===b()&&setTimeout(d,100);k=b()}}}function y(a){if(!n.disableTextInput&&a.data){a.stopPropagation();if(n.ontextinput)n.ontextinput(a);g&&a.preventDefault()}}var n=this,B=hi5.browser.isAndroid&&hi5.browser.isChrome,e=hi5.browser.isFirefox||hi5.browser.isOpera||B,G=!1,g=!hi5.browser.isRIM,k="",h="INPUT"==a.nodeName||"TEXTAREA"==a.nodeName,l="DIV"==a.nodeName;this.PLACE_HOLDER="`";this.setValue=function(b){var c=n.disableTextInput;n.disableTextInput=
!0;h?a.value=b:l&&(a.innerHTML=b);n.disableTextInput=c};this.init=d;this.disableTextInput=!1;d();a.addEventListener("keydown",c,!1);a.addEventListener("keyup",f,!1);e?(a.addEventListener("input",m,!1),B?a.onclick=d:a.addEventListener("mouseup",d,!1)):(a.addEventListener("textInput",y,!1),a.addEventListener("textinput",y,!1));this.release=function(){a.removeEventListener("keydown",c,!1);a.removeEventListener("keyup",f,!1);a.removeEventListener("input",m,!1);a.removeEventListener("focus",d,!1)};this.select=
function(){Ua(a)}}function D(a,b,d){function c(a){var c=0,n=0,d=0,e=a.pageX-a.target.offsetLeft,G=a.pageY-a.target.offsetTop;a.wheelDelta?(d=(new Date).getTime(),100<d-q&&(f=0),n=a.wheelDelta,f+=n,c=f/120|0,f%=120,0!==c&&b(c,e,G),q=d):(c=-a.detail,32768==Math.abs(c)&&(n=window.innerHeight/40|0,c=0>c?-n:n),b(c,e,G))}var f=0,q=0;a.addEventListener("DOMMouseScroll",c,!0);a.addEventListener("mousewheel",c,!0)}function x(a){function b(a){if(!q&&m.onmousedown)m.onmousedown(a)}function d(a){if(!q&&m.onmousemove)m.onmousemove(a)}
function c(a){if(q)q=!1;else if(m.onmouseup)m.onmouseup(a)}function f(a){"touchstart"==a.type&&(q=!0);if(m.ontouch)m.ontouch(a)}var q=!1,m=this,y=navigator.pointerEnabled||navigator.msPointerEnabled||!1;"ontouchstart"in window||!y?(a.addEventListener("touchstart",f,!1),a.addEventListener("touchend",f,!1),a.addEventListener("touchmove",f,!1),a.addEventListener("touchcancel",f,!1),a.addEventListener("mousemove",d,!1),a.addEventListener("mousedown",b,!1),a.addEventListener("mouseup",c,!1)):navigator.pointerEnabled?
(a.addEventListener("pointerdown",f,!1),a.addEventListener("pointerup",f,!1),a.addEventListener("pointermove",f,!1),a.addEventListener("pointercancel",f,!1)):navigator.msPointerEnabled&&(a.addEventListener("MSPointerDown",f,!1),a.addEventListener("MSPointerUp",f,!1),a.addEventListener("MSPointerMove",f,!1),a.addEventListener("MSPointerCancel",f,!1))}function r(){return k.railWin?!0:!ca&&N<=window.innerWidth&&L<=window.innerHeight}function z(a){function b(a,b){for(var d,n=a.length,f=Array(n),e=h.getElement().getBoundingClientRect(),
G=0;G<n;G++){d=a[G];var k=G,g;g=d.identifier;if(!(256>g)){var l=c.indexOf(g);-1!=l?g=l:(c.push(g),g=c.length-1)}f[k]={contactId:g,contactFlags:b,x:d.pageX-e.left,y:d.pageY-e.top}}return f}var d,c=[],f=!1;this.handle=function(q){var m=q.type,y=q.touches,n=q.changedTouches;cancelDefault(q);switch(m){case "touchstart":f=!1;d=q=b(y,25);break;case "touchmove":q=b(n,26);m=!1;if(0<d.length&&1==q.length){a:{y=d.length;for(n=0;n<y;n++)if(d[n].contactId==q[0].contactId){y=n;break a}y=-1}-1!=y&&d[y].x==q[0].x&&
d[y].y==q[0].y&&(m=!0)}if(m)break;else 0<d.length&&(a.redirectTouches(d),d.length=0);a.redirectTouches(q);f=!0;break;case "touchend":if(f)q=b(n,4);else{a.redirectTouches(d);q=d.length;for(m=0;m<q;m++)d[m].contactFlags=4;q=d}a.redirectTouches(q);c.length=d.length=0;break;case "touchcancel":a.redirectTouches(b(n,34)),c.length=d.length=0}}}function H(a){function b(a){var b=a[1].screenX-a[0].screenX;a=a[1].screenY-a[0].screenY;return Math.sqrt(b*b+a*a)}function d(a,n){var d=[],f=c(a,u[0].identifier)||
c(n,u[0].identifier);f&&d.push(f);(f=c(a,u[1].identifier)||c(n,u[1].identifier))&&d.push(f);f="";if(2!=d.length)return f;var q=b(d)-b(u);60>Math.abs(q)?80<d[0].screenX-u[0].screenX?f="RIGHT":80<u[0].screenX-d[0].screenX?f="LEFT":80<d[0].screenY-u[0].screenY?f="DOWN":80<u[0].screenY-d[0].screenY&&(f="UP"):f=0>q?"CLOSE":"OPEN";return f}function c(a,b){for(var c=0,n=a.length;c<n;c++)if(a[c].identifier==b)return a[c];return null}function f(a){this.identifier=a.pointerId;this.pageX=a.pageX;this.pageY=
a.pageY;this.screenX=a.screenX;this.screenY=a.screenY}var q=0,m=0,y=0,n=0,B=!1,e=0,G=0,g=0,k=0,h=!1,l=!1,t=3,p=!1;W&&(t*=3);this.delay=!1;var u=[],x=this;this.handlePointer=function(a){if(a.pointerType==a.MSPOINTER_TYPE_MOUSE||"mouse"==a.pointerType)switch(a.type){case "MSPointerDown":case "pointerdown":za(a);break;case "pointermove":case "MSPointerMove":Aa(a);break;case "pointerup":case "MSPointerUp":Ba(a)}else a.touches=a.changedTouches=[new f(a)],x.handle(a)};this.handle=function(b){var f=b.type,
A=0,A=b.touches,x=b.changedTouches,v,z;switch(f){case "touchstart":case "MSPointerDown":case "pointerdown":moveSpace=moveCount=0;p=!1;m="touchstart"==f?A.length:m+1;l=!1;n=(new Date).getTime();B=1==m&&200>n-y;f=A[0];q=f.identifier;e=f.pageX;G=f.pageY;h=!0;2!=A.length?p=!1:(v=A[1].screenX-A[0].screenX,p=100<Math.abs(A[1].screenY-A[0].screenY)||350<Math.abs(v));(B||2<m)&&cancelDefault(b);if(3==m){for(var f=z=v=0,x=9999,H=0,C=A.length;H<C;H++)A[H].screenY>f&&(f=A[H].screenY,v=H),A[H].screenY<x&&(x=A[H].screenY,
z=H);u=[{screenX:A[z].screenX,screenY:A[z].screenY,identifier:A[z].identifier},{screenX:A[v].screenX,screenY:A[v].screenY,identifier:A[v].identifier}]}break;case "pointermove":case "MSPointerMove":if(1<m)break;case "touchmove":if(p)return;1==m&&r()&&(w.disableScoll||window.scrollTo(0,0),cancelDefault(b));f=x[A.length-1];if(f.identifier!=q&&(f=c(x,q),!f)){cancelDefault(b);return}v=f.pageX;z=f.pageY;if(h){if(0===v-e&&0===z-G)return;if(Math.abs(v-e)<t&&Math.abs(z-G)<t){cancelDefault(b);return}h=!1;A=
(new Date).getTime()-n;if((l=180>A)&&!r()&&1==m){p=!0;return}a.touchstart({x:e,y:G,flick:l,pointes:m,screenX:f.screenX,screenY:f.screenY,moved:!0,target:b.target})}cancelDefault(b);a.touchmove({x:v,y:z,flick:l,pointes:m,moved:!0,screenX:f.screenX,screenY:f.screenY,target:b.target});break;case "MSPointerUp":case "touchend":case "pointerup":if(p)return;if(3==x.length+A.length){a.touchend({x:v,y:z,flick:l,pointes:m,moved:!h,target:b.target,gesture:d(A,x)});m=0;break}else{if(2<m){m=0;break}if(f=c(x,q))x=
(new Date).getTime(),v=f.pageX,z=f.pageY,l?a.touchend({x:v,y:z,flick:!0,pointes:m,moved:!h,screenX:f.screenX,screenY:f.screenY,target:b.target}):(A=x-n,h?(y=x,B?cancelDefault(b):(g=v,k=z),500>A?(y=x,a.touchstart({x:g,y:k,flick:!1,pointes:m,screenX:f.screenX,screenY:f.screenY,moved:!1,target:b.target}),a.touchend({x:g,y:k,flick:!1,pointes:m,moved:!1,screenX:f.screenX,screenY:f.screenY,target:b.target})):a.longpress({x:v,y:z,flick:!1,pointes:m,moved:!1,screenX:f.screenX,screenY:f.screenY,target:b.target})):
a.touchend({x:v,y:z,flick:!1,pointes:m,moved:!0,screenX:f.screenX,screenY:f.screenY,target:b.target}))}m=0;break;case "MSPointerCancel":case "touchcancel":m=0}B&&cancelDefault(b)}}function Va(){l(!0,14);l(!1,14)}function Ua(a){try{a.select?a.select():hi5.browser.selectEditable(a)}catch(b){console.log(b)}}function Wa(){function a(){f.focus()}function b(b,c){var d=document.createElement("a");d.href="#";d.accessKey=b;d.onfocus=a;d.style.position="absolute";d.style.width=1;d.style.height=1;d.style.left=
0;d.style.top=c+"px";return d}var d=hi5.browser.isIE,c=document.createElement(d?"textarea":"div"),f=this;this.setFontSize=function(a){c.style.fontSize=w.inputFontSize||a};d?(c.style.opacity=0,c.readOnly=C&&hi5.browser.isMetro?!0:!1):c.contentEditable=!C||hi5.browser.isChrome&&(hi5.browser.isWindows||hi5.browser.isCrOS)?!0:!1;c.accessKey="f";c.id="wsinput";c.tabIndex=1;c.style.opacity=0;c.style.resize="none";c.style.position="absolute";c.style.margin="0";c.style.border="none";c.style.outline="none";
var q=hi5.tool.getPos(e,!0);c.style.left=q.x+"px";c.style.top=q.y+"px";c.style.paddingRight=0;c.style.paddingBottom=0;c.style.width="10px";c.style.height="10px";c.style.zIndex=88;c.style.cursor="default";c.style.fontWeight="normal";c.style.fonStyle="normal";c.style.overflow="hidden";I=new F(c);I.onbackspace=Va;q=e.parentNode;q.appendChild(c);W&&(q.appendChild(b("E"),60),q.appendChild(b("V"),61),q.appendChild(b("A"),62),q.appendChild(b("T"),63),q.appendChild(b("H"),64));var m=c.style.opacity,y=c.style.textIndent;
this.resetCSS=function(){_fontSize=c.style.fontSize;m=c.style.opacity;c.style.opacity=0;c.style.textIndent=0};this.restoreCSS=function(){c.style.opacity=m;c.style.textIndent=y};this.getValue=function(){return d?c.value:c.innerHTML};this.setValue=function(a){I&&(I.disableTextInput=!0);d?c.value=a:c.innerHTML=a;I&&(I.disableTextInput=!1)};this.focus=function(){f.setValue(" ");v(c)};this.setContentEditable=function(a){d?c.readOnly==a&&(c.readOnly=!a):c.contentEditable!=a&&(c.contentEditable=a,"true"==
a&&W&&hi5.browser.selectEditable(c))};this.isIMEMode=!1;this.setIMEStatus=function(a){a?f.isIMEMode||(d&&(c.style.background="transparent",c.style.opacity=1),f.isIMEMode=!0):f.isIMEMode&&(d&&(c.style.background="",c.style.opacity=0),f.isIMEMode=!1)};this.adjust=function(a){var b=hi5.tool.getPos(e,!0),d=k.railWin?Math.min(window.innerWidth-b.x,N):N,q=k.railWin?Math.min(window.innerHeight-b.y,L):L,m=Math.min(window.innerWidth-b.x,N),y=Math.min(window.innerHeight-b.y,L),m=Math.round(.7*m);a=Math.round(y*
(a?.99:.7));d-=m;q-=a;w.disableAdjust&&(a=m=0,d=e.offsetWidth+"px",q=e.offsetHeight+"px");c.style.width=d+"px";c.style.height=q+"px";c.style.paddingLeft=m+"px";c.style.paddingTop=a+"px";c.style.left=b.x+"px";c.style.top=b.y+"px";c.style.textIndent=-(m+(W?48:0))+"px";hi5.browser.isFirefox&&(c.style.fontSize=0);C&&hi5.browser.isChrome&&f.setFontSize("2em");w.disableScoll||window.scrollTo(0,0)};this.remove=function(){c.parentNode&&c.parentNode.removeChild(c)};this.hide=function(){c.style.visibility=
"hidden"};this.getElement=function(){return c};this.select=function(){Ua(c)}}function Ca(){if(!g){var a=e.parentNode;g=a.querySelector('canvas[name="svImgCursor"]');g||(g=document.createElement("canvas"),g.name="svImgCursor",g.style.position="absolute",g.style.left=90,g.style.top=90,g.scrX=0,g.scrY=0,g.hotX=10,g.hotY=10,g.width=g.height=32,"ontouchstart"in window?(g.addEventListener("touchstart",O,!1),g.addEventListener("touchend",O,!1),g.addEventListener("touchmove",O,!1),g.addEventListener("touchcancel",
O,!1)):navigator.pointerEnabled?(g.addEventListener("pointerdown",O,!1),g.addEventListener("pointerup",O,!1),g.addEventListener("pointermove",O,!1),g.addEventListener("pointercancel",O,!1)):navigator.msPointerEnabled&&(g.addEventListener("MSPointerDown",O,!1),g.addEventListener("MSPointerUp",O,!1),g.addEventListener("MSPointerMove",O,!1),g.addEventListener("MSPointerCancel",O,!1)),g.setCursor=function(a){var d=a.width,c=a.height,f=a.rawData,q=d*c,m=0,e=0;if(!(1>q)){g.hotX=a.hotX;g.hotY=a.hotY;g.width=
d;g.height=c;a=g.getContext("2d");var n=a.createImageData(d,c),B=n.data;if(f){for(d=0;d<q;d++)m=f[d],B[e++]=m&255,B[e++]=m>>8&255,B[e++]=m>>16&255,B[e++]=m>>24&255;a.putImageData(n,0,0)}else a.fillStyle="rgba(0,0,0,0)",a.fillRect(0,0,d,c)}},Da?g.setCursor(Da):g.setCursor({rawData:[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,-16777216,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,-16777216,-1,-1,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-1,-16777216,-16777216,-16777216,-16777216,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-16777216,
-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-16777216,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-16777216,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-16777216,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,0,0,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],width:32,height:32}),a.appendChild(g))}}function Xa(a){if(!1!==w.disableScrollbars){var b=document.body;a?(Ea=a,b.style.overflow=a):(Ea=N<=window.innerWidth&&L<=window.innerHeight?
"hidden":"visible",b.style.overflow=Ea)}}function la(a){var b=e.parentNode,d=window.innerWidth,c=window.innerHeight;Math.max(N,L)<Math.max(d,c)&&Math.min(N,L)<Math.min(d,c)?1!=P&&(hi5.tool.scale(b,1),P=S=1):(document.body.style.overflow="hidden",P=S=a?Math.min(window.innerWidth/N,window.innerHeight/L):1,hi5.tool.scale(b,P,P))}function Ya(){var a=chrome.app.window.current();a&&a.fullscreen()}function Fa(a){a||(a="div");var b=document.createElement(a),d=document.body;b.id="_tmpEditable";"div"==a&&(b.contentEditable=
!0);b.style.position="absolute";b.style.zIndex=9999;b.style.left=d.scrollLeft+50+"px";b.style.top=d.scrollTop+50+"px";b.tabIndex=2;b.style.outline="none";b.style.opacity=0;d.appendChild(b);return b}function Za(a){Ga.clearPDF();k.focused=!0;t.onfocus(a);sa=!0;t.send("891");da.sendMissKey();T&&u&&u.startPasteCmd()}function $a(a){var b=__svi18n.remoteApp.close;if(!ab&&k.railWin&&k.railWin.isRunning()&&b&&(a||(a=window.event),2!=t.getAppMode()))return k.showMessage(b),a&&(a.returnValue=b),b}function Ha(a){k.focused=
!1;if(k.onunload)k.onunload()}function Ia(){h&&(h.getElement().oncontextmenu=function(){return!1},W||(h.getElement().onselectstart=function(){return!1}))}function Ja(){h&&(h.getElement().oncontextmenu=null,h.getElement().onselectstart=null)}function Bb(a){h&&h.adjust();if(ea)la(!0);else if(!(ca&&2500>(new Date).getTime()-ca)){var b=hi5.browser.isWindows&&!hi5.browser.isMetro;if(!C||b)t.onresize(a)}}function Cb(){window.svSurface||(window.svSurface=k);window.addEventListener("resize",Bb,!1);if(!U){var a=
!hi5.browser.isChromeApp;a&&window.addEventListener("beforeunload",$a,!1);a?window.addEventListener("unload",Ha,!1):chrome.runtime.onSuspend.addListener(Ha);Ia();window.addEventListener("focus",Za,!1);window.addEventListener("blur",function(a){k.focused=!1},!1);hi5.browser.isChromeApp&&chrome.app.window.current().onMaximized.addListener(Ya);(a=hi5.$("saveSession"))&&a.addEventListener("change",function(a){t.saveSession({save:a.target.checked})})}}function bb(){if(!M){var a=hi5.$("touchGesture");a&&
(a.style.display="block");if(a=hi5.$("extKBD"))a.onchange=function(a){k.setExtKeyboard(a.target.checked)};M=hi5.$("svTouchInput");try{window.parent==window||M||(M=window.parent.document.getElementById("svTouchInput"))}catch(b){}M&&(hi5.browser.isWindows&&(a=document.createElement("div"),a.contentEditable=!0,a.id="svTouchInput",M.parentNode.replaceChild(a,M),M=a),hi5.browser.isChrome&&(M.style.fontSize="2em"),E=new F(M),E.onkeydown=E.onkeyup=cb,E.ontextinput=db,E.onbackspace=Va)}}function ma(a,b){function d(a,
c){var d=document.createElement("span");d.data_path=a;d.className="path";d.innerHTML=c;d.onclick=function(){ma(this.data_path,b)};return d}function c(a){for(var b=f;b.hasChildNodes();)b.removeChild(b.firstChild);var c=d("/","&nbsp&nbsp&nbsp/");b.appendChild(c);if("/"!=a&&""!==a){a=a.split("/");for(var n="/",B=0,e=a.length;B<e;B++)c=a[B],""!==c&&(n=n+a[B]+"/",c=d(n,c+"/"),b.appendChild(c))}}var f=hi5.$("parentPath");f.currentDir||(f.currentDir="/");"."==a?a=f.currentDir:f.currentDir=a;f.currentDir=
a;t.getShareFiles(a,function(a){function d(b){b||(b=n.getValue("Name"));var c=a.parent;if(""===c||"/"!=c.charAt(c.length-1))c+="/";return c+b}a.error&&k.showMessage(__svi18n.file[a.error]);var f=new hi5.DataTable(a),n=new hi5.DataGrid(hi5.$("filelist"));n.dataTable=f;var B=hi5.tool.bytesToSize;n.beforeDisplayValue=function(a,b){var c=f.cols[a].name;return"Date Modified"==c?(new Date(b)).toLocaleString():"Size"==c?B(b):"Type"==c&&"folder"==b?__svi18n.file.folder:"Name"==c?decodeURIComponent(b):b};
n.onrowclick=function(c){var f=n.getValue("Name"),B=n.getValue("Type"),e=d(f);c=c.target.name;"delete"==c?(J.removeFile(e),ma(a.parent,b)):"folder"==B?ma(("/"==a.parent?"":a.parent)+"/"+f,b):("view"==c&&(e+="&action=view"),t.getFile(e))};n.beforeAppendRow=function(a){var b;if("folder"==f.getValue(f.getColNo("Type"))){if(b=a.querySelector('img[name="download"]'))b.style.visibility="hidden"}else{a.draggable=!0;b=n.getValue("Name");var c=d(b),c="application/octet-stream:"+b+":"+t.getFileLink(c);a.addEventListener("dragstart",
function(a){a.dataTransfer.setData("DownloadURL",c)},!1);if(10<b.length&&".uploading"==b.substring(b.length-10)){if(b=a.querySelector('img[name="download"]'))b.style.visibility="hidden";if(b=a.querySelector('img[name="view"]'))b.style.visibility="hidden"}}};n.open();c(a.parent);var e=document.getElementById("__diskSpace");e&&(e.innerHTML=hi5.tool.bytesToSize(a.freeSpace)+"/"+hi5.tool.bytesToSize(a.totalSpace));b.resize()})}function eb(a){a&&cancelDefault(a);a=hi5.$("filecontainer");V=new hi5.Lightbox(a);
ma(".",V);V.show()}function Ka(){var a=hi5.$("svToolbar");if(a){for(var b=a.childNodes,d=!1,c=0,f=b.length;c<f;c++)if(1==b[c].nodeType&&-1==["svTouchInput","svCloud","svInfo"].indexOf(b[c].id)){d=!0;break}b=hi5.$("appinfo");if(k.showToolbar&&(C||J||b||d)){if(d=null===k.toolbar)k.toolbar=new hi5.Toolbar(a);C?k.toolbar.activeObj=M:(a=hi5.$("svTouchInput"))&&a.parentNode.removeChild(a);if(a=k.toolbar.getButton("svCloud"))J?(a.style.display="",a.onclick=eb):a.style.display="none";new hi5.Fadable(k.toolbar,
w.toolbar.fadeDelay||5E3,h.getElement());a=w.toolbar.fadable;k.toolbar.setFadable(a);a&&(k.toolbar.style.display="none");if(a=k.toolbar.getButton("svInfo"))b?(a.style.display="",d&&(a.onclick=function(a){cancelDefault(a);a=t.getAppInfo();var b=hi5.$("numericId");b&&(b.innerHTML=a.numericId);if(b=hi5.$("connectingTo"))b.innerHTML=a.server;if(b=hi5.$("joinLink"))b.href=b.innerHTML=a.joinLink;a=new hi5.Lightbox(hi5.$("appinfo"));a.show();Ja();a.onclose=Ia})):a.style.display="none";if(k.onloadtoolbar)k.onloadtoolbar(k.toolbar)}}}
function fb(a){J.addFiles(a.target.files);a=hi5.$("uploadfile");var b=a.cloneNode(!0);a.parentNode.replaceChild(b,a);b.addEventListener("change",fb,!1)}function Db(){var a=h.getElement();J&&!U&&(svGlobal.util.initMapDisk(a,J),svGlobal.util.initMapDisk(hi5.$("filecontainer"),J),hi5.$("uploadfile").addEventListener("change",fb,!1))}function gb(a){a.target!=h.getElement()&&fa(hb,ib,a.button)}function La(a,b,d){g&&(a=g.scrX+a,b=g.scrY+b,0>a?a=0:a>N&&(a=N-1),0>b?b=0:b>L&&(b=L-1),g.scrX=a,g.scrY=b,g.style.left=
a-g.hotX+"px",g.style.top=b-g.hotY+"px",K&&!d&&t.sendInput("82"+a+"\t"+b))}function na(a,b,d){g||Ca();La(a-g.scrX,b-g.scrY,d)}function Ma(a,b,d,c){var f;switch(a){case "touchstart":Na=!1;0===g.scrX&&0===g.scrY&&na(b-50,d-50);c&&t.sendInput("80"+g.scrX+"\t"+g.scrY+"\t0");break;case "touchmove":c=b-ta;a=d-ga;if(0===c&&0===a)return;f=5>Math.abs(jb)&&5>Math.abs(kb)&&(7<Math.abs(c)||7<Math.abs(a));f||(La(c,a),Na=!0);jb=c;kb=a;break;case "touchend":(a=!Na&&!c)&&t.sendInput("80"+g.scrX+"\t"+g.scrY+"\t0"),
(a||c)&&t.sendInput("81"+g.scrX+"\t"+g.scrY+"\t0")}ta=b;ga=d}function O(a){K&&("ontouchstart"in window?oa.handle(a):oa.handlePointer(a))}function cb(a){if(!K)return!1;da.check(a);var b=ha.getKeyCode(a),d="keydown"==a.type;d&&h&&h.setIMEStatus(229==b);if(18==b&&(lb&&d&&(Oa=2==(a.location||a.keyLocation)),Oa))return!0;if(mb(a,b,d))return cancelDefault(a);17!=b||d||(pa=!1);var c=nb(b);if(0<c)return l(d,c),c=a.target==h.getElement(),d&&ia&&h&&17==b&&(hi5.browser.isFirefox||hi5.browser.isSafari||W&&!c)&&
(c?(h.setValue("`\t`"),h.select()):(E.setValue("`\t`"),E.select())),cancelDefault(a);if(a.ctrlKey||a.altKey&&!Oa||a.metaKey)return(86!=b||!a.ctrlKey&&!a.metaKey||a.ctrlKey&&a.altKey||!T)&&R(d,b),d&&(ua=b),17==b||(a.ctrlKey||a.metaKey)&&(86==b||67==b||88==b)?(!d||67!=b&&88!=b||(pa=!0),!0):a.altKey&&!a.ctrlKey||a.ctrlKey&&!a.altKey?cancelDefault(a):!0;if(!(b!=ua||d||a.ctrlKey&&a.altKey))return R(!1,b),ua=0,!0;ua=0;return!0}function mb(a,b,d){if(!a.altKey)return!1;switch(b){case 8:case 35:if(!a.ctrlKey&&
!a.metaKey)return!1;l(d,211);break;case 33:l(d,15);break;case 34:d?(l(!0,42),l(!0,15)):(l(!1,15),l(!1,42));break;case 45:l(d,1);break;case 36:d?(l(!1,56),l(!0,29),l(!0,1)):(l(!1,1),l(!1,29));break;default:return!1}return!0}function Eb(a){if(!K)return!1;da.check(a);var b=ha.getKeyCode(a),d="keydown"==a.type,c=da.preKeyCode;d?h&&h.setIMEStatus(229==b):h&&h.isIMEMode&&W&&h&&h.setIMEStatus(!1);if(mb(a,b,d))return cancelDefault(a);da.preKeyCode=b;if(229==b||229==c&&!d)return!0;44==b?(l(!0,170),l(!0,183),
c=!0):19==b?(d?(l(!0,225),l(!0,29),l(!0,69),l(!0,225),l(!0,157),l(!0,197)):l(!1,29),c=!0):c=!1;if(c)return cancelDefault(a);(c=ha.getScancode(a))||(c=nb(b)||0);var f=86==b&&(ob&&!d||(a.ctrlKey||a.metaKey)&&!(a.ctrlKey&&a.altKey))&&T;0<c&&!f?l(d,c):f||R(d,b);17!=b&&(ob=f);return 17==b||(a.ctrlKey||a.metaKey)&&(86==b||67==b||88==b)?(d&&(17==b&&ia&&h&&(h.setValue("`\t`"),h.select()),67==b||88==b)&&(pa=!0),17!=b||d||(pa=!1),!0):144==b||16==b?!1:cancelDefault(a)}function db(a){if(K&&(a=a.data,!(!C&&va&&
1==a.length&&128>a.charCodeAt(0))&&"`\t`"!=a)){var b=aa||ba;b&&(a=a.toLowerCase());W&&(a=a.replace(/\u00a0/g," "));t.sendInput("86"+a+"\t"+(b||va?1:0));X&&X.resetModifier()}}function pb(){l(!0,29);R(!0,86);R(!1,86);l(!1,29)}function Fb(a){var b=0===a.types.length||a.equals(u.clipData),d=b?"":a.types.join(","),c=0,f=!0;b||((b=a.getData("text/html"))?(b=b.replace(/(<([^>]+)>)|\r?\n/gi,""),-1==d.indexOf("text/richtext")&&(d+=",text/richtext")):b=a.getData("text/plain"),b&&(c=b.hashCode()),t.send("880"+
d+"\t"+c),u.clipData=a,k.onclipdata&&(f=!k.onclipdata(u.clipData)));f&&setTimeout(pb,500)}function ja(a,b){if(k.onscancode){var d=k.onscancode(a,b);if(d){for(var c=0,f=d.length;c<f;c++)t.sendInput("84"+(d[c].down?0:49152)+"\t"+d[c].key);return}}t.sendInput("84"+(a?0:49152)+"\t"+b)}function l(a,b){if(K)if(184==b)ja(a,29),ja(a,56);else switch(!a&&(hi5.browser.isCrOS&&61<b&&69>b||58==b&&qb||95==b)&&ja(!0,b),95!=b&&ja(a,b),b){case 221:a&&ja(!1,221);break;case 58:qb&&a&&ja(!1,58)}}function R(a,b){K&&(111==
b?a&&t.sendInput("86/\t1"):t.sendInput("8B"+(a?0:49152)+"\t"+b))}function qa(a,b,d,c,f){c||(c=P);f||(f=S);Pa[d]||(Pa[d]=!0,t.sendInput("80"+a/c+"\t"+b/f+"\t"+d))}function za(a){var b=a.target;v(b);if(!K)return!1;h&&h.setIMEStatus(!1);a.ctrlKey||a.shiftKey||a.metaKey||a.altKey||da.sendMissKey();b=b.getBoundingClientRect();qa(a.pageX-b.left,a.pageY-b.top,a.button);return cancelDefault(a)}function wa(a,b,d,c){d||(d=P);c||(c=S);hb=a;ib=b;t.sendInput("82"+a/d+"\t"+b/c)}function Aa(a){if(!K)return!1;var b=
a.target;g&&"-30px"!=g.style.left&&(g.style.left="-30px");b=b.getBoundingClientRect();wa(a.pageX-b.left,a.pageY-b.top);return cancelDefault(a)}function fa(a,b,d,c,f){c||(c=P);f||(f=S);Pa[d]=!1;t.sendInput("81"+a/c+"\t"+b/f+"\t"+d);0==d&&rb&&hi5.browser.isChrome&&u.waitForCopyContent();rb=2==d}function Ba(a){if(!K)return!1;var b=a.target.getBoundingClientRect();fa(a.pageX-b.left,a.pageY-b.top,a.button);return cancelDefault(a)}function sb(a,b,d,c,f){c||(c=P);f||(f=S);t.sendInput("83"+a/c+"\t"+b/f+"\t"+
d)}function tb(a,b,d){if(!K)return!1;sb(b,d,0>a?1:0);return!1}function nb(a){(a=Gb[a])||(a=-1);return a}function ub(a){return a.none?"none":a.url?"url("+a.url+"), pointer":0==a.data.indexOf("data:image/")?"url("+a.data+") "+a.hotX+" "+a.hotY+", default":a.data}e||(e=hi5.$("remotectrl"));if(window.svSurface&&svSurface.canvas==e&&svSurface.railWin)return svSurface.railWin.mainWin=null,window.svSurface;var C=hi5.browser.isTouch,Qa=!1,t=null,ea=!1,P=1,S=1;e.style.outline="none";var N=0,L=0,Q=e.getContext("2d"),
I=null,E=null,vb=!1,aa=!1,ba=!1,ka=!1,ab=!1,sa=!0,J=null,T=!0,pa=!1,ob=!1;this.context=Q;this.fileProgress=null;var k=this,K=!0,Y=!1,U=!1,va=!1,ra=null,V=null,g=null,Da=null,oa=null,M=null,ca=0,ta=-1,ga=-1,jb=0,kb=0,Na=!1,Ea=null,wb=document.queryCommandSupported("copy"),hb=0,ib=0,xb=0,yb=0;this._cr=[82,69,77,79,84,69,83,80,65,82,75];window.svSurface=this;var w=hi5.appcfg||{img:{},toolbar:{fadable:!0}};this.setConfig=function(a){w=a};this.railWin=this.toolbar=null;this.focused=!1;this.showToolbar=
!0;this.canvas=e;this.mouseMoveEmu=this.alwaysPaste=!1;"visible"in w.toolbar&&(this.showToolbar=w.toolbar.visible);var Ra=[],lb=!1,Oa=!1;this.getWindow=function(){return window};this.getScale=function(){return{x:P,y:S}};var Z=null,X=null,xa="",ia=!hi5.browser.isChromeApp&&!w.copyDialog,W=hi5.browser.isIE;this.getThumbnail=function(a){a=a||64;Z||(Z=document.createElement("canvas"));var b=Math.floor(e.height/e.width*a);Z.width!=a&&(Z.width=a);Z.height!=b&&(Z.height=b);Z.getContext("2d").drawImage(e,
0,0,e.width,e.height,0,0,a,b);return Z.toDataURL()};this.initChat=function(a){var b=document.getElementById("chatWindow");hi5.Dragable(b);return new hi5.Chat(b,a)};this.equals=function(a){return e==a.canvas};this.getFreeSpace=function(){var a=hi5.tool.getPos(e);return{width:window.innerWidth-a.x,height:window.innerHeight-a.y}};var ha=new function(){var a=1033,b=hi5.browser.isFirefox,d=hi5.browser.isMacOS||hi5.browser.isiOS,c=[0],f=null;c[8]=14;c[9]=15;c[13]=28;c[16]=42;c[17]=29;c[18]=56;c[19]=197;
c[20]=58;c[27]=1;c[33]=201;c[34]=209;c[35]=207;c[36]=199;c[37]=203;c[38]=200;c[39]=205;c[40]=208;c[44]=55;c[45]=210;c[46]=211;c[48]=11;c[49]=2;c[50]=3;c[51]=4;c[52]=5;c[53]=6;c[54]=7;c[55]=8;c[56]=9;c[57]=10;c[65]=30;c[66]=48;c[67]=46;c[68]=32;c[69]=18;c[70]=33;c[71]=34;c[72]=35;c[73]=23;c[74]=36;c[75]=37;c[76]=38;c[77]=50;c[78]=49;c[79]=24;c[80]=25;c[81]=16;c[82]=19;c[83]=31;c[84]=20;c[85]=22;c[86]=47;c[87]=17;c[88]=45;c[89]=21;c[90]=44;c[91]=219;c[92]=220;c[93]=221;c[96]=82;c[97]=79;c[98]=80;c[99]=
81;c[100]=75;c[101]=76;c[102]=77;c[103]=71;c[104]=72;c[105]=73;c[106]=55;c[107]=78;c[109]=74;c[110]=83;c[111]=181;c[112]=59;c[113]=60;c[114]=61;c[115]=62;c[116]=63;c[117]=64;c[118]=65;c[119]=66;c[120]=67;c[121]=68;c[122]=87;c[123]=88;c[144]=69;c[145]=70;c[154]=183;c[166]=59;c[167]=60;c[168]=61;c[173]=66;c[174]=67;c[175]=68;c[182]=63;c[183]=62;c[216]=64;c[217]=65;c[186]=39;c[187]=13;c[188]=51;c[189]=12;c[190]=52;c[191]=53;c[192]=41;c[219]=26;c[220]=43;c[221]=27;c[222]=40;c[224]=29;c[225]=184;var q=
function(a){a=a.keyCode;if(b)switch(a){case 173:return 189;case 61:return 187;case 59:return 186;case 224:return 17}return a},m=d?function(a){switch(a){case 91:case 93:return 17;case 17:return 91;case 229:return 69}return 0}:null;this.setLayout=function(b){a=b;var d=null,q="K"+b;q in e&&(d=e[q]());null===d&&(1033==b||0>b||3758096384<b)&&(d=c);f=d;null!==f&&svGlobal.logger.info("Keyboard layout: "+a)};this.getKeyCode=function(a){var b=0;m&&(b=m(a.keyCode));b||(b=q?q(a):a.keyCode);return b};this.getScancode=
function(a){a=ha.getKeyCode(a);return f?f[a]:0};var e=new function(){this.K3758162961=function(){var a=c.slice(0);a[244]=41;a[243]=41;a[189]=12;a[222]=13;a[220]=125;a[192]=26;a[219]=27;a[187]=39;a[186]=40;a[221]=43;a[188]=51;a[190]=52;a[191]=53;a[226]=115;a[29]=123;a[28]=121;a[240]=112;a[242]=112;b&&(a[173]=12,a[160]=13,a[64]=26,a[59]=39,a[58]=40,q=function(a){return 220==a.keyCode&&"_"==a.key?226:a.keyCode});return a};this.K1034=this.K66570=this.K2058=this.K1040=this.K66576=function(){var a=c.slice(0);
a[220]=41;a[219]=12;a[221]=13;a[186]=26;a[187]=27;a[191]=43;a[192]=39;a[189]=53;a[226]=86;b&&(a[171]=27,a[173]=53,q=function(a){var b=a.keyCode,c=a.key;if(0===b){if("\u00ba"==c||"\u00aa"==c&&a.shiftKey||"\\"==c&&a.ctrlKey&&a.altKey)return 220;if("\u00a1"==c||"\u00bf"==c&&a.shiftKey)return 221;if("\u00e7"==c||"\u00c7"==c&&a.shiftKey||"}"==c&&a.ctrlKey&&a.altKey)return 191;if("\u00f1"==c||"\u00d1"==c&&a.shiftKey)return 192;if("DeadAcute"==c||"\u00b4\u00b4"==c||"\u00b4"==c||"DeadUmlaut"==c&&a.shiftKey||
"{"==c&&a.ctrlKey&&a.altKey)return 222}else{if(192==b)return 186;if(222==b)return 219}return b});return a};this.K2057=function(){var a=c.slice(0);a[223]=41;a[222]=43;a[192]=40;a[220]=86;b&&(a[192]=41,a[173]=12,a[61]=13,a[59]=39,a[222]=40,a[163]=43);return a};this.K1031=this.K4106=this.K5130=this.K6154=this.K7178=this.K8202=this.K9226=this.K10250=this.K11274=this.K12298=this.K13322=this.K14346=this.K15370=this.K16395=this.K17418=this.K18442=this.K19466=this.K20490=this.K99997=this.K66567=this.K2952791047=
function(){var a=c.slice(0);a[220]=41;a[219]=12;a[221]=13;a[186]=26;a[187]=27;a[191]=43;a[192]=39;a[189]=53;a[226]=86;a[90]=21;a[89]=44;b&&(q=function(a){var b=a.keyCode,c=a.key;switch(b){case 60:return 226;case 160:return 220;case 63:return 219;case 192:return 221;case 171:return 187;case 163:return 191;case 173:return 189;case 0:if("\u00f6"==c||"\u00d6"==c&&a.shiftKey)return 192;if("\u00e4"==c||"\u00c4"==c&&a.shiftKey)return 222;if("\u00fc"==c||"\u00dc"==c&&a.shiftKey)return 186}return b});return a};
this.K2060=this.K99998=function(){var a=c.slice(0);a[222]=41;a[219]=12;a[189]=13;a[221]=26;a[186]=27;a[77]=39;a[192]=40;a[188]=50;a[190]=51;a[191]=52;a[187]=53;a[226]=86;a[65]=16;a[90]=17;a[81]=30;a[87]=44;b&&(q=function(a){var b=a.keyCode,c=a.key;switch(b){case 60:return 226;case 169:return 219;case 173:return 189;case 160:return 221;case 164:return 186;case 165:return 192;case 59:return 190;case 58:return 191;case 61:return 187;case 0:if("\u00b2"==c||"\u00b3"==c&&a.shiftKey)return 222;if("\u00b5"==
c||"`\u00b5"==c||"DeadGrave"==c||"\u00a3"==c&&a.shiftKey||("`"==c||"``"==c)&&a.ctrlKey&&a.altKey)return 220}return b});return a};this.K3084=this.K4105=function(){var a=c.slice(0);a[222]=41;a[192]=40;a[226]=86;b&&(q=function(a){var b=a.keyCode,c=a.key;switch(b){case 0:if("\u00b0"==c||"\u00ac"==c&&a.ctrlKey&&a.altKey)return 222;if("\u00e7"==c||"\u00c7"==c&&a.shiftKey)return 221;if("\u00e0"==c||"DeadGrave"==c||"\u00c0"==c&&a.shiftKey)return 220;if("\u00e8"==c||"\u00c8"==c&&a.shiftKey)return 192;if("\u00e9"==
c||"\u00c9"==c&&a.shiftKey)return 191;if("\u00f9"==c||"\u00d9"==c&&a.shiftKey)return 226;if("DeadTilde"==c)return 221;break;case 173:return 189;case 61:return 187;case 160:return 219;case 59:return 186}return b});return a};this.K1036=function(){var a=c.slice(0);a[222]=41;a[219]=12;a[187]=13;a[221]=26;a[186]=27;a[220]=43;a[77]=39;a[192]=40;a[190]=51;a[191]=52;a[223]=53;a[226]=86;a[65]=16;a[90]=17;a[81]=30;a[87]=44;a[188]=50;b&&(q=function(a){var c=a.keyCode,b=a.key;switch(c){case 0:if("\u00b2"==b)return 222;
if("\u00e7"==b||"\u00c7"==b&&a.shiftKey)return 221;if("\u00e0"==b||"\u00c0"==b&&a.shiftKey)return 220;if("\u00e8"==b||"\u00c8"==b&&a.shiftKey)return 192;if("\u00e9"==b||"\u00c9"==b&&a.shiftKey)return 189;if("\u00f9"==b||"\u00d9"==b&&a.shiftKey)return 226;if("DeadTilde"==b)return 221;break;case 60:return 226;case 169:return 219;case 61:return 187;case 160:return 221;case 164:return 186;case 170:return 220;case 165:return 192;case 59:return 190;case 58:return 191;case 161:return 223}return c});return a};
this.K4108=this.K2055=function(){var a=c.slice(0);a[191]=41;a[219]=12;a[221]=13;a[186]=26;a[192]=27;a[223]=43;a[222]=39;a[220]=40;a[188]=51;a[190]=52;a[189]=53;a[226]=86;a[90]=21;a[89]=44;b&&(q=function(a){var b=a.keyCode,c=a.key;switch(b){case 0:if("\u00a7"==c||"\u00b0"==c&&a.shiftKey)return 191;if("\u00e0"==c||"\u00e4"==c&&a.shiftKey||"{"==c&&a.ctrlKey&&a.altKey)return 220;if("\u00e8"==c||"\u00fc"==c&&a.shiftKey||"["==c&&a.ctrlKey&&a.altKey)return 186;if("\u00e9"==c||"\u00f6"==c&&a.shiftKey)return 222;
break;case 222:return 219;case 160:return 221;case 161:return 192;case 164:return 223;case 173:return 189;case 60:return 226}return b});return a};this.K1044=this.K1083=function(){var a=c.slice(0);a[220]=41;a[187]=12;a[219]=13;a[221]=26;a[186]=27;a[191]=43;a[192]=39;a[222]=40;a[189]=53;a[226]=86;b&&(q=function(a){var b=a.keyCode,c=a.key;switch(b){case 0:if("\u00e5"==c||"\u00c5"==c&&a.shiftKey)return 221;if("\u00f8"==c||"\u00d8"==c&&a.shiftKey||"\u00f6"==c&&a.ctrlKey&&a.altKey)return 192;if("\u00e6"==
c||"\u00c6"==c&&a.shiftKey||"\u00e4"==c&&a.ctrlKey&&a.altKey)return 222;break;case 172:return 220;case 171:return 187;case 220:return 219;case 160:return 186;case 222:return 191;case 173:return 189;case 60:return 226}return b});return a};this.K1053=function(){var a=c.slice(0);a[220]=41;a[187]=12;a[219]=13;a[221]=26;a[186]=27;a[191]=43;a[192]=39;a[222]=40;a[189]=53;a[226]=86;b&&(q=function(a){var c=a.keyCode,b=a.key;switch(c){case 0:if("\u00a7"==b||"\u00bd"==b&&a.shiftKey)return 220;if("\u00e5"==b||
"\u00c5"==b&&a.shiftKey)return 221;if("\u00f8"==b||"\u00d8"==b&&a.shiftKey||"\u00f6"==b&&a.ctrlKey&&a.altKey)return 192;if("\u00e4"==b||"\u00c4"==b&&a.shiftKey)return 222;break;case 171:return 187;case 192:return 219;case 160:return 186;case 222:return 191;case 173:return 189;case 60:return 226}return c});return a}}},u=new function(){function a(a,b){var c=d.parseClipData(b),e=!1;"text/plain"==c.type&&(e=window.clipboardData?window.clipboardData.setData("Text",c.value)||!0:a.clipboardData.setData("text/plain",
c.value)||!0,a.preventDefault());e||(hi5.browser.isIE?(e=Fa("div"),e.innerHTML=c.value,hi5.browser.selectEditable(e)):(h.resetCSS(),h.setValue(c.value),h.select()));return c}function b(){u.copyContent&&(u.copyToClipboard("text/plain"==u.copyContent.type?"textarea":"div",u.copyContent.value),u.copyContent=null);u.waitingCopyContent=!1}var d=this;this.clipData=null;this.paste=function(a,c,b){var d=new p,e=0,e=window.clipboardData||c.clipboardData;b=null;var g=e.getData(window.clipboardData?"Text":"text/plain");
if(g)d.setData("text/plain",g);else if(e)if(g=e.items)for(e=0,len=g.length;e<len;e++){if("image/png"==g[e].type){b=g[e].getAsFile();break}}else if(e.files)for(g=e.files,e=0,len=g.length;e<len;e++)if(-1!=g[e].type.indexOf("image/png")){b=g[e];break}if(b)e=new FileReader,c.preventDefault(),e.onloadend=function(c){c.target.readyState==FileReader.DONE&&(c=hi5.Base64.enc(new Uint8Array(c.target.result)),d.setData("image/png",c),a(d))},e.readAsArrayBuffer(b);else{var k=c.target.innerHTML;I&&(I.disableTextInput=
!0);E&&(E.disableTextInput=!0);var h=c.target.style.opacity;c.target.style.opacity=0;setTimeout(function(){var b=c.target.innerHTML;if(b&&b!=k){var e=c.target.childNodes;-1<b.search(/<.*(font|color|img|table|style|class).*>/gmi)?1==e.length&&"IMG"==e[0].nodeName&&0===e[0].src.indexOf("data:image/png;base64,")?d.setData("image/png",e[0].src.substring(22)):d.setData("text/html",b):0===d.types.length&&d.setData("text/plain",b);c.target.innerHTML="";I&&I.init()}a(d);c.target.style.opacity=h;I&&(I.disableTextInput=
!1);E&&(E.disableTextInput=!1)},300)}};var c=0;this.onCopy=function(b){K&&T||cancelDefault(b);if(!pa){l(!0,29);var e="copy"==b.type?"67":88;R(!0,e);R(!1,e);l(!1,29)}if(vb){var e=(new Date).getTime(),m=e-c;c=e;if(500<m)return}if(!hi5.browser.isChromeApp){xa=t.getClipData();if(h){var g=a(b,xa);setTimeout(function(){var a=document.getElementById("_tmpEditable");a?a.parentNode.removeChild(a):(h.setValue(""),E&&E.setValue(""),"text/html"==g.type&&h.restoreCSS());0<xa.indexOf("data-sv-img")&&Sa.open(g.value,
__svi18n.info.copy)},555)}d.clipData=null;sa=!1}};this.onPaste=function(a){if(!K||!T)return cancelDefault(a);if(!k.alwaysPaste&&!sa)return setTimeout(pb,500),cancelDefault(a);sa=!1;d.paste(Fb,a,null);return!0};this.parseClipData=function(a){var c=0===a.indexOf("text/plain;"),b=0===a.indexOf("text/html;"),d=b?"text/html":"text/plain",c=c?11:b?10:0;0<c&&(a=a.substring(c));return{type:d,value:a}};this.getContent=function(){var a=Fa("div");a.focus();try{document.execCommand("paste");var c=a.innerHTML,
b=new p;b.setData("text/html",c);b.setData("text/plain",a.innerText||c.replace(/<br>/gi,"\n").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&lt;/gi,"<").replace(/&gt;/gi,">"));b.equals(u.clipData)||(u.clipData=b,t.send("880text/plain,text/html\t0"))}finally{a.parentNode.removeChild(a),h&&(h.getElement().removeEventListener("click",u.getContent),h.focus())}};this.startPasteCmd=function(){h&&document.queryCommandSupported("paste")&&h.getElement().addEventListener("click",
u.getContent)};this.waitingCopyContent=!1;this.copyContent=null;this.waitForCopyContent=function(){u.waitingCopyContent=!0;setTimeout(b,700)};this.copyToClipboard=function(a,c){var b=Fa(a),d=!1;"div"==a?(b.innerHTML=c,hi5.browser.selectEditable(b)):(b.value=c,b.select());try{d=document.execCommand("copy",!1,null)}catch(e){}finally{b.parentNode.removeChild(b),h&&h.focus()}if(d)return d;Sa.open(c,__svi18n.info.copy,a)}},qb=hi5.browser.isMacOS||hi5.browser.isiOS,da=new function(){this.altUp=this.shiftUp=
this.winUp=this.ctrlUp=!0;this.preKeyCode=0;var a=this;this.sendMissKey=function(){a.shiftUp||(l(!1,42),a.shiftUp=!0);a.altUp||(l(!1,56),l(!0,56),l(!1,56),a.altUp=!0);a.ctrlUp||(l(!1,29),a.ctrlUp=!0);a.winUp||(l(!1,219),a.winUp=!0)};this.check=function(b){var d=ha.getKeyCode(b),c="keydown"==b.type;switch(d){case 16:!c||!a.shiftUp||b.altKey||b.ctrlKey||b.metaKey||a.sendMissKey();a.shiftUp=!c;break;case 17:c&&a.ctrlUp&&!b.altKey&&!b.shiftKey&&a.sendMissKey();a.ctrlUp=!c;break;case 18:!c||!a.altUp||
b.shiftKey||b.ctrlKey||b.metaKey||a.sendMissKey();a.altUp=!c;break;case 91:case 92:!c||!a.winUp||b.shiftKey||b.ctrlKey||b.metaKey||b.altKey||a.sendMissKey();a.winUp=!c;break;default:!c||b.ctrlKey||b.altKey||b.shiftKey||b.metaKey||a.sendMissKey()}}};this.requestCredential=function(a){Qa=!1;var b=__svi18n.template.login;if(b){var d=document.createElement("div");d.className="appdlg";d.innerHTML=b;document.body.appendChild(d);(b=hi5.$("loginDomain"))&&a.nbDomain&&(b.innerHTML=a.nbDomain);var c=new hi5.Lightbox(d,
.9);c.onclose=function(){document.body.removeChild(d)};try{k.close()}catch(f){}c.show();(b=hi5.$("loginUser"))&&b.focus();if(b=hi5.$("frmLogin"))b.onsubmit=function(){var a=hi5.$("loginUser").value,b=hi5.$("loginPassword").value,d=hi5.$("loginDomain").innerHTML;c.dismiss();setTimeout(function(){t.reconnect(a,b,d)},5);return!1}}else k.showMessage("No value for login template")};var h=null;if(C)bb();else{var Ta=hi5.$("tmContainer");Ta&&Ta.parentNode.removeChild(Ta)}h=new Wa;C&&hi5.browser.isSafari&&
window.addEventListener("scroll",function(){setTimeout(function(){var a=hi5.$("pc_key");a&&(a.style.top=window.pageYOffset+"px");k.toolbar&&(k.toolbar.style.top=window.pageYOffset+"px")},200)},!1);this.setCaretPos=function(a,b){};this.showMessage=function(a,b){a&&w.displayMsg&&hi5.notifications.notify({msg:a,timeout:b||0})};this.hideWhenClose="hideWhenClose"in w?w.hideWhenClose:!0;this.setReadOnly=function(a){K=!a};this.setPlayerMode=function(){U=!0;k.showToolbar=!1;k.setReadOnly(!0);k.hideWhenClose=
!1};this.setAutoScale=function(a){var b="autoScale"in w;b&&(a=w.autoScale);a?(la(!0),Xa("hidden")):b||la(!1);ea=a};this.setTouchpad=function(a){Y=a;var b=hi5.$("touchpadMode");b&&(b.checked=a,b.onchange=function(a){Y=a.target.checked});a?g||Ca():g&&g.parentNode&&(g.parentNode.removeChild(g),g=null)};this.setExtKeyboard=function(a){if(C){h.adjust(!0);h.setContentEditable(a?"true":"false");ca=a?1:0;hi5.browser.isChrome&&h.setFontSize("2em");a&&h.focus();var b=hi5.$("extKBD");b&&b.checked!=a&&(b.checked=
a)}};this.focus=function(){h&&v(h.getElement())};this.getInputElement=function(){return h};this.scaleTo=function(a,b,d){a/=N;b/=L;d?(P=a,S=b):S=P=b=a=Math.min(a,b);hi5.tool.scale(e.parentNode,a,b)};this.setSize=function(a,b,d){N=a;L=b;ea||Xa(d);e.width=N;e.height=L;ea&&la(!0);C&&bb();h||(h=new Wa);h.adjust();V&&V.visible()&&V.dismiss()};this.reposition=function(){h.adjust()};this.setController=function(a){t=a;t.sendInput||(t.sendInput=t.send);C&&hi5.browser.setOrientaionHandler(function(){ea?la(!0):
setTimeout(function(){t.onorientationchange({svSurface:k,innerWidth:window.innerWidth,innerHeight:window.innerHeight});w.disableScoll||window.scrollTo(0,0)},300)})};this.setFileHandler=function(a){"FileReader"in window||(a=null);if(a){if(!J&&!U&&hi5.$("filecontainer")){J=a;k.fileProgress=new hi5.ProgressBar(hi5.$("total"));Ka();Db();var b=document.getElementById("__cancelUpload");b&&b.addEventListener("click",function(){J.cancelAll()},!1);J.addEvent("beforeupload",function(a,c){b&&(b.style.visibility=
"visible");k.fileProgress.style.display="block";k.fileProgress.maxValue+=a.size});J.addEvent("uploaded",function(){b&&(b.style.visibility="hidden");k.fileProgress.maxValue=0;k.fileProgress.style.display="none";k.showMessage(__svi18n.file.uploadDone,5E3);k.refreshFiles()});J.addEvent("progress",function(a){k.fileProgress.setProgress(a)})}}else J=null,k.fileProgress=null,k.toolbar&&k.toolbar.removeButton("svCloud"),Ka()};this.setFeature=function(a){var b;!U&&a&16?a&128&&(b=hi5.$("uploadfile"))&&(b.style.visibility=
"hidden"):k.setFileHandler(null);a&256||(b=hi5.$("shadowing"))&&b.parentNode.removeChild(b);a&1024||(b=hi5.$("ssParent"))&&b.parentNode.removeChild(b)};var Ga=new function(){function a(){if(0===d.length){c=!1;var a=hi5.$("_sv_pdf_parent");a&&a.visible&&a.visible()&&a.dismiss&&a.dismiss();a&&a.parentNode&&(a.parentNode.removeChild(a),console.log("pdf removed"))}else b()}function b(){var b=d.shift();if(b){var e=hi5.$("_sv_pdf_parent"),g=__svi18n.info.printready||"Your document is ready.",g=C||w.showPDFLink?
'<p style="text-align:center;line-height:4em"><a href="'+b+'" target="_blank">'+g+"</a></p>":(hi5.browser.isChromeApp?"<webview":"<iframe")+' src="'+b+'" width="100%" height="100%" id="_iFramePDF">'+(hi5.browser.isChromeApp?"</webview>":"</iframe>");if(e){var k=hi5.$("_iFramePDF");k?k.src=b:e.innerHTML+=g}else e=document.createElement("div"),e.style.backgroundColor="white",e.style.width=C?"30%":"90%",e.style.height=C?"4elm":"85%",e.id="_sv_pdf_parent",e.innerHTML=g,document.body.appendChild(e),b=
new hi5.Lightbox(e),b.onclose=a,b.show()}c=!0}var d=[],c=!1;this.clearPDF=function(){a()};this.showPDF=function(a){d.push(a);c||b()}};this.close=function(){Ha();Ga.clearPDF();ea&&k.setAutoScale(!1);X&&X.setVisibility(!1);for(var a=0,b=Ra.length;a<b;a++)Ra[a]();try{J=null;k.fileProgress=null;window.svSurface=null;g&&g.parentNode&&(g.parentNode.removeChild(g),g=null);ab=!0;if(!window||U)return;if(0<hi5.notifications.notifySize()){hi5.notifications.onempty=function(){k.close();hi5.notifications.onempty=
null};return}if(Qa)window.close();else if(this.hide(),hi5.browser.isChromeApp){var d=chrome.app.window.current();d&&(d.onMaximized.removeListener(Ya),d.isFullscreen()&&(d.restore(),d.restore()))}}catch(c){}"clearScreen"in w&&!w.clearScreen||Q.fillRect(0,0,e.width,e.height)};this.setFastCopy=function(a){vb=a};this.drawLicense=function(a){if(0!=w.drawLicense){var b=a.charAt(0);Q.font="12pt Arial";Q.fillStyle="W"==b?"red":"black";a=a.substring(1);Q.fillText(a,10,L-24)}};this.drawText=function(a){var b=
w.text||{};if(b.backgroundFillStyle){var d=e.width,c=e.height;Q.fillStyle=b.backgroundFillStyle;Q.fillRect(0,0,d,c)}var f=20,g=50;"center"==b.textAlign&&(f=d/2,g=c/2);Q.font=b.font||"18pt Arial";Q.fillStyle=b.fillStyle||"black";b.textAlign&&(Q.textAlign=b.textAlign);b.textBaseline&&(Q.textBaseline=b.textBaseline);Q.fillText(a,f,g)};this.showPDF=function(a){Ga.showPDF(a)};this.hide=function(){k.hideWhenClose&&(e.height=1,e.width=1);h&&h.hide()};var ya=0,zb=!1,Sa=new function(){var a=null,b=null;this.createDialog=
function(d,c,f){var e=document.createElement("div");e.className="copyDialog";var g=document.createElement("div");g.innerHTML=c;g.className="hi5_notifer_title";e.appendChild(g);c=document.createElement(f);"div"==f?c.innerHTML=d:c.value=d;c.style.border="1px solid #666";c.style.width="100%";c.style.minHeight="80px";e.appendChild(c);a=c;wb&&(b=document.createElement("input"),b.className="btnCopy",b.type="button",b.value=__svi18n.info.copylable||"Copy",b.onclick=function(){"div"==f?hi5.browser.selectEditable(a):
a.select();document.execCommand("copy")},e.appendChild(b));if(0<d.indexOf('data-sv-img="wmf"')&&(c=d.indexOf('src="')+5,g=d.indexOf('"',c),g>c&&0<c)){var k=document.createElement("a");k.href=d.substring(c,g);k.target="_blank";k.innerHTML="Download image";e.appendChild(k)}return e};this.open=function(d,c,f){function e(){var g=Sa.createDialog(d,c,f);document.body.appendChild(g);var h=new hi5.Lightbox(g);h.show();a&&0!==d.indexOf("<img ")&&("div"==f?hi5.browser.selectEditable(a):a.select());Ja();h.onclose=
function(){Ia();g&&g.parentNode&&g.parentNode.removeChild(g);k.toolbar&&k.toolbar.removeButton("_svClipInfo")};document.queryCommandEnabled("copy")||g.removeChild(b)}f||(f="div");if(w.clipWarnAlways||!zb)k.showMessage(__svi18n.info.copyWarning,5E3),zb=!0;clearTimeout(ya);var g=k.toolbar;if(g){var h=g.getButton("_svClipInfo");h?h.onclick=e:(h=g.addButton(w.img.copy?w.img.copy:"copy.png",e),h.id="_svClipInfo",h.className="pulse");g.startFade();ya=setTimeout(function(){k.toolbar.removeButton("_svClipInfo")},
3E4)}}};this.copyToClip=function(a,b){var d=u.parseClipData(a);u.waitingCopyContent?u.copyContent=d:setTimeout(function(){if(!(!T||ia&&xa==a||M)){a=d.value;var b=0<a.indexOf("<img ")||w.copyDialog,e="text/plain"==d.type?"textarea":"div";b&&!wb||u.copyToClipboard(e,a)}},50)};this.fullScreen=function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)};Ra.push(function(){if(window){window.removeEventListener("beforeunload",$a,!1);window.removeEventListener("focus",Za,!1);window.onresize=null;
try{ra&&ra.parentNode&&(ra.parentNode.removeChild(ra),ra=null),h&&h.remove(),h=null}catch(a){}}if(document){Ja();document.body.style.overflow="";var b=window;try{for(;;){b.document.removeEventListener("mouseup",gb,!1);if(b.parent==b)break;b=b.parent}}catch(d){}}});var X=new function(){function a(a){ca=(new Date).getTime();if(a=hi5.$("pc_key"))a.style.display="block",a.style.top=window.pageYOffset+"px",E&&(E.setValue("`\t`"),E.select())}function b(a){ca=0;if(a=hi5.$("pc_key"))a=hi5.$("shortcuts"),
a&&a.checked||(n.style.display="none")}function d(){e&&(aa?hi5.html.addClass(e,"button_selected"):hi5.html.removeClass(e,"button_selected"));g&&(ba?hi5.html.addClass(g,"button_selected"):hi5.html.removeClass(g,"button_selected"));h&&(ka?hi5.html.addClass(h,"button_selected"):hi5.html.removeClass(h,"button_selected"))}function c(a){cancelDefault(a);a=a.target;var b=a.innerHTML,b=b.replace(/\u2190/g,"left").replace(/\u2191/g,"up").replace(/\u2192/g,"right").replace(/\u2193/g,"down");switch(b){case "Ctrl":e||
(e=a);aa?l(!1,29):l(!0,29);aa=!aa;d();break;case "Alt":g||(g=a);ba?l(!1,56):l(!0,56);ba=!ba;d();break;case "Shift":h||(h=a);ka?l(!1,42):l(!0,42);ka=!ka;d();break;case "...":if(a=hi5.$("pc_key_more"))a.style.display="block"==a.style.display?"none":"block";break;case "Start":b="Ctrl+Esc";default:k.writeKeyComb(b),r.resetModifier()}}var e=null,g=null,h=null,r=this;this.setVisibility=function(c){c?a():b()};this.resetModifier=function(){ba&&(ba=!1,l(!1,56));aa&&(aa=!1,l(!1,29));ka&&(ka=!1,l(!1,42));d()};
hi5.$("svTouchInput")&&(hi5.$("svTouchInput").addEventListener("focus",a,!1),hi5.$("svTouchInput").addEventListener("blur",b,!1));var n=hi5.$("pc_key");if(n){var p=n.getElementsByTagName("span"),t=p.length,u=hi5.browser.isFirefox?"mousedown":"touchstart";"ontouchstart"in window||(navigator.pointerEnabled?u="pointerdown":navigator.msPointerEnabled&&(u="MSPointerDown"));for(var x=0;x<t;x++){var v=p[x];v.className="button";v.addEventListener(u,c,!1);"mousedown"!=u&&v.addEventListener("mousedown",c,!1)}n.style.position=
"absolute"}},Ab=hi5.$("shortcuts");Ab&&Ab.addEventListener("change",function(a){X.setVisibility(a.target.checked)});this.setKeysVisibility=function(a){X&&X.setVisibility(a)};this.refreshFiles=function(){V&&V.visible()?ma(".",V):eb(null)};this.processLink=function(a){function b(b){window.open(a);b.target.parentNode.removeChild(b.target)}clearTimeout(ya);var d=k.toolbar,c=d.getButton("_svLinkInfo");c?c.onclick=b:(c=d.addButton(w.img.link?w.img.link:"link.png",b),c.id="_svLinkInfo",c.className="pulse");
c.title=a;d.startFade();ya=setTimeout(function(){k.toolbar.removeButton("_svLinkInfo")},1E4)};this.setUnicode=function(a){h&&(!a&&C&&(hi5.browser.isiOS||hi5.browser.isChrome&&!hi5.browser.isWindows)&&(a=!0),va=!a,svGlobal.logger.info("Unicode:"+a),I.onkeydown=I.onkeyup=a?cb:Eb,I.ontextinput=db)};this.setTouchRemoting=function(a){!0===a?(oa=new z(k,e),svGlobal.logger.info("touch remoting"),k.showMessage(__svi18n.info.touchremoting)):oa=new H(k)};this.setClipboard=function(a){(T=a)||(ia=!1)};this.setJoinMode=
function(a){t.setJoinMode(a)};this.requestControl=function(){t.requestControl()};this.run=function(a){hi5.notifications.clearAll();3758162961!=a&&3758162962!=a||!h||h.setContentEditable("false");ha.setLayout(a);var b=-1!=[99997,99998,99999].indexOf(a);va=!b;lb=(b||-1==[1033,3758162961,3758162962,1049].indexOf(a))&&hi5.browser.isMacOS;Qa="boolean"==typeof w.closeOnDisconn?w.closeOnDisconn:!!window.opener&&!hi5.browser.isChromeApp;w.disableScoll||window.scrollTo(0,0);Ka();Cb();a=h.getElement();if(C){if(!U){oa=
new H(k);var d=new x(a);d.ontouch=O;d.onmousedown=za;d.onmousemove=Aa;d.onmouseup=Ba;D(a,tb,!1);document.addEventListener("paste",u.onPaste,!1);T&&ia&&(document.addEventListener("copy",u.onCopy,!1),document.addEventListener("cut",u.onCopy,!1))}}else U||(a.addEventListener("mousemove",Aa,!1),a.addEventListener("mousedown",za,!1),a.addEventListener("mouseup",Ba,!1),D(a,tb,!1),a.addEventListener("paste",u.onPaste,!1),T&&ia&&(a.addEventListener("copy",u.onCopy,!1),a.addEventListener("cut",u.onCopy,!1))),
v(a);h.adjust();k.setUnicode(b);b=window;try{for(;;){b.document.addEventListener("mouseup",gb,!1);if(b.parent==b)break;b=b.parent}}catch(c){}this.drawText(__svi18n.wait);if(k.onstart)k.onstart(e);T&&u&&u.startPasteCmd()};this.movCursorBy=La;this.moveCursor=na;this.touchstart=function(a){switch(a.pointes){case 1:if(Y)g||Ca(),Ma("touchstart",a.screenX,a.screenY,!a.flick);else if(!a.flick||r()){var b=h.getElement().getBoundingClientRect(),d=a.x-b.left;a=a.y-b.top;if(k.mouseMoveEmu){var b=xb,c=yb,e=d-
b,l=a-c,m=Math.max(Math.abs(l),Math.abs(e))/2|0;if(0<m)for(var e=e/m|0,l=l/m|0,p=0;p<m;p++)b+=e,c+=l,wa(b,c);b==d&&c==a||wa(d,a);xb=d;yb=a}qa(d,a,0)}break;case 2:ta=a.screenX,ga=a.screenY}};this.touchmove=function(a){var b=h.getElement().getBoundingClientRect();switch(a.pointes){case 1:Y?Ma("touchmove",a.screenX,a.screenY,!a.flick):a.flick&&!r()||wa(a.x-b.left,a.y-b.top);break;case 2:40<=Math.abs(a.screenY-ga)&&(sb(a.x-b.left,a.y-b.top,0<a.screenY-ga?0:1),ta=a.screenX,ga=a.screenY)}};this.touchend=
function(a){var b=a.pointes,d=h.getElement().getBoundingClientRect();switch(b){case 1:Y?Ma("touchend",a.screenX,a.screenY,!a.flick):(na(a.x,a.y,!0),a.flick&&!r()||fa(a.x-d.left,a.y-d.top,0));break;case 2:a.moved||(b=Y?g.scrX:a.x-d.left,a=Y?g.scrY:a.y-d.top,na(b,a),qa(b,a,2),fa(b,a,2));break;case 3:if(a.gesture)switch(a.gesture){case "OPEN":l(!0,219);l(!0,200);l(!1,200);l(!1,219);break;case "CLOSE":l(!0,219);l(!0,208);l(!1,208);l(!1,219);break;case "LEFT":l(!0,56);l(!0,1);l(!1,1);l(!1,56);break;case "RIGHT":l(!0,
42);l(!0,56);l(!0,1);l(!1,1);l(!1,56);l(!1,42);break;case "UP":l(!0,42);l(!0,219);R(!0,77);R(!1,77);l(!1,219);l(!1,42);break;case "DOWN":l(!0,219),R(!0,77),R(!1,77),l(!1,219)}else k.toolbar&&k.toolbar.startFade&&k.toolbar.startFade(),M&&M.focus()}};this.flick=function(a){switch(a.from){case 4:t.sendInput("840\t209");t.sendInput("8449152\t209");break;case 2:t.sendInput("840\t201"),t.sendInput("8449152\t201")}};this.longpress=function(a){Y&&(a.pointes=2);var b=h.getElement().getBoundingClientRect();
switch(a.pointes){case 1:var d=a.x-b.left;a=a.y-b.top;na(d,a);qa(d,a,2);fa(d,a,2);break;case 2:g&&(qa(g.scrX,g.scrY,2,1),fa(g.scrX,g.scrY,2,1))}};this.redirectTouches=function(a){if(K){for(var b=a.length,d,c="90"+b,e=0;e<b;e++)d=a[e],c=c+"\t"+d.contactId+";"+d.contactFlags+";"+Math.floor(d.x/P)+";"+Math.floor(d.y/S);t.send(c)}};var ua=0;this.processClipReq=function(a){var b=u.clipData,d=b?b.getData("text/richtext"==a?"text/html":a):null;if(d)return t.send("881"+a+"\t"+d),b.sent=!0;t.send("881"+a+
"\t"+("text/plain"==a?"":"ERROR"));return!1};var Pa={},rb=!1,Gb={33:201,34:209,35:207,36:199,37:203,38:200,39:205,40:208,154:183,45:210,46:211,225:184,91:219,92:220,93:221,27:1,8:14,9:15,13:28,224:29,17:29,16:42,18:56,20:58,166:59,112:59,167:60,113:60,168:61,114:61,183:62,115:62,182:63,116:63,216:64,117:64,217:65,118:65,173:66,119:66,174:67,120:67,175:68,121:68,122:87,123:88};this.writeKeyComb=function(a){t.writeKeyComb(a)};this.setCursor=function(a){!w.disableCursor&&a&&(a.data||a.url||a.none)&&
(Da=a,g&&g.setCursor(a),U||(h?(h.getElement().style.cursor="default",h.getElement().style.cursor=ub(a)):e.style.cursor=ub(a)))};this.setVisible=function(a,b){var d=a?"visible":"hidden";"number"==typeof b?setTimeout(function(){e.style.visibility=d},b):e.style.visibility=d}}svGlobal.LocalInterface=LocalInterface;
svGlobal.rdpFile={loadRdpFile:function(e,v){var p=v.elements,F=e.split("\r\n");2>F.length&&(F=e.split("\n"));if(2>F.length)return!1;var D=hi5.$("gateway"),x=D.value;v.reset();D.value=x;D=0;for(x=F.length;D<x;D++){var r=F[D],z=r.indexOf(":"),H=r.substring(0,z),r=r.substring(z+3),H=H.toLowerCase();switch(H){case "full address":z=r.indexOf(":");0<z?(p.server.value=r.substring(0,z),p.port.value=r.substring(z+1)):p.server.value=r;break;case "username":p.user.value=r;break;case "domain":p.domain.value=
r;break;case "connect to console":p.useConsole.checked="0"!=r;break;case "desktopwidth":p.width.value=r;break;case "desktopheight":p.height.value=r;break;case "session bpp":p.server_bpp.value=r;break;case "audiomode":p.playSound.value=r;break;case "alternate shell":0<r.length&&(p.command.value=r,hi5.$("app").checked||(hi5.$("shell").checked=!0));break;case "shell working directory":p.directory=r;break;case "redirectclipboard":p.mapClipboard.checked="0"!=r;break;case "redirectprinters":p.mapPrinter.checked=
"0"!=r;break;case "server port":0<r.length&&(p.port.value=r);break;case "disable wallpaper":p.background.checked="0"==r;break;case "disable themes":p.styles.checked="0"==r;break;case "disable menu anims":p.animation.checked="0"==r;break;case "disable full window drag":p.contents.checked="0"==r;break;case "allow font smoothing":p.smoothfont.checked="0"!=r;break;case "allow desktop composition":p.composition.checked="0"!=r;break;case "bitmapcachepersistenable":p.bitmap.checked="0"!=r;break;case "remoteapplicationprogram":p.exe.value=
r;break;case "remoteapplicationcmdline":p.args.value=r;break;case "remoteapplicationmode":hi5.$("app").checked="1"==r;break;case "loadbalanceinfo":p.loadBalanceInfo.value=r}}return!0},handleFiles:function(e,v){if(1!=e.length)hi5.notifications.notify({msg:"Please one file only"});else{var p=e[0],F=p.name,D=F.length;if(4<D&&".rdp"==F.substring(D-4).toLowerCase()){var x=new FileReader,r=!1;x.onload=function(e){!(e=e.target.result)||svGlobal.rdpFile.loadRdpFile(e,v)||r||(r=!0,x.readAsText(p))};x.readAsText(p,
"UTF-16LE")}else hi5.notifications.notify({msg:"Sorry, Please .rdp file only"})}}};
function initDragDrop(e,v){function p(e){svGlobal.rdpFile.handleFiles(e.target.files,v)}function F(p){cancelDefault(p);e.style.backgroundColor=r;svGlobal.rdpFile.handleFiles(p.dataTransfer.files,v)}function D(p){cancelDefault(p);e.style.backgroundColor="yellow"}function x(p){cancelDefault(p);e.style.backgroundColor=r}if("FileReader"in window){var r=e.style.backgroundColor,z=hi5.$("rdpfile");z&&z.addEventListener("change",p,!1);e.addEventListener("dragover",D,!1);e.addEventListener("dragleave",x,!1);
e.addEventListener("drop",F,!1)}}svGlobal.util.initDragDrop=initDragDrop;
svGlobal.util.initMapDisk=function(e,v){function p(p){cancelDefault(p);"0.6"!=e.style.opacity&&(e.style.opacity="0.6");e.style.backgroundColor="yellow"}function F(p){cancelDefault(p);e.style.opacity=e.__oldOpacity;e.style.backgroundColor=e.__oldColor}function D(p){cancelDefault(p);e.style.opacity=e.__oldOpacity;e.style.backgroundColor=e.__oldColor;var r=hi5.file.getEntries(p);r.length?(p=new hi5.file.DirectoryReader(r),p.onfile=function(e,p){v.addFile(e,p)},p.start()):v.addFiles(p.dataTransfer.files)}
"FileReader"in window&&(e.__oldColor=e.style.backgroundColor,e.__oldOpacity=e.style.opacity,e.addEventListener("dragover",p,!1),e.addEventListener("dragleave",F,!1),e.addEventListener("drop",D,!1))};window.addEventListener("load",function(e){e=document.getElementsByClassName("ver");for(var v=e.length,p=0;p<v;p++)e[p].innerHTML=svGlobal.version},!1);svGlobal.logger.info("ver:"+svGlobal.version);
