var svGlobal=svGlobal||{logger:new hi5.Logger,util:{}};svGlobal.version="5.0.0";svGlobal.build="773";function cancelDefault(l){if(l.preventDefault)l.preventDefault();if(l.stopPropagation)l.stopPropagation();return false}
function LocalInterface(l){function H(c){var d=hi5.tool.cumulativePos(c);if(ob)d.y+=c.scrollTop;return d}function v(c){var d=c-hi5.browser.innerHeight;if(d>10&&d<22)c=hi5.browser.innerHeight;return c}function D(c){if(u.detectInput&&L&&da)if(Ba||da.system=="text"||da.system=="none")setTimeout(function(){$a(true)},5);else setTimeout(function(){$a(false)},5);if(document.activeElement!=c){var d=c;var e;var a;for(var b=[];d.parentElement;){d=d.parentElement;e=getComputedStyle(d);if(e){a=e.getPropertyValue("overflow");
if(e.getPropertyValue("display")=="block")b.push([d,d.scrollTop,d.scrollLeft])}}c.focus();if(b.length){var g=0;for(var h=b.length;g<h;g++){d=b[g];if(d[0].scrollTop!=d[1]||d[0].scrollLeft!=d[2]){d[0].scrollTop=d[1];d[0].scrollLeft=d[2]}b[g]=null}b=null}}}function J(){var c=[];this.sent=0;this.types=[];var d=this;this.datas=c;this.setData=function(e,a){if(e=="text/plain"||e=="text/html"){if(a.length>2&&a.substring(0,3)=="`\t`")a=a.substring(3);a=a.replace(/\r?\n/g,"\r\n")}d.types.push(e);c.push(a)};
this.getData=function(e){var a=c[d.types.indexOf(e)];if(!a&&e=="text/richtext")a=c[d.types.indexOf("text/html")];return a};this.removeData=function(e){var a=d.types.indexOf(e);if(a!=-1){d.types.splice(a,1);c.splice(a,1)}};this.equals=function(c){if(!c)return false;if(!hi5.Arrays.equals(d.types,c.types))return false;var a;var b;var g;var h=d.types;var y=0;for(var p=h.length;y<p;y++){a=h[y];b=d.getData(a);g=c.getData(a);if(b!=g)return false}return true}}function T(c){function d(a){a.focus();if(typeof window.getSelection!=
"undefined"&&typeof document.createRange!="undefined"){var c=document.createRange();c.selectNodeContents(a);c.collapse(false);var b=window.getSelection();b.removeAllRanges();b.addRange(c)}else if(typeof document.body.createTextRange!="undefined"){var d=document.body.createTextRange();d.moveToElementText(a);d.collapse(false);d.select()}}function e(){var a=O?c.value:x.isFirefox?c.textContent:c.innerText;if(f&&!O&&a.charAt(0)!=C.PLACE_HOLDER)a=C.PLACE_HOLDER+a;return a}function a(){if(f)if(O){if(c.setSelectionRange)c.setSelectionRange(c.value.length,
c.value.length)}else d(c)}function b(){if(C){var a=f||Z&&L?C.PLACE_HOLDER:"";n=a;C.setValue(a)}}function g(){setTimeout(b,100)}function h(a){r=a.keyCode;if(C.onkeydown)C.onkeydown(a)}function y(a){if(C.onkeyup)C.onkeyup(a);var c=a.keyCode;if(c==13||c==32&&r==32)g()}function p(a){if(C.onkeypress)C.onkeypress(a)}function A(a){if(C.onbackspace)for(var c=0;c<a;c++)C.onbackspace()}function G(a){if(C.disableTextInput)return;a.stopPropagation();var d=e();var h=d.length;if(h>1&&d.charAt(0)!=C.PLACE_HOLDER&&
d.charAt(h-1)==C.PLACE_HOLDER){d=C.PLACE_HOLDER+d.substring(0,h-1);C.setValue(d)}if(d==n)return;var p=n.length;var y=d.indexOf(n);if(d&&y===0){d=d.substring(p);if(d.length>0&&l&&C.ontextinput){C.ontextinput({data:d,"target":c});if(d=="."){b();return}}}else{y=n.indexOf(d);if(y===0){if(r!=8)A(p-h)}else if(l){if(f){p--;d=d.substring(1)}A(p);if(d.length>0&&C.ontextinput)C.ontextinput({data:d,"target":c})}}if(e()==="")g();n=e()}function k(a){if(C.disableTextInput)return;if(!a.data)return;a.stopPropagation();
if(C.ontextinput)C.ontextinput(a)}var C=this;var f=false;var l=x.isFirefox||x.isOpera||x.isAndroid&&x.isChrome;var m=!x.isRIM;var n="";var r=0;var O="INPUT"==c.nodeName||"TEXTAREA"==c.nodeName;var ea="DIV"==c.nodeName;this.PLACE_HOLDER="`";this.setValue=function(a){var b=C.disableTextInput;C.disableTextInput=true;if(O)c.value=a;else if(ea)c.innerHTML=a;C.disableTextInput=b};this.init=b;this.disableTextInput=false;b();c.addEventListener("keydown",h,false);c.addEventListener("keyup",y,false);c.addEventListener("keypress",
p,false);if(l){c.addEventListener("input",G,false);if(f)c.onclick=b;else c.addEventListener("mouseup",b,false)}else{c.addEventListener("textInput",k,false);c.addEventListener("textinput",k,false)}this.release=function(){C=null;c.removeEventListener("keydown",h,false);c.removeEventListener("keyup",y,false);c.removeEventListener("input",G,false);c.removeEventListener("focus",b,false);c.removeEventListener("textInput",k,false);c.removeEventListener("textinput",k,false);c=null};this.select=function(){pb(c)}}
function W(c,d,e){function a(a){var c=0;var e=0;var A=0;var G=Ga(a);var k=a.deltaMode||0;var C=!!a.deltaX||!!a.wheelDeltaX;a.preventDefault();a.stopPropagation();if(k==1){d(-a.deltaY||-a.deltaX,G,C);return}var f="deltaY"in a;var l=f?40:"wheelDelta"in a?120:0;if(l){A=Date.now();if(A-g>100)b=0;e=-a.deltaY||-a.deltaX||a.wheelDelta;if(e!=0){b+=e;c=b/l|0;b=b%l;if(c!==0)d(c,G,C)}g=A}else{c=-a.detail;if(Math.abs(c)==32768){e=window.innerHeight/40|0;c=c<0?-e:e}d(c,G,false)}}var b=0;var g=0;c.addEventListener("DOMMouseScroll",
a,true);c.addEventListener("mousewheel",a,true)}function ja(c){function d(a){if(g)return;if(h.onmousedown)h.onmousedown(a)}function e(a){if(g)return;if(h.onmousemove)h.onmousemove(a)}function a(a){if(g){g=false;return}if(h.onmouseup)h.onmouseup(a)}function b(a){var c=a.type;if(c=="touchstart")g=true;if(h.ontouch)h.ontouch(a)}var g=false;var h=this;var y=navigator.pointerEnabled||navigator.msPointerEnabled||false;if("ontouchstart"in window||!y){c.addEventListener("touchstart",b,false);c.addEventListener("touchend",
b,false);c.addEventListener("touchmove",b,false);c.addEventListener("touchcancel",b,false);c.addEventListener("mousemove",e,false);c.addEventListener("mousedown",d,false);c.addEventListener("mouseup",a,false)}else if(navigator.pointerEnabled){c.addEventListener("pointerdown",b,false);c.addEventListener("pointerup",b,false);c.addEventListener("pointermove",b,false);c.addEventListener("pointercancel",b,false)}else if(navigator.msPointerEnabled){c.addEventListener("MSPointerDown",b,false);c.addEventListener("MSPointerUp",
b,false);c.addEventListener("MSPointerMove",b,false);c.addEventListener("MSPointerCancel",b,false)}}function na(){return!oa&&U<=window.innerWidth&&Q<=window.innerHeight}function pa(c){function d(a){if(a<256)return a;var c=g.indexOf(a);if(c!=-1)return c;g.push(a);return g.length-1}function e(a,c){var b;var e=a.length;var h=new Array(e);for(var g=0;g<e;g++){b=a[g];var k=Ha(b.clientX,b.clientY,l);h[g]={"contactId":d(b.identifier),"contactFlags":c,"x":k.x,"y":k.y}}return h}function a(a){var c=b.length;
for(var d=0;d<c;d++)if(b[d].contactId==a)return d;return-1}var b;var g=[];var h=false;this.handle=function(d){var p=d.type;var A=d.touches;var G;var k;var f=d.changedTouches;cancelDefault(d);switch(p){case "touchstart":h=false;k=A.length;G=e(A,25);b=G;break;case "touchmove":G=e(f,26);if(!b)b=e(A||f,25);var l=false;if(b.length>0&&G.length==1){var m=a(G[0].contactId);if(m!=-1&&b[m].x==G[0].x&&b[m].y==G[0].y)l=true}if(l)return;else if(b.length>0){c.redirectTouches(b);b.length=0}c.redirectTouches(G);
h=true;break;case "touchend":if(!h){c.redirectTouches(b);k=b.length;for(var n=0;n<k;n++)b[n].contactFlags=4;G=b}else G=e(f,4);c.redirectTouches(G);g.length=b.length=0;break;case "touchcancel":c.redirectTouches(e(f,34));g.length=b.length=0}}}function ua(c){function d(a){var c=a[1].screenX-a[0].screenX;var b=a[1].screenY-a[0].screenY;return Math.sqrt(c*c+b*b)}function e(a){if(a.length!=2)return false;var c=a[1].screenX-a[0].screenX;var b=a[1].screenY-a[0].screenY;return Math.abs(b)>100||Math.abs(c)>
350}function a(a){var c=0;var b=0;var d=0;var e=9999;var A=0;for(var h=a.length;A<h;A++){if(a[A].screenY>d){d=a[A].screenY;c=A}if(a[A].screenY<e){e=a[A].screenY;b=A}}return[{screenX:a[b].screenX,screenY:a[b].screenY,identifier:a[b].identifier},{screenX:a[c].screenX,screenY:a[c].screenY,identifier:a[c].identifier}]}function b(a,c){var b=[];var e=g(a,P[0].identifier)||g(c,P[0].identifier);if(e)b.push(e);e=g(a,P[1].identifier)||g(c,P[1].identifier);if(e)b.push(e);var A="";if(b.length!=2)return A;var h=
d(b)-d(P);if(Math.abs(h)<60){var p=80;if(b[0].screenX-P[0].screenX>p)A="RIGHT";else if(P[0].screenX-b[0].screenX>p)A="LEFT";else if(b[0].screenY-P[0].screenY>p)A="DOWN";else if(P[0].screenY-b[0].screenY>p)A="UP"}else A=h<0?"CLOSE":"OPEN";return A}function g(a,c){var b=0;for(var d=a.length;b<d;b++)if(a[b].identifier==c)return a[b];return null}function h(a){this.identifier=a.pointerId;this.clientX=a.clientX;this.clientY=a.clientY;this.pageX=a.pageX;this.pageY=a.pageY;this.screenX=a.screenX;this.screenY=
a.screenY}var y=0;var p=0;var A=0;var G=0;var k=false;var f=0;var m=0;var n=0;var r=0;var q=false;var t=false;var O=3;var ea=false;if(Z)O*=3;this.delay=false;var P=[];var ga=this;this.handlePointer=function(a){if(a.pointerType==a.MSPOINTER_TYPE_MOUSE||a.pointerType=="mouse")switch(a.type){case "MSPointerDown":case "pointerdown":Ia(a);break;case "pointermove":case "MSPointerMove":Ja(a);break;case "pointerup":case "MSPointerUp":Ka(a)}else{a.touches=a.changedTouches=[new h(a)];ga.handle(a)}};this.handle=
function(d){var h=d.type;var ga=0;var u=d.touches;var x=d.changedTouches;var v=0;var z=0;var F=0;var B;switch(h){case "touchstart":case "MSPointerDown":case "pointerdown":moveCount=0;moveSpace=0;ea=false;p="touchstart"==h?u.length:p+1;t=false;G=Date.now();k=p==1&&G-A<200;F=u[0];y=F.identifier;B=Ha(F.clientX,F.clientY,l);f=B.x|0;m=B.y|0;q=true;ea=e(u);if(k||p>2)cancelDefault(d);if(p==3)P=a(u);break;case "pointermove":case "MSPointerMove":if(p>1)break;case "touchmove":if(ea)return;F=x[u.length-1];if(F.identifier!=
y){F=g(x,y);if(!F){cancelDefault(d);return}}B=Ha(F.clientX,F.clientY,l);v=B.x|0;z=B.y|0;if(q){if(v-f===0&&z-m===0)return;if(Math.abs(v-f)<O&&Math.abs(z-m)<O){cancelDefault(d);return}q=false;ga=Date.now()-G;t=ga<88;if(t&&!na()&&p==1){ea=true;return}c.touchstart({"x":f,"y":m,"flick":t,"pointes":p,"screenX":F.screenX,"screenY":F.screenY,"moved":true,"target":d.target})}cancelDefault(d);c.touchmove({"x":v,"y":z,"flick":t,"pointes":p,"moved":true,"screenX":F.screenX,"screenY":F.screenY,"target":d.target});
break;case "MSPointerUp":case "touchend":case "pointerup":if(ea)return;if(x.length+u.length==3){c.touchend({"x":v,"y":z,"flick":t,"pointes":p,"moved":!q,"target":d.target,"gesture":b(u,x)});p=0;break}else{if(p>2){p=0;break}F=g(x,y);if(F){var E=Date.now();B=Ha(F.clientX,F.clientY,l);v=B.x|0;z=B.y|0;if(!t){ga=E-G;if(q){A=E;if(!k){n=v;r=z}else cancelDefault(d);if(ga<500){A=E;c.touchstart({"x":n,"y":r,"flick":false,"pointes":p,"screenX":F.screenX,"screenY":F.screenY,"moved":false,"target":d.target});
c.touchend({"x":n,"y":r,"flick":false,"pointes":p,"moved":false,"screenX":F.screenX,"screenY":F.screenY,"target":d.target})}else c.longpress({"x":v,"y":z,"flick":false,"pointes":p,"moved":false,"screenX":F.screenX,"screenY":F.screenY,"target":d.target})}else c.touchend({"x":v,"y":z,"flick":false,"pointes":p,"moved":true,"screenX":F.screenX,"screenY":F.screenY,"target":d.target})}else c.touchend({"x":v,"y":z,"flick":true,"pointes":p,"moved":!q,"screenX":F.screenX,"screenY":F.screenY,"target":d.target})}}p=
0;break;case "MSPointerCancel":case "touchcancel":p=0}if(k)cancelDefault(d)}}function z(){n(true,14);n(false,14)}function pb(c){try{if(c.select)c.select();else x.selectEditable(c)}catch(d){svGlobal.logger.info(d)}}function tc(c,d){if(c.value)c.value=d;else c.innerHTML=d}function Yb(){function c(){b.focus()}function d(a,b){var d=document.createElement("a");d.href="#";d.accessKey=a;d.onfocus=c;d.style.position="absolute";d.style.width=1;d.style.height=1;d.style.left=0;d.style.top=b+"px";return d}var e=
k.forceTextArea||x.isIE;var a=document.createElement(e?"textarea":"div");var b=this;this.element=a;this.setFontSize=function(c){a.style.fontSize=u.inputFontSize||c};if(e){a.style.opacity=0;a.readOnly=L&&x.isMetro?true:false}else a.contentEditable=L&&!(x.isChrome&&(x.isWindows||x.isCrOS))?false:true;a.autocomplete=x.isChrome?"new-password":"off";a.autocorrect="off";a.autocapitalize="off";a.spellcheck="false";a.accessKey="f";a.id="wsinput";a.tabIndex=1;a.style.opacity=0;a.style.resize="none";a.style.position=
"absolute";a.style.margin="0";a.style.border="none";a.style.outline="none";var g=hi5.tool.getPos(l,true);a.style.left=g.x+"px";a.style.top=g.y+"px";a.style.paddingRight=0;a.style.paddingBottom=0;a.style.width="10px";a.style.height="10px";a.style.zIndex=88;a.style.cursor="default";a.style.fontWeight="normal";a.style.fonStyle="normal";a.style.overflow="hidden";if(L)a.style.fontSize="2em";if(x.isiOS){a.addEventListener("focus",function(a){setTimeout(function(){a.target.style.fontSize="0px"},333)},false);
a.addEventListener("blur",function(a){a.target.style.fontSize="1em"},false)}else if(x.isFirefox)a.style.fontSize=0;else a.style.textIndent="-999em";K=new T(a);K.onbackspace=z;var h=l.parentNode;h.appendChild(a);if(Z){h.appendChild(d("E"),60);h.appendChild(d("V"),61);h.appendChild(d("A"),62);h.appendChild(d("T"),63);h.appendChild(d("H"),64)}var y=a.style.opacity;var p=a.style.textIndent;this.resetCSS=function(){_fontSize=a.style.fontSize;y=a.style.opacity;a.style.opacity=0;a.style.textIndent=0};this.restoreCSS=
function(){a.style.opacity=y;a.style.textIndent=p};this.getValue=function(){return e?a.value:a.innerHTML};this.setValue=function(c){if(K)K.disableTextInput=true;if(e)a.value=c;else a.innerHTML=c;if(K)K.disableTextInput=false};this.focus=function(){b.setValue(" ");D(a)};this.setContentEditable=function(c){if(e){var b=c=="true";if(a.readOnly==b)a.readOnly=!b}else a.setAttribute("contenteditable",c)};this.isIMEMode=false;this.setIMEStatus=function(c){if(c){if(!b.isIMEMode){if(e){a.style.background="transparent";
a.style.opacity=1}b.isIMEMode=true}}else if(b.isIMEMode){if(e){a.style.background="";a.style.opacity=0}b.isIMEMode=false}};this.adjust=function(c){var b=hi5.tool.getPos(l,true);q.offX=b.x;q.offY=b.y;var d=k.railWin?Math.min(window.innerWidth-b.x,U):U;var e=k.railWin?Math.min(window.innerHeight-b.y,Q):Q;var h=0;var p=0;if(L){h=Math.max(window.pageXOffset+100,b.x);p=Math.max(window.pageYOffset+100,b.y)}else{var y=Math.min(window.innerWidth-b.x,U);var g=Math.min(window.innerHeight-b.y,Q);h=Math.round(y*
.7);p=Math.round(g*(c?.99:.7))}var f=d-h;var O=e-p;if(u.disableAdjust){h=0;p=0;f=l.offsetWidth;O=l.offsetHeight}a.style.width=f+"px";a.style.height=O+"px";a.style.paddingLeft=h+"px";a.style.paddingTop=p+"px";a.style.left=b.x+"px";a.style.top=b.y+"px"};this.remove=function(){if(K){K.release();K=null}if(a.parentNode)a.parentNode.removeChild(a);a=null};this.hide=function(){a.style.visibility="hidden"};this.getElement=function(){return a};this.select=function(){pb(a)}}function Zb(){var c=window.innerWidth;
var d=window.innerHeight;return Math.max(U,Q)<Math.max(c,d)&&Math.min(U,Q)<Math.min(c,d)}function Ca(){function c(){if(!u.text)u.text={};return u.text}function d(a){return(a.measureText("W").width+1)*1.2}function e(a){var c=(a&16777215).toString(16).toUpperCase();return"00000".substring(0,6-c.length)+c}function a(a,b,d,p,g){if(h){var k=c();a.fillStyle=k.backgroundFillStyle||"white";a.fillRect(b,d-g+2,p,g);a.fillStyle=k.fillStyle||"#337788";a.textBaseline="bottom";a.fillText(h,b+3,d-2);a.strokeStyle=
"#"+e(h.hashCode());a.lineWidth=2;a.beginPath();a.moveTo(b,d);var f=p*.382|0;a.lineTo(b+f,d);a.stroke();a.strokeStyle="#"+e(y);a.beginPath();a.moveTo(b+f+1,d);a.lineTo(b+p,d);a.stroke()}}function b(){var b=f.getContext("2d");var e=b.getImageData(0,0,f.cursorWidth,f.cursorHeight);if(h){b.font=c().font||"11px Arial";var p=d(b)+4;f.width=Math.max(f.cursorWidth,b.measureText(h).width+4);f.height=f.cursorHeight+p;a(b,0,f.height-1,f.width,p)}else{f.width=f.cursorWidth;f.height=f.cursorHeight}b.putImageData(e,
0,0)}if(f)return;var g=l.parentNode;var h="";var y=0;f=g.querySelector('canvas[name="svImgCursor"]');if(f)return;f=document.createElement("canvas");f.name="svImgCursor";f.style.position="absolute";f.style.left=90;f.style.top=90;f.scrX=0;f.scrY=0;f.hotX=10;f.hotY=10;f.width=f.height=32;f.style.visibility="hidden";f.style.zIndex=87;f.setCursor=function(b){var e=b.width;var p=b.height;var y=b.rawData;var g=f.getContext("2d");if(y&&e&&p){var k=e*p;var l=0;var m=0;var n=g.createImageData(e,p);var O=n.data;
var ea=0;var P=0;if(h){g.font=c().font||"11px Arial";ea=g.measureText(h).width;P=d(g)+4}f.cursorWidth=e;f.cursorHeight=p;f.hotX=b.hotX;f.hotY=b.hotY;f.width=Math.max(e,ea+4);f.height=p+P+4;if(h)a(g,0,f.height-1,f.width,P);for(var ga=0;ga<k;ga++){l=y[ga];O[m++]=l&255;O[m++]=l>>8&255;O[m++]=l>>16&255;O[m++]=l>>24&255}g.putImageData(n,0,0,0,0,e,p)}};f.hideCursor=function(){f.style.visibility="hidden"};if(da&&da.rawData)f.setCursor(da);else{var p=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
-16777216,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-1,-16777216,-16777216,-16777216,-16777216,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-16777216,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-16777216,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-16777216,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,-16777216,0,0,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];f.setCursor({"rawData":p,
"width":32,"height":32,"hotX":10,"hotY":10})}f.moveCursor=function(a,c,d,e){f.style.left=a+"px";f.style.top=c+"px";if(h!=d||y!=e){h=d;y=e;b()}};g.appendChild(f)}function $b(){da=null;if(f){if(f.parentNode)f.parentNode.removeChild(f);f=null}}function ab(c){if(u.disableScrollbars===false)return;var d=document.body;if(c){bb=c;d.style.overflow=c;return}var e=U<=window.innerWidth&&Q<=window.innerHeight;bb=e?"hidden":"visible";d.style.overflow=bb}function Da(c){var d=l.parentNode;if(Zb()){if(R!=1){hi5.tool.scale(d,
1);R=aa=1}return}document.body.style.overflow="hidden";R=aa=c?Math.min(window.innerWidth/U,window.innerHeight/Q):1;hi5.tool.scale(d,R,R)}function qb(){if(!m)m=new Yb;m.adjust()}function cb(){if(k.toolbar)k.toolbar.removeButton("svCloud");else{var c=hi5.$("svCloud");if(c)c.parentNode.removeChild(c)}}function rb(){var c=chrome.app.window.current();if(c)c.fullscreen()}function ac(){va=null;if(document){var c=m.element;document.removeEventListener("mousemove",Ja,false);c.removeEventListener("mousedown",
Ia,false);document.removeEventListener("mouseup",Ka,false);c.removeEventListener("mouseleave",La,false);c.removeEventListener("mouseenter",La,false);c.removeEventListener("paste",t.onPaste,false);c.removeEventListener("copy",t.onCopy,false);c.removeEventListener("cut",t.onCopy,false);document.removeEventListener("visibilitychange",bc,false);if(t){document.removeEventListener("paste",t.onPaste,false);document.removeEventListener("copy",t.onCopy,false);document.removeEventListener("cut",t.onCopy,false)}}if(window){window.removeEventListener("resize",
sb,false);window.removeEventListener("beforeunload",tb,false);window.removeEventListener("focus",ub,false);window.removeEventListener("blur",vb,false);window.removeEventListener("unload",Ma,false);$b();if(k&&k.toolbar){k.toolbar.setFadable=null;k.toolbar.startFade=null;k.toolbar.style.display="none";hi5.ui.clean(k.toolbar);k.toolbar=null}try{if(ra&&ra.parentNode){ra.parentNode.removeChild(ra);ra=null}if(m){m.remove();m=null}}catch(d){}}}function db(c,d){var e="_tmpEditable";var a=document.getElementById(e);
if(!c)c="div";var b=document.body;if(a&&a.nodeName!=c.toUpperCase()){b.removeChild(a);a=null}var g=!a;if(g){a=document.createElement(c);a.id=e;if(c=="div"&&d!==false){a.contentEditable=true;if(Z)a.style.textIndent="-999px"}a.style.position="absolute";a.style.zIndex=9999;a.style.left=b.scrollLeft+50+"px";a.style.top=b.scrollTop+50+"px";a.style.width="4px";a.style.height="4px";a.tabIndex=2;a.style.outline="none";a.style.opacity=0;b.appendChild(a)}return a}function ub(c){eb.clearPDF();k.focused=true;
r.onfocus(c);if(ba){if(r.fromSyncedSurface)ca=r.fromSyncedSurface(200);else ca=false;if(!ca){if(t)t.clipData=null;r.send("891"+(k.onreqpaste||wb?1:0))}}Na=true;if(!I.noKeyStuck)I.sendMissKey(true)}function tb(c){var d=__svi18n.remoteApp.close;var e=xb||!k.railWin||!k.railWin.isRunning()||!d;if(e)return;if(!c)c=window.event;if(r.getAppMode()!=2){k.showMessage(d);if(c)c.returnValue=d;return d}}function Ma(c){if(k){k.focused=false;if(k.onunload)k.onunload()}}function yb(){if(m){m.element.oncontextmenu=
function(){return false};if(!Z)m.element.onselectstart=function(){return false}}}function cc(){if(m){m.element.oncontextmenu=null;m.element.onselectstart=null}}function sb(c){if(m)m.adjust();if(wa)Da(true);else{if(oa&&Date.now()-oa<2500)return;var d=x.isWindows&&!x.isMetro;if(!L||d&&!oa||x.isCrOS||x.isChromeApp)r.onresize(c)}}function vb(){if(k){k.focused=false;k.blurTime=Date.now()}}function dc(){if(!window.svSurface)window.svSurface=k;window.addEventListener("resize",sb,false);if(ha)return;var c=
!x.isChromeApp;if(c)window.addEventListener("beforeunload",tb,false);if(c)window.addEventListener("unload",Ma,false);else chrome.runtime.onSuspend.addListener(Ma);yb();window.addEventListener("focus",ub,false);window.addEventListener("blur",vb,false);if(x.isChromeApp&&!u.disableMaxFullScn)chrome.app.window.current().onMaximized.addListener(rb);var d=hi5.$("saveSession");if(d)d.addEventListener("change",function(c){r.saveSession({save:c.target.checked})})}function uc(c){return c.replace(/</g,"&lt;").replace(/>/g,
"&gt;")}function zb(){if(ka)return;var c=hi5.$("touchGesture");if(c)c.style.display="block";var d=hi5.$("extKBD");if(d)d.onchange=function(a){k.setExtKeyboard(a.target.checked)};ka=hi5.$("svTouchInput");try{if(window.parent!=window&&!ka)ka=window.parent.document.getElementById("svTouchInput")}catch(a){}if(!ka)return;if(ka.nodeName!="IMG"){var e=document.createElement("img");e.id="svTouchInput";e.src=u.img&&u.img.kbd||"kbd.png";ka.parentNode.replaceChild(e,ka);ka=e}}function vc(){if(!ra)return;ra.style.display=
"block";if(fb)clearTimeout(fb);fb=setTimeout(inputTimeout,3E3)}function xa(c,d){function e(a,c){var b=document.createElement("span");b.data_path=a;b.className="path";b.innerHTML=c;b.onclick=function(){xa(this.data_path,d)};return b}function a(a){for(var c=g;c.hasChildNodes();)c.removeChild(c.firstChild);var b=e("/","&nbsp&nbsp&nbsp/");c.appendChild(b);if(a=="/"||a==="")return;var d=a.split("/");var k="/";var f=0;for(var l=d.length;f<l;f++){var m=d[f];if(m==="")continue;k=k+d[f]+"/";b=e(k,m+"/");c.appendChild(b)}}
function b(c){function b(a){if(!a)a=g.getValue("Name");var d=c.parent;if(d===""||d.charAt(d.length-1)!="/")d+="/";d+=a;return d}if(c.error)k.showMessage(__svi18n.file[c.error]);var e=new hi5.DataTable(c);var g=new hi5.DataGrid(hi5.$("filelist"));g.dataTable=e;var f=hi5.tool.bytesToSize;g.beforeDisplayValue=function(a,c){var b=e.cols[a].name;if(b=="Date Modified")return(new Date(c)).toLocaleString();else if(b=="Size")return f(c);else if(b=="Type"&&"folder"==c)return __svi18n.file.folder;else if(b==
"Name")return decodeURIComponent(c);else return c};g.onrowclick=function(a){var e=g.getValue("Name");var p=g.getValue("Type");var k=b(e);var f=a.target.name;if(f=="delete"){M.removeFile(k);xa(c.parent,d);return}if(p=="folder"){var l=c.parent=="/"?"":c.parent;xa(l+"/"+e,d);return}if(f=="view")k+="&action=view";r.getFile(k)};g.beforeAppendRow=function(a){var c;var d=e.getValue(e.getColNo("Type"));if(d=="folder"){c=a.querySelector('img[name="download"]');if(c)c.style.visibility="hidden";return}a.draggable=
true;var h=g.getValue("Name");var k=b(h);k="application/octet-stream:"+h+":"+r.getFileLink(k);a.addEventListener("dragstart",function(a){a.dataTransfer.setData("DownloadURL",k)},false);if(h.length>10&&h.substring(h.length-10)==".uploading"){c=a.querySelector('img[name="download"]');if(c)c.style.visibility="hidden";c=a.querySelector('img[name="view"]');if(c)c.style.visibility="hidden"}};g.open();a(c.parent);var l=document.getElementById("__diskSpace");if(l)l.innerHTML=hi5.tool.bytesToSize(c.freeSpace)+
"/"+hi5.tool.bytesToSize(c.totalSpace);d.resize();d.__position="\\\\tsclient\\"+c.name+c.parent.replace(new RegExp("/","g"),"\\")}var g=hi5.$("parentPath");if(!g.currentDir)g.currentDir="/";if("."==c)c=g.currentDir;else g.currentDir=c;g.currentDir=c;r.getShareFiles(c,b)}function Ab(c){if(c)cancelDefault(c);var d=hi5.$("filecontainer");X=new hi5.Lightbox(d);xa(".",X);X.show();var e=document.getElementById("__sv_folder__");if(e&&M.mkdirs)e.onclick=function(){var a=document.getElementById("__sv_folder_name_");
if(a&&a.value){M.mkdirs(a.value);xa(".",X)}};e=document.getElementById("__sv_position__");if(e)e.onclick=function(){r.writeKeyComb("Windows+R");setTimeout(function(){r.writeText(X.__position);V(true,28);V(false,28)},555);X.dismiss()}}function Bb(){var c=hi5.$("svToolbar");if(!c)return;var d=c.childNodes;var e=false;var a=0;for(var b=d.length;a<b;a++)if(d[a].nodeType==1&&["svTouchInput","svCloud","svInfo"].indexOf(d[a].id)==-1){e=true;break}var g=hi5.$("appinfo");if(g)g.className="h5-form";var h=k.showToolbar&&
(L||M||g||e);if(h){c.style.left=window.innerWidth*.45+"px";var y=k.toolbar===null;if(y)k.toolbar=new hi5.Toolbar(c,u.toolbar.draggable,u.img.handle||"handle.png");if(!L){var p=hi5.$("svTouchInput");if(p)p.parentNode.removeChild(p)}var A=k.toolbar.getButton("svCloud");if(A)if(M){A.style.display="";A.onclick=Ab}else A.style.display="none";var f=u.toolbar.fadeDelay||5E3;new hi5.Fadable(k.toolbar,f,m.element,"inline-block");var l=u.toolbar.fadable;k.toolbar.setFadable(l);if(l)k.toolbar.style.display=
"none";A=k.toolbar.getButton("svInfo");if(A)if(g){A.style.display="";if(y)A.onclick=function(a){cancelDefault(a);var c=r.getAppInfo();var b=hi5.$("numericId");if(b)b.innerHTML=c.numericId;b=hi5.$("connectingTo");if(b)b.innerHTML=c.server;b=hi5.$("joinLink");if(b)b.href=b.innerHTML=c.joinLink;var d=new hi5.Lightbox(hi5.$("appinfo"));d.show();cc();d.onclose=yb}}else A.style.display="none";if(k.onloadtoolbar)k.onloadtoolbar(k.toolbar)}}function ec(){return m.element}function Cb(c){M.addFiles(c.target.files,
false);var d=hi5.$("uploadfile");var e=d.cloneNode(true);var a=d.parentNode;a.replaceChild(e,d);e.addEventListener("change",Cb,false)}function fc(){var c=ec();if(la)la.release();la=new svGlobal.util.MapDisk(c,M,true);if(hi5.$("filecontainer")){Oa=new svGlobal.util.MapDisk(hi5.$("filecontainer"),M,false);hi5.$("uploadfile").addEventListener("change",Cb,false)}}function La(c){if(f)f.hideCursor()}function bc(){if(document.hidden==false&&l)setTimeout(function(){if(l&&r){l.width++;l.width--;var c=r.refresh(q.left,
q.top,q.right,q.bottom);if(c)E.putImageData(c.imgData,c.left-q.left,c.top-q.top,0,0,c.width,c.height)}},50)}function Db(c){if(E){if(c-gb>Eb)if(q.isMultiMon){var d=Ea(q.left,q.top,q.right,q.bottom);if(d){E.putImageData(d.imgData,d.left-q.left,d.top-q.top,0,0,d.width,d.height);gb=c}}else{d=Ea(0,0,q.right,q.bottom);if(d){E.putImageData(d.imgData,d.left,d.top,0,0,d.width,d.height);gb=c}}Pa=requestAnimationFrame(Db)}}function wc(c){c=c.replace(/<br\/?>/gi,"\r\n").replace(/(<([^>]+)>)/gi,"");return c.replace(/&[^;]+;/gi,
function(c){return gc[c]||c})}function Fb(c,d,e){if(!f)Ca();if(f.style.visibility=="hidden")f.style.visibility="visible";var a=f.scrX;var b=f.scrY;var g=a+c;var h=b+d;if(g<0)g=0;else if(g>U)g=U-1;if(h<0)h=0;else if(h>Q)h=Q-1;f.scrX=g;f.scrY=h;var y=g-f.hotX;var p=h-f.hotY;if(Z){y=y/R|0;p=p/aa|0}f.style.left=y+q.offX+"px";f.style.top=p+q.offY+"px";if(N&&!e)r.sendInput("82"+g+"\t"+h);q.x=g;q.y=h}function Qa(c,d,e){c=c/R|0;d=d/aa|0;k.moveCursor(c,d,e)}function $a(c){if(m)m.setContentEditable(c?"true":
"false");else{var d=document.getElementById("wsinput");if(d)input.setAttribute("contenteditable",c?"true":"false")}oa=c?1:0;if(Y)Y.setVisibility(c);if(k.toolbar){var e=k.toolbar.getButton("svTouchInput");if(e)e.className=c?"h5-img-btn-on":"h5-img-btn"}}function Gb(){Ba=!Ba;if(Ba&&m)m.adjust();$a(Ba);if(m)m.element.focus()}function hb(c,d,e,a){var b;var g;var h;switch(c){case "touchstart":ib=false;if(f.scrX===0&&f.scrY===0)Qa(d-50,e-50);if(a){if(k.beforemousedown)k.beforemousedown(f.scrX,f.scrY,0);
r.sendInput("80"+f.scrX+"\t"+f.scrY+"\t0")}break;case "touchmove":b=d-Ra;g=e-ya;if(b===0&&g===0)return;h=Math.abs(Hb)<5&&Math.abs(Ib)<5&&(Math.abs(b)>7||Math.abs(g)>7);if(!h){Fb(b,g);ib=true}Hb=b;Ib=g;break;case "touchend":var y=!ib&&!a;if(y){if(k.beforemousedown)k.beforemousedown(f.scrX,f.scrY,0);r.sendInput("80"+f.scrX+"\t"+f.scrY+"\t0")}if(y||a){r.sendInput("81"+f.scrX+"\t"+f.scrY+"\t0");if(k.aftermouseup)k.aftermouseup(f.scrX,f.scrY,0)}}Ra=d;ya=e}function Jb(c,d){Qa(c,d);Sa(c,d,2);Ta(c,d,2)}function hc(c){if(N&&
sa)if(c.touches||c.changedTouches)sa.handle(c);else sa.handlePointer(c)}function ic(c){if(!N)return false;c.stopPropagation();I.check(c);var d=fa.getKeyCode(c);var e=c.type=="keydown";if(e)if(m)m.setIMEStatus(d==229);if(d==18){if(Kb&&e)jb=2==(c.location||c.keyLocation);if(jb)return true}if(Lb(c,d,e))return cancelDefault(c);if(d==17&&!e)Fa=false;var a=kb(d,c);if(a>0){n(e,a);var b=c.target==m.element;var g=e&&za&&m&&d==17&&(x.isFirefox||x.isSafari||Z&&!b);if(g)if(b){m.setValue("`\t`");m.select()}else{S.setValue("`\t`");
S.select()}return cancelDefault(c)}if(B||c.altKey&&!jb||c.metaKey){var h=d==86&&(B||c.metaKey)&&!(B&&c.altKey)&&ba;if(!h)ia(e,d,c.key);if(e)Ua=d;if(d==17||(B||c.metaKey)&&(d==86||d==67||d==88)){if(e)if(d==67||d==88)Fa=true;return true}return c.altKey&&!B||B&&!c.altKey||c.metaKey?cancelDefault(c):true}else{if(d==Ua&&!e&&!(B&&c.altKey)){ia(false,d,c.key);Ua=0;return cancelDefault(c)}Ua=0;return true}}function Lb(c,d,e){switch(d){case 8:case 35:if(!B&&!c.metaKey)return false;if(!c.altKey||u.disableShortcuts)return false;
n(e,211);break;case 33:if(!c.altKey||u.disableShortcuts)return false;n(e,15);break;case 34:if(!c.altKey||u.disableShortcuts)return false;if(e){n(true,42);n(true,15)}else{n(false,15);n(false,42)}break;case 45:if(!c.altKey||u.disableShortcuts)return false;n(e,1);break;case 36:if(!c.altKey||u.disableShortcuts)return false;if(e){n(false,56);n(true,29);n(true,1)}else{n(false,1);n(false,29)}break;case 124:n(e,59);break;case 125:n(e,62);break;case 126:n(e,63);break;case 127:n(e,64);break;case 128:n(e,87);
break;case 129:n(e,88);break;default:return false}return true}function jc(c){if(!Na||I.preKeyCode==229||I.preKeyCode==0)return;I.ignoreText=true;var d=String.fromCharCode(c.charCode||c.keyCode||w.which);if(d.toUpperCase()==d.toLowerCase())return;var e=d.toUpperCase()==d;var a=c.shiftKey?!e:e;Na=false;if(r.capsLock!=a){r.sendKeyboardSynchronize(false,r.numLock,a);if(I.preKeyCode){V(true,14);V(false,14);var b=fa.getScancodeByKeyCode(I.preKeyCode);V(true,b);V(false,b)}}}function kc(c){if(!N)return false;
I.check(c);var d=fa.getKeyCode(c);var e=c.type=="keydown";var a=I.preKeyCode;if(e){if(m)m.setIMEStatus(d==229)}else if(m&&m.isIMEMode)if(Z)if(m)m.setIMEStatus(false);var b=fa.getScancode(c);if(c.key=="Dead"&&!e&&I.preKeyDownCode!=d)n(true,b);I.preKeyCode=d;if(e)I.preKeyDownCode=d;else if(I.preKeyDownCode==d)I.preKeyDownCode=0;if(d==229||a==229&&!e)return true;if(Lb(c,d,e))return cancelDefault(c);if(lc(d,e,c))return cancelDefault(c);var g=kb(d,c)<1&&!B&&!c.altKey&&!c.metaKey;if(!b)b=kb(d,c)||0;var h=
d==86&&(Mb&&!e||(c.ctrlKey||c.metaKey)&&!(c.ctrlKey&&c.altKey))&&ba;if(b>0)if(h){if(Va&&e)Va.sendCtrlVLater()}else n(e,b);if(d!=17)Mb=h;if(d==17||(B||c.metaKey)&&(d==86||d==67||d==88)){if(e){if(d==17&&za&&m){m.setValue("Copying... Please try again");m.select()}if(d==67||d==88)Fa=true}if(d==17&&!e)Fa=false;return true}var y=d==144||d==16||Na&&g;return y?false:cancelDefault(c)}function mc(c){if(!N)return;if(I.ignoreText){I.ignoreText=false;return}var d=c.data;if(!L&&Wa&&d.length==1&&d.charCodeAt(0)<
128)return;if(d=="`\t`")return;var e=B||ta;if(e)d=d.toLowerCase();d=d.replace(/\u00a0/g," ");r.sendInput("86"+d+"\t"+(e||Wa?1:0));if(Y)Y.resetModifier()}function Nb(c,d){var e=c?c.getData(d):null;if(e&&d=="text/plain"){var a=0;var b="";for(var g=e.length;a<g;a++){b=e.charAt(a);if(b!="\r"&&b!="\n")break}if(a)e=e.substring(a)}if(e){r.send("881"+d+"\t"+e);c.sent=Date.now();return true}else if(k.onreqpaste){k.onreqpaste(d,function(a){r.send("881"+d+"\t"+a)},function(){r.send("881ERROR\t")});return true}else{r.send("881"+
d+"\t"+"");return false}}function Xa(){n(true,29);ia(true,86);ia(false,86);n(false,29)}function nc(c){var d=c.types.length===0||c.equals(t.clipData);var e=d?"":c.types.join(",");var a=true;if(!d){if(e.indexOf("text/html")!=-1&&e.indexOf("text/richtext")==-1)e+=",text/richtext";var b=c.getData("text/plain");var g=b?b.hashCode():0;r.send("880"+e+"\t"+g);t.clipData=c}if(k.onclipdata)a=!k.onclipdata(c,d);if(a)setTimeout(Xa,500)}function lc(c,d,e){if(c==44){if(B||e.shiftKey){n(true,128|55);n(false,128|
55)}else{n(true,128|42);n(true,128|55);n(false,128|55);n(false,128|42)}return true}return false}function V(c,d){if(k.onscancode){var e=k.onscancode(c,d);if(e){var a=0;for(var b=e.length;a<b;a++)r.sendInput("84"+(e[a].down?0:49152)+"\t"+e[a].key);return}}r.sendInput("84"+(c?0:49152)+"\t"+d)}function n(c,d){if(!N)return;switch(d){case 221:if(c){V(true,221);V(false,221);return}break;case 58:if(c){r.capsLock=!r.capsLock;if(Ob){V(true,58);V(false,58);return}}break;case 69:if(c)r.numLock=!r.numLock;break;
default:if(c&&d>70&&d<84&&r.sendKeyboardSynchronize&&I.altUp)r.sendKeyboardSynchronize(false,true,r.capsLock)}if(d==184){V(c,29);V(c,56);return}var e=!c&&(x.isCrOS&&d>61&&d<69||d==58&&Ob||d==95);if(e)V(true,d);if(d!=95)V(c,d)}function ia(c,d,e){if(!N)return;if(d==111){if(c)r.sendInput("86/\t1");return}var a="8B"+(c?0:49152)+"\t"+d;if(e)a+="\t"+e;r.sendInput(a)}function Sa(c,d,e,a,b){if(!N)return false;D(m.element);if(!a)a=R;if(!b)b=aa;if(va[e])return;va[e]=true;c=(c/a|0)+q.left;d=(d/b|0)+q.top;if(k.beforemousedown)k.beforemousedown(c,
d,e);r.sendInput("80"+c+"\t"+d+"\t"+e)}function Ia(c){if(m)m.setIMEStatus(false);if(!(B||c.shiftKey||c.metaKey||c.altKey))I.sendMissKey();var d=Ga(c);Sa(d.x,d.y,c.button);return cancelDefault(c)}function Pb(c,d,e,a){if(!e)e=R;if(!a)a=aa;c=(c/e|0)+q.left;d=(d/a|0)+q.top;if(c<0)c=0;if(d<0)d=0;if(k.onmousemove)k.onmousemove(c,d);q.x=c;q.y=d;r.sendInput("82"+c+"\t"+d)}function Ja(c){if(!Qb)return false;if(c.target!=m.element&&!va[0])return false;var d=Ga(c,m.element);if(Ya&&(x.isAndroid||x.isiOS||!(da&&
da.system)))Qa(d.x,d.y,true);Pb(d.x,d.y);return cancelDefault(c)}function Ta(c,d,e,a,b){if(!a)a=R;if(!b)b=aa;va[e]=false;c=(c/a|0)+q.left;d=(d/b|0)+q.top;if(c<0)c=0;if(d<0)d=0;r.sendInput("81"+c+"\t"+d+"\t"+e);if(k.aftermouseup)k.aftermouseup(c,d,e);if(x.isChrome&&t)t.waitForCopyContent()}function Ka(c){if(!N)return false;if(c.target!=m.element&&!va[0])return false;var d=c.target;var e=Ga(c,m.element);Ta(e.x,e.y,c.button);if(t)t.prePaste();return cancelDefault(c)}function Rb(c,d,e,a,b){if(!a)a=R;
if(!b)b=aa;c=(c/a|0)+q.left;d=(d/b|0)+q.top;if(k.onmousewheel)if(k.onmousewheel(c,d,e))return;r.sendInput("83"+c+"\t"+d+"\t"+e)}function Sb(c,d){if(!N)return false;var e=Math.abs(c);var a=c<0?1:0;for(var b=0;b<e;b++)Rb(d.x,d.y,a);return false}function kb(c,d){var e=d.keyCode;if(e==17)return d.location==2?157:29;else if(e==16)return d.location==2?54:42;var a=oc[c];if(!a)a=-1;return a}function pc(c,d,e){var a=document.createElement("canvas");var b=a.getContext("2d");var g=b.createImageData(d,e);var h=
g.data;var y=d*e;var p=window.devicePixelRatio||1;var A=0;var k=0;var f=0;a.width=d;for(a.height=e;A<y;A++){f=c[A];h[k++]=f&255;h[k++]=f>>8&255;h[k++]=f>>16&255;h[k++]=f>>24&255}b.putImageData(g,0,0,0,0,d,e);if(p==1)return a.toDataURL();else if(a.toDataURLHD)return a.toDataURLHD();else{var l=document.createElement("canvas");var m=l.getContext("2d");l.width=d*p|0;l.height=e*p|0;m.scale(p,p);m.drawImage(a,0,0);return l.toDataURL()}}function qc(c){if(c.none)return"none";else if(c.system)return c.system;
else if(Ya)return"none";else return"url("+(c.url||pc(c.rawData,c.width,c.height))+") "+c.hotX+" "+c.hotY+", default"}if(!l)l=hi5.$("remotectrl");if(window.svSurface&&svSurface.canvas==l&&svSurface.railWin){svSurface.railWin.mainWin=null;return window.svSurface}var x=hi5.browser;var L=x.isTouch;var Za=false;var r=null;var wa=false;var R=1;var aa=1;l.style.outline="none";var U=0;var Q=0;var rc=0;var sc=0;var E=l.getContext("2d");var K=null;var S=null;var Tb=false;var B=false;var ta=false;var Aa=false;
var xb=false;var ca=false;var M=null;var ba=true;var Fa=false;var Mb=false;this.context=E;this.fileProgress=null;this.blurTime=0;var k=this;var N=true;var qa=false;var ha=false;var Wa=false;var Qb=true;var ra=null;var fb=null;var X=null;var f=null;var da=null;var sa=null;var ka=null;var oa=0;var Ra=-1;var ya=-1;var Hb=0;var Ib=0;var ib=false;var bb=null;var ob=false;var Na=true;var q={x:0,y:0,offX:0,offY:0,left:0,top:0,right:0,bottom:0,primary:false,isMultiMon:false};var xc=0;var yc=0;var la=null;
var Oa=null;var gb=0;var Ea;var lb=false;var Ub=0;var Pa=0;var Ba=false;this._cr=[82,69,77,79,84,69,83,80,65,82,75];window.svSurface=this;var u=hi5.appcfg||{img:{},toolbar:{fadable:true}};if(u.toolbar.draggable==undefined)u.toolbar.draggable=true;var Z=x.isIE;var Ya=Z&&!u.disableCursor;var wb=x.isChromeApp||Z&&!x.isEdge||u.directClipAccess==true;this.setConfig=function(c){u=c};this.toolbar=null;this.railWin=null;this.focused=false;this.showToolbar=true;this.canvas=l;this.alwaysPaste=false;this.forceTextArea=
false;if("visible"in u.toolbar)this.showToolbar=u.toolbar.visible;var Kb=false;var jb=false;var Ga=x.getMousePos;var Ha=x.calMousePos;this.getWindow=function(){return window};this.setMonitor=function(c,d,e,a){q.left=c;q.top=d;q.right=e;q.bottom=a;q.primary=c==0&&d==0;if(e!=0&&a!=0){q.isMultiMon=false;k.setSize(e-c+1,a-d+1);q.isMultiMon=true;ab("hidden")}};this.isClipSynced=function(c){if(!ca)return false;var d=Date.now()-k.blurTime;if(c&&d>c)return false;svGlobal.logger.info("clip synced in "+d);
return true};this.getScale=function(){return{x:R,y:aa}};var ma=null;var Y=null;var mb="";var za=!x.isChromeApp&&!u.copyDialog;this.getThumbnail=function(c){c=c||64;if(!ma)ma=document.createElement("canvas");var d=Math.floor(l.height/l.width*c);if(ma.width!=c)ma.width=c;if(ma.height!=d)ma.height=d;ma.getContext("2d").drawImage(l,0,0,l.width,l.height,0,0,c,d);return ma.toDataURL()};this.initChat=function(c){var d=document.getElementById("chatWindow");hi5.Dragable(d);return new hi5.Chat(d,c)};this.equals=
function(c){return l==c.canvas};this.getFreeSpace=function(){var c=hi5.tool.getPos(l);var d=window.innerWidth-c.x;var e=v(window.innerHeight)-c.y;var a=d>e?Math.max(screen.width,screen.height):Math.min(screen.width,screen.height);var b=d>e?Math.min(screen.width,screen.height):Math.max(screen.width,screen.height);if(d>a)d=a;if(e>b)e=b;return{"width":d,"height":e}};var fa=new function(){function c(a){var c=null;var d="K"+a;if(d in p)c=p[d]();if(c===null)c=b;return c}var d=1033;var e=x.isFirefox;var a=
x.isMacOS||x.isiOS;var b=[0|0];var g=null;b[3]=197;b[8]=14;b[9]=15;b[12]=76;b[13]=28;b[16]=42;b[17]=29;b[18]=56;b[19]=197;b[20]=58;b[27]=1;b[32]=57;b[33]=201;b[34]=209;b[35]=207;b[36]=199;b[37]=203;b[38]=200;b[39]=205;b[40]=208;b[44]=55;b[45]=210;b[46]=211;b[48]=11;b[49]=2;b[50]=3;b[51]=4;b[52]=5;b[53]=6;b[54]=7;b[55]=8;b[56]=9;b[57]=10;b[65]=30;b[66]=48;b[67]=46;b[68]=32;b[69]=18;b[70]=33;b[71]=34;b[72]=35;b[73]=23;b[74]=36;b[75]=37;b[76]=38;b[77]=50;b[78]=49;b[79]=24;b[80]=25;b[81]=16;b[82]=19;
b[83]=31;b[84]=20;b[85]=22;b[86]=47;b[87]=17;b[88]=45;b[89]=21;b[90]=44;b[91]=219;b[92]=220;b[93]=221;b[96]=82;b[97]=79;b[98]=80;b[99]=81;b[100]=75;b[101]=76;b[102]=77;b[103]=71;b[104]=72;b[105]=73;b[106]=55;b[107]=78;b[109]=74;b[110]=83;b[111]=181;b[112]=59;b[113]=60;b[114]=61;b[115]=62;b[116]=63;b[117]=64;b[118]=65;b[119]=66;b[120]=67;b[121]=68;b[122]=87;b[123]=88;b[144]=69;b[145]=70;b[154]=183;b[166]=59;b[167]=60;b[168]=61;b[173]=66;b[174]=67;b[175]=68;b[182]=63;b[183]=62;b[216]=64;b[217]=65;b[186]=
39;b[187]=13;b[188]=51;b[189]=12;b[190]=52;b[191]=53;b[192]=41;b[219]=26;b[220]=43;b[221]=27;b[222]=40;b[224]=29;b[225]=184;b[226]=86;var h=function(a){var c=a.keyCode;if(e){switch(c){case 173:return 189;case 61:return 187;case 59:return 186;case 224:return 17}return c}return c};this.converMacCtrl=true;var y=a?function(a){switch(a){case 91:case 93:return 17;case 17:return fa.converMacCtrl?91:17;case 229:return 69}return 0}:null;this.setLayout=function(a){d=a;g=c(a);if(g!==null)svGlobal.logger.info("Keyboard layout: "+
d)};this.getKeyCode=function(a){var c=0;if(y)c=y(a.keyCode);if(!c)c=h?h(a):a.keyCode;return c};this.getScancode=function(a){var c=fa.getKeyCode(a);if(c==17)return a.location==2?157:29;else if(c==16)return a.location==2?54:42;return g?g[c]:0};this.getScancodeByKeyCode=function(a){return g?g[a]:0};this.getCodeTable=function(){return g};this.getLayoutCreator=function(){return p};var p=new function(){function a(){var c=b.slice(0);c[220]=41;c[219]=12;c[221]=13;c[186]=26;c[187]=27;c[191]=43;c[192]=39;c[189]=
53;c[226]=86;if(e){c[171]=27;c[173]=53;h=function(a){var c=a.keyCode;var b=a.key;if(c===0)if(b=="\u00ba"||b=="\u00aa"&&a.shiftKey||b=="\\"&&a.ctrlKey&&a.altKey)return 220;else if(b=="\u00a1"||b=="\u00bf"&&a.shiftKey)return 221;else if(b=="\u00e7"||b=="\u00c7"&&a.shiftKey||b=="}"&&a.ctrlKey&&a.altKey)return 191;else if(b=="\u00f1"||b=="\u00d1"&&a.shiftKey)return 192;else{if(b=="DeadAcute"||b=="\u00b4\u00b4"||b=="\u00b4"||b=="DeadUmlaut"&&a.shiftKey||b=="{"&&a.ctrlKey&&a.altKey)return 222}else if(c==
192)return 186;else if(c==222)return 219;return c}}return c}function c(){var a=b.slice(0);a[220]=41;a[219]=12;a[221]=13;a[186]=26;a[187]=27;a[191]=43;a[192]=39;a[189]=53;a[226]=86;a[90]=21;a[89]=44;if(e)h=function(a){var c=a.keyCode;var b=a.key;switch(c){case 60:return 226;case 160:return 220;case 63:return 219;case 192:return 221;case 171:return 187;case 163:return 191;case 173:return 189;case 0:if(b=="\u00f6"||b=="\u00d6"&&a.shiftKey)return 192;else if(b=="\u00e4"||b=="\u00c4"&&a.shiftKey)return 222;
else if(b=="\u00fc"||b=="\u00dc"&&a.shiftKey)return 186}return c};else if(hi5.browser.isLinux)h=function(a){var c=a.keyCode;var b=a.key;switch(c){case 187:if(b=="Dead")return 221;break;case 192:if(b=="Dead"||b=="\u00b0")return 220;break;case 220:return 226}return c};return a}function d(){var a=b.slice(0);a[220]=41;a[219]=12;a[221]=13;a[186]=27;a[187]=26;a[191]=43;a[192]=39;a[189]=53;a[226]=86;a[90]=21;a[89]=44;return a}function p(){var a=b.slice(0);a[222]=41;a[219]=12;a[189]=13;a[221]=26;a[186]=27;
a[77]=39;a[192]=40;a[188]=50;a[190]=51;a[191]=52;a[187]=53;a[226]=86;a[65]=16;a[90]=17;a[81]=30;a[87]=44;if(e)h=function(a){var c=a.keyCode;var b=a.key;switch(c){case 60:return 226;case 169:return 219;case 173:return 189;case 160:return 221;case 164:return 186;case 165:return 192;case 59:return 190;case 58:return 191;case 61:return 187;case 0:if(b=="\u00b2"||b=="\u00b3"&&a.shiftKey)return 222;else if(b=="\u00b5"||b=="`\u00b5"||b=="DeadGrave"||b=="\u00a3"&&a.shiftKey)return 220;else if((b=="`"||b==
"``")&&a.ctrlKey&&a.altKey)return 220}return c};return a}function g(){var a=b.slice(0);a[222]=41;a[192]=40;a[226]=86;if(e)h=function(a){var c=a.keyCode;var b=a.key;switch(c){case 0:if(b=="\u00b0"||b=="\u00ac"&&a.ctrlKey&&a.altKey)return 222;else if(b=="\u00e7"||b=="\u00c7"&&a.shiftKey)return 221;else if(b=="\u00e0"||b=="DeadGrave"||b=="\u00c0"&&a.shiftKey)return 220;else if(b=="\u00e8"||b=="\u00c8"&&a.shiftKey)return 192;else if(b=="\u00e9"||b=="\u00c9"&&a.shiftKey)return 191;else if(b=="\u00f9"||
b=="\u00d9"&&a.shiftKey)return 226;else if(b=="DeadTilde")return 221;break;case 173:return 189;case 61:return 187;case 160:return 219;case 59:return 186}return c};return a}function y(){var a=b.slice(0);a[222]=41;a[219]=12;a[187]=13;a[221]=26;a[186]=27;a[220]=43;a[77]=39;a[192]=40;a[190]=51;a[191]=52;a[223]=53;a[226]=86;a[65]=16;a[90]=17;a[81]=30;a[87]=44;a[188]=50;if(e)h=function(a){var c=a.keyCode;var b=a.key;switch(c){case 0:if(b=="\u00b2")return 222;else if(b=="\u00e7"||b=="\u00c7"&&a.shiftKey)return 221;
else if(b=="\u00e0"||b=="\u00c0"&&a.shiftKey)return 220;else if(b=="\u00e8"||b=="\u00c8"&&a.shiftKey)return 192;else if(b=="\u00e9"||b=="\u00c9"&&a.shiftKey)return 189;else if(b=="\u00f9"||b=="\u00d9"&&a.shiftKey)return 226;else if(b=="DeadTilde")return 221;break;case 60:return 226;case 169:return 219;case 61:return 187;case 160:return 221;case 164:return 186;case 170:return 220;case 165:return 192;case 59:return 190;case 58:return 191;case 161:return 223}return c};return a}function k(){var a=b.slice(0);
a[191]=41;a[219]=12;a[221]=13;a[186]=26;a[192]=27;a[223]=43;a[222]=39;a[220]=40;a[188]=51;a[190]=52;a[189]=53;a[226]=86;a[90]=21;a[89]=44;if(e)h=function(a){var c=a.keyCode;var b=a.key;switch(c){case 0:if(b=="\u00a7"||b=="\u00b0"&&a.shiftKey)return 191;else if(b=="\u00e0"||b=="\u00e4"&&a.shiftKey||b=="{"&&a.ctrlKey&&a.altKey)return 220;else if(b=="\u00e8"||b=="\u00fc"&&a.shiftKey||b=="["&&a.ctrlKey&&a.altKey)return 186;else if(b=="\u00e9"||b=="\u00f6"&&a.shiftKey)return 222;break;case 222:return 219;
case 160:return 221;case 161:return 192;case 164:return 223;case 173:return 189;case 60:return 226}return c};return a}function f(){var a=b.slice(0);a[220]=41;a[187]=12;a[219]=13;a[221]=26;a[186]=27;a[191]=43;a[192]=39;a[222]=40;a[189]=53;a[226]=86;if(e)h=function(a){var c=a.keyCode;var b=a.key;switch(c){case 0:if(b=="\u00e5"||b=="\u00c5"&&a.shiftKey)return 221;else if(b=="\u00f8"||b=="\u00d8"&&a.shiftKey||b=="\u00f6"&&a.ctrlKey&&a.altKey)return 192;else if(b=="\u00e6"||b=="\u00c6"&&a.shiftKey||b==
"\u00e4"&&a.ctrlKey&&a.altKey)return 222;break;case 172:return 220;case 171:return 187;case 220:return 219;case 160:return 186;case 222:return 191;case 173:return 189;case 60:return 226}return c};return a}function l(){var a=b.slice(0);a[220]=41;a[187]=12;a[219]=13;a[221]=26;a[186]=27;a[191]=43;a[192]=39;a[222]=40;a[189]=53;a[226]=86;if(e)h=function(a){var c=a.keyCode;var b=a.key;switch(c){case 0:if(b=="\u00a7"||b=="\u00bd"&&a.shiftKey)return 220;else if(b=="\u00e5"||b=="\u00c5"&&a.shiftKey)return 221;
else if(b=="\u00f8"||b=="\u00d8"&&a.shiftKey||b=="\u00f6"&&a.ctrlKey&&a.altKey)return 192;else if(b=="\u00e4"||b=="\u00c4"&&a.shiftKey)return 222;break;case 171:return 187;case 192:return 219;case 160:return 186;case 222:return 191;case 173:return 189;case 60:return 226}return c};return a}this.K3758162961=function ea(){var a=b.slice(0);a[244]=41;a[243]=41;a[189]=12;a[222]=13;a[220]=125;a[192]=26;a[219]=27;a[187]=39;a[186]=40;a[221]=43;a[188]=51;a[190]=52;a[191]=53;a[226]=115;a[29]=123;a[28]=121;a[240]=
112;a[242]=112;if(e){a[173]=12;a[160]=13;a[64]=26;a[59]=39;a[58]=40;h=function(a){return a.keyCode==220&&a.key=="_"?226:a.keyCode}}return a};this.K1034=this.K66570=this.K2058=this.K1040=this.K66576=a;this.K2057=function P(){var a=b.slice(0);a[223]=41;a[222]=43;a[192]=40;a[220]=86;if(e){a[192]=41;a[173]=12;a[61]=13;a[59]=39;a[222]=40;a[163]=43}return a};this.K1031=this.K4106=this.K5130=this.K6154=this.K7178=this.K8202=this.K9226=this.K10250=this.K11274=this.K12298=this.K13322=this.K14346=this.K15370=
this.K16395=this.K17418=this.K18442=this.K19466=this.K20490=this.K99997=this.K66567=this.K2952791047=c;this.K2070=d;this.K2060=this.K99998=p;this.K3084=this.K4105=g;this.K1036=y;this.K4108=this.K2055=k;this.K1044=this.K1083=f;this.K1053=l;this.K1055=function(){var a=b.slice(0);a[220]=52;a[223]=12;a[189]=13;a[191]=51;a[188]=43;a[190]=53;a[226]=86;if(e)h=function(a){var c=a.keyCode;var b=a.key;switch(c){case 0:if(b=="\u011f"||b=="\u011e"&&a.shiftKey||a.ctrlKey&&a.altKey&&a.code=="BracketLeft")return 219;
else if(b=="\u00fc"||b=="\u00dc"&&a.shiftKey||a.ctrlKey&&a.altKey&&a.code=="BracketRight")return 221;else if(b=="\u015f"||b=="\u015e"&&a.shiftKey||a.ctrlKey&&a.altKey&&a.code=="Semicolon")return 186;else if(b=="\u00f6"||b=="\u00d6"&&a.shiftKey)return 191;else if(b=="\u00e7"||b=="\u00c7"&&a.shiftKey)return 220;break;case 73:return 222;case 60:return 226;case 173:return 189;case 170:return 223;case 162:return 192}return c};return a}}};this.getKeyboardMgr=function(){return fa};var t=new function d(){function e(a){return a.search(/<.*(font|color|img|table|style|class).*>/gmi)>
-1}function a(a,b){var d=t.parseClipData(b);if(u.copyTextOnly&&d.type!="text/plain")return;if(t.processFileGroup(d))return;if(x.isEdge&&d.type!="text/plain"){m.resetCSS();m.setValue(d.value);m.select();setTimeout(function(){m.setValue("");if(S)S.setValue("");m.restoreCSS();t.processImgCopy(d.value)},555)}else{a.clipboardData.setData(d.type,d.value);if(d.type!="text/plain"){var e=hi5.browser.html2text(d.value);if(e)a.clipboardData.setData("text/plain",e);t.processImgCopy(d.value)}a.preventDefault()}}
function b(a){return a.replace(/<br>/gi,"\n").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&lt;/gi,"<").replace(/&gt;/gi,">")}function g(){if(!t)return;if(t.copyContent){t.copyToClipboard(t.copyContent.type,t.copyContent.value);t.copyContent=null}t.waitingCopyContent=false}var h=0;this.hasCopyCmd=document.queryCommandSupported("copy");this.hasPasteCmd=document.queryCommandSupported("paste");this.release=function(){t.clipData=null};this.clipData=null;this.paste=function(a,
b){var d=new J;var e=0;var h=null;var g=window.clipboardData||b.clipboardData;var k=window.clipboardData?g.getData("Text"):g.getData("text/plain");var f="";var l="";if(g.types)l=g.getData("text/html");if(l&&!k)k=hi5.browser.html2text(l);if(k)d.setData("text/plain",k);if(u.pasteTextOnly){b.preventDefault();a(d);return}var m=g.items;if(m)for(e=0,len=m.length;e<len;e++){if(m[e].type=="image/png"){h=m[e].getAsFile();break}}else if(g.files){var n=g.files;for(e=0,len=n.length;e<len;e++)if(n[e].type.indexOf("image/png")!=
-1){h=n[e];break}}if(h){var r=new FileReader;b.preventDefault();r.onloadend=function(b){if(b.target.readyState==FileReader.DONE){var e=hi5.Base64.enc(new Uint8Array(b.target.result));d.setData("image/png",e);a(d)}};r.readAsArrayBuffer(h);return}if(!k){b.preventDefault();a(d);return}if(g.types){var q=g.types.indexOf?g.types.indexOf("text/rtf")!=-1:g.types.contains("text/rtf");f=g.getData("text/rtf");if(f){if(f.charCodeAt(f.length-1)==0)f=f.substring(0,f.length-1);d.setData("text/richtext",f)}if(l){e=
l.lastIndexOf("</html>");if(e+7<l.length)l=l.substring(0,e+7);d.setData("text/html",l)}var x=hi5.browser.isEdge||q&&!f&&!l;if(!x){b.preventDefault();a(d);return}}if("TEXTAREA"==b.target.nodeName&&document.queryCommandSupported("paste")){b.preventDefault();d=t.getClipContent(d);a(d);return}if(K)K.disableTextInput=true;if(S)S.disableTextInput=true;b.target.innerHTML="";var v=b.target.style.opacity;b.target.style.opacity=0;setTimeout(function(){var e=b.target.innerHTML;if(e&&e!=k){d.setData("text/html",
"<body>"+e+"</body>");if(K)K.init();else b.target.innerHTML=""}a(d);b.target.style.opacity=v;if(K)K.disableTextInput=false;if(S)S.disableTextInput=false},300)};this.onCopy=function(b){if(b.target!=m.element)return;if(!N||!ba)cancelDefault(b);if(!Fa){n(true,29);var d=b.type=="copy"?"67":88;ia(true,d);ia(false,d);n(false,29)}if(Tb){var e=Date.now();var g=e-h;h=e;if(g>500)return}if(!ba||wb)return;mb=r.getClipData();a(b,mb);t.clipData=null;ca=true;svGlobal.logger.info("clip synced: true")};this.onPaste=
function(a){if(a.target!=m.element)return;if(Va)Va.cancelCtrlV();if(!N||!ba)return cancelDefault(a);if(!k.alwaysPaste&&ca){var b=true;if(k.onclipdata)b=!k.onclipdata(t.clipData,true);if(b)setTimeout(Xa,500);svGlobal.logger.info("Ctrl+V only");return cancelDefault(a)}ca=true;t.paste(nc,a);return true};this.parseClipData=function(a){var b=a.indexOf(";");var d=a.substring(0,b);a=a.substring(b+1);return{type:d,value:a}};this.getClipContent=function(a){if(!document.queryCommandSupported("paste"))return a;
var d=db(u.pasteTextOnly?"textarea":"div");d.focus();try{if(document.queryCommandEnabled("paste")){var e=document.execCommand("paste");if(e){if(!a)a=new J;if(!u.pasteTextOnly)a.setData("text/html","<body>"+d.innerHTML+"</body>");if(a.types.indexOf("text/plain")==-1)a.setData("text/plain",u.pasteTextOnly?d.value:d.innerText||b(d.innerHTML));return a}}}finally{d.parentNode.removeChild(d);if(m)m.focus()}return a};this.accessClip=function(a){if(!document.queryCommandSupported("paste"))a(null);var b=db(u.pasteTextOnly?
"textarea":"div");b.focus();b.addEventListener("paste",function(d){d.stopPropagation();t.paste(function(d){if(b.parentNode)b.parentNode.removeChild(b);if(m)m.focus();a(d)},d)},false);if(!document.queryCommandEnabled("paste")||!document.execCommand("paste")){a(null);if(b.parentNode)b.parentNode.removeChild(b);if(m)m.focus()}};this.getContent=function(){var a=t.getClipContent();if(m)m.element.removeEventListener("click",t.getContent,false);if(a&&!a.equals(t.clipData)){t.clipData=a;r.send("880text/plain,text/html\t0");
return true}else return false};this.startPasteCmd=function(){if(m&&document.queryCommandSupported("paste"))m.element.addEventListener("click",t.getContent)};this.waitingCopyContent=false;this.copyContent=null;this.waitForCopyContent=function(){t.waitingCopyContent=true;setTimeout(g,700)};this.prePaste=function(){if(ca||!document.queryCommandEnabled("paste")&&!window.clipboardData)return;t.accessClip(function(a){if(!a)return;var b=a.types.length===0||a.equals(t.clipData);var d=b?"":a.types.join(",");
if(!b){if(d.indexOf("text/html")!=-1&&d.indexOf("text/richtext")==-1)d+=",text/richtext";var e=a.getData("text/plain");var g=e?e.hashCode():0;r.send("880"+d+"\t"+g);t.clipData=a;ca=true}})};this.copyToClipboard=function(a,b){var d=a=="text/plain"?"textarea":"div";var e=db(d,false);var g=false;var h=b.indexOf("data-sv-img")>0;var f;if(d=="div"){e.innerHTML=b;e.focus();if(h&&document.body.createControlRange){f=document.body.createControlRange();f.add(e.childNodes[0]);h=false}else x.selectEditable(e)}else{e.value=
b;e.focus();e.select()}try{if(f)g=f.execCommand("Copy");else g=document.execCommand("copy",false,null)}catch(l){}finally{e.parentNode.removeChild(e);if(m)m.focus()}ca=true;if(!g&&k.beforeCopyDialog&&k.beforeCopyDialog(b,__svi18n.info.imgCopyDownload,a))return true;var n=h&&t.processImgCopy(b);if(!g)if(!n)hi5.notifications.notify({"title":__svi18n.info.userCopy,"msg":b,"timeout":9999,"select":true,"format":a});return g};this.processFileGroup=function(a){if(a.type=="application/x-filegroup"){var b=
a.value.split("\r\n");var d="";var e=0;b.forEach(function(a){var b=a.split("\t");if(b.length>1){if(d)d+=",";d+=b[0];e+=parseInt(b[1],10)}});if(d.length>28)d=d.substring(0,28)+"...";d=d+"<br>Total: "+hi5.tool.bytesToSize(e)+" Qty:"+b.length;hi5.notifications.notify({"title":__svi18n.info.download,"msg":d,"timeout":9E3,"cbYes":function(){this.destroy();M.download()},"cbNo":function(){this.destroy()}});return true}else return false};this.processImgCopy=function(a){if(a.indexOf("data-sv-img")>0){hi5.notifications.notify({"title":__svi18n.info.imgCopyDownload,
"msg":a,"timeout":9999});return true}else return false}};var Ob=x.isMacOS||x.isiOS;var I=new function e(){this.altUp=this.shiftUp=this.winUp=this.ctrlUp=true;this.preKeyCode=0;this.preKeyDownCode=0;this.ignoreText=false;this.noKeyStuck=false;var a=this;this.sendMissKey=function(b){if(!a.shiftUp||b){n(false,42);a.shiftUp=true}if(!a.altUp||b){if(!a.altUp){n(false,56);n(true,56)}n(false,56);a.altUp=true}if(!a.ctrlUp||b){n(false,29);a.ctrlUp=true}if(!a.winUp||b){n(false,219);a.winUp=true}};this.check=
function(b){var e=fa.getKeyCode(b);var h=b.type=="keydown";switch(e){case 16:if(h&&a.shiftUp&&!b.altKey&&!B&&!b.metaKey)a.sendMissKey();a.shiftUp=!h;break;case 17:if(h&&a.ctrlUp&&!b.altKey&&!b.shiftKey)a.sendMissKey();a.ctrlUp=!h;B=h;break;case 18:if(h&&a.altUp&&!b.shiftKey&&!B&&!b.metaKey)a.sendMissKey();a.altUp=!h;break;case 91:case 92:if(h&&a.winUp&&!b.shiftKey&&!B&&!b.metaKey&&!b.altKey)a.sendMissKey();a.winUp=!h;break;default:if(h&&!(B||b.altKey||b.shiftKey||b.metaKey))a.sendMissKey()}}};this.requestCredential=
function(e,a){Za=false;var b=__svi18n.template.login;if(!b){k.showMessage("No value for login template");return}var g=document.createElement("div");g.className="appdlg";g.innerHTML=b;document.body.appendChild(g);var h=hi5.$("loginDomain");if(h&&e.nbDomain)h.innerHTML=e.nbDomain;var f=new hi5.Lightbox(g,.9);f.onclose=function(){document.body.removeChild(g)};f.show();h=hi5.$("loginUser");if(h)h.focus();h=hi5.$("frmLogin");if(h)h.onsubmit=function(){var b=hi5.$("loginUser").value;var e=hi5.$("loginPassword").value;
var g=hi5.$("loginDomain").innerHTML;f.dismiss();setTimeout(function(){a(b,e,g)},5);return false}};var m=null;if(L)zb();else{var nb=hi5.$("tmContainer");if(nb)nb.parentNode.removeChild(nb)}if(L&&!u.toolbar.draggable)window.addEventListener("scroll",function(){setTimeout(function(){if(Y){var e=hi5.$("pc_key");if(e){e.style.top=window.pageYOffset+"px";e.style.left=window.pageXOffset+"px"}}if(k.toolbar){k.toolbar.style.top=window.pageYOffset+"px";var a=window.pageXOffset+window.innerWidth*.45;k.toolbar.style.left=
a+"px"}},200)},false);this.setCaretPos=function(e,a){rc=e;sc=a};this.showMessage=function(e,a){if(e&&u.displayMsg)hi5.notifications.notify(typeof e=="string"?{"msg":e,"timeout":a||0}:e)};this.hideWhenClose="hideWhenClose"in u?u.hideWhenClose:true;this.setReadOnly=function(e,a){N=!e;Qb=N||a===true};this.setPlayerMode=function(){ha=true;k.showToolbar=false;k.setReadOnly(true);k.hideWhenClose=false};this.setAutoScale=function(e){var a="autoScale"in u;if(a)e=u.autoScale;if(e){Da(true);ab("hidden")}else if(!a)Da(false);
wa=e};if(Ya)Ca();this.setTouchpad=function(e){qa=e;var a=hi5.$("touchpadMode");if(a){a.checked=e;a.onchange=function(a){qa=a.target.checked}}if(e)if(!f)Ca()};this.setExtKeyboard=function(e){if(L){ob=true;m.adjust(true);m.setContentEditable(e?"true":"false");oa=e?1:0;if(x.isChrome)m.setFontSize("2em");if(e)m.focus();var a=hi5.$("extKBD");if(a&&a.checked!=e)a.checked=e}};this.focus=function(){if(m)D(m.element)};this.getInputElement=function(){return m};this.scaleTo=function(e,a,b){if(l){var g=e/U;var h=
a/Q;if(!b){g=Math.min(g,h);h=g;R=g;aa=g}else{R=g;aa=h}hi5.tool.scale(l.parentNode,g,h)}};this.setSize=function(e,a,b){if(q.isMultiMon)return;if(q.right!=q.left+e-1){q.right=q.left+e-1;q.bottom=q.top+a-1}U=e;Q=a;if(!wa)ab(b);l.width=U;l.height=Q;if(r)k.drawText(__svi18n.wait);if(wa)Da(true);if(L)zb();qb();if(X&&X.visible())X.dismiss()};this.reposition=function(){m.adjust()};this.setController=function(e){r=e;Ea=e.draw;if(!r.sendInput)r.sendInput=r.send;if(L)x.setOrientaionHandler(function(){if(wa)Da(true);
else setTimeout(function(){r.onorientationchange({svSurface:k,innerWidth:window.innerWidth,innerHeight:v(window.innerHeight)});if(!u.disableScoll)window.scrollTo(0,0)},300)})};this.setFileHandler=function(e){if(!("FileReader"in window))e=null;if(e){if(!M&&!ha){M=e;M.addEvent("uploaded",function(a){if(a)return;if(hi5.$("filecontainer")&&Ub&16){if(hi5.$("__cancelUpload"))hi5.$("__cancelUpload").style.visibility="hidden";k.fileProgress.maxValue=0;k.fileProgress.style.display="none";k.refreshFiles();
k.showMessage(__svi18n.file.uploadDone,5E3)}});M.addEvent("uploadstarted",function(a){if(a)setTimeout(Xa,999)});if(hi5.$("filecontainer")){hi5.$("filecontainer").className="h5-form";k.fileProgress=new hi5.ProgressBar(hi5.$("total"));var a=hi5.$("__cancelUpload");if(a)a.addEventListener("click",function(){M.cancelAll()},false);M.addEvent("beforeupload",function(b,e,h){if(h)return;if(a)a.style.visibility="visible";k.fileProgress.style.display="block";k.fileProgress.maxValue+=b.size});M.addEvent("progress",
function(a){k.fileProgress.setProgress(a)})}else cb()}}else{M=null;k.fileProgress=null;cb();if(la){la.release();la=null}}Bb();fc()};this.setFeature=function(e){Ub=e;var a;var b=ha||!(e&16)&&!(e&65536);var g=!(e&16);var h=!(e&65536);if(g||ha)cb();if(e&128){a=hi5.$("uploadfile");if(a)a.style.visibility="hidden"}if(!(e&256)){a=hi5.$("shadowing");if(a)a.parentNode.removeChild(a)}if(!(e&1024)){a=hi5.$("ssParent");if(a)a.parentNode.removeChild(a)}if(h&&g||ha)k.setFileHandler(null)};var eb=new function(){function e(){if(g.length===
0){h=false;if(!f){var a=hi5.$("_sv_pdf_parent");if(a&&a.visible&&a.visible()&&a.dismiss)a.dismiss();setTimeout(function(){if(a&&a.parentNode)a.parentNode.removeChild(a)},9999)}}else b()}function a(a){var b=hi5.$("_sv_pdf_parent");var g=__svi18n.info.printready||"Your document is ready.";f=L&&!(x.isChrome&&(x.isWindows||x.isCrOS))||!!u.showPDFLink||x.isEdge;var h=f?'<p style="text-align:center;line-height:4em"><a href="'+a+'" target="_blank">'+g+"</a></p>":(x.isChromeApp?"<webview":"<iframe")+' src="'+
a+'" width="100%" height="100%" id="_iFramePDF">'+(x.isChromeApp?"</webview>":"</iframe>");if(!b){b=document.createElement("div");b.style.backgroundColor="white";b.style.width=f?"30%":"70%";b.style.height=f?"4elm":"70%";b.id="_sv_pdf_parent";if(f)b.style.overflow="scroll";b.innerHTML=h;document.body.appendChild(b);var k=new hi5.Lightbox(b);k.onclose=e;k.show()}else{var l=hi5.$("_iFramePDF");if(l)l.src=a;else b.innerHTML+=h}}function b(){var b=g.shift();if(b)a(b);h=true}var g=[];var h=false;var f=
false;this.clearPDF=function(){e()};this.showPDF=function(a){g.push(a);if(!h)b()}};this.close=function(){lb=false;if(!r)return;svGlobal.logger.info("close ui...");N=false;if(Pa)cancelAnimationFrame(Pa);Ma();ac();if(t){t.release();t=null}if(Oa){Oa.release();Oa=null}if(la){la.release();la=null}if(S){S.release();S=null}fa=null;I=null;ma=null;S=null;M=null;X=null,f=null,da=null,sa=null;Ea=null;r=null;k.fileProgress=null;eb.clearPDF();if(wa)k.setAutoScale(false);if(Y){Y.setVisibility(false);Y=null}if(!("clearScreen"in
u)||u.clearScreen)E.fillRect(0,0,l.width,l.height);window.svSurface=null;xb=true;if(!window||ha)return;try{if(hi5.notifications.notifySize()>0){hi5.notifications.onempty=function(){k.close();hi5.notifications.onempty=null};return}if(Za)window.close();else{this.hide();if(x.isChromeApp){var e=chrome.app.window.current();if(e&&!u.disableMaxFullScn){e.onMaximized.removeListener(rb);if(e.isFullscreen()){e.restore();e.restore()}}}}}catch(a){}k.context=null;E=null;l=null;k=null;svGlobal.logger.info("closed ui")};
this.setFastCopy=function(e){Tb=e};this.drawLicense=function(e){if(u.drawLicense!=false){var a=e.charAt(0);E.save();E.font="12pt Arial";E.fillStyle=a=="W"?"red":"black";var b=e.substring(1);E.fillText(b,10,Q-24);E.restore()}};this.drawText=function(e){var a=u.text||{};E.save();if(a.backgroundFillStyle){var b=l.width;var g=l.height;E.fillStyle=a.backgroundFillStyle;E.fillRect(0,0,b,g)}var h=20;var f=50;if(a.textAlign=="center"){h=b/2;f=g/2}E.font=a.font||"18pt Arial";E.fillStyle=a.fillStyle||"black";
if(a.textAlign)E.textAlign=a.textAlign;if(a.textBaseline)E.textBaseline=a.textBaseline;E.fillText(e,h,f);E.restore()};this.showPDF=function(e){eb.showPDF(e)};this.hide=function(){if(k.hideWhenClose){l.height=1;l.width=1}if(m)m.hide()};var Vb=0;var zc=false;this.copyToClip=function(e,a){if(!ba)return;var b=t.parseClipData(e);if(u.copyTextOnly&&b.type!="text/plain")return;if(t.processFileGroup(b))return;if(t.waitingCopyContent){t.copyContent=b;return}setTimeout(function(){if(!ba||za&&mb==e)return;e=
b.value;var a=e.indexOf("<img ")>0||u.copyDialog;if(!a||t.hasCopyCmd)a=!t.copyToClipboard(b.type,e)},50)};this.fullScreen=function(){l.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)};Y=new function a(){function b(a){oa=Date.now();var b=hi5.$("pc_key");if(!b)return;b.style.display="block";b.style.top=window.pageYOffset+"px";if(S){S.setValue("`\t`");S.select()}}function g(a){oa=0;var b=hi5.$("pc_key");if(!b)return;b=hi5.$("shortcuts");if(b&&b.checked)return;q.style.display="none"}function h(){if(l)if(B)hi5.html.addClass(l,
"button_selected");else hi5.html.removeClass(l,"button_selected");if(m)if(ta)hi5.html.addClass(m,"button_selected");else hi5.html.removeClass(m,"button_selected");if(r)if(Aa)hi5.html.addClass(r,"button_selected");else hi5.html.removeClass(r,"button_selected")}function f(a){cancelDefault(a);var b=a.target;var g=b.innerHTML;g=g.replace(/\u2190/g,"left").replace(/\u2191/g,"up").replace(/\u2192/g,"right").replace(/\u2193/g,"down");switch(g){case "Ctrl":if(!l)l=b;if(B)n(false,29);else n(true,29);B=!B;
h();return;case "Alt":if(!m)m=b;if(ta)n(false,56);else n(true,56);ta=!ta;h();return;case "Shift":if(!r)r=b;if(Aa)n(false,42);else n(true,42);Aa=!Aa;h();return;case "...":var q=hi5.$("pc_key_more");if(q)q.style.display=q.style.display=="block"?"none":"block";return;case "Start":g="Ctrl+Esc";default:k.writeKeyComb(g);Y.resetModifier()}}var l=null;var m=null;var r=null;this.setVisibility=function(a){if(a)b();else g()};this.resetModifier=function(){if(ta){ta=false;n(false,56)}if(B){B=false;n(false,29)}if(Aa){Aa=
false;n(false,42)}h()};var q=hi5.$("pc_key");if(!q)return;var t=q.getElementsByTagName("span");var u=t.length;var v=x.isFirefox?"mousedown":"touchstart";if(!("ontouchstart"in window))if(navigator.pointerEnabled)v="pointerdown";else if(navigator.msPointerEnabled)v="MSPointerDown";for(var z=0;z<u;z++){var E=t[z];E.className="button";E.addEventListener(v,f,false);if(v!="mousedown")E.addEventListener("mousedown",f,false)}q.style.position="absolute"};var Wb=hi5.$("shortcuts");if(Wb)Wb.addEventListener("change",
function(a){Y.setVisibility(a.target.checked)});this.setKeysVisibility=function(a){if(Y)Y.setVisibility(a)};this.refreshFiles=function(){if(!X||!X.visible())Ab(null);else xa(".",X)};this.processLink=function(a){function b(b){window.open(a);b.target.parentNode.removeChild(b.target)}if(k.beforeOpenLink&&k.beforeOpenLink(a))return;clearTimeout(Vb);var g=k.toolbar;var h=g.getButton("_svLinkInfo");if(h)h.onclick=b;else{h=g.addButton(u.img.link?u.img.link:"link.png",b);h.id="_svLinkInfo"}h.title=a;g.startFade();
Vb=setTimeout(function(){k.toolbar.removeButton("_svLinkInfo")},1E4)};this.setUnicode=function(a){if(!m)return;if(!a&&L&&(x.isiOS||x.isChrome&&!x.isWindows))a=true;Wa=!a;svGlobal.logger.info("Unicode:"+a);K.onkeydown=K.onkeyup=a?ic:kc;if(!a&&r&&r.sendKeyboardSynchronize)K.onkeypress=jc;K.ontextinput=mc};this.setTouchRemoting=function(a){if(a===true){sa=new pa(k,l);svGlobal.logger.info("touch remoting");k.showMessage(__svi18n.info.touchremoting)}else sa=new ua(k)};this.setClipboard=function(a){ba=
a;za=a?!x.isChromeApp&&!u.copyDialog:false};this.setJoinMode=function(a){r.setJoinMode(a)};this.requestControl=function(){r.requestControl()};this.repaint=function(a,b,g,h){if(q.isMultiMon){if(a<q.left)a=q.left;if(b<q.top)b=q.top;if(g>q.right)g=q.right;if(h>q.bottom)h=q.bottom;if(a<=q.right&&b<=q.bottom){var f=r.refresh(a,b,g,h);if(f)E.putImageData(f.imgData,f.left-q.left,f.top-q.top,0,0,f.width,f.height)}}else{f=r.refresh(a,b,g,h);if(f)E.putImageData(f.imgData,f.left,f.top,0,0,f.width,f.height)}};
this.running=function(){return lb};this.run=function(a,b,g){function f(a){a.target.removeEventListener("click",f,false);r.send("884")}fa.converMacCtrl=b!==false;I.noKeyStuck=!!g;lb=true;qb();hi5.notifications.clearAll();if((a==3758162961||a==3758162962)&&m)m.setContentEditable("false");fa.setLayout(a);var n=[99997,99998,99999].indexOf(a)!=-1;Wa=!n;Kb=(n||[1033,3758162961,3758162962,1049].indexOf(a)==-1)&&x.isMacOS;if(typeof u.closeOnDisconn=="boolean")Za=u.closeOnDisconn;else Za=!!window.opener&&
!x.isChromeApp;if(!u.disableScoll)window.scrollTo(0,0);Bb();dc();var p=m.element;if(L){if(!ha){sa=new ua(k);var q=new ja(p);q.ontouch=hc;q.onmousedown=Ia;q.onmousemove=Ja;q.onmouseup=Ka;W(p,Sb,false);document.addEventListener("paste",t.onPaste,false);if(ba)if(za){document.addEventListener("copy",t.onCopy,false);document.addEventListener("cut",t.onCopy,false)}}}else{if(!ha){document.addEventListener("mousemove",Ja,false);p.addEventListener("mousedown",Ia,false);document.addEventListener("mouseup",
Ka,false);p.addEventListener("mouseleave",La,false);p.addEventListener("mouseenter",La,false);W(p,Sb,false);p.addEventListener("paste",t.onPaste,false);if(ba)if(za){p.addEventListener("copy",t.onCopy,false);p.addEventListener("cut",t.onCopy,false)}}if(u.autoFocus!==false)D(p)}k.setUnicode(n);this.drawText(__svi18n.wait);if(k.onstart)k.onstart(l);p.addEventListener("click",f,false);if(Ea)Pa=requestAnimationFrame(Db);m.adjust();if(!u.disableScoll)window.scrollTo(0,0)};var Eb=u.animation||42;if(Z&&!x.isEdge)Eb*=
2;var gc={"&euro;":"\ufffd","&nbsp;":" ","&quot;":'"',"&amp;":"&","&lt;":"<","&gt;":">","&iexcl;":"\ufffd","&cent;":"\ufffd","&pound;":"\ufffd","&curren;":"\ufffd","&yen;":"\ufffd","&brvbar;":"\ufffd","&sect;":"\ufffd","&uml;":"\ufffd","&copy;":"\ufffd","&ordf;":"\ufffd","&reg;":"\ufffd"};this.moveCursorBy=this.movCursorBy=Fb;this.moveCursor=function(a,b,g,h,k){a-=q.left;b-=q.top;if(a<0||b<0||a>=U||b>=Q)return;if(!f)Ca();if(f.style.visibility=="hidden")f.style.visibility="visible";f.scrX=a;f.scrY=
b;var l=a-f.hotX;var m=b-f.hotY;if(h&&h.length>9)h=h.substring(0,9);f.moveCursor(l+q.offX,m+q.offY,h,k);if(N&&!g)r.sendInput("82"+a+"\t"+b);q.x=a;q.y=b};var Xb=hi5.$("svTouchInput");if(Xb)Xb.addEventListener("click",function(){Gb()},false);this.touchstart=function(a){switch(a.pointes){case 1:if(qa){if(!f)Ca();hb("touchstart",a.screenX,a.screenY,!a.flick)}else if(!a.flick||na())Sa(a.x,a.y,0);break;case 2:Ra=a.screenX;ya=a.screenY}};this.touchmove=function(a){switch(a.pointes){case 1:if(qa)hb("touchmove",
a.screenX,a.screenY,!a.flick);else if(!a.flick||na())Pb(a.x,a.y);break;case 2:if(Math.abs(a.screenY-ya)>=40){Rb(a.x,a.y,a.screenY-ya>0?0:1);Ra=a.screenX;ya=a.screenY}case 3:}};this.touchend=function(a){var b=a.pointes;switch(b){case 1:if(qa)hb("touchend",a.screenX,a.screenY,!a.flick);else{Qa(a.x,a.y,true);if(!a.flick||na())Ta(a.x,a.y,0)}break;case 2:if(!a.moved)Jb(qa?f.scrX:a.x,qa?f.scrY:a.y);break;case 3:if(a.gesture)switch(a.gesture){case "OPEN":n(true,219);n(true,200);n(false,200);n(false,219);
break;case "CLOSE":n(true,219);n(true,208);n(false,208);n(false,219);break;case "LEFT":n(true,56);n(true,1);n(false,1);n(false,56);break;case "RIGHT":n(true,42);n(true,56);n(true,1);n(false,1);n(false,56);n(false,42);break;case "UP":n(true,42);n(true,219);ia(true,77);ia(false,77);n(false,219);n(false,42);break;case "DOWN":n(true,219);ia(true,77);ia(false,77);n(false,219)}else Gb()}};this.flick=function(a){switch(a.from){case 4:r.sendInput("84"+"0\t"+209);r.sendInput("84"+"49152\t"+209);break;case 2:r.sendInput("84"+
"0\t"+201);r.sendInput("84"+"49152\t"+201)}};this.longpress=function(a){if(qa)a.pointes=2;switch(a.pointes){case 1:Jb(a.x,a.y);break;case 2:if(f){Sa(f.scrX,f.scrY,2,1);Ta(f.scrX,f.scrY,2,1)}}};this.redirectTouches=function(a){if(!N)return;var b=a.length;var g;var f="90"+b;for(var k=0;k<b;k++){g=a[k];f=f+"\t"+g.contactId+";"+g.contactFlags+";"+Math.floor(g.x/R)+";"+Math.floor(g.y/aa)}r.send(f)};var Ua=0;this.setIgnorePaste=function(a){ca=a};this.processClipReq=function(a){if(!ba){r.send("881ERROR\t");
return true}var b=t.clipData;if(b||ca){Nb(b,a);return true}else t.accessClip(function(b){Nb(b,a)});return document.queryCommandSupported("paste")};var Va=Z?function(){var a;this.sendCtrlVLater=function(){a=setTimeout(Xa,333)};this.cancelCtrlV=function(){clearTimeout(a)};return this}():null;var va={};this.getMousePosition=function(){return q};var oc={29:197,33:201,34:209,35:207,36:199,37:203,38:200,39:205,40:208,154:183,45:210,46:211,225:184,91:219,92:220,93:221,27:1,8:14,9:15,13:28,224:29,17:29,16:42,
18:56,20:58,166:59,112:59,167:60,113:60,168:61,114:61,183:62,115:62,182:63,116:63,216:64,117:64,217:65,118:65,173:66,119:66,174:67,120:67,175:68,121:68,122:87,123:88};this.writeKeyComb=function(a){r.writeKeyComb(a)};this.setCursor=function(a){if(!a||u.disableCursor)return;da=a;if(f)f.setCursor(a);if(f&&(!Ya||a.system))f.hideCursor();if(!ha){if(!a.result)a.result=qc(a);if(m)m.element.style.cursor=a.result;else l.style.cursor=a.result}};this.setVisible=function(a,b){var f=a?"visible":"hidden";if(typeof b==
"number")setTimeout(function(){l.style.visibility=f},b);else l.style.visibility=f}}if(!svGlobal.LocalInterface)svGlobal.LocalInterface=LocalInterface;
svGlobal.rdpFile={loadRdpFile:function(l,H){var v=H.elements;var D=l.split("\r\n");if(D.length<2)D=l.split("\n");if(D.length<2)return false;var J=hi5.$("gateway");var T=J.value;H.reset();J.value=T;var W=0;for(var ja=D.length;W<ja;W++){var na=D[W];var pa=na.indexOf(":");var ua=na.substring(0,pa);var z=na.substring(pa+3);ua=ua.toLowerCase();switch(ua){case "full address":pa=z.indexOf(":");if(pa>0){v["server"].value=z.substring(0,pa);v["port"].value=z.substring(pa+1)}else v["server"].value=z;break;case "username":v["user"].value=
z;break;case "domain":v["domain"].value=z;break;case "connect to console":v["useConsole"].checked=z!="0";break;case "desktopwidth":v["width"].value=z;break;case "desktopheight":v["height"].value=z;break;case "session bpp":v["server_bpp"].value=z;break;case "audiomode":v["playSound"].value=z;break;case "alternate shell":if(z.length>0){v["command"].value=z;if(!hi5.$("app").checked)hi5.$("shell").checked=true}break;case "shell working directory":v["directory"]=z;break;case "redirectclipboard":v["mapClipboard"].checked=
z!="0";break;case "redirectprinters":v["mapPrinter"].checked=z!="0";break;case "server port":if(z.length>0)v["port"].value=z;break;case "disable wallpaper":v["background"].checked=z=="0";break;case "disable themes":v["styles"].checked=z=="0";break;case "disable menu anims":v["animation"].checked=z=="0";break;case "disable full window drag":v["contents"].checked=z=="0";break;case "allow font smoothing":v["smoothfont"].checked=z!="0";break;case "allow desktop composition":v["composition"].checked=z!=
"0";break;case "bitmapcachepersistenable":v["bitmap"].checked=z!="0";break;case "remoteapplicationprogram":v["exe"].value=z;break;case "remoteapplicationcmdline":v["args"].value=z;break;case "remoteapplicationmode":hi5.$("app").checked=z=="1";break;case "loadbalanceinfo":v["loadBalanceInfo"].value=z}}return true},handleFiles:function(l,H){if(l.length!=1){hi5.notifications.notify({"msg":"Please one file only"});return}var v=l[0];var D=v.name;var J=D.length;var T=J>4&&D.substring(J-4).toLowerCase()==
".rdp";if(!T){hi5.notifications.notify({"msg":"Sorry, Please .rdp file only"});return}var W=new FileReader;var ja=false;W.onload=function(l){var D=l.target.result;if(!D)return;var J=svGlobal.rdpFile.loadRdpFile(D,H);if(!J&&!ja){ja=true;W.readAsText(v)}};W.readAsText(v,"UTF-16LE")}};
function initDragDrop(l,H){function v(l){svGlobal.rdpFile.handleFiles(l.target.files,H)}function D(v){cancelDefault(v);l.style.backgroundColor=W;var D=v.dataTransfer.files;svGlobal.rdpFile.handleFiles(D,H)}function J(v){cancelDefault(v);l.style.backgroundColor="yellow"}function T(v){cancelDefault(v);l.style.backgroundColor=W}if(!("FileReader"in window))return;var W=l.style.backgroundColor;var ja=hi5.$("rdpfile");if(ja)ja.addEventListener("change",v,false);l.addEventListener("dragover",J,false);l.addEventListener("dragleave",
T,false);l.addEventListener("drop",D,false)}svGlobal.util.initDragDrop=initDragDrop;
svGlobal.util.initMapDisk=svGlobal.util.MapDisk=function(l,H,v){function D(v){cancelDefault(v);if(!H)return;if(l.style.opacity!="0.6")l.style.opacity="0.6";l.style.backgroundColor="yellow"}function J(v){cancelDefault(v);if(!H)return;l.style.opacity=l.__oldOpacity;l.style.backgroundColor=l.__oldColor}function T(D){cancelDefault(D);if(!H)return;l.style.opacity=l.__oldOpacity;l.style.backgroundColor=l.__oldColor;var J=hi5.file.getEntries(D);if(J.length&&location.protocol!="file:")hi5.file.getFilesFromEntries(J,
function(l){if(H.addFiles)H.addFiles(l,v);else H.addFile(l[0])});else if(H.addFiles)H.addFiles(D.dataTransfer.files,v);else H.addFile(D.dataTransfer.files[0])}if(!("FileReader"in window))return;l.__oldColor=l.style.backgroundColor;l.__oldOpacity=l.style.opacity;l.addEventListener("dragover",D,false);l.addEventListener("dragleave",J,false);l.addEventListener("drop",T,false);this.release=function(){l.removeEventListener("dragover",D,false);l.removeEventListener("dragleave",J,false);l.removeEventListener("drop",
T,false);H=null;l=null}};(function init(){function H(v){var D=document.getElementsByClassName("ver");var J=D.length;for(var T=0;T<J;T++)D[T].innerHTML=svGlobal.version;window.removeEventListener("load",H,false)}window.addEventListener("load",H,false)})();svGlobal.logger.info("ver:"+svGlobal.version);
