var svGlobal={version:"4.8",log:1,isMultitask:hi5.browser.isMultitask,util:{},logger:{debug:function(e){2<svGlobal.log&&console.log(e)},info:function(e){1<svGlobal.log&&console.log(e)},warn:function(e){0<svGlobal.log&&console.log(e)}}};function cancelDefault(e){e.preventDefault&&e.preventDefault();e.stopPropagation&&e.stopPropagation();return!1}
function LocalInterface(e){function v(a){var b=0,d=0,c=a.offsetParent;c&&c.offsetParent&&(c=c.offsetParent,b=c.scrollTop,d=c.scrollLeft);a.focus();b&&(c.scrollTop=b);d&&(c.scrollLeft=d)}function q(){var a=[];this.sent=!1;this.types=[];var b=this;this.datas=a;this.setData=function(d,c){if("text/plain"==d||"text/html"==d)2<c.length&&"`\t`"==c.substring(0,3)&&(c=c.substring(3)),c=c.replace(/\r?\n/g,"\r\n");b.types.push(d);a.push(c)};this.getData=function(d){return a[b.types.indexOf(d)]};this.equals=
function(a){if(!a||!hi5.Arrays.equals(b.types,a.types))return!1;for(var c,f,p=b.types,n=0,B=p.length;n<B;n++)if(c=p[n],f=b.getData(c),c=a.getData(c),f!=c)return!1;return!0}}function H(a){function b(){var b=h?a.value:a.innerText||a.textContent;C&&!h&&b.charAt(0)!=m.PLACE_HOLDER&&(b=m.PLACE_HOLDER+b);return b}function d(){var b=C?m.PLACE_HOLDER:"";k=b;m.setValue(b);if(C)if(h)a.setSelectionRange&&a.setSelectionRange(a.value.length,a.value.length);else if(a.focus(),"undefined"!=typeof window.getSelection&&
"undefined"!=typeof document.createRange){b=document.createRange();b.selectNodeContents(a);b.collapse(!1);var c=window.getSelection();c.removeAllRanges();c.addRange(b)}else"undefined"!=typeof document.body.createTextRange&&(b=document.body.createTextRange(),b.moveToElementText(a),b.collapse(!1),b.select())}function c(a){I=8==a.keyCode;if(m.onkeydown)m.onkeydown(a);return!0}function f(b){if(m.onkeyup)m.onkeyup(b);b=b.keyCode;1!=(h?a.value:a.innerText||a.textContent).length&&13!=b&&32!=b||setTimeout(d,
100);return!0}function p(a){if(m.onbackspace)for(var b=0;b<a;b++)m.onbackspace()}function n(c){if(!m.disableTextInput){c.stopPropagation();c=b();var f=c.length;1<f&&c.charAt(0)!=m.PLACE_HOLDER&&c.charAt(f-1)==m.PLACE_HOLDER&&(c=m.PLACE_HOLDER+c.substring(0,f-1),m.setValue(c));if(c!=k){var n=k.length,B=c.indexOf(k);if(c&&0===B){if(c=c.substring(n),0<c.length&&e&&m.ontextinput&&(m.ontextinput({data:c,target:a}),"."==c)){d();return}}else if(B=k.indexOf(c),0===B)I||p(n-f);else if(e&&(C&&(n--,c=c.substring(1)),
p(n),0<c.length&&m.ontextinput))m.ontextinput({data:c,target:a});""===b()&&setTimeout(d,100);k=b()}}}function B(a){if(!m.disableTextInput&&a.data){a.stopPropagation();if(m.ontextinput)m.ontextinput(a);g&&a.preventDefault()}}var m=this,C=hi5.browser.isAndroid&&hi5.browser.isChrome,e=hi5.browser.isFirefox||hi5.browser.isOpera||C,I=!1,g=!hi5.browser.isRIM,k="",h="INPUT"==a.nodeName||"TEXTAREA"==a.nodeName,l="DIV"==a.nodeName;this.PLACE_HOLDER="`";this.setValue=function(b){var c=m.disableTextInput;m.disableTextInput=
!0;h?a.value=b:l&&(a.innerHTML=b);m.disableTextInput=c};this.init=d;this.disableTextInput=!1;d();a.addEventListener("keydown",c,!1);a.addEventListener("keyup",f,!1);a.addEventListener("keypress",function(a){if(m.onkeypress)m.onkeypress(a)},!1);e?(a.addEventListener("input",n,!1),C?a.onclick=d:a.addEventListener("mouseup",d,!1)):(a.addEventListener("textInput",B,!1),a.addEventListener("textinput",B,!1));this.release=function(){a.removeEventListener("keydown",c,!1);a.removeEventListener("keyup",f,!1);
a.removeEventListener("input",n,!1);a.removeEventListener("focus",d,!1)};this.select=function(){Ya(a)}}function E(a,b,d){function c(a){var c=0,m=0,d=0,e=a.pageX-a.target.offsetLeft,I=a.pageY-a.target.offsetTop;a.wheelDelta?(d=(new Date).getTime(),100<d-p&&(f=0),m=a.wheelDelta,f+=m,c=f/120|0,f%=120,0!==c&&b(c,e,I),p=d):(c=-a.detail,32768==Math.abs(c)&&(m=window.innerHeight/40|0,c=0>c?-m:m),b(c,e,I))}var f=0,p=0;a.addEventListener("DOMMouseScroll",c,!0);a.addEventListener("mousewheel",c,!0)}function y(a){function b(a){if(!p&&
n.onmousedown)n.onmousedown(a)}function d(a){if(!p&&n.onmousemove)n.onmousemove(a)}function c(a){if(p)p=!1;else if(n.onmouseup)n.onmouseup(a)}function f(a){"touchstart"==a.type&&(p=!0);if(n.ontouch)n.ontouch(a)}var p=!1,n=this,B=navigator.pointerEnabled||navigator.msPointerEnabled||!1;"ontouchstart"in window||!B?(a.addEventListener("touchstart",f,!1),a.addEventListener("touchend",f,!1),a.addEventListener("touchmove",f,!1),a.addEventListener("touchcancel",f,!1),a.addEventListener("mousemove",d,!1),
a.addEventListener("mousedown",b,!1),a.addEventListener("mouseup",c,!1)):navigator.pointerEnabled?(a.addEventListener("pointerdown",f,!1),a.addEventListener("pointerup",f,!1),a.addEventListener("pointermove",f,!1),a.addEventListener("pointercancel",f,!1)):navigator.msPointerEnabled&&(a.addEventListener("MSPointerDown",f,!1),a.addEventListener("MSPointerUp",f,!1),a.addEventListener("MSPointerMove",f,!1),a.addEventListener("MSPointerCancel",f,!1))}function t(){return k.railWin?!0:!ga&&O<=window.innerWidth&&
M<=window.innerHeight}function z(a){function b(a,b){for(var d,m=a.length,f=Array(m),e=h.getElement().getBoundingClientRect(),I=0;I<m;I++){d=a[I];var k=I,g;g=d.identifier;if(!(256>g)){var l=c.indexOf(g);-1!=l?g=l:(c.push(g),g=c.length-1)}f[k]={contactId:g,contactFlags:b,x:d.pageX-e.left,y:d.pageY-e.top}}return f}var d,c=[],f=!1;this.handle=function(p){var n=p.type,B=p.touches,m=p.changedTouches;cancelDefault(p);switch(n){case "touchstart":f=!1;d=p=b(B,25);break;case "touchmove":p=b(m,26);n=!1;if(0<
d.length&&1==p.length){a:{B=d.length;for(m=0;m<B;m++)if(d[m].contactId==p[0].contactId){B=m;break a}B=-1}-1!=B&&d[B].x==p[0].x&&d[B].y==p[0].y&&(n=!0)}if(n)break;else 0<d.length&&(a.redirectTouches(d),d.length=0);a.redirectTouches(p);f=!0;break;case "touchend":if(f)p=b(m,4);else{a.redirectTouches(d);p=d.length;for(n=0;n<p;n++)d[n].contactFlags=4;p=d}a.redirectTouches(p);c.length=d.length=0;break;case "touchcancel":a.redirectTouches(b(m,34)),c.length=d.length=0}}}function J(a){function b(a){var b=
a[1].screenX-a[0].screenX;a=a[1].screenY-a[0].screenY;return Math.sqrt(b*b+a*a)}function d(a,m){var d=[],f=c(a,u[0].identifier)||c(m,u[0].identifier);f&&d.push(f);(f=c(a,u[1].identifier)||c(m,u[1].identifier))&&d.push(f);f="";if(2!=d.length)return f;var p=b(d)-b(u);60>Math.abs(p)?80<d[0].screenX-u[0].screenX?f="RIGHT":80<u[0].screenX-d[0].screenX?f="LEFT":80<d[0].screenY-u[0].screenY?f="DOWN":80<u[0].screenY-d[0].screenY&&(f="UP"):f=0>p?"CLOSE":"OPEN";return f}function c(a,b){for(var c=0,m=a.length;c<
m;c++)if(a[c].identifier==b)return a[c];return null}function f(a){this.identifier=a.pointerId;this.pageX=a.pageX;this.pageY=a.pageY;this.screenX=a.screenX;this.screenY=a.screenY}var p=0,n=0,B=0,m=0,C=!1,e=0,I=0,g=0,k=0,h=!1,l=!1,r=3,q=!1;Y&&(r*=3);this.delay=!1;var u=[],y=this;this.handlePointer=function(a){if(a.pointerType==a.MSPOINTER_TYPE_MOUSE||"mouse"==a.pointerType)switch(a.type){case "MSPointerDown":case "pointerdown":Da(a);break;case "pointermove":case "MSPointerMove":Ea(a);break;case "pointerup":case "MSPointerUp":Fa(a)}else a.touches=
a.changedTouches=[new f(a)],y.handle(a)};this.handle=function(b){var f=b.type,A=0,A=b.touches,y=b.changedTouches,v,z;switch(f){case "touchstart":case "MSPointerDown":case "pointerdown":moveSpace=moveCount=0;q=!1;n="touchstart"==f?A.length:n+1;l=!1;m=(new Date).getTime();C=1==n&&200>m-B;f=A[0];p=f.identifier;e=f.pageX;I=f.pageY;h=!0;2!=A.length?q=!1:(v=A[1].screenX-A[0].screenX,q=100<Math.abs(A[1].screenY-A[0].screenY)||350<Math.abs(v));(C||2<n)&&cancelDefault(b);if(3==n){for(var f=z=v=0,y=9999,J=
0,D=A.length;J<D;J++)A[J].screenY>f&&(f=A[J].screenY,v=J),A[J].screenY<y&&(y=A[J].screenY,z=J);u=[{screenX:A[z].screenX,screenY:A[z].screenY,identifier:A[z].identifier},{screenX:A[v].screenX,screenY:A[v].screenY,identifier:A[v].identifier}]}break;case "pointermove":case "MSPointerMove":if(1<n)break;case "touchmove":if(q)return;1==n&&t()&&(x.disableScoll||window.scrollTo(0,0),cancelDefault(b));f=y[A.length-1];if(f.identifier!=p&&(f=c(y,p),!f)){cancelDefault(b);return}v=f.pageX;z=f.pageY;if(h){if(0===
v-e&&0===z-I)return;if(Math.abs(v-e)<r&&Math.abs(z-I)<r){cancelDefault(b);return}h=!1;A=(new Date).getTime()-m;if((l=180>A)&&!t()&&1==n){q=!0;return}a.touchstart({x:e,y:I,flick:l,pointes:n,screenX:f.screenX,screenY:f.screenY,moved:!0,target:b.target})}cancelDefault(b);a.touchmove({x:v,y:z,flick:l,pointes:n,moved:!0,screenX:f.screenX,screenY:f.screenY,target:b.target});break;case "MSPointerUp":case "touchend":case "pointerup":if(q)return;if(3==y.length+A.length){a.touchend({x:v,y:z,flick:l,pointes:n,
moved:!h,target:b.target,gesture:d(A,y)});n=0;break}else{if(2<n){n=0;break}if(f=c(y,p))y=(new Date).getTime(),v=f.pageX,z=f.pageY,l?a.touchend({x:v,y:z,flick:!0,pointes:n,moved:!h,screenX:f.screenX,screenY:f.screenY,target:b.target}):(A=y-m,h?(B=y,C?cancelDefault(b):(g=v,k=z),500>A?(B=y,a.touchstart({x:g,y:k,flick:!1,pointes:n,screenX:f.screenX,screenY:f.screenY,moved:!1,target:b.target}),a.touchend({x:g,y:k,flick:!1,pointes:n,moved:!1,screenX:f.screenX,screenY:f.screenY,target:b.target})):a.longpress({x:v,
y:z,flick:!1,pointes:n,moved:!1,screenX:f.screenX,screenY:f.screenY,target:b.target})):a.touchend({x:v,y:z,flick:!1,pointes:n,moved:!0,screenX:f.screenX,screenY:f.screenY,target:b.target}))}n=0;break;case "MSPointerCancel":case "touchcancel":n=0}C&&cancelDefault(b)}}function Za(){l(!0,14);l(!1,14)}function Ya(a){try{a.select?a.select():hi5.browser.selectEditable(a)}catch(b){console.log(b)}}function $a(){function a(){f.focus()}function b(b,c){var d=document.createElement("a");d.href="#";d.accessKey=
b;d.onfocus=a;d.style.position="absolute";d.style.width=1;d.style.height=1;d.style.left=0;d.style.top=c+"px";return d}var d=hi5.browser.isIE,c=document.createElement(d?"textarea":"div"),f=this;this.setFontSize=function(a){c.style.fontSize=x.inputFontSize||a};d?(c.style.opacity=0,c.readOnly=D&&hi5.browser.isMetro?!0:!1):c.contentEditable=!D||hi5.browser.isChrome&&(hi5.browser.isWindows||hi5.browser.isCrOS)?!0:!1;c.accessKey="f";c.id="wsinput";c.tabIndex=1;c.style.opacity=0;c.style.resize="none";c.style.position=
"absolute";c.style.margin="0";c.style.border="none";c.style.outline="none";var p=hi5.tool.getPos(e,!0);c.style.left=p.x+"px";c.style.top=p.y+"px";c.style.paddingRight=0;c.style.paddingBottom=0;c.style.width="10px";c.style.height="10px";c.style.zIndex=88;c.style.cursor="default";c.style.fontWeight="normal";c.style.fonStyle="normal";c.style.overflow="hidden";F=new H(c);F.onbackspace=Za;p=e.parentNode;p.appendChild(c);Y&&(p.appendChild(b("E"),60),p.appendChild(b("V"),61),p.appendChild(b("A"),62),p.appendChild(b("T"),
63),p.appendChild(b("H"),64));var n=c.style.opacity,B=c.style.textIndent;this.resetCSS=function(){_fontSize=c.style.fontSize;n=c.style.opacity;c.style.opacity=0;c.style.textIndent=0};this.restoreCSS=function(){c.style.opacity=n;c.style.textIndent=B};this.getValue=function(){return d?c.value:c.innerHTML};this.setValue=function(a){F&&(F.disableTextInput=!0);d?c.value=a:c.innerHTML=a;F&&(F.disableTextInput=!1)};this.focus=function(){f.setValue(" ");v(c)};this.setContentEditable=function(a){d?(a="true"==
a,c.readOnly==a&&(c.readOnly=!a)):c.contentEditable!=a&&(c.contentEditable=a,"true"==a&&Y&&hi5.browser.selectEditable(c))};this.isIMEMode=!1;this.setIMEStatus=function(a){a?f.isIMEMode||(d&&(c.style.background="transparent",c.style.opacity=1),f.isIMEMode=!0):f.isIMEMode&&(d&&(c.style.background="",c.style.opacity=0),f.isIMEMode=!1)};this.adjust=function(a){var b=hi5.tool.getPos(e,!0),d=Math.round(.7*Math.min(window.innerWidth-b.x,O));a=Math.round(Math.min(window.innerHeight-b.y,M)*(a?.99:.7));var p=
(k.railWin?Math.min(window.innerWidth-b.x,O):O)-d,n=(k.railWin?Math.min(window.innerHeight-b.y,M):M)-a;x.disableAdjust&&(a=d=0,p=e.offsetWidth+"px",n=e.offsetHeight+"px");c.style.width=p+"px";c.style.height=n+"px";c.style.paddingLeft=d+"px";c.style.paddingTop=a+"px";c.style.left=b.x+"px";c.style.top=b.y+"px";c.style.textIndent=-(d+(Y?48:0))+"px";hi5.browser.isFirefox&&(c.style.fontSize=0);D&&hi5.browser.isChrome&&f.setFontSize("2em");x.disableScoll||window.scrollTo(0,0)};this.remove=function(){c.parentNode&&
c.parentNode.removeChild(c)};this.hide=function(){c.style.visibility="hidden"};this.getElement=function(){return c};this.select=function(){Ya(c)}}function Ga(){if(!g){var a=e.parentNode;g=a.querySelector('canvas[name="svImgCursor"]');g||(g=document.createElement("canvas"),g.name="svImgCursor",g.style.position="absolute",g.style.left=90,g.style.top=90,g.scrX=0,g.scrY=0,g.hotX=10,g.hotY=10,g.width=g.height=32,"ontouchstart"in window?(g.addEventListener("touchstart",P,!1),g.addEventListener("touchend",
P,!1),g.addEventListener("touchmove",P,!1),g.addEventListener("touchcancel",P,!1)):navigator.pointerEnabled?(g.addEventListener("pointerdown",P,!1),g.addEventListener("pointerup",P,!1),g.addEventListener("pointermove",P,!1),g.addEventListener("pointercancel",P,!1)):navigator.msPointerEnabled&&(g.addEventListener("MSPointerDown",P,!1),g.addEventListener("MSPointerUp",P,!1),g.addEventListener("MSPointerMove",P,!1),g.addEventListener("MSPointerCancel",P,!1)),g.setCursor=function(a){var d=a.width,c=a.height,
f=a.rawData,p=d*c,n=0,e=0;if(!(1>p)){g.hotX=a.hotX;g.hotY=a.hotY;g.width=d;g.height=c;a=g.getContext("2d");var m=a.createImageData(d,c),C=m.data;if(f){for(d=0;d<p;d++)n=f[d],C[e++]=n&255,C[e++]=n>>8&255,C[e++]=n>>16&255,C[e++]=n>>24&255;a.putImageData(m,0,0)}else a.fillStyle="rgba(0,0,0,0)",a.fillRect(0,0,d,c)}},Ha?g.setCursor(Ha):g.setCursor({rawData:[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,
-1,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-1,-1,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-1,-1,-1,-16777216,-16777216,-16777216,-16777216,-16777216,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-1,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-16777216,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-16777216,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-16777216,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,0,0,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-1,-1,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-16777216,-16777216,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],width:32,height:32}),a.appendChild(g))}}function ab(a){if(!1!==x.disableScrollbars){var b=document.body;a?(Ia=a,
b.style.overflow=a):(Ia=O<=window.innerWidth&&M<=window.innerHeight?"hidden":"visible",b.style.overflow=Ia)}}function oa(a){var b=e.parentNode,d=window.innerWidth,c=window.innerHeight;Math.max(O,M)<Math.max(d,c)&&Math.min(O,M)<Math.min(d,c)?1!=Q&&(hi5.tool.scale(b,1),Q=U=1):(document.body.style.overflow="hidden",Q=U=a?Math.min(window.innerWidth/O,window.innerHeight/M):1,hi5.tool.scale(b,Q,Q))}function bb(){var a=chrome.app.window.current();a&&a.fullscreen()}function Ja(a){a||(a="div");var b=document.createElement(a),
d=document.body;b.id="_tmpEditable";"div"==a&&(b.contentEditable=!0);b.style.position="absolute";b.style.zIndex=9999;b.style.left=d.scrollLeft+50+"px";b.style.top=d.scrollTop+50+"px";b.tabIndex=2;b.style.outline="none";b.style.opacity=0;d.appendChild(b);return b}function cb(a){Ka.clearPDF();k.focused=!0;r.onfocus(a);va=wa=!0;r.send("891");Z.sendMissKey();V&&u&&u.startPasteCmd()}function db(a){var b=__svi18n.remoteApp.close;if(!eb&&k.railWin&&k.railWin.isRunning()&&b&&(a||(a=window.event),2!=r.getAppMode()))return k.showMessage(b),
a&&(a.returnValue=b),b}function La(a){k.focused=!1;if(k.onunload)k.onunload()}function Ma(){h&&(h.getElement().oncontextmenu=function(){return!1},Y||(h.getElement().onselectstart=function(){return!1}))}function Na(){h&&(h.getElement().oncontextmenu=null,h.getElement().onselectstart=null)}function Fb(a){h&&h.adjust();if(ha)oa(!0);else if(!(ga&&2500>(new Date).getTime()-ga)){var b=hi5.browser.isWindows&&!hi5.browser.isMetro;if(!D||b)r.onresize(a)}}function Gb(){window.svSurface||(window.svSurface=k);
window.addEventListener("resize",Fb,!1);if(!W){var a=!hi5.browser.isChromeApp;a&&window.addEventListener("beforeunload",db,!1);a?window.addEventListener("unload",La,!1):chrome.runtime.onSuspend.addListener(La);Ma();window.addEventListener("focus",cb,!1);window.addEventListener("blur",function(a){k.focused=!1},!1);hi5.browser.isChromeApp&&chrome.app.window.current().onMaximized.addListener(bb);(a=hi5.$("saveSession"))&&a.addEventListener("change",function(a){r.saveSession({save:a.target.checked})})}}
function fb(){if(!N){var a=hi5.$("touchGesture");a&&(a.style.display="block");if(a=hi5.$("extKBD"))a.onchange=function(a){k.setExtKeyboard(a.target.checked)};N=hi5.$("svTouchInput");try{window.parent==window||N||(N=window.parent.document.getElementById("svTouchInput"))}catch(b){}N&&(hi5.browser.isWindows&&(a=document.createElement("div"),a.contentEditable=!0,a.id="svTouchInput",N.parentNode.replaceChild(a,N),N=a),hi5.browser.isChrome&&(N.style.fontSize="2em"),G=new H(N),G.onkeydown=G.onkeyup=gb,G.ontextinput=
hb,G.onbackspace=Za)}}function pa(a,b){function d(a,c){var d=document.createElement("span");d.data_path=a;d.className="path";d.innerHTML=c;d.onclick=function(){pa(this.data_path,b)};return d}function c(a){for(var b=f;b.hasChildNodes();)b.removeChild(b.firstChild);var c=d("/","&nbsp&nbsp&nbsp/");b.appendChild(c);if("/"!=a&&""!==a){a=a.split("/");for(var m="/",C=0,e=a.length;C<e;C++)c=a[C],""!==c&&(m=m+a[C]+"/",c=d(m,c+"/"),b.appendChild(c))}}var f=hi5.$("parentPath");f.currentDir||(f.currentDir="/");
"."==a?a=f.currentDir:f.currentDir=a;f.currentDir=a;r.getShareFiles(a,function(a){function d(b){b||(b=m.getValue("Name"));var c=a.parent;if(""===c||"/"!=c.charAt(c.length-1))c+="/";return c+b}a.error&&k.showMessage(__svi18n.file[a.error]);var f=new hi5.DataTable(a),m=new hi5.DataGrid(hi5.$("filelist"));m.dataTable=f;var C=hi5.tool.bytesToSize;m.beforeDisplayValue=function(a,b){var c=f.cols[a].name;return"Date Modified"==c?(new Date(b)).toLocaleString():"Size"==c?C(b):"Type"==c&&"folder"==b?__svi18n.file.folder:
"Name"==c?decodeURIComponent(b):b};m.onrowclick=function(c){var f=m.getValue("Name"),C=m.getValue("Type"),e=d(f);c=c.target.name;"delete"==c?(K.removeFile(e),pa(a.parent,b)):"folder"==C?pa(("/"==a.parent?"":a.parent)+"/"+f,b):("view"==c&&(e+="&action=view"),r.getFile(e))};m.beforeAppendRow=function(a){var b;if("folder"==f.getValue(f.getColNo("Type"))){if(b=a.querySelector('img[name="download"]'))b.style.visibility="hidden"}else{a.draggable=!0;b=m.getValue("Name");var c=d(b),c="application/octet-stream:"+
b+":"+r.getFileLink(c);a.addEventListener("dragstart",function(a){a.dataTransfer.setData("DownloadURL",c)},!1);if(10<b.length&&".uploading"==b.substring(b.length-10)){if(b=a.querySelector('img[name="download"]'))b.style.visibility="hidden";if(b=a.querySelector('img[name="view"]'))b.style.visibility="hidden"}}};m.open();c(a.parent);var e=document.getElementById("__diskSpace");e&&(e.innerHTML=hi5.tool.bytesToSize(a.freeSpace)+"/"+hi5.tool.bytesToSize(a.totalSpace));b.resize()})}function ib(a){a&&cancelDefault(a);
a=hi5.$("filecontainer");X=new hi5.Lightbox(a);pa(".",X);X.show()}function Oa(){var a=hi5.$("svToolbar");if(a){for(var b=a.childNodes,d=!1,c=0,f=b.length;c<f;c++)if(1==b[c].nodeType&&-1==["svTouchInput","svCloud","svInfo"].indexOf(b[c].id)){d=!0;break}b=hi5.$("appinfo");if(k.showToolbar&&(D||K||b||d)){if(d=null===k.toolbar)k.toolbar=new hi5.Toolbar(a);D?k.toolbar.activeObj=N:(a=hi5.$("svTouchInput"))&&a.parentNode.removeChild(a);if(a=k.toolbar.getButton("svCloud"))K?(a.style.display="",a.onclick=
ib):a.style.display="none";new hi5.Fadable(k.toolbar,x.toolbar.fadeDelay||5E3,h.getElement());a=x.toolbar.fadable;k.toolbar.setFadable(a);a&&(k.toolbar.style.display="none");if(a=k.toolbar.getButton("svInfo"))b?(a.style.display="",d&&(a.onclick=function(a){cancelDefault(a);a=r.getAppInfo();var b=hi5.$("numericId");b&&(b.innerHTML=a.numericId);if(b=hi5.$("connectingTo"))b.innerHTML=a.server;if(b=hi5.$("joinLink"))b.href=b.innerHTML=a.joinLink;a=new hi5.Lightbox(hi5.$("appinfo"));a.show();Na();a.onclose=
Ma})):a.style.display="none";if(k.onloadtoolbar)k.onloadtoolbar(k.toolbar)}}}function jb(a){K.addFiles(a.target.files);a=hi5.$("uploadfile");var b=a.cloneNode(!0);a.parentNode.replaceChild(b,a);b.addEventListener("change",jb,!1)}function Hb(){var a=h.getElement();K&&!W&&(svGlobal.util.initMapDisk(a,K),svGlobal.util.initMapDisk(hi5.$("filecontainer"),K),hi5.$("uploadfile").addEventListener("change",jb,!1))}function kb(a){a.target!=h.getElement()&&ia(lb,mb,a.button)}function Pa(a,b,d){g&&(a=g.scrX+
a,b=g.scrY+b,0>a?a=0:a>O&&(a=O-1),0>b?b=0:b>M&&(b=M-1),g.scrX=a,g.scrY=b,g.style.left=a-g.hotX+"px",g.style.top=b-g.hotY+"px",L&&!d&&r.sendInput("82"+a+"\t"+b))}function qa(a,b,d){g||Ga();Pa(a-g.scrX,b-g.scrY,d)}function Qa(a,b,d,c){var f;switch(a){case "touchstart":Ra=!1;0===g.scrX&&0===g.scrY&&qa(b-50,d-50);c&&r.sendInput("80"+g.scrX+"\t"+g.scrY+"\t0");break;case "touchmove":c=b-xa;a=d-ja;if(0===c&&0===a)return;f=5>Math.abs(nb)&&5>Math.abs(ob)&&(7<Math.abs(c)||7<Math.abs(a));f||(Pa(c,a),Ra=!0);
nb=c;ob=a;break;case "touchend":(a=!Ra&&!c)&&r.sendInput("80"+g.scrX+"\t"+g.scrY+"\t0"),(a||c)&&r.sendInput("81"+g.scrX+"\t"+g.scrY+"\t0")}xa=b;ja=d}function P(a){L&&("ontouchstart"in window?ra.handle(a):ra.handlePointer(a))}function gb(a){if(!L)return!1;Z.check(a);var b=aa.getKeyCode(a),d="keydown"==a.type;d&&h&&h.setIMEStatus(229==b);if(18==b&&(pb&&d&&(Sa=2==(a.location||a.keyLocation)),Sa))return!0;if(qb(a,b,d))return cancelDefault(a);17!=b||d||(sa=!1);var c=rb(b);if(0<c)return l(d,c),c=a.target==
h.getElement(),d&&ka&&h&&17==b&&(hi5.browser.isFirefox||hi5.browser.isSafari||Y&&!c)&&(c?(h.setValue("`\t`"),h.select()):(G.setValue("`\t`"),G.select())),cancelDefault(a);if(a.ctrlKey||a.altKey&&!Sa||a.metaKey)return(86!=b||!a.ctrlKey&&!a.metaKey||a.ctrlKey&&a.altKey||!V)&&T(d,b),d&&(ya=b),17==b||(a.ctrlKey||a.metaKey)&&(86==b||67==b||88==b)?(!d||67!=b&&88!=b||(sa=!0),!0):a.altKey&&!a.ctrlKey||a.ctrlKey&&!a.altKey?cancelDefault(a):!0;if(!(b!=ya||d||a.ctrlKey&&a.altKey))return T(!1,b),ya=0,!0;ya=0;
return!0}function qb(a,b,d){if(!a.altKey)return!1;switch(b){case 8:case 35:if(!a.ctrlKey&&!a.metaKey)return!1;l(d,211);break;case 33:l(d,15);break;case 34:d?(l(!0,42),l(!0,15)):(l(!1,15),l(!1,42));break;case 45:l(d,1);break;case 36:d?(l(!1,56),l(!0,29),l(!0,1)):(l(!1,1),l(!1,29));break;default:return!1}return!0}function Ib(a){if(va){var b=String.fromCharCode(a.charCode||a.keyCode||w.which);b.toUpperCase()!=b.toLowerCase()&&(b=b.toUpperCase()==b,a=a.shiftKey?!b:b,va=!1,la!=a&&(la=a,r.sendKeyboardSynchronize(!1,
ma,la),Z.preKeyCode&&(R(!0,14),R(!1,14),a=aa.getScancodeByKeyCode(Z.preKeyCode),R(!0,a),R(!1,a))))}}function Jb(a){if(!L)return!1;Z.check(a);var b=aa.getKeyCode(a),d="keydown"==a.type,c=Z.preKeyCode;d?h&&h.setIMEStatus(229==b):h&&h.isIMEMode&&Y&&h&&h.setIMEStatus(!1);if(qb(a,b,d))return cancelDefault(a);Z.preKeyCode=b;if(229==b||229==c&&!d)return!0;44==b?(l(!0,170),l(!0,183),c=!0):19==b?(d?(l(!0,225),l(!0,29),l(!0,69),l(!0,225),l(!0,157),l(!0,197)):l(!1,29),c=!0):c=!1;if(c)return cancelDefault(a);
(c=aa.getScancode(a))||(c=rb(b)||0);var f=86==b&&(sb&&!d||(a.ctrlKey||a.metaKey)&&!(a.ctrlKey&&a.altKey))&&V;0<c&&!f?l(d,c):f||T(d,b);17!=b&&(sb=f);return 17==b||(a.ctrlKey||a.metaKey)&&(86==b||67==b||88==b)?(d&&(17==b&&ka&&h&&(h.setValue("`\t`"),h.select()),67==b||88==b)&&(sa=!0),17!=b||d||(sa=!1),!0):144==b||16==b||va?!1:cancelDefault(a)}function hb(a){if(L&&(a=a.data,!(!D&&za&&1==a.length&&128>a.charCodeAt(0))&&"`\t`"!=a)){var b=ea||fa;b&&(a=a.toLowerCase());Y&&(a=a.replace(/\u00a0/g," "));r.sendInput("86"+
a+"\t"+(b||za?1:0));ba&&ba.resetModifier()}}function tb(){l(!0,29);T(!0,86);T(!1,86);l(!1,29)}function Kb(a){var b=0===a.types.length||a.equals(u.clipData),d=b?"":a.types.join(","),c=0,f=!0;b||((b=a.getData("text/html"))?(b=b.replace(/(<([^>]+)>)|\r?\n/gi,""),-1==d.indexOf("text/richtext")&&(d+=",text/richtext")):b=a.getData("text/plain"),b&&(c=b.hashCode()),r.send("880"+d+"\t"+c),u.clipData=a,k.onclipdata&&(f=!k.onclipdata(u.clipData)));f&&setTimeout(tb,500)}function R(a,b){if(k.onscancode){var d=
k.onscancode(a,b);if(d){for(var c=0,f=d.length;c<f;c++)r.sendInput("84"+(d[c].down?0:49152)+"\t"+d[c].key);return}}r.sendInput("84"+(a?0:49152)+"\t"+b)}function l(a,b){if(L){switch(b){case 221:if(a){R(!0,221);R(!1,221);return}break;case 58:if(a&&(la=!la,ub)){R(!0,58);R(!1,58);return}break;case 69:a&&(ma=!ma);break;default:70<b&&84>b&&!ma&&(ma=!0,r.sendKeyboardSynchronize(!1,ma,la))}184==b?(R(a,29),R(a,56)):(!a&&(hi5.browser.isCrOS&&61<b&&69>b||58==b&&ub||95==b)&&R(!0,b),95!=b&&R(a,b))}}function T(a,
b){L&&(111==b?a&&r.sendInput("86/\t1"):r.sendInput("8B"+(a?0:49152)+"\t"+b))}function ta(a,b,d,c,f){c||(c=Q);f||(f=U);Ta[d]||(Ta[d]=!0,r.sendInput("80"+a/c+"\t"+b/f+"\t"+d))}function Da(a){var b=a.target;v(b);if(!L)return!1;h&&h.setIMEStatus(!1);a.ctrlKey||a.shiftKey||a.metaKey||a.altKey||Z.sendMissKey();b=b.getBoundingClientRect();ta(a.pageX-b.left,a.pageY-b.top,a.button);return cancelDefault(a)}function Aa(a,b,d,c){d||(d=Q);c||(c=U);lb=a;mb=b;r.sendInput("82"+a/d+"\t"+b/c)}function Ea(a){if(!L)return!1;
var b=a.target;g&&"-30px"!=g.style.left&&(g.style.left="-30px");b=b.getBoundingClientRect();Aa(a.pageX-b.left,a.pageY-b.top);return cancelDefault(a)}function ia(a,b,d,c,f){c||(c=Q);f||(f=U);Ta[d]=!1;r.sendInput("81"+a/c+"\t"+b/f+"\t"+d);0==d&&vb&&hi5.browser.isChrome&&u.waitForCopyContent();vb=2==d}function Fa(a){if(!L)return!1;var b=a.target.getBoundingClientRect();ia(a.pageX-b.left,a.pageY-b.top,a.button);return cancelDefault(a)}function wb(a,b,d,c,f){c||(c=Q);f||(f=U);r.sendInput("83"+a/c+"\t"+
b/f+"\t"+d)}function xb(a,b,d){if(!L)return!1;wb(b,d,0>a?1:0);return!1}function rb(a){(a=Lb[a])||(a=-1);return a}function yb(a){return a.none?"none":a.url?"url("+a.url+"), pointer":0==a.data.indexOf("data:image/")?"url("+a.data+") "+a.hotX+" "+a.hotY+", default":a.data}e||(e=hi5.$("remotectrl"));if(window.svSurface&&svSurface.canvas==e&&svSurface.railWin)return svSurface.railWin.mainWin=null,window.svSurface;var D=hi5.browser.isTouch,Ua=!1,r=null,ha=!1,Q=1,U=1;e.style.outline="none";var O=0,M=0,S=
e.getContext("2d"),F=null,G=null,zb=!1,ea=!1,fa=!1,na=!1,eb=!1,wa=!0,K=null,V=!0,sa=!1,sb=!1;this.context=S;this.fileProgress=null;var k=this,L=!0,ca=!1,W=!1,za=!1,ua=null,X=null,g=null,Ha=null,ra=null,N=null,ga=0,xa=-1,ja=-1,nb=0,ob=0,Ra=!1,Ia=null,Ab=document.queryCommandSupported("copy"),lb=0,mb=0,va=!0,la=!1,ma=!1,Bb=0,Cb=0;this._cr=[82,69,77,79,84,69,83,80,65,82,75];window.svSurface=this;var x=hi5.appcfg||{img:{},toolbar:{fadable:!0}};this.setConfig=function(a){x=a};this.railWin=this.toolbar=
null;this.focused=!1;this.showToolbar=!0;this.canvas=e;this.mouseMoveEmu=this.alwaysPaste=!1;"visible"in x.toolbar&&(this.showToolbar=x.toolbar.visible);var Va=[],pb=!1,Sa=!1;this.getWindow=function(){return window};this.getScale=function(){return{x:Q,y:U}};var da=null,ba=null,Ba="",ka=!hi5.browser.isChromeApp&&!x.copyDialog,Y=hi5.browser.isIE;this.getThumbnail=function(a){a=a||64;da||(da=document.createElement("canvas"));var b=Math.floor(e.height/e.width*a);da.width!=a&&(da.width=a);da.height!=b&&
(da.height=b);da.getContext("2d").drawImage(e,0,0,e.width,e.height,0,0,a,b);return da.toDataURL()};this.initChat=function(a){var b=document.getElementById("chatWindow");hi5.Dragable(b);return new hi5.Chat(b,a)};this.equals=function(a){return e==a.canvas};this.getFreeSpace=function(){var a=hi5.tool.getPos(e);return{width:window.innerWidth-a.x,height:window.innerHeight-a.y}};var aa=new function(){var a=1033,b=hi5.browser.isFirefox,d=hi5.browser.isMacOS||hi5.browser.isiOS,c=[0],f=null;c[8]=14;c[9]=15;
c[12]=76;c[13]=28;c[16]=42;c[17]=29;c[18]=56;c[19]=197;c[20]=58;c[27]=1;c[33]=201;c[34]=209;c[35]=207;c[36]=199;c[37]=203;c[38]=200;c[39]=205;c[40]=208;c[44]=55;c[45]=210;c[46]=211;c[48]=11;c[49]=2;c[50]=3;c[51]=4;c[52]=5;c[53]=6;c[54]=7;c[55]=8;c[56]=9;c[57]=10;c[65]=30;c[66]=48;c[67]=46;c[68]=32;c[69]=18;c[70]=33;c[71]=34;c[72]=35;c[73]=23;c[74]=36;c[75]=37;c[76]=38;c[77]=50;c[78]=49;c[79]=24;c[80]=25;c[81]=16;c[82]=19;c[83]=31;c[84]=20;c[85]=22;c[86]=47;c[87]=17;c[88]=45;c[89]=21;c[90]=44;c[91]=
219;c[92]=220;c[93]=221;c[96]=82;c[97]=79;c[98]=80;c[99]=81;c[100]=75;c[101]=76;c[102]=77;c[103]=71;c[104]=72;c[105]=73;c[106]=55;c[107]=78;c[109]=74;c[110]=83;c[111]=181;c[112]=59;c[113]=60;c[114]=61;c[115]=62;c[116]=63;c[117]=64;c[118]=65;c[119]=66;c[120]=67;c[121]=68;c[122]=87;c[123]=88;c[144]=69;c[145]=70;c[154]=183;c[166]=59;c[167]=60;c[168]=61;c[173]=66;c[174]=67;c[175]=68;c[182]=63;c[183]=62;c[216]=64;c[217]=65;c[186]=39;c[187]=13;c[188]=51;c[189]=12;c[190]=52;c[191]=53;c[192]=41;c[219]=26;
c[220]=43;c[221]=27;c[222]=40;c[224]=29;c[225]=184;var p=function(a){a=a.keyCode;if(b)switch(a){case 173:return 189;case 61:return 187;case 59:return 186;case 224:return 17}return a},n=d?function(a){switch(a){case 91:case 93:return 17;case 17:return 91;case 229:return 69}return 0}:null;this.setLayout=function(b){a=b;var d=null,p="K"+b;p in e&&(d=e[p]());null===d&&(1033==b||0>b||3758096384<b)&&(d=c);f=d;null!==f&&svGlobal.logger.info("Keyboard layout: "+a)};this.getKeyCode=function(a){var b=0;n&&(b=
n(a.keyCode));b||(b=p?p(a):a.keyCode);return b};this.getScancode=function(a){a=aa.getKeyCode(a);return f?f[a]:0};this.getScancodeByKeyCode=function(a){return f?f[a]:0};this.getLayoutCreator=function(){return e};var e=new function(){this.K3758162961=function(){var a=c.slice(0);a[244]=41;a[243]=41;a[189]=12;a[222]=13;a[220]=125;a[192]=26;a[219]=27;a[187]=39;a[186]=40;a[221]=43;a[188]=51;a[190]=52;a[191]=53;a[226]=115;a[29]=123;a[28]=121;a[240]=112;a[242]=112;b&&(a[173]=12,a[160]=13,a[64]=26,a[59]=39,
a[58]=40,p=function(a){return 220==a.keyCode&&"_"==a.key?226:a.keyCode});return a};this.K1034=this.K66570=this.K2058=this.K1040=this.K66576=function(){var a=c.slice(0);a[220]=41;a[219]=12;a[221]=13;a[186]=26;a[187]=27;a[191]=43;a[192]=39;a[189]=53;a[226]=86;b&&(a[171]=27,a[173]=53,p=function(a){var b=a.keyCode,c=a.key;if(0===b){if("\u00ba"==c||"\u00aa"==c&&a.shiftKey||"\\"==c&&a.ctrlKey&&a.altKey)return 220;if("\u00a1"==c||"\u00bf"==c&&a.shiftKey)return 221;if("\u00e7"==c||"\u00c7"==c&&a.shiftKey||
"}"==c&&a.ctrlKey&&a.altKey)return 191;if("\u00f1"==c||"\u00d1"==c&&a.shiftKey)return 192;if("DeadAcute"==c||"\u00b4\u00b4"==c||"\u00b4"==c||"DeadUmlaut"==c&&a.shiftKey||"{"==c&&a.ctrlKey&&a.altKey)return 222}else{if(192==b)return 186;if(222==b)return 219}return b});return a};this.K2057=function(){var a=c.slice(0);a[223]=41;a[222]=43;a[192]=40;a[220]=86;b&&(a[192]=41,a[173]=12,a[61]=13,a[59]=39,a[222]=40,a[163]=43);return a};this.K1031=this.K4106=this.K5130=this.K6154=this.K7178=this.K8202=this.K9226=
this.K10250=this.K11274=this.K12298=this.K13322=this.K14346=this.K15370=this.K16395=this.K17418=this.K18442=this.K19466=this.K20490=this.K99997=this.K66567=this.K2952791047=function(){var a=c.slice(0);a[220]=41;a[219]=12;a[221]=13;a[186]=26;a[187]=27;a[191]=43;a[192]=39;a[189]=53;a[226]=86;a[90]=21;a[89]=44;b&&(p=function(a){var b=a.keyCode,c=a.key;switch(b){case 60:return 226;case 160:return 220;case 63:return 219;case 192:return 221;case 171:return 187;case 163:return 191;case 173:return 189;case 0:if("\u00f6"==
c||"\u00d6"==c&&a.shiftKey)return 192;if("\u00e4"==c||"\u00c4"==c&&a.shiftKey)return 222;if("\u00fc"==c||"\u00dc"==c&&a.shiftKey)return 186}return b});return a};this.K2060=this.K99998=function(){var a=c.slice(0);a[222]=41;a[219]=12;a[189]=13;a[221]=26;a[186]=27;a[77]=39;a[192]=40;a[188]=50;a[190]=51;a[191]=52;a[187]=53;a[226]=86;a[65]=16;a[90]=17;a[81]=30;a[87]=44;b&&(p=function(a){var b=a.keyCode,c=a.key;switch(b){case 60:return 226;case 169:return 219;case 173:return 189;case 160:return 221;case 164:return 186;
case 165:return 192;case 59:return 190;case 58:return 191;case 61:return 187;case 0:if("\u00b2"==c||"\u00b3"==c&&a.shiftKey)return 222;if("\u00b5"==c||"`\u00b5"==c||"DeadGrave"==c||"\u00a3"==c&&a.shiftKey||("`"==c||"``"==c)&&a.ctrlKey&&a.altKey)return 220}return b});return a};this.K3084=this.K4105=function(){var a=c.slice(0);a[222]=41;a[192]=40;a[226]=86;b&&(p=function(a){var b=a.keyCode,c=a.key;switch(b){case 0:if("\u00b0"==c||"\u00ac"==c&&a.ctrlKey&&a.altKey)return 222;if("\u00e7"==c||"\u00c7"==
c&&a.shiftKey)return 221;if("\u00e0"==c||"DeadGrave"==c||"\u00c0"==c&&a.shiftKey)return 220;if("\u00e8"==c||"\u00c8"==c&&a.shiftKey)return 192;if("\u00e9"==c||"\u00c9"==c&&a.shiftKey)return 191;if("\u00f9"==c||"\u00d9"==c&&a.shiftKey)return 226;if("DeadTilde"==c)return 221;break;case 173:return 189;case 61:return 187;case 160:return 219;case 59:return 186}return b});return a};this.K1036=function(){var a=c.slice(0);a[222]=41;a[219]=12;a[187]=13;a[221]=26;a[186]=27;a[220]=43;a[77]=39;a[192]=40;a[190]=
51;a[191]=52;a[223]=53;a[226]=86;a[65]=16;a[90]=17;a[81]=30;a[87]=44;a[188]=50;b&&(p=function(a){var b=a.keyCode,c=a.key;switch(b){case 0:if("\u00b2"==c)return 222;if("\u00e7"==c||"\u00c7"==c&&a.shiftKey)return 221;if("\u00e0"==c||"\u00c0"==c&&a.shiftKey)return 220;if("\u00e8"==c||"\u00c8"==c&&a.shiftKey)return 192;if("\u00e9"==c||"\u00c9"==c&&a.shiftKey)return 189;if("\u00f9"==c||"\u00d9"==c&&a.shiftKey)return 226;if("DeadTilde"==c)return 221;break;case 60:return 226;case 169:return 219;case 61:return 187;
case 160:return 221;case 164:return 186;case 170:return 220;case 165:return 192;case 59:return 190;case 58:return 191;case 161:return 223}return b});return a};this.K4108=this.K2055=function(){var a=c.slice(0);a[191]=41;a[219]=12;a[221]=13;a[186]=26;a[192]=27;a[223]=43;a[222]=39;a[220]=40;a[188]=51;a[190]=52;a[189]=53;a[226]=86;a[90]=21;a[89]=44;b&&(p=function(a){var c=a.keyCode,b=a.key;switch(c){case 0:if("\u00a7"==b||"\u00b0"==b&&a.shiftKey)return 191;if("\u00e0"==b||"\u00e4"==b&&a.shiftKey||"{"==
b&&a.ctrlKey&&a.altKey)return 220;if("\u00e8"==b||"\u00fc"==b&&a.shiftKey||"["==b&&a.ctrlKey&&a.altKey)return 186;if("\u00e9"==b||"\u00f6"==b&&a.shiftKey)return 222;break;case 222:return 219;case 160:return 221;case 161:return 192;case 164:return 223;case 173:return 189;case 60:return 226}return c});return a};this.K1044=this.K1083=function(){var a=c.slice(0);a[220]=41;a[187]=12;a[219]=13;a[221]=26;a[186]=27;a[191]=43;a[192]=39;a[222]=40;a[189]=53;a[226]=86;b&&(p=function(a){var b=a.keyCode,c=a.key;
switch(b){case 0:if("\u00e5"==c||"\u00c5"==c&&a.shiftKey)return 221;if("\u00f8"==c||"\u00d8"==c&&a.shiftKey||"\u00f6"==c&&a.ctrlKey&&a.altKey)return 192;if("\u00e6"==c||"\u00c6"==c&&a.shiftKey||"\u00e4"==c&&a.ctrlKey&&a.altKey)return 222;break;case 172:return 220;case 171:return 187;case 220:return 219;case 160:return 186;case 222:return 191;case 173:return 189;case 60:return 226}return b});return a};this.K1053=function(){var a=c.slice(0);a[220]=41;a[187]=12;a[219]=13;a[221]=26;a[186]=27;a[191]=43;
a[192]=39;a[222]=40;a[189]=53;a[226]=86;b&&(p=function(a){var c=a.keyCode,b=a.key;switch(c){case 0:if("\u00a7"==b||"\u00bd"==b&&a.shiftKey)return 220;if("\u00e5"==b||"\u00c5"==b&&a.shiftKey)return 221;if("\u00f8"==b||"\u00d8"==b&&a.shiftKey||"\u00f6"==b&&a.ctrlKey&&a.altKey)return 192;if("\u00e4"==b||"\u00c4"==b&&a.shiftKey)return 222;break;case 171:return 187;case 192:return 219;case 160:return 186;case 222:return 191;case 173:return 189;case 60:return 226}return c});return a};this.K1055=function(){var a=
c.slice(0);a[220]=52;a[223]=12;a[189]=13;a[191]=51;a[188]=43;a[190]=53;a[226]=86;b&&(p=function(a){var b=a.keyCode,c=a.key;switch(b){case 0:if("\u011f"==c||"\u011e"==c&&a.shiftKey||a.ctrlKey&&a.altKey&&"BracketLeft"==a.code)return 219;if("\u00fc"==c||"\u00dc"==c&&a.shiftKey||a.ctrlKey&&a.altKey&&"BracketRight"==a.code)return 221;if("\u015f"==c||"\u015e"==c&&a.shiftKey||a.ctrlKey&&a.altKey&&"Semicolon"==a.code)return 186;if("\u00f6"==c||"\u00d6"==c&&a.shiftKey)return 191;if("\u00e7"==c||"\u00c7"==
c&&a.shiftKey)return 220;break;case 73:return 222;case 60:return 226;case 173:return 189;case 170:return 223;case 162:return 192}return b});return a}}};this.getKeyboardMgr=function(){return aa};var u=new function(){function a(a,c){var b=d.parseClipData(c),e=!1;"text/plain"==b.type&&(e=window.clipboardData?window.clipboardData.setData("Text",b.value)||!0:a.clipboardData.setData("text/plain",b.value)||!0,a.preventDefault());e||(hi5.browser.isIE?(e=Ja("div"),e.innerHTML=b.value,hi5.browser.selectEditable(e)):
(h.resetCSS(),h.setValue(b.value),h.select()));return b}function b(){u.copyContent&&(u.copyToClipboard("text/plain"==u.copyContent.type?"textarea":"div",u.copyContent.value),u.copyContent=null);u.waitingCopyContent=!1}var d=this;this.clipData=null;this.paste=function(a,b,c){var d=new q,e=0,e=window.clipboardData||b.clipboardData;c=null;var g=e.getData(window.clipboardData?"Text":"text/plain");if(g)d.setData("text/plain",g);else if(e)if(g=e.items)for(e=0,len=g.length;e<len;e++){if("image/png"==g[e].type){c=
g[e].getAsFile();break}}else if(e.files)for(g=e.files,e=0,len=g.length;e<len;e++)if(-1!=g[e].type.indexOf("image/png")){c=g[e];break}if(c)e=new FileReader,b.preventDefault(),e.onloadend=function(b){b.target.readyState==FileReader.DONE&&(b=hi5.Base64.enc(new Uint8Array(b.target.result)),d.setData("image/png",b),a(d))},e.readAsArrayBuffer(c);else{var k=b.target.innerHTML;F&&(F.disableTextInput=!0);G&&(G.disableTextInput=!0);var h=b.target.style.opacity;b.target.style.opacity=0;setTimeout(function(){var c=
b.target.innerHTML;if(c&&c!=k){var e=b.target.childNodes;-1<c.search(/<.*(font|color|img|table|style|class).*>/gmi)?1==e.length&&"IMG"==e[0].nodeName&&0===e[0].src.indexOf("data:image/png;base64,")?d.setData("image/png",e[0].src.substring(22)):d.setData("text/html",c):0===d.types.length&&d.setData("text/plain",c);b.target.innerHTML="";F&&F.init()}a(d);b.target.style.opacity=h;F&&(F.disableTextInput=!1);G&&(G.disableTextInput=!1)},300)}};var c=0;this.onCopy=function(b){L&&V||cancelDefault(b);if(!sa){l(!0,
29);var e="copy"==b.type?"67":88;T(!0,e);T(!1,e);l(!1,29)}if(zb){var e=(new Date).getTime(),n=e-c;c=e;if(500<n)return}if(!hi5.browser.isChromeApp){Ba=r.getClipData();if(h){var g=a(b,Ba);setTimeout(function(){var a=document.getElementById("_tmpEditable");a?a.parentNode.removeChild(a):(h.setValue(""),G&&G.setValue(""),"text/html"==g.type&&h.restoreCSS());0<Ba.indexOf("data-sv-img")&&Wa.open(g.value,__svi18n.info.copy)},555)}d.clipData=null;wa=!1}};this.onPaste=function(a){if(!L||!V)return cancelDefault(a);
if(!k.alwaysPaste&&!wa)return setTimeout(tb,500),cancelDefault(a);wa=!1;d.paste(Kb,a,null);return!0};this.parseClipData=function(a){var b=0===a.indexOf("text/plain;"),c=0===a.indexOf("text/html;"),d=c?"text/html":"text/plain",b=b?11:c?10:0;0<b&&(a=a.substring(b));return{type:d,value:a}};this.getContent=function(){var a=Ja("div");a.focus();try{document.execCommand("paste");var b=a.innerHTML,c=new q;c.setData("text/html",b);c.setData("text/plain",a.innerText||b.replace(/<br>/gi,"\n").replace(/&nbsp;/gi,
" ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&lt;/gi,"<").replace(/&gt;/gi,">"));c.equals(u.clipData)||(u.clipData=c,r.send("880text/plain,text/html\t0"))}finally{a.parentNode.removeChild(a),h&&(h.getElement().removeEventListener("click",u.getContent),h.focus())}};this.startPasteCmd=function(){h&&document.queryCommandSupported("paste")&&h.getElement().addEventListener("click",u.getContent)};this.waitingCopyContent=!1;this.copyContent=null;this.waitForCopyContent=function(){u.waitingCopyContent=
!0;setTimeout(b,700)};this.copyToClipboard=function(a,b){var c=Ja(a),d=!1;"div"==a?(c.innerHTML=b,hi5.browser.selectEditable(c)):(c.value=b,c.select());try{d=document.execCommand("copy",!1,null)}catch(e){}finally{c.parentNode.removeChild(c),h&&h.focus()}if(d)return d;Wa.open(b,__svi18n.info.copy,a)}},ub=hi5.browser.isMacOS||hi5.browser.isiOS,Z=new function(){this.altUp=this.shiftUp=this.winUp=this.ctrlUp=!0;this.preKeyCode=0;var a=this;this.sendMissKey=function(){a.shiftUp||(l(!1,42),a.shiftUp=!0);
a.altUp||(l(!1,56),l(!0,56),l(!1,56),a.altUp=!0);a.ctrlUp||(l(!1,29),a.ctrlUp=!0);a.winUp||(l(!1,219),a.winUp=!0)};this.check=function(b){var d=aa.getKeyCode(b),c="keydown"==b.type;switch(d){case 16:!c||!a.shiftUp||b.altKey||b.ctrlKey||b.metaKey||a.sendMissKey();a.shiftUp=!c;break;case 17:c&&a.ctrlUp&&!b.altKey&&!b.shiftKey&&a.sendMissKey();a.ctrlUp=!c;break;case 18:!c||!a.altUp||b.shiftKey||b.ctrlKey||b.metaKey||a.sendMissKey();a.altUp=!c;break;case 91:case 92:!c||!a.winUp||b.shiftKey||b.ctrlKey||
b.metaKey||b.altKey||a.sendMissKey();a.winUp=!c;break;default:!c||b.ctrlKey||b.altKey||b.shiftKey||b.metaKey||a.sendMissKey()}}};this.requestCredential=function(a){Ua=!1;var b=__svi18n.template.login;if(b){var d=document.createElement("div");d.className="appdlg";d.innerHTML=b;document.body.appendChild(d);(b=hi5.$("loginDomain"))&&a.nbDomain&&(b.innerHTML=a.nbDomain);var c=new hi5.Lightbox(d,.9);c.onclose=function(){document.body.removeChild(d)};try{k.close()}catch(f){}c.show();(b=hi5.$("loginUser"))&&
b.focus();if(b=hi5.$("frmLogin"))b.onsubmit=function(){var a=hi5.$("loginUser").value,b=hi5.$("loginPassword").value,d=hi5.$("loginDomain").innerHTML;c.dismiss();setTimeout(function(){r.reconnect(a,b,d)},5);return!1}}else k.showMessage("No value for login template")};var h=null;if(D)fb();else{var Xa=hi5.$("tmContainer");Xa&&Xa.parentNode.removeChild(Xa)}h=new $a;D&&hi5.browser.isSafari&&window.addEventListener("scroll",function(){setTimeout(function(){var a=hi5.$("pc_key");a&&(a.style.top=window.pageYOffset+
"px");k.toolbar&&(k.toolbar.style.top=window.pageYOffset+"px")},200)},!1);this.setCaretPos=function(a,b){};this.showMessage=function(a,b){a&&x.displayMsg&&hi5.notifications.notify({msg:a,timeout:b||0})};this.hideWhenClose="hideWhenClose"in x?x.hideWhenClose:!0;this.setReadOnly=function(a){L=!a};this.setPlayerMode=function(){W=!0;k.showToolbar=!1;k.setReadOnly(!0);k.hideWhenClose=!1};this.setAutoScale=function(a){var b="autoScale"in x;b&&(a=x.autoScale);a?(oa(!0),ab("hidden")):b||oa(!1);ha=a};this.setTouchpad=
function(a){ca=a;var b=hi5.$("touchpadMode");b&&(b.checked=a,b.onchange=function(a){ca=a.target.checked});a?g||Ga():g&&g.parentNode&&(g.parentNode.removeChild(g),g=null)};this.setExtKeyboard=function(a){if(D){h.adjust(!0);h.setContentEditable(a?"true":"false");ga=a?1:0;hi5.browser.isChrome&&h.setFontSize("2em");a&&h.focus();var b=hi5.$("extKBD");b&&b.checked!=a&&(b.checked=a)}};this.focus=function(){h&&v(h.getElement())};this.getInputElement=function(){return h};this.scaleTo=function(a,b,d){a/=O;
b/=M;d?(Q=a,U=b):U=Q=b=a=Math.min(a,b);hi5.tool.scale(e.parentNode,a,b)};this.setSize=function(a,b,d){O=a;M=b;ha||ab(d);e.width=O;e.height=M;ha&&oa(!0);D&&fb();h||(h=new $a);h.adjust();X&&X.visible()&&X.dismiss()};this.reposition=function(){h.adjust()};this.setController=function(a){r=a;r.sendInput||(r.sendInput=r.send);D&&hi5.browser.setOrientaionHandler(function(){ha?oa(!0):setTimeout(function(){r.onorientationchange({svSurface:k,innerWidth:window.innerWidth,innerHeight:window.innerHeight});x.disableScoll||
window.scrollTo(0,0)},300)})};this.setFileHandler=function(a){"FileReader"in window||(a=null);if(a){if(!K&&!W&&hi5.$("filecontainer")){K=a;k.fileProgress=new hi5.ProgressBar(hi5.$("total"));Oa();Hb();var b=document.getElementById("__cancelUpload");b&&b.addEventListener("click",function(){K.cancelAll()},!1);K.addEvent("beforeupload",function(a,c){b&&(b.style.visibility="visible");k.fileProgress.style.display="block";k.fileProgress.maxValue+=a.size});K.addEvent("uploaded",function(){b&&(b.style.visibility=
"hidden");k.fileProgress.maxValue=0;k.fileProgress.style.display="none";k.showMessage(__svi18n.file.uploadDone,5E3);k.refreshFiles()});K.addEvent("progress",function(a){k.fileProgress.setProgress(a)})}}else K=null,k.fileProgress=null,k.toolbar&&k.toolbar.removeButton("svCloud"),Oa()};this.setFeature=function(a){var b;!W&&a&16?a&128&&(b=hi5.$("uploadfile"))&&(b.style.visibility="hidden"):k.setFileHandler(null);a&256||(b=hi5.$("shadowing"))&&b.parentNode.removeChild(b);a&1024||(b=hi5.$("ssParent"))&&
b.parentNode.removeChild(b)};var Ka=new function(){function a(){if(0===d.length){c=!1;var a=hi5.$("_sv_pdf_parent");a&&a.visible&&a.visible()&&a.dismiss&&a.dismiss();a&&a.parentNode&&(a.parentNode.removeChild(a),console.log("pdf removed"))}else b()}function b(){var b=d.shift();if(b){var e=hi5.$("_sv_pdf_parent"),g=__svi18n.info.printready||"Your document is ready.",g=D||x.showPDFLink?'<p style="text-align:center;line-height:4em"><a href="'+b+'" target="_blank">'+g+"</a></p>":(hi5.browser.isChromeApp?
"<webview":"<iframe")+' src="'+b+'" width="100%" height="100%" id="_iFramePDF">'+(hi5.browser.isChromeApp?"</webview>":"</iframe>");if(e){var k=hi5.$("_iFramePDF");k?k.src=b:e.innerHTML+=g}else e=document.createElement("div"),e.style.backgroundColor="white",e.style.width=D?"30%":"90%",e.style.height=D?"4elm":"85%",e.id="_sv_pdf_parent",e.innerHTML=g,document.body.appendChild(e),b=new hi5.Lightbox(e),b.onclose=a,b.show()}c=!0}var d=[],c=!1;this.clearPDF=function(){a()};this.showPDF=function(a){d.push(a);
c||b()}};this.close=function(){La();Ka.clearPDF();ha&&k.setAutoScale(!1);ba&&ba.setVisibility(!1);for(var a=0,b=Va.length;a<b;a++)Va[a]();try{K=null;k.fileProgress=null;window.svSurface=null;g&&g.parentNode&&(g.parentNode.removeChild(g),g=null);eb=!0;if(!window||W)return;if(0<hi5.notifications.notifySize()){hi5.notifications.onempty=function(){k.close();hi5.notifications.onempty=null};return}if(Ua)window.close();else if(this.hide(),hi5.browser.isChromeApp){var d=chrome.app.window.current();d&&(d.onMaximized.removeListener(bb),
d.isFullscreen()&&(d.restore(),d.restore()))}}catch(c){}"clearScreen"in x&&!x.clearScreen||S.fillRect(0,0,e.width,e.height)};this.setFastCopy=function(a){zb=a};this.drawLicense=function(a){if(0!=x.drawLicense){var b=a.charAt(0);S.font="12pt Arial";S.fillStyle="W"==b?"red":"black";a=a.substring(1);S.fillText(a,10,M-24)}};this.drawText=function(a){var b=x.text||{};if(b.backgroundFillStyle){var d=e.width,c=e.height;S.fillStyle=b.backgroundFillStyle;S.fillRect(0,0,d,c)}var f=20,g=50;"center"==b.textAlign&&
(f=d/2,g=c/2);S.font=b.font||"18pt Arial";S.fillStyle=b.fillStyle||"black";b.textAlign&&(S.textAlign=b.textAlign);b.textBaseline&&(S.textBaseline=b.textBaseline);S.fillText(a,f,g)};this.showPDF=function(a){Ka.showPDF(a)};this.hide=function(){k.hideWhenClose&&(e.height=1,e.width=1);h&&h.hide()};var Ca=0,Db=!1,Wa=new function(){var a=null,b=null;this.createDialog=function(d,c,f){var e=document.createElement("div");e.className="copyDialog";var g=document.createElement("div");g.innerHTML=c;g.className=
"hi5_notifer_title";e.appendChild(g);c=document.createElement(f);"div"==f?c.innerHTML=d:c.value=d;c.style.border="1px solid #666";c.style.width="100%";c.style.minHeight="80px";e.appendChild(c);a=c;Ab&&(b=document.createElement("input"),b.className="btnCopy",b.type="button",b.value=__svi18n.info.copylable||"Copy",b.onclick=function(){"div"==f?hi5.browser.selectEditable(a):a.select();document.execCommand("copy")},e.appendChild(b));if(0<d.indexOf('data-sv-img="wmf"')&&(c=d.indexOf('src="')+5,g=d.indexOf('"',
c),g>c&&0<c)){var k=document.createElement("a");k.href=d.substring(c,g);k.target="_blank";k.innerHTML="Download image";e.appendChild(k)}return e};this.open=function(d,c,f){function e(){var g=Wa.createDialog(d,c,f);document.body.appendChild(g);var h=new hi5.Lightbox(g);h.show();a&&0!==d.indexOf("<img ")&&("div"==f?hi5.browser.selectEditable(a):a.select());Na();h.onclose=function(){Ma();g&&g.parentNode&&g.parentNode.removeChild(g);k.toolbar&&k.toolbar.removeButton("_svClipInfo")};document.queryCommandEnabled("copy")||
g.removeChild(b)}f||(f="div");if(x.clipWarnAlways||!Db)k.showMessage(__svi18n.info.copyWarning,5E3),Db=!0;clearTimeout(Ca);var g=k.toolbar;if(g){var h=g.getButton("_svClipInfo");h?h.onclick=e:(h=g.addButton(x.img.copy?x.img.copy:"copy.png",e),h.id="_svClipInfo",h.className="pulse");g.startFade();Ca=setTimeout(function(){k.toolbar.removeButton("_svClipInfo")},3E4)}}};this.copyToClip=function(a,b){var d=u.parseClipData(a);u.waitingCopyContent?u.copyContent=d:setTimeout(function(){if(!(!V||ka&&Ba==a||
N)){a=d.value;var b=0<a.indexOf("<img ")||x.copyDialog,e="text/plain"==d.type?"textarea":"div";b&&!Ab||u.copyToClipboard(e,a)}},50)};this.fullScreen=function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)};Va.push(function(){if(window){window.removeEventListener("beforeunload",db,!1);window.removeEventListener("focus",cb,!1);window.onresize=null;try{ua&&ua.parentNode&&(ua.parentNode.removeChild(ua),ua=null),h&&h.remove(),h=null}catch(b){}}if(document){Na();document.body.style.overflow=
"";var a=window;try{for(;;){a.document.removeEventListener("mouseup",kb,!1);if(a.parent==a)break;a=a.parent}}catch(b){}}});var ba=new function(){function a(a){ga=(new Date).getTime();if(a=hi5.$("pc_key"))a.style.display="block",a.style.top=window.pageYOffset+"px",G&&(G.setValue("`\t`"),G.select())}function b(a){ga=0;if(a=hi5.$("pc_key"))a=hi5.$("shortcuts"),a&&a.checked||(m.style.display="none")}function d(){e&&(ea?hi5.html.addClass(e,"button_selected"):hi5.html.removeClass(e,"button_selected"));
g&&(fa?hi5.html.addClass(g,"button_selected"):hi5.html.removeClass(g,"button_selected"));h&&(na?hi5.html.addClass(h,"button_selected"):hi5.html.removeClass(h,"button_selected"))}function c(a){cancelDefault(a);a=a.target;var b=a.innerHTML,b=b.replace(/\u2190/g,"left").replace(/\u2191/g,"up").replace(/\u2192/g,"right").replace(/\u2193/g,"down");switch(b){case "Ctrl":e||(e=a);ea?l(!1,29):l(!0,29);ea=!ea;d();break;case "Alt":g||(g=a);fa?l(!1,56):l(!0,56);fa=!fa;d();break;case "Shift":h||(h=a);na?l(!1,
42):l(!0,42);na=!na;d();break;case "...":if(a=hi5.$("pc_key_more"))a.style.display="block"==a.style.display?"none":"block";break;case "Start":b="Ctrl+Esc";default:k.writeKeyComb(b),t.resetModifier()}}var e=null,g=null,h=null,t=this;this.setVisibility=function(c){c?a():b()};this.resetModifier=function(){fa&&(fa=!1,l(!1,56));ea&&(ea=!1,l(!1,29));na&&(na=!1,l(!1,42));d()};hi5.$("svTouchInput")&&(hi5.$("svTouchInput").addEventListener("focus",a,!1),hi5.$("svTouchInput").addEventListener("blur",b,!1));
var m=hi5.$("pc_key");if(m){var r=m.getElementsByTagName("span"),q=r.length,u=hi5.browser.isFirefox?"mousedown":"touchstart";"ontouchstart"in window||(navigator.pointerEnabled?u="pointerdown":navigator.msPointerEnabled&&(u="MSPointerDown"));for(var y=0;y<q;y++){var v=r[y];v.className="button";v.addEventListener(u,c,!1);"mousedown"!=u&&v.addEventListener("mousedown",c,!1)}m.style.position="absolute"}},Eb=hi5.$("shortcuts");Eb&&Eb.addEventListener("change",function(a){ba.setVisibility(a.target.checked)});
this.setKeysVisibility=function(a){ba&&ba.setVisibility(a)};this.refreshFiles=function(){X&&X.visible()?pa(".",X):ib(null)};this.processLink=function(a){function b(b){window.open(a);b.target.parentNode.removeChild(b.target)}clearTimeout(Ca);var d=k.toolbar,c=d.getButton("_svLinkInfo");c?c.onclick=b:(c=d.addButton(x.img.link?x.img.link:"link.png",b),c.id="_svLinkInfo",c.className="pulse");c.title=a;d.startFade();Ca=setTimeout(function(){k.toolbar.removeButton("_svLinkInfo")},1E4)};this.setUnicode=
function(a){h&&(!a&&D&&(hi5.browser.isiOS||hi5.browser.isChrome&&!hi5.browser.isWindows)&&(a=!0),za=!a,svGlobal.logger.info("Unicode:"+a),F.onkeydown=F.onkeyup=a?gb:Jb,F.onkeypress=Ib,F.ontextinput=hb)};this.setTouchRemoting=function(a){!0===a?(ra=new z(k,e),svGlobal.logger.info("touch remoting"),k.showMessage(__svi18n.info.touchremoting)):ra=new J(k)};this.setClipboard=function(a){(V=a)||(ka=!1)};this.setJoinMode=function(a){r.setJoinMode(a)};this.requestControl=function(){r.requestControl()};this.run=
function(a){hi5.notifications.clearAll();3758162961!=a&&3758162962!=a||!h||h.setContentEditable("false");aa.setLayout(a);var b=-1!=[99997,99998,99999].indexOf(a);za=!b;pb=(b||-1==[1033,3758162961,3758162962,1049].indexOf(a))&&hi5.browser.isMacOS;Ua="boolean"==typeof x.closeOnDisconn?x.closeOnDisconn:!!window.opener&&!hi5.browser.isChromeApp;x.disableScoll||window.scrollTo(0,0);Oa();Gb();a=h.getElement();if(D){if(!W){ra=new J(k);var d=new y(a);d.ontouch=P;d.onmousedown=Da;d.onmousemove=Ea;d.onmouseup=
Fa;E(a,xb,!1);document.addEventListener("paste",u.onPaste,!1);V&&ka&&(document.addEventListener("copy",u.onCopy,!1),document.addEventListener("cut",u.onCopy,!1))}}else W||(a.addEventListener("mousemove",Ea,!1),a.addEventListener("mousedown",Da,!1),a.addEventListener("mouseup",Fa,!1),E(a,xb,!1),a.addEventListener("paste",u.onPaste,!1),V&&ka&&(a.addEventListener("copy",u.onCopy,!1),a.addEventListener("cut",u.onCopy,!1))),v(a);h.adjust();k.setUnicode(b);b=window;try{for(;;){b.document.addEventListener("mouseup",
kb,!1);if(b.parent==b)break;b=b.parent}}catch(c){}this.drawText(__svi18n.wait);if(k.onstart)k.onstart(e);V&&u&&u.startPasteCmd()};this.movCursorBy=Pa;this.moveCursor=qa;this.touchstart=function(a){switch(a.pointes){case 1:if(ca)g||Ga(),Qa("touchstart",a.screenX,a.screenY,!a.flick);else if(!a.flick||t()){var b=h.getElement().getBoundingClientRect(),d=a.x-b.left;a=a.y-b.top;if(k.mouseMoveEmu){var b=Bb,c=Cb,e=d-b,l=a-c,n=Math.max(Math.abs(l),Math.abs(e))/2|0;if(0<n)for(var e=e/n|0,l=l/n|0,r=0;r<n;r++)b+=
e,c+=l,Aa(b,c);b==d&&c==a||Aa(d,a);Bb=d;Cb=a}ta(d,a,0)}break;case 2:xa=a.screenX,ja=a.screenY}};this.touchmove=function(a){var b=h.getElement().getBoundingClientRect();switch(a.pointes){case 1:ca?Qa("touchmove",a.screenX,a.screenY,!a.flick):a.flick&&!t()||Aa(a.x-b.left,a.y-b.top);break;case 2:40<=Math.abs(a.screenY-ja)&&(wb(a.x-b.left,a.y-b.top,0<a.screenY-ja?0:1),xa=a.screenX,ja=a.screenY)}};this.touchend=function(a){var b=a.pointes,d=h.getElement().getBoundingClientRect();switch(b){case 1:ca?Qa("touchend",
a.screenX,a.screenY,!a.flick):(qa(a.x,a.y,!0),a.flick&&!t()||ia(a.x-d.left,a.y-d.top,0));break;case 2:a.moved||(b=ca?g.scrX:a.x-d.left,a=ca?g.scrY:a.y-d.top,qa(b,a),ta(b,a,2),ia(b,a,2));break;case 3:if(a.gesture)switch(a.gesture){case "OPEN":l(!0,219);l(!0,200);l(!1,200);l(!1,219);break;case "CLOSE":l(!0,219);l(!0,208);l(!1,208);l(!1,219);break;case "LEFT":l(!0,56);l(!0,1);l(!1,1);l(!1,56);break;case "RIGHT":l(!0,42);l(!0,56);l(!0,1);l(!1,1);l(!1,56);l(!1,42);break;case "UP":l(!0,42);l(!0,219);T(!0,
77);T(!1,77);l(!1,219);l(!1,42);break;case "DOWN":l(!0,219),T(!0,77),T(!1,77),l(!1,219)}else k.toolbar&&k.toolbar.startFade&&k.toolbar.startFade(),N&&N.focus()}};this.flick=function(a){switch(a.from){case 4:r.sendInput("840\t209");r.sendInput("8449152\t209");break;case 2:r.sendInput("840\t201"),r.sendInput("8449152\t201")}};this.longpress=function(a){ca&&(a.pointes=2);var b=h.getElement().getBoundingClientRect();switch(a.pointes){case 1:var d=a.x-b.left;a=a.y-b.top;qa(d,a);ta(d,a,2);ia(d,a,2);break;
case 2:g&&(ta(g.scrX,g.scrY,2,1),ia(g.scrX,g.scrY,2,1))}};this.redirectTouches=function(a){if(L){for(var b=a.length,d,c="90"+b,e=0;e<b;e++)d=a[e],c=c+"\t"+d.contactId+";"+d.contactFlags+";"+Math.floor(d.x/Q)+";"+Math.floor(d.y/U);r.send(c)}};var ya=0;this.processClipReq=function(a){var b=u.clipData,d=b?b.getData("text/richtext"==a?"text/html":a):null;if(d)return r.send("881"+a+"\t"+d),b.sent=!0;r.send("881"+a+"\t"+("text/plain"==a?"":"ERROR"));return!1};var Ta={},vb=!1,Lb={33:201,34:209,35:207,36:199,
37:203,38:200,39:205,40:208,154:183,45:210,46:211,225:184,91:219,92:220,93:221,27:1,8:14,9:15,13:28,224:29,17:29,16:42,18:56,20:58,166:59,112:59,167:60,113:60,168:61,114:61,183:62,115:62,182:63,116:63,216:64,117:64,217:65,118:65,173:66,119:66,174:67,120:67,175:68,121:68,122:87,123:88};this.writeKeyComb=function(a){r.writeKeyComb(a)};this.setCursor=function(a){!x.disableCursor&&a&&(a.data||a.url||a.none)&&(Ha=a,g&&g.setCursor(a),W||(h?(h.getElement().style.cursor="default",h.getElement().style.cursor=
yb(a)):e.style.cursor=yb(a)))};this.setVisible=function(a,b){var d=a?"visible":"hidden";"number"==typeof b?setTimeout(function(){e.style.visibility=d},b):e.style.visibility=d}}svGlobal.LocalInterface=LocalInterface;
svGlobal.rdpFile={loadRdpFile:function(e,v){var q=v.elements,H=e.split("\r\n");2>H.length&&(H=e.split("\n"));if(2>H.length)return!1;var E=hi5.$("gateway"),y=E.value;v.reset();E.value=y;E=0;for(y=H.length;E<y;E++){var t=H[E],z=t.indexOf(":"),J=t.substring(0,z),t=t.substring(z+3),J=J.toLowerCase();switch(J){case "full address":z=t.indexOf(":");0<z?(q.server.value=t.substring(0,z),q.port.value=t.substring(z+1)):q.server.value=t;break;case "username":q.user.value=t;break;case "domain":q.domain.value=
t;break;case "connect to console":q.useConsole.checked="0"!=t;break;case "desktopwidth":q.width.value=t;break;case "desktopheight":q.height.value=t;break;case "session bpp":q.server_bpp.value=t;break;case "audiomode":q.playSound.value=t;break;case "alternate shell":0<t.length&&(q.command.value=t,hi5.$("app").checked||(hi5.$("shell").checked=!0));break;case "shell working directory":q.directory=t;break;case "redirectclipboard":q.mapClipboard.checked="0"!=t;break;case "redirectprinters":q.mapPrinter.checked=
"0"!=t;break;case "server port":0<t.length&&(q.port.value=t);break;case "disable wallpaper":q.background.checked="0"==t;break;case "disable themes":q.styles.checked="0"==t;break;case "disable menu anims":q.animation.checked="0"==t;break;case "disable full window drag":q.contents.checked="0"==t;break;case "allow font smoothing":q.smoothfont.checked="0"!=t;break;case "allow desktop composition":q.composition.checked="0"!=t;break;case "bitmapcachepersistenable":q.bitmap.checked="0"!=t;break;case "remoteapplicationprogram":q.exe.value=
t;break;case "remoteapplicationcmdline":q.args.value=t;break;case "remoteapplicationmode":hi5.$("app").checked="1"==t;break;case "loadbalanceinfo":q.loadBalanceInfo.value=t}}return!0},handleFiles:function(e,v){if(1!=e.length)hi5.notifications.notify({msg:"Please one file only"});else{var q=e[0],H=q.name,E=H.length;if(4<E&&".rdp"==H.substring(E-4).toLowerCase()){var y=new FileReader,t=!1;y.onload=function(e){!(e=e.target.result)||svGlobal.rdpFile.loadRdpFile(e,v)||t||(t=!0,y.readAsText(q))};y.readAsText(q,
"UTF-16LE")}else hi5.notifications.notify({msg:"Sorry, Please .rdp file only"})}}};
function initDragDrop(e,v){function q(e){svGlobal.rdpFile.handleFiles(e.target.files,v)}function H(q){cancelDefault(q);e.style.backgroundColor=t;svGlobal.rdpFile.handleFiles(q.dataTransfer.files,v)}function E(q){cancelDefault(q);e.style.backgroundColor="yellow"}function y(q){cancelDefault(q);e.style.backgroundColor=t}if("FileReader"in window){var t=e.style.backgroundColor,z=hi5.$("rdpfile");z&&z.addEventListener("change",q,!1);e.addEventListener("dragover",E,!1);e.addEventListener("dragleave",y,!1);
e.addEventListener("drop",H,!1)}}svGlobal.util.initDragDrop=initDragDrop;
svGlobal.util.initMapDisk=function(e,v){function q(q){cancelDefault(q);"0.6"!=e.style.opacity&&(e.style.opacity="0.6");e.style.backgroundColor="yellow"}function H(q){cancelDefault(q);e.style.opacity=e.__oldOpacity;e.style.backgroundColor=e.__oldColor}function E(q){cancelDefault(q);e.style.opacity=e.__oldOpacity;e.style.backgroundColor=e.__oldColor;var t=hi5.file.getEntries(q);t.length?(q=new hi5.file.DirectoryReader(t),q.onfile=function(e,q){v.addFile(e,q)},q.start()):v.addFiles(q.dataTransfer.files)}
"FileReader"in window&&(e.__oldColor=e.style.backgroundColor,e.__oldOpacity=e.style.opacity,e.addEventListener("dragover",q,!1),e.addEventListener("dragleave",H,!1),e.addEventListener("drop",E,!1))};window.addEventListener("load",function(e){e=document.getElementsByClassName("ver");for(var v=e.length,q=0;q<v;q++)e[q].innerHTML=svGlobal.version},!1);svGlobal.logger.info("ver:"+svGlobal.version);
