var svManager={getInstance:function(){var m=window.$telnet;return m&&m.running&&m.running()?m:null}};function connvertServer(m){var u={};u.id=m.id;u.server=m.id;u.displayName=m.displayName||m.id;if(m=m.vnc)for(var z in m)u[z]=m[z];return u}
svGlobal.TELNET=function(m,u,z,D){function Aa(a,c){var d=[],g=null,n=new hi5.graphic.Rectangle(0,0,0,0),h="Uint8ClampedArray"in window;this.width=a;this.height=c;var f=!1,e=this;this.pause=function(a){f=a};this.isPaused=function(){return f};this.setContext=function(a){a!=g&&(g||!a||a.createImageData(1,1).data.buffer||(h=!1),g=a)};this.getContext=function(){return g};this.resize=function(n,g){for(var h=0;h<g;h++)d[h]=new Uint32Array(n);e.width=a=n;e.height=c=g};e.resize(a,c);this.getBuffer=function(){return d};
this.setRGB=function(a,c,n){d[c][a]=n|4278190080};this.getRGB=function(a,c){return d[c][a]};this.setRGBs=function(a,c,n,g,h,e,f){if(h){var w=0,l=0;n=a+n;g=c+g;for(var k=c;k<g;k++,e+=f)for(l=e,c=d[k],w=a;w<n;w++)c[w]=h[l++]}else console.log("pixel null")};this.moveArea=function(a,c,n,g,h,e){if(0<e){h=a+h;e=c+e;var f,w,k;for(f=g-1;0<=f;f--)for(w=d[e+f],k=d[c+f],g=0;g<n;g++)w[h+g]=k[a+g]}else if(0>e){h=a+h;e=c+e;var l;for(w=0;w<g;w++)for(k=d[e+w],l=d[c+w],f=0;f<n;f++)k[h+f]=l[a+f]}else if(0<h)for(h=
a+h,e=c+e,--n;0<=n;n--)for(w=h+n,k=a+n,f=0;f<g;f++)d[e+f][w]=d[c+f][k];else for(h=a+h,e=c+e,f=0;f<n;f++)for(k=h+f,l=a+f,w=0;w<g;w++)d[e+w][k]=d[c+w][l]};this.getRGBs=function(a,c,n,g){var h=_Uint32Array(n*g);h[0]=0;n=a+n;g=c+g;for(var f=0,e=c;e<g;e++)for(c=a;c<n;c++)h[f++]=d[e][c];return h};this.repaint=function(n,f,e,k){if(g){0>n&&(e+=n,n=0);0>f&&(k+=f,f=0);n+e>a&&(e=a-n);f+k>c&&(k=c-f);var l=g.createImageData(e,k),m=l.data;e=n+e;k=f+k;var Z=0;if(h)for(var m=new Uint32Array(m.buffer),p,q=f;q<k;q++)for(p=
n;p<e;p++)m[Z++]=d[q][p];else for(var r,t,q=f;q<k;q++)for(p=n;p<e;p++)r=d[q][p],t=Z<<2,m[t]=r&255,m[t+1]=r>>8&255,m[t+2]=r>>16&255,m[t+3]=255,Z++;g.putImageData(l,n,f)}};this.postPaint=function(a,c,d,f){0<n.width?n.union(a,c,d,f):(n.x=a,n.y=c,n.width=d,n.height=f)};this.commitPaint=function(){0<n.width&&(this.repaint(n.x,n.y,n.width,n.height),n.width=0)};this.fillRect=function(a,c,n,f,g){n=a+n;f=c+f;for(var e=c;e<f;e++)for(c=a;c<n;c++)d[e][c]=g}}function la(a,c){H?H.resize(a,c):H=new Aa(a,c);return H}
function ma(){var a=m.indexOf("://"),c=m.substring(a+3),a=c.indexOf("/");0<a&&(c=c.substring(0,a));return location.protocol+"//"+c}function Ba(a){return sessionId?hi5.browser.httpGet(ma()+"/CLIP?s="+sessionId+"&t="+(new Date).getTime(),!1):""}function aa(a){return"on"==a||"true"==a}function na(a,c,d){this.need=a;this.handler=c;this.repeat=d||1}function Ca(){if(!A){oa();if(ba)q=ba;else{var a=hi5.tool.replaceQuery(m,"pwd","x");hi5.browser.binaryWS()&&(a+="&binary=on");var c=window.opener;if(c){var d=
null;try{d=c.__sparkUser}catch(f){}d&&(c=d.account,d=d.session,c&&(a+="&account="+c),d&&(a+="&session="+d))}a+="&pasteCap="+(hi5.browser.isChrome&&hi5.browser.isDesktop?3:0);q=new WebSocket(a,[]);q.binaryType="arraybuffer"}pa.ws=q;svGlobal.logger.info(m);q.onopen=Da;void 0!=k.recording&&"on"==k.recording&&Ea(k);q.onmessage=function(a){a=a.data;if("string"!=typeof a){var c=new Uint8Array(a);null!=I&&I.add(new RecordingObj(c,0,a.byteLength));V.set(c,0,a.byteLength);V.handle()}else{var d=parseInt(a.substring(0,
2),16),c=a.substring(2);switch(d){case 26:a=JSON.parse(c);if(a.name){svGlobal.logger.info("msg="+c);if(g.onerror)g.onerror(a);c=__svi18n.errorCode["S"+a.name]||"";c+=a.message;g.showMessage(c)}else 0<svGlobal.log&&console.erro("No error code for message:"+c);break;case 27:0!=hi5.appcfg.drawLicense&&B.drawLicense(c);break;case 56:a=JSON.parse(c);sessionId=a.session;a.server=g.server;if(c=hi5.$("joinSelect"))c.value=a.joinMode;if(c=hi5.$("requestControl"))c.disabled=a.hasControl;var c=hi5.appcfg.page&&
hi5.appcfg.page.joinssh||"jointelnet.html",c=location.protocol+"//"+location.host+"/"+c+"?id="+a.numericId,f=a.webAddress;f&&0<f.length&&(d=f.indexOf("://"),f=f.substring(d+3),d=f.indexOf("/"),0<d&&(f=f.substring(0,d)),f.toLowerCase()!=location.host.toLowerCase()&&(c+="&gateway="+f));a.joinLink=c;g.sessionInfo.appInfo=a;a.ver&&a.ver!=svGlobal.version&&console.log("Client:"+svGlobal.version+" server:"+a.ver);if(g.onsessionstart)g.onsessionstart(g.sessionInfo);break;case 59:break;case 61:a=JSON.parse(c);
switch(a.type){case 0:k.fontSize=parseInt(a.fontSize);u=a.width;z=a.height;oa();B.setAutoScale(!0);ca(u+x,z+x);a.server&&(g.server=a.server,g.setTitle&&(document.title=k.displayName||g.server));qa=a.length;if(g.onopened)g.onopened(a);break;case 1:a=a.duration;if(g.onprogress)g.onprogress(a,qa);break;case 2:2==a.status?A=!0:(c=0==a.status,H.pause(c),a.warn&&g.showMessage(c?__svi18n.info.sessionPaused:__svi18n.info.sessionResumed))}break;case 62:Fa(c);break;default:svGlobal.logger.warn("@TODO:"+a+"\n")}}};
q.onclose=function(a){svGlobal.logger.warn("closed, code="+a.code+" reason="+a.reason);M.style.display="none";if(!A&&0==g.mode){(a=__svi18n.errorCode.connection)||(a="error connection");if(g.onerror)g.onerror({name:"connection",message:a});g.displayMsg&&hi5.notifications.notify({msg:a});0<svGlobal.log&&console.error(a)}da=A=!1;try{null!=I&&(I.exit(),I=null),B&&B.close(),O&&O.visible()&&O.dismiss()}catch(c){}window&&window.$telnet&&(window.$telnet=null);if(g&&g.onclose)g.onclose()};q.onerror=Ga}}function Ea(a){I=
new RecordingManager;I.setHeader({name:a.server,width:a.width,height:a.height,color:a.fontSize,namesuffix:".telnetv",filetag:"TELV",duration:0})}function Fa(a){var c=parseInt(a.substring(0,1),16),d,e=a.substring(1);a=!1;var h=g.sessionInfo.appInfo;switch(c){case 1:d=JSON.parse(e);g.onsessionjoin&&(a=g.onsessionjoin(d));if(a)break;g.showMessage(__svi18n.info.joinsession.applyArgs([d.numericId,d.__ip,d.name]));break;case 2:d=JSON.parse(e);g.onsessionexit&&(a=g.onsessionexit(d));if(a)break;g.showMessage(__svi18n.info.exitsession.applyArgs([d.numericId,
d.__ip,d.name]));break;case 3:d=JSON.parse(e);h.joinMode!=d.mode&&(h.joinMode=d.mode,c=hi5.$("joinSelect"))&&(c.value=d.mode);if(h.hasControl)break;B.setReadOnly(!1);if(c=hi5.$("requestControl"))c.disabled=!0;g.ongivecontrol&&(a=g.ongivecontrol());if(a)break;g.showMessage(__svi18n.info.givecontrol);break;case 4:B.setReadOnly(!0);h.hasControl=!1;if(c=hi5.$("requestControl"))c.disabled=!1;g.ontakebackcontrol&&(a=g.ontakebackcontrol());if(a)break;g.showMessage(__svi18n.info.nocontrol);break;case 5:d=
JSON.parse(e);g.onrequirecontrol&&(a=g.onrequirecontrol(d));if(a)break;a=__svi18n.info.title.applyArgs([d.name,d.numericId,d.__ip]);hi5.notifications.notify({title:a,msg:__svi18n.info.recontrol,cbYes:function(){g.giveControl(d.numericId);this.destroy()},cbNo:function(){g.refuseControl(d.numericId);this.destroy()}});break;case 6:B.setTouchRemoting(!0);break;case 7:d=JSON.parse(e);d.cols&&d.rows&&(a=r*d.cols+2*x,c=f*d.rows+2*x,H=la(a,c),ca(a,c));break;case 8:d=JSON.parse(e);if(g.onrequestcredential&&
g.onrequestcredential(d))break;B.requestCredential(d);break;case 11:d=JSON.parse(e);g.onrequirejoin&&(a=g.onrequirejoin(d));if(a)break;a=__svi18n.info.title.applyArgs([d.name,d.numericId,d.__ip]);hi5.notifications.notify({title:a,msg:__svi18n.info.reqjoin,cbYes:function(){g.allowJoin(d.numericId,!0);this.destroy()},cbNo:function(){g.allowJoin(d.numericId,!1);this.destroy()}})}}function Da(a){svGlobal.logger.info("opened...");A=!0;q.send("87"+navigator.userAgent);if(g.onopen)g.onopen()}function Ga(a){svGlobal.logger.warn(a)}
function ea(a){V.setHandler(null);if(q&&A){q.onmessage=null;try{q.send("85"),q.close()}catch(c){}}window&&window.$telnet&&(window.$telnet=null);null!=I&&(I.exit(),I=null)}function ca(a,c){var d=a-x,e=c-x,g=Math.floor(e/f),l=Math.floor(d/r),m=null;if(A)var m=Math.min(l*r+x,C*r+x),p=Math.min(g*f+x,P*f+x),m=h.getImageData(0,0,m,p);u=d;z=e;B.setSize(a,c);h.font=k.fontSize+"px Courier New";ra();m&&h.putImageData(m,0,0);P=g;C=l;F=Math.floor(z/f)}function oa(){M||(ra(),l=p,e=t,10>k.fontSize&&(k.fontSize=
10),12>=k.fontSize?(f=k.fontSize+6,W=2):13<=k.fontSize&&18>k.fontSize?(f=k.fontSize+8,W=2):19<=k.fontSize&&25>k.fontSize?(f=k.fontSize+12,W=3):25<=k.fontSize&&(f=k.fontSize+16,W=4),h.font=k.fontSize+"px Courier New",r=h.measureText("X").width,F=parseInt(z/f),P=parseInt(z/f),C=parseInt(u/r),remotectrl.style.cursor="text",M=document.getElementById("cursorID"),M.style.display="block",M.style.width=r+"px",M.style.height=f+"px",da=!0)}function ra(){h.fillStyle="black";h.fillRect(0,0,h.canvas.width,h.canvas.height);
h.fillStyle="white"}function sa(a){var c="";0!=v||fa[a]?(""!=J&&ta(J),Ha(a)):ga?(c=E[a]||"",J=""!=c?J+c:J+String.fromCharCode(a)):J+=String.fromCharCode(a)}function ha(a){for(;;){var c=a.getByte();if(255==c&&(c=a.getByte(),240==c))break}}function U(a,c,d){q.send("D5"+a+"\t"+c+"\t"+(1==d?1:0));251==a?ia(c):252==a?ia(c):253==a?ja(c):254==a&&ja(c)}function ia(a){return 39>=a&&0<=a&&Ia[a-0]}function ja(a){return 39>=a&&0<=a&&Ja[a-0]}function Ha(a){switch(a){case 0:case 24:return v=0,!1;case 26:return v=
0,!1;case 5:return!1;case 7:return!1;case 8:return l-=r,l<p&&(l=p),y(),!1;case 9:var c=(l-p)/r/8,c=parseInt(1*c)+1;l=8*c*r+p;l>=C*r&&(l=p,e+=f,Q("\n"));y();return!1;case 13:return l=p,e>t+(F-1)*f&&(e=t+(F-1)*f),y(),!1;case 10:case 11:case 12:e+=f;Q("\n");y();l>=C*r&&(l=p,e+=f,Q("\n"));if(e>(F-1)*f+t){for(;e>(F-1)*f+t;)e-=f;y();c=h.getImageData(p,t+f,C*r,(F-1)*f);h.fillStyle="black";h.fillRect(p,t,C*r,F*f);h.putImageData(c,p,t);h.fillStyle="white"}return!1;case 15:return!1;case 14:return!1;case 17:case 19:return!1;
case 27:return L="",v=27,!1;default:if(128<=a&&159>=a)return!1}switch(v){case 0:return!0;case 27:if("\\"==a)return!1;if(32<=a&&47>=a)return L+=String.fromCharCode(a),!1;if(32<=a&&126>=a||160<=a){null==L&&(L="");switch(a){case 48:"("==L&&(ga=!0);break;case 65:e-=f;y();break;case 66:"("==L&&(ga=!1);break;case "C":l+=r;y();break;case 68:""==L&&ua(1);y();break;case 72:l=p;e+=f;break;case 77:""==L&&va(1);break;case "P":v=0;v=144;break;case "Y":v=161;break;case "c":v=0;break;case 91:K="";v=0;v=155;break;
case 93:v=0;v=157;break;case "^":v=0,v=158}27==v&&(v=0);return!1}return!0;case 155:if(48<=a&&63>=a||32<=a&&47>=a)return K+=String.fromCharCode(a),!1;if(32<=a&&126>=a||160<=a){c=null;null==K&&(K="");""!=K&&(c=K.split(";"));var d=0,d=0;switch(a){case 65:d=null!=c&&1<=c.length?parseInt(c[0]):1;e-=d*f;e<t&&(e=t);y();break;case 66:d=null!=c&&1<=c.length?parseInt(c[0]):1;a=e;e+=d*f;a=(e-a)/f;Q("\n",0==a?1:a);y();break;case 67:d=null!=c&&1<=c.length?parseInt(c[0]):1;l+=d*r;y();break;case 68:d=null!=c&&1<=
c.length?parseInt(c[0]):1;l-=d*r;l<p&&(l=p);y();break;case 69:d=null!=c&&1<=c.length?parseInt(c[0]):1;a=e;e+=d*f;a=(e-a)/f;a=0==a?1:a;Q("\n",a);l=p;y();break;case 70:d=null!=c&&1<=c.length?parseInt(c[0]):1;e-=d*f;e<t&&(e=t);l=p;y();break;case 72:case 102:null!=c?(1<=c.length&&(d=parseInt(c[0]),a=e,e=t+(d-1)*f,a=(e-a)/f,a=0==a?1:a,Q("\n",a)),2<=c.length&&(d=parseInt(c[1])-1,l=p+d*r)):""==K&&(l=p,e=t);break;case 73:c=1<=c.length?parseInt(c[0]):1;l=p+8*c*r;break;case 74:null!=c&&1<=c.length?(c=parseInt(c[0]),
1==c&&(h.fillStyle="black",h.fillRect(p,t,C*r,e-chart_height-t),h.fillRect(p,e,e-p,chart_height),h.fillStyle="white")):(h.fillStyle="black",h.fillRect(l,e,C*r-l+p,P*f-e+t),h.fillStyle="white");break;case 75:null!=c&&1<=c.length?(c=parseInt(c[0]),1==c?ka(p,l):2==c&&ka(p,u+x),y()):ka(l,u+x);break;case 76:null!=c&&1<=c.length&&(d=parseInt(c[0]),va(d),y());break;case 77:null!=c&&1<=c.length&&(d=parseInt(c[0]),ua(d),y());break;case 80:d=null!=c&&1<=c.length?parseInt(c[0]):1;c=h.getImageData(l+d*r,e,u+
x-l-d*r,f);h.fillStyle="black";h.fillRect(l,e,u+x-l,f);h.putImageData(c,l,e);h.fillStyle="white";y();break;case 88:d=null!=c&&1<=c.length?parseInt(c[0]):1;h.fillStyle="black";h.fillRect(l,e,d*r,f);h.fillStyle="white";break;case 109:if(null==c||0==c.length)h.font="normal "+k.fontSize+"px Courier New",R=0,S=7;else{a=c.length;for(var g=d=0;g<a;g++)switch(d=1*c[g],d){case 0:h.font="normal "+k.fontSize+"px Courier New";R=0;S=7;break;case 1:h.font="bold "+k.fontSize+"px Courier New";break;case 4:break;
case 5:h.font="italic "+k.fontSize+"px Courier New";break;case 7:h.font="normal "+k.fontSize+"px Courier New";R=7;S=0;break;case 22:h.font="normal "+k.fontSize+"px Courier New";R=0;S=7;break;case 24:break;case 25:h.font="italic "+k.fontSize+"px Courier New";break;case 27:h.font="normal "+k.fontSize+"px Courier New";R=7;S=0;break;default:30<=c[g]&&39>=c[g]?S=c[g]-30+1:40<=c[g]&&49>=c[g]&&(R=c[g]-40+1)}}break;case 114:null!=c&&2<=c.length&&(a=parseInt(c[0]),c=parseInt(c[1]),N=a,F=c)}v=0;return!1}return!0;
case 144:case 157:case 158:case 159:return 48<=a&&63>=a||32<=a&&47>=a?!1:32<=a&&126>=a||160<=a?(v=160,!1):!0;case 160:return 32<=a&&126>=a||160<=a?!1:!0;case 161:return v=162,!1;case 162:return v=0,!1;default:return v=0,!1}}function ka(a,c){h.fillStyle="black";h.fillRect(a,e,c-a,f);h.fillStyle="white"}function va(a){var c=h.getImageData(p,t+(N-1)*f,C*r,(F-N-a+1)*f);h.fillStyle="black";h.fillRect(p,t+(N-1)*f,C*r,f*a);h.putImageData(c,p,t+(N+a-1)*f);h.fillStyle="white"}function ua(a){var c=h.getImageData(p,
(N+a-1)*f+t,C*r,(F-N-a+1)*f);h.fillStyle="black";h.fillRect(p,(F-a)*f+t,C*r,a*f);h.putImageData(c,p,(N-1)*f+t);h.fillStyle="white"}function ta(a){var c=a.length;e+f>z&&(e=(P-1)*f+t);h.fillStyle=wa[R];h.fillRect(l,e,r*c,f);h.fillStyle=wa[S];h.fillText(a,l,e+f-3*W);l+=h.measureText(a).width;Q(a);y();J=""}function y(){M.style.top=e+"px";M.style.left=l+"px"}function Ka(a){if(A)return(a=a.getData("text/plain"))?(a=a.replace(/\r\n/g,"\n"),T(0,a,3),!0):!1}function La(){O&&X&&!O.visible()&&(X.value=Y,O.show(),
setTimeout(function(){X.scrollTop=X.scrollHeight},10))}function Q(a,c){if(O)if(c)for(var d=0;d<c;d++)Y+=a;else Y+=a}function T(a,c,d){q.send("8B"+d+"\t"+c)}sessionStorage&&sessionStorage.clear();hi5.appcfg.copyDialog=!0;var X=document.getElementById("copytextarea"),O=X?new hi5.Lightbox(document.getElementById("copydialog")):null,Y="";this.displayMsg=!0;this.reconnectTimes=0;this.setTitle=this.openLink=!0;this.mode=0;var ba="object"==typeof m?m:null,xa="object"==typeof m||0<m.indexOf("/PLAY?");xa?
(this.mode=1,ba&&(m=""),m+="&touchpad=on"):0<m.indexOf("/JOIN?")&&(this.mode=2,this.reconnectOnResize=!1);this.sessionInfo={major:0,minor:0,width:0,height:0,bpp:0,bigEndian:!0,trueColor:!0};var B=null,A=!1,da=!1,x=5,I=null;window.$telnet=this;for(var E=[],G=0;127>G;G++)E[G]=String.fromCharCode(G);E[106]="+";E[107]="+";E[108]="+";E[109]="+";E[110]="+";E[113]="_";E[116]="+";E[117]="+";E[118]="+";E[119]="+";E[120]="|";for(var Ja=[!0,!0,!1,!0,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,
!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1],Ia=[!0,!1,!1,!0,!1,!1,!1,!1,!1,!1,!1,!1,!0,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!0,!1,!1,!1,!1,!1,!1,!0,!0,!1,!1,!1,!1,!1,!1,!1,!1],fa=Array(256),ya=[0,5,7,8,9,10,11,12,13,14,15,17,19,24,26,27,127,132,133,136,141,142,143,144,155,156,157,158,159],G=0;256>G;G++)fa[G]=!1;for(G=0;G<ya.length;G++)fa[ya[G]]=!0;var V=new function(a){var c=0,d=0,f=new Uint8Array(a),g=this,e=new na(0,null,0);this.getHandler=function(){return e};this.getData=function(){return f};
this.getPosition=function(){return c};this.setPosition=function(a){c=a};this.getEnd=function(){return d};this.set=function(a,e,g){f=a;c=e;d=g};this.handle=function(){e.handler(g,e)};this.setHandler=function(a){a&&1>a.need&&console.log("need < 1");(e=a)&&d-c>=a.need&&a.handler(g,a)};this.getByte=function(){return f[c++]};this.peekByte=function(){return f[c]};this.getBE32=function(){return f[c++]<<24|f[c++]<<16|f[c++]<<8|f[c++]};this.getBE16=function(){return f[c++]<<8|f[c++]};this.skip=function(a){c+=
a};this.skipBack=function(a){c-=a};this.getBytes=function(a,d){if(d)for(var e=0;e<a;e++)d[e]=f[c++];else return e=c,c+=a,f.subarray(e,c)};this.copyToByteArray=function(a,c,d,e){hi5.Arrays.arraycopy(f,d,a,c,e)}}(4194304);this.__que=V;this.running=function(){return A};var g=this,q=null,k=hi5.tool.queryToObj(m.substring(m.indexOf("?")+1));u||(u=window.innerWidth);u-=x;k.width=u;m+="&width="+u;z||(z=window.innerHeight);z-=x;k.height=z;m+="&height="+z;k.fontSize||(k.fontSize=D,m+="&fontSize="+D);k.fontSize=
k.fontSize?parseInt(k.fontSize,10):13;this.server=k.server;this.port=k.port?parseInt(k.port,10):23;var wa="black red green yellow blue magenta cyan white gray violet".split(" "),H=la(u,z),h=H.getContext(),pa=new function(){this.ws=null;this.setJoinMode=g.setJoinMode;this.requestControl=g.requestControl;this.writeKeyComb=g.writeKeyComb;this.getAppMode=function(){return g.mode};this.send=function(a){"891"!=a&&A&&this.ws.send(a)};this.sendInput=function(a){g.writeRawInput(a);if(g.onactivity)g.onactivity(a)};
var a=null;this.getAppInfo=function(){return g.sessionInfo.appInfo};this.onresize=function(c){if(c=c.target.svSurface){c=c.getFreeSpace();var d=c.width,f=c.height;hi5.browser.isTouch||hi5.browser.isOpera||!A||(a&&(clearTimeout(a),a=null),a=setTimeout(function(){ca(d,f);q.send("D9"+C+"\t"+P)},200))}};this.onorientationchange=function(a){};this.getClipData=Ba;this.onfocus=function(a){};this.fileCallback=[];this.getShareFiles=function(a,d){loggedin&&(this.ws.send("3A5"+a),this.fileCallback.push(d))};
this.notifyFiles=function(a){for(var d=this.fileCallback,f=0,e=d.length;f<e;f++)d[f](a)};this.getFile=function(a){window.open(g.getFileUrl(a))};this.removeFile=function(a){uploadMgr&&uploadMgr.fileService.remove(a)};this.getFileLink=function(a){return ma()+"/DOWNLOAD?s="+sessionId+"&f="+a};this.getGateway=function(){return m};this.reconnect=function(a,d,f){}};hi5.appcfg&&(D=hi5.appcfg,"undefined"!=typeof D.displayMsg&&(this.displayMsg=D.displayMsg),"undefined"!=typeof D.reconnectTimes&&(this.reconnectTimes=
D.reconnectTimes),"undefined"!=typeof D.openLink&&(this.openLink=D.openLink),"undefined"!=typeof D.setTitle&&(this.setTitle=D.setTitle),"boolean"==typeof D.useWSS&&(m=(hi5.appcfg.useWSS?"wss":"ws")+m.substring(m.indexOf("://"))));this.getURL=function(){return m};window.onerror=function(a,c,d){console.log("Uncatched error, msg: "+a+" url: "+c+" line: "+d)};this.setJoinMode=function(a){A&&q.send("8E1"+a)};this.refuseControl=function(a){A&&q.send("8E3"+a)};this.giveControl=function(a){A&&q.send("8E4"+
a)};this.requestControl=function(){A&&q.send("8E2")};this.play=function(){q.send("F3")};this.pause=function(){q.send("F2")};this.scan=function(a){q.send("F4"+(a?"1":"0"))};this.seek=function(a){B&&A&&(q.send("F4"+(a?"1":"0")+"\t"+(a/B.getScale()|0)),H.pause(!0))};var qa=0;this.run=function(){setTimeout(Ca,5)};this.hide=function(){B&&("block"==document.getElementById("cursorID").style.display&&(document.getElementById("cursorID").style.display="none"),B.hide())};this.showMessage=function(a){g.displayMsg&&
a&&hi5.notifications.notify({msg:a})};this.close=ea;hi5.browser.isChromeApp?chrome.runtime.onSuspend.addListener(ea):window.addEventListener("unload",ea,!1);var za=!1,M=null,p=x=5,t=5,l=0,e=0,S=7,R=0,v=0,K="",L="",r=0,f=18,W=0,J="",ga=!1,P=0,C=0,N=1,F=24;D=new na(1024,function(a){for(var c=!0;c;){b=a.getByte();if(0>b)break;if(255==b)a:{var d=a,f=d.getByte();switch(f){case 255:sa(f);break;case 254:case 253:case 252:case 251:var e=d.getByte(),d=f;253!=d||ia(e)?251!=d||ja(e)?254==d?U(252,e,!1):252==
d?U(254,e,!1):253==d?(U(251,e,!1),31==e?q.send("D9"+C+"\t"+P):12==e&&q.send("D7")):251==d&&U(253,e,!1):U(254,e,!0):U(252,e,!0);break;case 250:e=d.getByte();switch(e){case 24:e=d.getByte();ha(d);if(1!=e)break;q.send("DA");break;case 32:e=d.getByte();ha(d);if(1!=e)break;q.send("DC");break;default:ha(d)}break;default:break a}za||(za=!0,q.send("D0"))}else sa(b);a.getPosition()>=a.getEnd()&&(""!=J&&ta(J),c=!1)}});V.setHandler(D);this.addSurface=function(a){B=a;xa&&a.setPlayerMode();H.setContext(B.context);
h=H.getContext();a.setAutoScale(0<g.mode);a.setSize(u+x,z+x);a.setController(pa);a.setFastCopy(aa(k.fastCopy));a.setTouchpad(aa(k.touchpad));a.setClipboard(aa(k.mapClipboard));a.run(!0);a.onclipdata=Ka};(new Uint8Array(6))[0]=5;(new Uint8Array(8))[0]=4;this.writeRawInput=function(a){if(da){var c=parseInt(a.substring(0,2),16);a=a.substring(2).split("\t");var d=0,e=!1;switch(c){case 128:2==a[2]&&La();return;case 129:return;case 130:return;case 131:return;case 132:0==a[0]?(d=parseInt(a[1]),e=0==a[0],
T(e,d,0)):42==a[1]?T(0,42,2):29==a[1]&&T(0,29,2);return;case 139:0==a[0]&&(d=parseInt(a[1]),e=0==a[0],T(e,d,1));return;case 134:d=a[0].charCodeAt(0);47==d?T(!0,191,1):T(0,a[0],3);return}console.log("Unknowncode: "+a[1]+" type:"+c)}}};
