var svManager={getInstance:function(){var n=window.$telnet;if(n&&n.running&&n.running())return n;return null}};function connvertServer(n){var w=new Object;w.id=n.id;w.server=n.id;w.displayName=n.displayName||n.id;var x=n.vnc;if(x)for(var fa in x)w[fa]=x[fa];return w}
svGlobal.TELNET=function(n,w,x){function fa(a,b){function d(b,a,c,d,e,f){var g=b+e;var v=a+f;var k=I;var h;var t;var u;var l;for(t=0;t<d;t++){u=k[v+t];l=k[a+t];for(h=0;h<c;h++)u[g+h]=l[b+h]}}function c(b,a,c,d,e,f){var g=b+e;var v=a+f;var h=I;var t;var k;var u;var l;for(k=d-1;k>=0;k--){u=h[v+k];l=h[a+k];for(t=0;t<c;t++)u[g+t]=l[b+t]}}function g(b,a,c,d,e,f){var v=b+e;var t=a+f;var k=I;var h;var u;var l;var m;for(h=c-1;h>=0;h--){l=v+h;m=b+h;for(u=0;u<d;u++)k[t+u][l]=k[a+u][m]}}function v(b,a,c,d,e,
f){var g=b+e;var v=a+f;var h=I;var k;var t;var u;var l;for(k=0;k<c;k++){u=g+k;l=b+k;for(t=0;t<d;t++)h[v+t][u]=h[a+t][l]}}var I=[];var f=null;var e=new hi5.graphic.Rectangle(0,0,0,0);var k="Uint8ClampedArray"in window;this.width=a;this.height=b;var h=false;var u=this;this.pause=function(b){h=b};this.release=function(){u=null;f=null;I=null};this.isPaused=function(){return h};this.setContext=function(b){if(b==f)return;if(!f&&b&&!b.createImageData(1,1).data.buffer)k=false;f=b};this.getContext=function(){return f};
this.resize=function(c,d){for(var e=0;e<d;e++)I[e]=new Uint32Array(c);u.width=a=c;u.height=b=d};u.resize(a,b);this.getBuffer=function(){return I};this.setRGB=function(b,a,c){I[a][b]=c|4278190080};this.getRGB=function(b,a){return I[a][b]};this.setRGBs=function(b,a,c,d,e,f,g){var v=f;var k=0;var t=0;var h=b+c;var u=a+d;var l=I;var m;for(var p=a;p<u;p++,v+=g){t=v;m=l[p];for(k=b;k<h;k++)m[k]=e[t++]}};this.moveArea=function(b,a,e,f,k,h){if(h>0)c(b,a,e,f,k,h);else if(h<0)d(b,a,e,f,k,h);else if(k>0)g(b,
a,e,f,k,h);else v(b,a,e,f,k,h)};this.getRGBs=function(b,a,c,d){var e=c*d;var f=_Uint32Array(e);f[0]=0;var k=I;var h=b+c;var v=a+d;var g=0;var t;for(var u=a;u<v;u++)for(t=b;t<h;t++)f[g++]=k[u][t];return f};this.repaint=function(c,d,e,h){if(!f)return;if(c<0){e+=c;c=0}if(d<0){h+=d;d=0}if(c+e>a)e=a-c;if(d+h>b)h=b-d;var t=f.createImageData(e,h);var v=t.data;var g=c+e;var u=d+h;var l=0;var m=I;if(k){var p=new Uint32Array(v.buffer);var n;for(var q=d;q<u;q++)for(n=c;n<g;n++)p[l++]=m[q][n]}else{var r;var da;
for(q=d;q<u;q++)for(n=c;n<g;n++){r=m[q][n];da=l<<2;v[da]=r&255;v[da+1]=r>>8&255;v[da+2]=r>>16&255;v[da+3]=255;l++}}f.putImageData(t,c,d);t=null};this.postPaint=function(b,a,c,d){if(e.width>0)e.union(b,a,c,d);else{e.x=b;e.y=a;e.width=c;e.height=d}};this.commitPaint=function(){if(e.width>0){this.repaint(e.x,e.y,e.width,e.height);e.width=0}};this.fillRect=function(b,a,c,d,e){var f=I;var h=b+c;var k=a+d;var v;for(var t=a;t<k;t++)for(v=b;v<h;v++)f[t][v]=e}}function Ea(a,b){if(M)M.resize(a,b);else M=new fa(a,
b);return M}function Fa(){var a=n.indexOf("://");var b=n.substring(a+3);a=b.indexOf("/");if(a>0)b=b.substring(0,a);return location.protocol+"//"+b}function eb(a){if(!ga)return"";return hi5.browser.httpGet(Fa()+"/CLIP?s="+ga+"&t="+(new Date).getTime(),false)}function fb(){this.ws=null;this.setJoinMode=g.setJoinMode;this.requestControl=g.requestControl;this.writeKeyComb=g.writeKeyComb;this.getAppMode=function(){return g.mode};this.send=function(b){if(b=="891")return;if(!E)return;this.ws.send(b)};this.sendInput=
function(b){g.writeRawInput(b);if(g.onactivity)g.onactivity(b)};var a=null;this.getAppInfo=function(){return g.sessionInfo.appInfo};this.onresize=function(b){var d=b.target.svSurface;if(!d)return;var c=d.getFreeSpace();var e=c.width;var f=c.height;if(hi5.browser.isTouch||hi5.browser.isOpera)return;if(E){var h=function(){ha(e,f);Ga(C,Y)};if(a){clearTimeout(a);a=null}a=setTimeout(h,200)}};this.onorientationchange=function(b){};this.getClipData=eb;this.onfocus=function(b){};this.fileCallback=[];this.getShareFiles=
function(b,a){if(loggedin){this.ws.send("3A5"+b);this.fileCallback.push(a)}};this.notifyFiles=function(b){var a=this.fileCallback;var c=0;for(var e=a.length;c<e;c++)a[c](b)};this.getFile=function(b){window.open(g.getFileUrl(b))};this.removeFile=function(b){if(uploadMgr)uploadMgr.fileService.remove(b)};this.getFileLink=function(b){return Fa()+"/DOWNLOAD?s="+ga+"&f="+b};this.getGateway=function(){return n};this.reconnect=function(b,a,c){}}function gb(){}function ma(a){return a=="on"||a=="true"}function hb(){return h.displayName||
g.server}function ib(a){if(g.setTitle)document.title=a}function Ha(a,b,d){this.need=a;this.handler=b;this.repeat=d||1}function jb(a){var b=0;var d=0;var c=new Uint8Array(a);var e=this;var f=new Ha(0,null,0);this.release=function(){f=null;c=null;e=null};this.getHandler=function(){return f};this.getData=function(){return c};this.getPosition=function(){return b};this.setPosition=function(a){b=a};this.getEnd=function(){return d};this.set=function(a,e,f){c=a;b=e;d=f};this.handle=function(){f.handler(e,
f)};this.setHandler=function(a){if(a&&a.need<1)svGlobal.logger.warn("need < 1");f=a;if(a&&d-b>=a.need)a.handler(e,a)};this.getByte=function(){return c[b++]};this.peekByte=function(){return c[b]};this.getBE32=function(){return c[b++]<<24|c[b++]<<16|c[b++]<<8|c[b++]};this.getBE16=function(){return c[b++]<<8|c[b++]};this.skip=function(a){b+=a};this.skipBack=function(a){b-=a};this.getBytes=function(a,d){if(!d){var e=b;b+=a;return c.subarray(e,b)}else for(var f=0;f<a;f++)d[f]=c[b++]};this.copyToByteArray=
function(b,a,d,e){hi5.Arrays.arraycopy(c,d,b,a,e)}}function kb(){if(E)return;Ia();if(na)m=na;else{var a=hi5.tool.replaceQuery(n,"pwd","x");var b=hi5.browser.binaryWS();if(b)a+="&binary=on";var d=window.opener;if(d){var c=null;try{c=d.__sparkUser}catch(e){}if(c){var f=c.account;var k=c.session;if(f)a+="&account="+f;if(k)a+="&session="+k}}var g=hi5.browser.isChrome&&hi5.browser.isDesktop;a+="&pasteCap="+(g?3:0);m=new WebSocket(a,"telnet");m.binaryType="arraybuffer"}oa.ws=m;svGlobal.logger.info(n);m.onopen=
lb;if(h["recording"]!=undefined&&h["recording"]=="on")mb(h);m.onmessage=function(b){var a=b.data;if(typeof a!="string"){var c=new Uint8Array(a);if(N!=null)N.add(new RecordingObj(c,0,a.byteLength));Z.set(c,0,a.byteLength);Z.handle()}else{var d=parseInt(a.substring(0,2),16);var e=a.substring(2);switch(d){case 26:nb(e);break;case 27:ob(e);break;case 56:pb(e);break;case 59:qb(e);break;case 61:rb(e);break;case 62:sb(e);break;default:svGlobal.logger.warn("@TODO:"+a+"\n")}}};m.onclose=ia;m.onerror=tb;ha(w+
y,x+y)}function mb(a){N=new RecordingManager;var b=a.server;var d={name:b,width:a.width,height:a.height,color:a.fontSize,namesuffix:".telnetv",filetag:"TELV",duration:0};N.setHeader(d)}function ob(a){if(G.drawLicense!=false){z.drawLicense(a);pa(h.fontSize)}}function qb(a){}function rb(a){var b=JSON.parse(a);switch(b.type){case 0:h.fontSize=parseInt(b.fontSize);w=b.width;x=b.height;Ia();z.setAutoScale(true);ha(w+y,x+y);var d=b.server;if(d){g.server=b.server;ib(hb())}Ja=b.length;if(g.onopened)g.onopened(b);
break;case 1:var c=b.duration;if(g.onprogress)g.onprogress(c,Ja);break;case 2:if(b.status==2){gb();E=true}else{var e=b.status==0;M.pause(e);if(b.warn)g.showMessage(e?__svi18n.info.sessionPaused:__svi18n.info.sessionResumed)}}}function sb(a){var b=parseInt(a.substring(0,1),16);var d;var c;var f=a.substring(1);var h=false;var k=g.sessionInfo.appInfo;switch(b){case 1:c=JSON.parse(f);if(g.onsessionjoin)h=g.onsessionjoin(c);if(h)break;g.showMessage(__svi18n.info.joinsession.applyArgs([c.numericId,c.__ip,
c.name]));break;case 2:c=JSON.parse(f);if(g.onsessionexit)h=g.onsessionexit(c);if(h)break;g.showMessage(__svi18n.info.exitsession.applyArgs([c.numericId,c.__ip,c.name]));break;case 3:c=JSON.parse(f);if(k.joinMode!=c.mode){k.joinMode=c.mode;var l=hi5.$("joinSelect");if(l)l.value=c.mode}if(k.hasControl)return;z.setReadOnly(false);d=hi5.$("requestControl");if(d)d.disabled=true;if(g.ongivecontrol)h=g.ongivecontrol();if(h)break;g.showMessage(__svi18n.info.givecontrol);break;case 4:z.setReadOnly(true);
k.hasControl=false;d=hi5.$("requestControl");if(d)d.disabled=false;if(g.ontakebackcontrol)h=g.ontakebackcontrol();if(h)break;g.showMessage(__svi18n.info.nocontrol);break;case 5:var m=function(){g.refuseControl(c.numericId);this.destroy()};var n=function(){g.giveControl(c.numericId);this.destroy()};c=JSON.parse(f);if(g.onrequirecontrol)h=g.onrequirecontrol(c);if(h)break;var p=__svi18n.info.title.applyArgs([c.name,c.numericId,c.__ip]);hi5.notifications.notify({"title":p,"msg":__svi18n.info.recontrol,
"cbYes":n,"cbNo":m});break;case 6:z.setTouchRemoting(true);break;case 7:c=JSON.parse(f);if(c.cols&&c.rows){var u=q*c.cols+y*2;var r=e*c.rows+y*2;M=Ea(u,r);ha(u,r)}break;case 8:c=JSON.parse(f);if(g.onrequestcredential&&g.onrequestcredential(c))return;z.requestCredential(c);break;case 9:break;case 11:var w=function(){g.allowJoin(c.numericId,false);this.destroy()};var x=function(){g.allowJoin(c.numericId,true);this.destroy()};c=JSON.parse(f);if(g.onrequirejoin)h=g.onrequirejoin(c);if(h)break;p=__svi18n.info.title.applyArgs([c.name,
c.numericId,c.__ip]);hi5.notifications.notify({"title":p,"msg":__svi18n.info.reqjoin,"cbYes":x,"cbNo":w})}}function pb(a){var b=JSON.parse(a);var d=b;ga=b.session;d.server=g.server;var c=hi5.$("joinSelect");if(c)c.value=d.joinMode;c=hi5.$("requestControl");if(c)c.disabled=d.hasControl;var e=G.page&&G.page.joinssh||"jointelnet.html";e=location.protocol+"//"+location.host+"/"+e+"?id="+b.numericId;var f=b.webAddress;if(f&&f.length>0){var h=f.indexOf("://");var k=f.substring(h+3);h=k.indexOf("/");if(h>
0)k=k.substring(0,h);if(k.toLowerCase()!=location.host.toLowerCase())e+="&gateway="+k}d.joinLink=e;g.sessionInfo.appInfo=d;if(b.ver&&b.ver!=svGlobal.version)svGlobal.logger.warn("Client:"+svGlobal.version+" server:"+b.ver);if(g.onsessionstart)g.onsessionstart(g.sessionInfo)}function Zb(a){var b=__svi18n.errorCode[a];if(!b)b="error "+a;if(g.onerror)g.onerror({name:a,message:b});if(g.displayMsg)hi5.notifications.notify({"msg":b});if(svGlobal.log>0)console.error(b)}function nb(a){var b=JSON.parse(a);
if(!b.name){if(svGlobal.log>0)console.erro("No error code for message:"+a);return}svGlobal.logger.info("msg="+a);if(g.onerror)g.onerror(b);var d=__svi18n.errorCode["S"+b.name]||"";d+=b.message;g.showMessage(d)}function lb(a){svGlobal.logger.info("opened...");E=true;m.send("87"+navigator.userAgent);if(g.onopen)g.onopen()}function tb(a){svGlobal.logger.warn(a)}function ia(a){svGlobal.logger.warn("closed ...");if(R)R.style.display="none";E=false;qa=false;if(g&&g.onclose)g.onclose();try{if(N!=null){N.exit();
N=null}if(z)z.close();if(W&&W.visible()){W.dismiss();W=null}}catch(b){}if(Z){Z.release();Z=null}f=null;S=null;if(m){m.onopen=null;m.onmessage=null;m.onclose=null;m.onerror=null;m=null}oa=null;z=null;g=null;if(window&&window.$telnet)window.$telnet=null;if(N!=null){N.exit();N=null}}function ub(){D=h.fgColor||H[7];B=h.bgColor||H[0]}function pa(a,b){if(!b)b=L;f.font=a+"px "+b;q=f.measureText("X").width;Y=parseInt(x/e);C=parseInt(w/q);ra(parseInt(x/e))}function ra(a,b){if(b)T=b;if(a){O=a;ja=(O-1)*e+r}Ka=
T==1&&O==Math.floor(x/e)}function ha(a,b){var d=a-y;var c=b-y;var k=Math.floor(c/e);var g=Math.floor(d/q);var l=null;if(E){var m=Math.min(g*q+y,C*q+y);var p=Math.min(k*e+y,Y*e+y);l=f.getImageData(0,0,m,p)}w=d;x=c;z.setSize(a,b);pa(h.fontSize);sa();if(l)f.putImageData(l,0,0);Y=k;C=g;ra(Math.floor(x/e))}function vb(){l=p;k=r;if(h.fontSize<10)h.fontSize=10;if(h.fontSize<=12){e=h.fontSize+6;ea=2}else if(h.fontSize>=13&&h.fontSize<18){e=h.fontSize+8;ea=2}else if(h.fontSize>=19&&h.fontSize<25){e=h.fontSize+
12;ea=3}else if(h.fontSize>=25){e=h.fontSize+16;ea=4}pa(h.fontSize);remotectrl.style.cursor="text"}function Ia(){if(!R){sa();vb();R=document.getElementById("cursorID");R.style.display="block";R.style.width=q+"px";R.style.height=e+"px";qa=true}}function sa(){f.fillStyle=B;f.fillRect(0,0,S.width,S.height);f.fillStyle=D}function La(a){var b="";if(wb(a))if(ta){b=F[a]||"";if(b!="")J=J+b;else J=J+String.fromCharCode(a)}else if(a>127&&a<256)J=J+F[a];else J=J+String.fromCharCode(a);else{if(J!="")ua(J);xb(a)}}
function yb(a){var b=a.getByte();switch(b){case 255:La(b);break;case 254:case 253:case 252:case 251:var d=a.getByte();zb(b,d);break;case 250:d=a.getByte();Ab(d,a);break;default:return}if(!Ma){Ma=true;Bb()}}function Bb(){m.send("D0")}function Ab(a,b){switch(a){case 24:var d=b.getByte();va(b);if(d!=1)break;Cb();break;case 32:d=b.getByte();va(b);if(d!=1)break;Db();break;default:va(b)}}function va(a){for(;!Eb;){var b=a.getByte();if(b==255){b=a.getByte();if(b==240)break}}}function zb(a,b){if(a==253&&!wa(b))aa(252,
b,true);else if(a==251&&!xa(b))aa(254,b,true);else if(a==254)aa(252,b,false);else if(a==252)aa(254,b,false);else if(a==253){aa(251,b,false);if(b==31)Ga(C,Y);else if(b==12)Fb()}else if(a==251)aa(253,b,false)}function aa(a,b,d){m.send("D5"+a+"\t"+b+"\t"+(d==true?1:0));if(a==251){if(wa(b))Na[b-0]=true}else if(a==252){if(wa(b))Na[b-0]=false}else if(a==253){if(xa(b))Oa[b-0]=true}else if(a==254)if(xa(b))Oa[b-0]=false}function Fb(){m.send("D7")}function Ga(a,b){m.send("D9"+a+"\t"+b)}function Cb(){m.send("DA")}
function Db(){m.send("DC")}function wa(a){return Pa(a)&&Gb[a-0]}function xa(a){return Pa(a)&&Hb[a-0]}function $b(a){return cmd<=255&&cmd>=236}function Pa(a){return a<=39&&a>=0}function wb(a){return K==ka&&!ya[a]}function P(){K=ka}function xb(a){switch(a){case 0:case 24:P();return false;case 26:P();return false;case 5:return false;case 7:return false;case 8:Ib();return false;case 9:Jb();return false;case 13:Kb();return false;case 10:case 11:case 12:Qa();return false;case 15:return false;case 14:return false;
case 17:case 19:return false;case 27:U="";K=za;return false;default:if(a>=128&&a<=159)return false}switch(K){case ka:return true;case za:if(a=="\\")return false;else if(a>=32&&a<=47){U=U+String.fromCharCode(a);return false}else if(a>=32&&a<=126||a>=160){Lb(a);if(K==za)P();return false}return true;case Ra:if(a>=48&&a<=63){Q=Q+String.fromCharCode(a);return false}else if(a>=32&&a<=47){Q=Q+String.fromCharCode(a);return false}else if(a>=32&&a<=126||a>=160){Mb(a);P();return false}return true;case Sa:case Ta:case Ua:case Nb:if(a>=
48&&a<=63)return false;else if(a>=32&&a<=47)return false;else if(a>=32&&a<=126||a>=160){K=Va;return false}return true;case Va:if(a>=32&&a<=126||a>=160)return false;return true;case Wa:K=Xa;return false;case Xa:P();return false;default:K=ka;return false}}function Ob(a,b){ra(b,a)}function Lb(a){if(U==null)U="";switch(a){case 48:if(U=="(")ta=true;break;case 65:k=k-e;A();return;case 66:if(U=="(")ta=false;return;case "C":l+=q;A();return;case 68:if(U=="")Ya(1);A();return;case "E":return;case 72:l=p;k=k+
e;return;case "I":return;case "J":return;case "K":case "L":return;case 77:if(U=="")Za(1);return;case "N":return;case "O":return;case "P":P();K=Sa;return;case "V":return;case "W":return;case "X":return;case "Y":K=Wa;return;case "Z":return;case "<":return;case " ":return;case "c":P();return;case 91:Q="";P();K=Ra;return;case 93:P();K=Ta;return;case "^":P();K=Ua;case "_":case "\\":case ">":case "=":case "8":case "7":case "(":}}function Mb(a){var b=null;if(Q==null)Q="";if(Q!="")b=Q.split(";");var d=0;
var c=0;switch(a){case 65:if(b!=null&&b.length>=1)d=parseInt(b[0]);else d=1;k=k-d*e;if(k<r)k=r;A();return;case 66:if(b!=null&&b.length>=1)d=parseInt(b[0]);else d=1;var h=k;k+=d*e;var g=(k-h)/e;g=g==0?1:g;ba("\n",g);A();return;case 67:if(b!=null&&b.length>=1)c=parseInt(b[0]);else c=1;l=l+c*q;A();return;case 68:if(b!=null&&b.length>=1)c=parseInt(b[0]);else c=1;l=l-c*q;if(l<p)l=p;A();return;case 69:if(b!=null&&b.length>=1)d=parseInt(b[0]);else d=1;h=k;k+=d*e;g=(k-h)/e;g=g==0?1:g;ba("\n",g);l=p;A();return;
case 70:if(b!=null&&b.length>=1)d=parseInt(b[0]);else d=1;k=k-d*e;if(k<r)k=r;l=p;A();return;case 72:case 102:if(b!=null){if(b.length>=1){d=parseInt(b[0]);d=d-1;h=k;k=r+d*e;g=(k-h)/e;g=g==0?1:g;ba("\n",g)}if(b.length>=2){c=parseInt(b[1])-1;l=p+c*q}return}else if(Q==""){l=p;k=r}return;case 73:if(b.length>=1)var m=parseInt(b[0]);else m=1;l=p+m*8*q;return;case 74:if(b!=null&&b.length>=1){var n=parseInt(b[0]);if(n==1)Pb();else if(n==2){sa();l=p;k=r}}else Qb();return;case 75:if(b!=null&&b.length>=1){n=
parseInt(b[0]);if(n==1)Aa(p,l);else if(n==2)Aa(p,w+y);A()}else Aa(l,w+y);return;case 76:if(b!=null&&b.length>=1){d=parseInt(b[0]);Za(d);A()}break;case 77:if(b!=null&&b.length>=1){d=parseInt(b[0]);Ya(d);A()}break;case "S":break;case "T":break;case 80:if(b!=null&&b.length>=1)c=parseInt(b[0]);else c=1;var x=f.getImageData(l+c*q,k,w+y-l-c*q,e);f.fillStyle=B;f.fillRect(l,k,w+y-l,e);f.putImageData(x,l,k);f.fillStyle=D;A();break;case 88:if(b!=null&&b.length>=1)c=parseInt(b[0]);else c=1;f.fillStyle=B;f.fillRect(l,
k,c*q,e);f.fillStyle=D;break;case "c":break;case "g":break;case "i":break;case 109:Rb(b);break;case "n":break;case "q":break;case 114:if(b!=null&&b.length>=2)Ob(parseInt(b[0]),parseInt(b[1]));case "x":case "y":default:}}function Pb(){f.fillStyle=B;f.fillRect(p,r,C*q,k-chart_height-r);f.fillRect(p,k,k-p,chart_height);f.fillStyle=D}function Aa(a,b){f.fillStyle=B;f.fillRect(a,k,b-a,e);f.fillStyle=D}function Rb(a){Ba=false;if(a==null||a.length==0){f.font="normal "+h.fontSize+"px "+L;ub()}else{var b=a.length;
var d=0;for(var c=0;c<b;c++){d=a[c]*1;switch(d){case 0:f.font="normal "+h.fontSize+"px "+L;B=H[0];D=H[7];break;case 1:f.font="bold "+h.fontSize+"px "+L;break;case 4:Ba=true;break;case 5:f.font="italic "+h.fontSize+"px "+L;break;case 7:f.font="normal "+h.fontSize+"px "+L;B=H[7];D=H[0];break;case 22:f.font="normal "+h.fontSize+"px "+L;B=H[0];D=H[7];break;case 24:Ba=false;break;case 25:f.font="italic "+h.fontSize+"px "+L;break;case 27:f.font="normal "+h.fontSize+"px "+L;B=H[7];D=H[0];break;default:if(a[c]>=
30&&a[c]<=39)D=H[a[c]-30+1];else if(a[c]>=40&&a[c]<=49)B=H[a[c]-40+1]}}}}function Qb(){f.fillStyle=B;f.fillRect(l,k,C*q-l+p,Y*e-k+r);f.fillStyle=D}function Ib(){l=l-q;if(l<p)l=p;A()}function Jb(){var a=(l-p)/q/$a;a=a*1;a=parseInt(a)+1;l=a*$a*q+p;if(l>=C*q){l=p;k+=e;ba("\n")}A()}function Za(a){var b=f.getImageData(p,r+(T-1)*e,C*q,(O-T-a+1)*e);f.fillStyle=B;f.fillRect(p,r+(T-1)*e,C*q,e*a);f.putImageData(b,p,r+(T+a-1)*e);f.fillStyle=D}function Ya(a){var b=f.getImageData(p,(T+a-1)*e+r,C*q,(O-T-a+1)*e);
f.fillStyle=B;f.fillRect(p,(O-a)*e+r,C*q,a*e);f.putImageData(b,p,(T-1)*e+r);f.fillStyle=D}function Kb(){l=p;if(k>r+(O-1)*e)k=r+(O-1)*e;A()}function Qa(){k+=e;ba("\n");A();ab()}function ab(){if(l>=C*q){l=p;k+=e}if(k>ja){for(;k>ja;)k-=e;A();if(Ka){var a=S.height-(r+e);f.drawImage(S,0,r+e,S.width,a,0,r,S.width,a);f.fillStyle=B;f.fillRect(0,ja,S.width,e)}else{var b=f.getImageData(p,r+e,C*q,(O-1)*e);f.fillStyle=B;f.fillRect(p,r,C*q,O*e);f.putImageData(b,p,r)}f.fillStyle=D}}function ua(a){var b=a.length;
var d=(l-p)/q|0;var c=d+b-C;if(c>0){b-=c;bb(a.substring(0,b),b);ab();ua(a.substring(b))}else{bb(a,b);if(a.trim()=="--More--")Qa()}}function bb(a,b){if(k+e>x)k=(Y-1)*e+r;f.fillStyle=B;f.fillRect(l,k,q*b,e);f.fillStyle=D;f.fillText(a,l,k+e-3*ea);l=l+f.measureText(a).width;ba(a);A();J=""}function ac(a,b,d){var c=(b-r)/e;if(a==p)Sb[c]=d}function A(){R.style.top=k+"px";R.style.left=l+"px"}function bc(a){if(!g.openLink)return false;var b=a;a=a.toLowerCase();var d=a.indexOf("http://")==0||a.indexOf("https://")==
0||a.indexOf("ftp://")==0||a.indexOf("mailto:")==0||a.indexOf("tel:")==0||a.indexOf("callto:")==0;if(!d)if(a.indexOf("www.")==0){d=true;a="http://"+a}else if(a.indexOf("ftp.")==0){d=true;a="ftp://"+a}if(d){if(a.indexOf("\r")>0||a.indexOf("\n")>0)return false;if(g.onurlredirection&&g.onurlredirection(d))return true;z.processLink(b);return true}return false}function Tb(a){if(!E)return;var b=a.getData("text/plain");if(b){b=b.replace(/\r\n/g,"\n");Ub(0,b,3);return true}return false}function Vb(){if(!W)return;
if(!ca)return;if(W.visible())return;ca.value=V;W.show();if(z)z.setIgnorePaste(false);setTimeout(function(){ca.scrollTop=ca.scrollHeight;ca.disabled=false},10)}function ba(a,b){if(W){if(b)for(var d=0;d<b;d++)V=V+a;else V=V+a;if(V.length>1E5)V=V.substring(4E4)}}function Ub(a,b,d){m.send("8B"+d+"\t"+b)}function la(a){if(!a)return;var b=a.length+1;var d=new Uint8Array(b);d[0]=147;for(var c=1;c<b;c++)d[c]=a.charCodeAt(c-1);m.send(d.buffer)}if(sessionStorage)sessionStorage.clear();var ca=document.getElementById("copytextarea");
var W=ca?new hi5.Lightbox(document.getElementById("copydialog")):null;var V="";this.displayMsg=true;this.reconnectTimes=0;this.openLink=true;this.setTitle=true;this.mode=0;var na=typeof n=="object"?n:null;var cb=typeof n=="object"||n.indexOf("/PLAY?")>0;if(cb){this.mode=1;if(na)n="";n+="&touchpad=on"}else if(n.indexOf("/JOIN?")>0){this.mode=2;this.reconnectOnResize=false}var G=hi5.appcfg||{img:{},toolbar:{fadable:true}};this.sessionInfo={major:0,minor:0,width:0,height:0,bpp:0,bigEndian:true,trueColor:true};
var ga="";var z=null;var E=false;var qa=false;var Ba=false;var y=5;var N=null;window.$telnet=this;G.copyDialog=true;var ka=0;var za=27;var Ra=155;var Sa=144;var Ta=157;var Ua=158;var Nb=159;var Va=160;var Wa=161;var Xa=162;var F=new Array;for(var X=0;X<127;X++)F[X]=String.fromCharCode(X);F[106]="+";F[107]="+";F[108]="+";F[109]="+";F[110]="+";F[113]="_";F[116]="+";F[117]="+";F[118]="+";F[119]="+";F[120]="|";(function b(){var d={128:199,129:252,130:233,131:226,132:228,133:224,134:229,135:231,136:234,
137:235,138:232,139:239,140:238,141:236,142:196,143:197,144:201,145:230,146:198,147:244,148:246,149:242,150:251,151:249,152:255,153:214,154:220,155:162,156:163,157:165,158:8359,159:402,160:225,161:237,162:243,163:250,164:241,165:209,166:170,167:186,168:191,169:8976,170:172,171:189,172:188,173:161,174:171,175:187,176:9617,177:9618,178:9619,179:9474,180:9508,181:9569,182:9570,183:9558,184:9557,185:9571,186:9553,187:9559,188:9565,189:9564,190:9563,191:9488,192:9492,193:9524,194:9516,195:9500,196:9472,
197:9532,198:9566,199:9567,200:9562,201:9556,202:9577,203:9574,204:9568,205:9552,206:9580,207:9575,208:9576,209:9572,210:9573,211:9561,212:9560,213:9554,214:9555,215:9579,216:9578,217:9496,218:9484,219:9608,220:9604,221:9612,222:9616,223:9600,224:945,225:223,226:915,227:960,228:931,229:963,230:181,231:964,232:934,233:920,234:937,235:948,236:8734,237:966,238:949,239:8745,240:8801,241:177,242:8805,243:8804,244:8992,245:8993,246:247,247:8776,248:176,249:8729,250:183,251:8730,252:8319,253:178,254:9632,
255:160};for(var c=128;c<256;c++)F[c]=String.fromCharCode(d[c])})();var Hb=[true,true,false,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false];var Gb=[true,false,false,true,false,false,false,false,false,false,false,false,true,false,false,false,false,false,false,false,false,false,false,false,true,false,false,false,false,false,
false,true,true,false,false,false,false,false,false,false,false];var Na=[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false];var Oa=[false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,
false,false,false,false,false,false,false,false,false,false];var ya=new Array(256);var db=[0,5,7,8,9,10,11,12,13,14,15,17,19,24,26,27,127,132,133,136,141,142,143,144,155,156,157,158,159];for(X=0;X<256;X++)ya[X]=false;for(var Ca=0;Ca<db.length;Ca++)ya[db[Ca]]=true;var Z=new jb(4194304);this.running=function(){return E};this.getHistory=function(){return V};var g=this;var m=null;var h=hi5.tool.queryToObj(n.substring(n.indexOf("?")+1));if(!w)w=window.innerWidth;w-=y;h.width=w;n+="&width="+w;if(!x)x=window.innerHeight;
x-=y;h.height=x;n+="&height="+x;if(!h.fontSize){h.fontSize=13;n+="&fontSize="+13}else h.fontSize=parseInt(h.fontSize,10);this.server=h["server"];this.port=h["port"]?parseInt(h["port"],10):23;var H=["black","red","green","yellow","blue","magenta","cyan","white","gray","violet"];var M=Ea(w,x);var f=M.getContext();var S;var oa=new fb;if(G.displayMsg!=undefined)this.displayMsg=G.displayMsg;if(G.reconnectTimes!=undefined)this.reconnectTimes=G.reconnectTimes;if(G.openLink!=undefined)this.openLink=G.openLink;
if(G.setTitle!=undefined)this.setTitle=G.setTitle;if(typeof G.useWSS=="boolean")n=(G.useWSS?"wss":"ws")+n.substring(n.indexOf("://"));this.getURL=function(){return n};this.setJoinMode=function(b){if(!E)return;m.send("8E1"+b)};this.refuseControl=function(b){if(!E)return;m.send("8E3"+b)};this.giveControl=function(b){if(!E)return;m.send("8E4"+b)};this.requestControl=function(){if(!E)return;m.send("8E2")};this.play=function(){m.send("F3")};this.pause=function(){m.send("F2")};this.scan=function(b){m.send("F4"+
(b?"1":"0"))};this.seek=function(b){if(z&&E){m.send("F4"+(b?"1":"0")+"\t"+(b/z.getScale()|0));M.pause(true)}};var Ja=0;this.run=function(){kb()};this.hide=function(){if(!z)return;if(document.getElementById("cursorID").style.display=="block")document.getElementById("cursorID").style.display="none";z.hide()};this.showMessage=function(b){if(!g.displayMsg||!b)return;hi5.notifications.notify({"msg":b})};this.close=function(){if(m&&E)try{m.send("85");m.close()}catch(b){}else ia()};if(!hi5.browser.isChromeApp)window.addEventListener("unload",
ia,false);else chrome.runtime.onSuspend.addListener(ia);var Ma=false;var Eb=false;var R=null;y=5;var p=y;var r=5;var l=0;var k=0;var L=h.fontName||"Courier New";if(L.indexOf(" ")>0)L='"'+L+'"';var D=h.fgColor||H[7];var B=h.bgColor||H[0];var K=0;var $a=8;var Q="";var U="";var q=0;var e=18;var ea=0;var J="";var ta=false;var Y=0;var C=0;var T=1;var O=24;var ja=0;var Ka=true;var Wb=new Ha(1024,function d(c){var e=true;for(var f=0;e;){f=c.getByte();if(f<0)break;if(f==255)yb(c);else La(f);if(c.getPosition()>=
c.getEnd()){if(J!="")ua(J);e=false}}});Z.setHandler(Wb);var Sb=new Array;this.addSurface=function(d){z=d;if(cb)d.setPlayerMode();M.setContext(z.context);f=M.getContext();S=f.canvas;d.forceTextArea=true;d.setAutoScale(g.mode>0);d.setSize(w+y,x+y);d.setController(oa);d.setFastCopy(ma(h["fastCopy"]));d.setTouchpad(ma(h["touchpad"]));d.setClipboard(ma(h["mapClipboard"]));d.run(99997,false,true);d.onclipdata=Tb};var Xb=new Uint8Array(6);Xb[0]=5;var Yb=new Uint8Array(8);Yb[0]=4;this.writeText=la;this.writeRawInput=
function(d){if(!qa)return;var c=parseInt(d.substring(0,2),16);var e=d.substring(2).split("\t");var f=0;var h=false;switch(c){case 128:var k=e[2];if(k==2)Vb();return;case 129:return;case 130:return;case 131:return;case 132:f=parseInt(e[1]);h=e[0]==0;la(Da.process(h,f,0));return;case 139:f=parseInt(e[1]);h=e[0]==0;la(Da.process(h,f,1));return;case 134:la(Da.process(true,e[0],3));return}svGlobal.logger.warn("Unknowncode: "+e[1]+" type:"+c)};var Da=new function(d,c,e){var f=false;var h=false;var k=false;
this.process=function(c,d,e){if(e==3)return d;if(e==0){switch(d){case 29:case 157:f=c;return"";case 56:case 56|128:h=c;return"";case 42:case 54:k=c;return""}if(c){var g="";switch(d){case 28:g="\r\n";break;case 200:g="\u001b[A";break;case 208:g="\u001b[B";break;case 205:g="\u001b[C";break;case 203:g="\u001b[D";break;case 59:g="\u001bOP";break;case 60:g="\u001bOQ";break;case 61:g="\u001bOR";break;case 62:g="\u001bOS";break;case 63:g="\u001bOt";break;case 64:g="\u001bOu";break;case 65:g="\u001bOv";break;
case 66:g="\u001bOI";break;case 67:g="\u001bOw";break;case 68:g="\u001bOx";break;case 15:g="\t";break;case 209:g="\u001b[6~";break;case 201:g="\u001b[5~";break;case 199:g="\u0001";break;case 207:g="\u0005";break;case 14:g=k?"\b":"\u007f";break;case 211:g="\u001b[3~";break;case 197:g="\u00ff\u00f3";break;case 210:g="\u001b[2~";break;case 1:g="\u001b";break;default:console.log("Invalid code:"+d);return""}if(h)g="\u001b"+g;return g}else return""}if(e==1)if(f)if(d>64&&d<91)return String.fromCharCode(d-
64);else switch(d){case 54:return"\u001e";case 219:return"\u001b";case 220:return"\u001c";case 221:return"\u001d";case 32:return"\x00";case 192:return"\u001e";case 191:return"\u001f";default:console.log("Invalid key code:"+d);return""}if(h)return"\u001b"+String.fromCharCode(d).toLowerCase()}}};
