var svManager={getInstance:function(){var n=window.$telnet;return n&&n.running&&n.running()?n:null}};function connvertServer(n){var v={};v.id=n.id;v.server=n.id;v.displayName=n.displayName||n.id;if(n=n.vnc)for(var x in n)v[x]=n[x];return v}
svGlobal.TELNET=function(n,v,x){function Ka(a,c){var d=[],f=null,m=new hi5.graphic.Rectangle(0,0,0,0),k="Uint8ClampedArray"in window;this.width=a;this.height=c;var g=!1,h=this;this.pause=function(a){g=a};this.release=function(){d=f=h=null};this.isPaused=function(){return g};this.setContext=function(a){a!=f&&(f||!a||a.createImageData(1,1).data.buffer||(k=!1),f=a)};this.getContext=function(){return f};this.resize=function(f,m){for(var k=0;k<m;k++)d[k]=new Uint32Array(f);h.width=a=f;h.height=c=m};h.resize(a,
c);this.getBuffer=function(){return d};this.setRGB=function(a,c,f){d[c][a]=f|4278190080};this.getRGB=function(a,c){return d[c][a]};this.setRGBs=function(a,c,f,m,k,g,h){var e=0,l=0;f=a+f;m=c+m;for(var p=d,n=c;n<m;n++,g+=h)for(l=g,c=p[n],e=a;e<f;e++)c[e]=k[l++]};this.moveArea=function(a,c,f,m,k,g){if(0<g){k=a+k;g=c+g;var h=d,e,l,n;for(e=m-1;0<=e;e--)for(l=h[g+e],n=h[c+e],m=0;m<f;m++)l[k+m]=n[a+m]}else if(0>g){k=a+k;g=c+g;var h=d,p;for(l=0;l<m;l++)for(n=h[g+l],p=h[c+l],e=0;e<f;e++)n[k+e]=p[a+e]}else if(0<
k)for(k=a+k,g=c+g,h=d,--f;0<=f;f--)for(l=k+f,n=a+f,e=0;e<m;e++)h[g+e][l]=h[c+e][n];else for(k=a+k,g=c+g,h=d,e=0;e<f;e++)for(n=k+e,p=a+e,l=0;l<m;l++)h[g+l][n]=h[c+l][p]};this.getRGBs=function(a,c,f,m){var k=_Uint32Array(f*m);k[0]=0;var g=d;f=a+f;m=c+m;for(var e=0,h=c;h<m;h++)for(c=a;c<f;c++)k[e++]=g[h][c];return k};this.repaint=function(m,g,e,h){if(f){0>m&&(e+=m,m=0);0>g&&(h+=g,g=0);m+e>a&&(e=a-m);g+h>c&&(h=c-g);var l=f.createImageData(e,h),n=l.data;e=m+e;h=g+h;var p=0,na=d;if(k)for(var n=new Uint32Array(n.buffer),
q,r=g;r<h;r++)for(q=m;q<e;q++)n[p++]=na[r][q];else for(var t,u,r=g;r<h;r++)for(q=m;q<e;q++)t=na[r][q],u=p<<2,n[u]=t&255,n[u+1]=t>>8&255,n[u+2]=t>>16&255,n[u+3]=255,p++;f.putImageData(l,m,g)}};this.postPaint=function(a,c,f,d){0<m.width?m.union(a,c,f,d):(m.x=a,m.y=c,m.width=f,m.height=d)};this.commitPaint=function(){0<m.width&&(this.repaint(m.x,m.y,m.width,m.height),m.width=0)};this.fillRect=function(a,c,f,m,g){var e=d;f=a+f;m=c+m;for(var h=c;h<m;h++)for(c=a;c<f;c++)e[h][c]=g}}function oa(a,c){I?I.resize(a,
c):I=new Ka(a,c);return I}function pa(){var a=n.indexOf("://"),c=n.substring(a+3),a=c.indexOf("/");0<a&&(c=c.substring(0,a));return location.protocol+"//"+c}function La(a){return sessionId?hi5.browser.httpGet(pa()+"/CLIP?s="+sessionId+"&t="+(new Date).getTime(),!1):""}function Ma(){this.ws=null;this.setJoinMode=g.setJoinMode;this.requestControl=g.requestControl;this.writeKeyComb=g.writeKeyComb;this.getAppMode=function(){return g.mode};this.send=function(a){"891"!=a&&D&&this.ws.send(a)};this.sendInput=
function(a){g.writeRawInput(a);if(g.onactivity)g.onactivity(a)};var a=null;this.getAppInfo=function(){return g.sessionInfo.appInfo};this.onresize=function(c){if(c=c.target.svSurface){c=c.getFreeSpace();var d=c.width,f=c.height;hi5.browser.isTouch||hi5.browser.isOpera||!D||(c=function(){aa(d,f);q.send("D9"+E+"\t"+Q)},a&&(clearTimeout(a),a=null),a=setTimeout(c,200))}};this.onorientationchange=function(a){};this.getClipData=La;this.onfocus=function(a){};this.fileCallback=[];this.getShareFiles=function(a,
d){loggedin&&(this.ws.send("3A5"+a),this.fileCallback.push(d))};this.notifyFiles=function(a){for(var d=this.fileCallback,f=0,m=d.length;f<m;f++)d[f](a)};this.getFile=function(a){window.open(g.getFileUrl(a))};this.removeFile=function(a){uploadMgr&&uploadMgr.fileService.remove(a)};this.getFileLink=function(a){return pa()+"/DOWNLOAD?s="+sessionId+"&f="+a};this.getGateway=function(){return n};this.reconnect=function(a,d,f){}}function ca(a){return"on"==a||"true"==a}function qa(a,c,d){this.need=a;this.handler=
c;this.repeat=d||1}function Na(a){var c=0,d=0,f=new Uint8Array(a),m=this,g=new qa(0,null,0);this.release=function(){m=f=g=null};this.getHandler=function(){return g};this.getData=function(){return f};this.getPosition=function(){return c};this.setPosition=function(a){c=a};this.getEnd=function(){return d};this.set=function(a,m,g){f=a;c=m;d=g};this.handle=function(){g.handler(m,g)};this.setHandler=function(a){a&&1>a.need&&svGlobal.logger.warn("need < 1");(g=a)&&d-c>=a.need&&a.handler(m,a)};this.getByte=
function(){return f[c++]};this.peekByte=function(){return f[c]};this.getBE32=function(){return f[c++]<<24|f[c++]<<16|f[c++]<<8|f[c++]};this.getBE16=function(){return f[c++]<<8|f[c++]};this.skip=function(a){c+=a};this.skipBack=function(a){c-=a};this.getBytes=function(a,d){if(d)for(var m=0;m<a;m++)d[m]=f[c++];else return m=c,c+=a,f.subarray(m,c)};this.copyToByteArray=function(a,c,d,m){hi5.Arrays.arraycopy(f,d,a,c,m)}}function Oa(){if(!D){ra();if(da)q=da;else{var a=hi5.tool.replaceQuery(n,"pwd","x"),
c=hi5.browser.binaryWS();c&&(a+="&binary=on");var d=window.opener;if(d){c=null;try{c=d.__sparkUser}catch(f){}c&&(d=c.account,c=c.session,d&&(a+="&account="+d),c&&(a+="&session="+c))}c=hi5.browser.isChrome&&hi5.browser.isDesktop;q=new WebSocket(a+("&pasteCap="+(c?3:0)),"telnet");q.binaryType="arraybuffer"}ea.ws=q;svGlobal.logger.info(n);q.onopen=Pa;void 0!=p.recording&&"on"==p.recording&&Qa(p);q.onmessage=function(a){a=a.data;if("string"!=typeof a){var c=new Uint8Array(a);null!=J&&J.add(new RecordingObj(c,
0,a.byteLength));V.set(c,0,a.byteLength);V.handle()}else{var c=parseInt(a.substring(0,2),16),d=a.substring(2);switch(c){case 26:c=d;a=JSON.parse(c);if(a.name){svGlobal.logger.info("msg="+c);if(g.onerror)g.onerror(a);c=__svi18n.errorCode["S"+a.name]||"";c+=a.message;g.showMessage(c)}else 0<svGlobal.log&&console.erro("No error code for message:"+c);break;case 27:0!=hi5.appcfg.drawLicense&&(C.drawLicense(d),sa(p.fontSize));break;case 56:c=a=JSON.parse(d);sessionId=a.session;c.server=g.server;if(d=hi5.$("joinSelect"))d.value=
c.joinMode;if(d=hi5.$("requestControl"))d.disabled=c.hasControl;var d=hi5.appcfg.page&&hi5.appcfg.page.joinssh||"jointelnet.html",d=location.protocol+"//"+location.host+"/"+d+"?id="+a.numericId,e=a.webAddress;if(e&&0<e.length){var h=e.indexOf("://"),e=e.substring(h+3),h=e.indexOf("/");0<h&&(e=e.substring(0,h));e.toLowerCase()!=location.host.toLowerCase()&&(d+="&gateway="+e)}c.joinLink=d;g.sessionInfo.appInfo=c;a.ver&&a.ver!=svGlobal.version&&svGlobal.logger.warn("Client:"+svGlobal.version+" server:"+
a.ver);if(g.onsessionstart)g.onsessionstart(g.sessionInfo);break;case 59:break;case 61:a=JSON.parse(d);switch(a.type){case 0:p.fontSize=parseInt(a.fontSize);v=a.width;x=a.height;ra();C.setAutoScale(!0);aa(v+y,x+y);if(c=a.server)g.server=a.server,g.setTitle&&(document.title=p.displayName||g.server);ta=a.length;if(g.onopened)g.onopened(a);break;case 1:a=a.duration;if(g.onprogress)g.onprogress(a,ta);break;case 2:2==a.status?D=!0:(c=0==a.status,I.pause(c),a.warn&&g.showMessage(c?__svi18n.info.sessionPaused:
__svi18n.info.sessionResumed))}break;case 62:Ra(d);break;default:svGlobal.logger.warn("@TODO:"+a+"\n")}}};q.onclose=ba;q.onerror=Sa;aa(v,x)}}function Qa(a){J=new RecordingManager;var c=a.server;a={name:c,width:a.width,height:a.height,color:a.fontSize,namesuffix:".telnetv",filetag:"TELV",duration:0};J.setHeader(a)}function Ra(a){var c=parseInt(a.substring(0,1),16),d,f;d=a.substring(1);a=!1;var e=g.sessionInfo.appInfo;switch(c){case 1:f=JSON.parse(d);g.onsessionjoin&&(a=g.onsessionjoin(f));if(a)break;
g.showMessage(__svi18n.info.joinsession.applyArgs([f.numericId,f.__ip,f.name]));break;case 2:f=JSON.parse(d);g.onsessionexit&&(a=g.onsessionexit(f));if(a)break;g.showMessage(__svi18n.info.exitsession.applyArgs([f.numericId,f.__ip,f.name]));break;case 3:f=JSON.parse(d);e.joinMode!=f.mode&&(e.joinMode=f.mode,d=hi5.$("joinSelect"))&&(d.value=f.mode);if(e.hasControl)break;C.setReadOnly(!1);if(d=hi5.$("requestControl"))d.disabled=!0;g.ongivecontrol&&(a=g.ongivecontrol());if(a)break;g.showMessage(__svi18n.info.givecontrol);
break;case 4:C.setReadOnly(!0);e.hasControl=!1;if(d=hi5.$("requestControl"))d.disabled=!1;g.ontakebackcontrol&&(a=g.ontakebackcontrol());if(a)break;g.showMessage(__svi18n.info.nocontrol);break;case 5:c=function(){g.refuseControl(f.numericId);this.destroy()};e=function(){g.giveControl(f.numericId);this.destroy()};f=JSON.parse(d);g.onrequirecontrol&&(a=g.onrequirecontrol(f));if(a)break;a=__svi18n.info.title.applyArgs([f.name,f.numericId,f.__ip]);hi5.notifications.notify({title:a,msg:__svi18n.info.recontrol,
cbYes:e,cbNo:c});break;case 6:C.setTouchRemoting(!0);break;case 7:f=JSON.parse(d);f.cols&&f.rows&&(a=t*f.cols+2*y,d=h*f.rows+2*y,I=oa(a,d),aa(a,d));break;case 8:f=JSON.parse(d);if(g.onrequestcredential&&g.onrequestcredential(f))break;C.requestCredential(f);break;case 11:c=function(){g.allowJoin(f.numericId,!1);this.destroy()};e=function(){g.allowJoin(f.numericId,!0);this.destroy()};f=JSON.parse(d);g.onrequirejoin&&(a=g.onrequirejoin(f));if(a)break;a=__svi18n.info.title.applyArgs([f.name,f.numericId,
f.__ip]);hi5.notifications.notify({title:a,msg:__svi18n.info.reqjoin,cbYes:e,cbNo:c})}}function Pa(a){svGlobal.logger.info("opened...");D=!0;q.send("87"+navigator.userAgent);if(g.onopen)g.onopen()}function Sa(a){svGlobal.logger.warn(a)}function ba(a){svGlobal.logger.warn("closed ...");M&&(M.style.display="none");fa=D=!1;if(g&&g.onclose)g.onclose();try{null!=J&&(J.exit(),J=null),C&&C.close(),O&&O.visible()&&(O.dismiss(),O=null)}catch(c){}V&&(V.release(),V=null);k=null;q&&(q.onopen=null,q.onmessage=
null,q.onclose=null,q=q.onerror=null);g=C=ea=null;window&&window.$telnet&&(window.$telnet=null);null!=J&&(J.exit(),J=null)}function sa(a,c){c||(c="Courier New");k.font=a+"px "+c}function aa(a,c){var d=a-y,f=c-y,e=Math.floor(f/h),g=Math.floor(d/t),l=null;if(D)var l=Math.min(g*t+y,E*t+y),n=Math.min(e*h+y,Q*h+y),l=k.getImageData(0,0,l,n);v=d;x=f;C.setSize(a,c);sa(p.fontSize);ua();l&&k.putImageData(l,0,0);Q=e;E=g;H=Math.floor(x/h)}function ra(){M||(ua(),l=r,e=u,10>p.fontSize&&(p.fontSize=10),12>=p.fontSize?
(h=p.fontSize+6,X=2):13<=p.fontSize&&18>p.fontSize?(h=p.fontSize+8,X=2):19<=p.fontSize&&25>p.fontSize?(h=p.fontSize+12,X=3):25<=p.fontSize&&(h=p.fontSize+16,X=4),k.font=p.fontSize+"px Courier New",t=k.measureText("X").width,H=parseInt(x/h),Q=parseInt(x/h),E=parseInt(v/t),remotectrl.style.cursor="text",M=document.getElementById("cursorID"),M.style.display="block",M.style.width=t+"px",M.style.height=h+"px",fa=!0)}function ua(){k.fillStyle="black";k.fillRect(0,0,k.canvas.width,k.canvas.height);k.fillStyle=
"white"}function va(a){var c="";w!=F||ga[a]?(""!=K&&wa(K),Ta(a)):ha?(c=G[a]||"",K=""!=c?K+c:K+String.fromCharCode(a)):K+=String.fromCharCode(a)}function ia(a){for(;!Ua;){var c=a.getByte();if(255==c&&(c=a.getByte(),240==c))break}}function W(a,c,d){q.send("D5"+a+"\t"+c+"\t"+(1==d?1:0));251==a?ja(c):252==a?ja(c):253==a?ka(c):254==a&&ka(c)}function ja(a){return 39>=a&&0<=a&&Va[a-0]}function ka(a){return 39>=a&&0<=a&&Wa[a-0]}function Ta(a){switch(a){case 0:case 24:return w=F,!1;case 26:return w=F,!1;case 5:return!1;
case 7:return!1;case 8:return l-=t,l<r&&(l=r),z(),!1;case 9:return a=(l-r)/t/xa,a=parseInt(1*a)+1,l=a*xa*t+r,l>=E*t&&(l=r,e+=h,R("\n")),z(),!1;case 13:return l=r,e>u+(H-1)*h&&(e=u+(H-1)*h),z(),!1;case 10:case 11:case 12:e+=h;R("\n");z();l>=E*t&&(l=r,e+=h,R("\n"));if(e>(H-1)*h+u){for(;e>(H-1)*h+u;)e-=h;z();a=k.getImageData(r,u+h,E*t,(H-1)*h);k.fillStyle="black";k.fillRect(r,u,E*t,H*h);k.putImageData(a,r,u);k.fillStyle="white"}return!1;case 15:return!1;case 14:return!1;case 17:case 19:return!1;case 27:return N=
"",w=la,!1;default:if(128<=a&&159>=a)return!1}switch(w){case F:return!0;case la:if("\\"==a)return!1;if(32<=a&&47>=a)return N+=String.fromCharCode(a),!1;if(32<=a&&126>=a||160<=a){null==N&&(N="");switch(a){case 48:"("==N&&(ha=!0);break;case 65:e-=h;z();break;case 66:"("==N&&(ha=!1);break;case "C":l+=t;z();break;case 68:""==N&&ya(1);z();break;case 72:l=r;e+=h;break;case 77:""==N&&za(1);break;case "P":w=F;w=Aa;break;case "Y":w=Ba;break;case "c":w=F;break;case 91:L="";w=F;w=Ca;break;case 93:w=F;w=Da;break;
case "^":w=F,w=Ea}w==la&&(w=F);return!1}return!0;case Ca:if(48<=a&&63>=a||32<=a&&47>=a)return L+=String.fromCharCode(a),!1;if(32<=a&&126>=a||160<=a){var c=a;a=null;null==L&&(L="");""!=L&&(a=L.split(";"));var d=0,d=0;switch(c){case 65:d=null!=a&&1<=a.length?parseInt(a[0]):1;e-=d*h;e<u&&(e=u);z();break;case 66:d=null!=a&&1<=a.length?parseInt(a[0]):1;c=e;e+=d*h;c=(e-c)/h;R("\n",0==c?1:c);z();break;case 67:d=null!=a&&1<=a.length?parseInt(a[0]):1;l+=d*t;z();break;case 68:d=null!=a&&1<=a.length?parseInt(a[0]):
1;l-=d*t;l<r&&(l=r);z();break;case 69:d=null!=a&&1<=a.length?parseInt(a[0]):1;c=e;e+=d*h;c=(e-c)/h;c=0==c?1:c;R("\n",c);l=r;z();break;case 70:d=null!=a&&1<=a.length?parseInt(a[0]):1;e-=d*h;e<u&&(e=u);l=r;z();break;case 72:case 102:null!=a?(1<=a.length&&(d=parseInt(a[0]),c=e,e=u+(d-1)*h,c=(e-c)/h,c=0==c?1:c,R("\n",c)),2<=a.length&&(d=parseInt(a[1])-1,l=r+d*t)):""==L&&(l=r,e=u);break;case 73:a=1<=a.length?parseInt(a[0]):1;l=r+8*a*t;break;case 74:null!=a&&1<=a.length?(a=parseInt(a[0]),1==a&&(k.fillStyle=
"black",k.fillRect(r,u,E*t,e-chart_height-u),k.fillRect(r,e,e-r,chart_height),k.fillStyle="white")):(k.fillStyle="black",k.fillRect(l,e,E*t-l+r,Q*h-e+u),k.fillStyle="white");break;case 75:null!=a&&1<=a.length?(a=parseInt(a[0]),1==a?ma(r,l):2==a&&ma(r,v+y),z()):ma(l,v+y);break;case 76:null!=a&&1<=a.length&&(d=parseInt(a[0]),za(d),z());break;case 77:null!=a&&1<=a.length&&(d=parseInt(a[0]),ya(d),z());break;case 80:d=null!=a&&1<=a.length?parseInt(a[0]):1;a=k.getImageData(l+d*t,e,v+y-l-d*t,h);k.fillStyle=
"black";k.fillRect(l,e,v+y-l,h);k.putImageData(a,l,e);k.fillStyle="white";z();break;case 88:d=null!=a&&1<=a.length?parseInt(a[0]):1;k.fillStyle="black";k.fillRect(l,e,d*t,h);k.fillStyle="white";break;case 109:if(null==a||0==a.length)k.font="normal "+p.fontSize+"px Courier New",S=0,T=7;else for(var c=a.length,f=d=0;f<c;f++)switch(d=1*a[f],d){case 0:k.font="normal "+p.fontSize+"px Courier New";S=0;T=7;break;case 1:k.font="bold "+p.fontSize+"px Courier New";break;case 4:break;case 5:k.font="italic "+
p.fontSize+"px Courier New";break;case 7:k.font="normal "+p.fontSize+"px Courier New";S=7;T=0;break;case 22:k.font="normal "+p.fontSize+"px Courier New";S=0;T=7;break;case 24:break;case 25:k.font="italic "+p.fontSize+"px Courier New";break;case 27:k.font="normal "+p.fontSize+"px Courier New";S=7;T=0;break;default:30<=a[f]&&39>=a[f]?T=a[f]-30+1:40<=a[f]&&49>=a[f]&&(S=a[f]-40+1)}break;case 114:null!=a&&2<=a.length&&(c=parseInt(a[0]),a=parseInt(a[1]),P=c,H=a)}w=F;return!1}return!0;case Aa:case Da:case Ea:case Xa:return 48<=
a&&63>=a||32<=a&&47>=a?!1:32<=a&&126>=a||160<=a?(w=Fa,!1):!0;case Fa:return 32<=a&&126>=a||160<=a?!1:!0;case Ba:return w=Ga,!1;case Ga:return w=F,!1;default:return w=F,!1}}function ma(a,c){k.fillStyle="black";k.fillRect(a,e,c-a,h);k.fillStyle="white"}function za(a){var c=k.getImageData(r,u+(P-1)*h,E*t,(H-P-a+1)*h);k.fillStyle="black";k.fillRect(r,u+(P-1)*h,E*t,h*a);k.putImageData(c,r,u+(P+a-1)*h);k.fillStyle="white"}function ya(a){var c=k.getImageData(r,(P+a-1)*h+u,E*t,(H-P-a+1)*h);k.fillStyle="black";
k.fillRect(r,(H-a)*h+u,E*t,a*h);k.putImageData(c,r,(P-1)*h+u);k.fillStyle="white"}function wa(a){var c=a.length;e+h>x&&(e=(Q-1)*h+u);k.fillStyle=Ha[S];k.fillRect(l,e,t*c,h);k.fillStyle=Ha[T];k.fillText(a,l,e+h-3*X);l+=k.measureText(a).width;R(a);z();K=""}function z(){M.style.top=e+"px";M.style.left=l+"px"}function Ya(a){if(D)return(a=a.getData("text/plain"))?(a=a.replace(/\r\n/g,"\n"),U(0,a,3),!0):!1}function Za(){O&&Y&&!O.visible()&&(Y.value=Z,O.show(),setTimeout(function(){Y.scrollTop=Y.scrollHeight},
10))}function R(a,c){if(O)if(c)for(var d=0;d<c;d++)Z+=a;else Z+=a}function U(a,c,d){q.send("8B"+d+"\t"+c)}sessionStorage&&sessionStorage.clear();hi5.appcfg.copyDialog=!0;var Y=document.getElementById("copytextarea"),O=Y?new hi5.Lightbox(document.getElementById("copydialog")):null,Z="";this.displayMsg=!0;this.reconnectTimes=0;this.setTitle=this.openLink=!0;this.mode=0;var da="object"==typeof n?n:null,Ia="object"==typeof n||0<n.indexOf("/PLAY?");Ia?(this.mode=1,da&&(n=""),n+="&touchpad=on"):0<n.indexOf("/JOIN?")&&
(this.mode=2,this.reconnectOnResize=!1);this.sessionInfo={major:0,minor:0,width:0,height:0,bpp:0,bigEndian:!0,trueColor:!0};var C=null,D=!1,fa=!1,y=5,J=null;window.$telnet=this;for(var F=0,la=27,Ca=155,Aa=144,Da=157,Ea=158,Xa=159,Fa=160,Ba=161,Ga=162,G=[],B=0;127>B;B++)G[B]=String.fromCharCode(B);G[106]="+";G[107]="+";G[108]="+";G[109]="+";G[110]="+";G[113]="_";G[116]="+";G[117]="+";G[118]="+";G[119]="+";G[120]="|";for(var Wa=[!0,!0,!1,!0,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,
!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1],Va=[!0,!1,!1,!0,!1,!1,!1,!1,!1,!1,!1,!1,!0,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!1,!0,!1,!1,!1,!1,!1,!1,!0,!0,!1,!1,!1,!1,!1,!1,!1,!1],ga=Array(256),A=[0,5,7,8,9,10,11,12,13,14,15,17,19,24,26,27,127,132,133,136,141,142,143,144,155,156,157,158,159],B=0;256>B;B++)ga[B]=!1;for(B=0;B<A.length;B++)ga[A[B]]=!0;var V=new Na(4194304);this.running=function(){return D};var g=this,q=null,p=hi5.tool.queryToObj(n.substring(n.indexOf("?")+1));v||(v=window.innerWidth);
v-=y;p.width=v;n+="&width="+v;x||(x=window.innerHeight);x-=y;p.height=x;n+="&height="+x;p.fontSize?p.fontSize=parseInt(p.fontSize,10):(p.fontSize=13,n+="&fontSize=13");this.server=p.server;this.port=p.port?parseInt(p.port,10):23;var Ha="black red green yellow blue magenta cyan white gray violet".split(" "),I=oa(v,x),k=I.getContext(),ea=new Ma;hi5.appcfg&&(A=hi5.appcfg,B="undefined",typeof A.displayMsg!=B&&(this.displayMsg=A.displayMsg),typeof A.reconnectTimes!=B&&(this.reconnectTimes=A.reconnectTimes),
typeof A.openLink!=B&&(this.openLink=A.openLink),typeof A.setTitle!=B&&(this.setTitle=A.setTitle),"boolean"==typeof A.useWSS&&(n=(hi5.appcfg.useWSS?"wss":"ws")+n.substring(n.indexOf("://"))));this.getURL=function(){return n};this.setJoinMode=function(a){D&&q.send("8E1"+a)};this.refuseControl=function(a){D&&q.send("8E3"+a)};this.giveControl=function(a){D&&q.send("8E4"+a)};this.requestControl=function(){D&&q.send("8E2")};this.play=function(){q.send("F3")};this.pause=function(){q.send("F2")};this.scan=
function(a){q.send("F4"+(a?"1":"0"))};this.seek=function(a){C&&D&&(q.send("F4"+(a?"1":"0")+"\t"+(a/C.getScale()|0)),I.pause(!0))};var ta=0;this.run=function(){Oa()};this.hide=function(){C&&("block"==document.getElementById("cursorID").style.display&&(document.getElementById("cursorID").style.display="none"),C.hide())};this.showMessage=function(a){g.displayMsg&&a&&hi5.notifications.notify({msg:a})};this.close=function(){if(q&&D)try{q.send("85"),q.close()}catch(a){}else ba()};hi5.browser.isChromeApp?
chrome.runtime.onSuspend.addListener(ba):window.addEventListener("unload",ba,!1);var Ja=!1,Ua=!1,M=null,r=y=5,u=5,l=0,e=0,T=7,S=0,w=0,xa=8,L="",N="",t=0,h=18,X=0,K="",ha=!1,Q=0,E=0,P=1,H=24,A=new qa(1024,function(a){for(var c=!0;c;){b=a.getByte();if(0>b)break;if(255==b)a:{var d=a,f=d.getByte();switch(f){case 255:va(f);break;case 254:case 253:case 252:case 251:var e=d.getByte(),d=f;253!=d||ja(e)?251!=d||ka(e)?254==d?W(252,e,!1):252==d?W(254,e,!1):253==d?(W(251,e,!1),31==e?q.send("D9"+E+"\t"+Q):12==
e&&q.send("D7")):251==d&&W(253,e,!1):W(254,e,!0):W(252,e,!0);break;case 250:e=d.getByte();switch(e){case 24:e=d.getByte();ia(d);if(1!=e)break;q.send("DA");break;case 32:e=d.getByte();ia(d);if(1!=e)break;q.send("DC");break;default:ia(d)}break;default:break a}Ja||(Ja=!0,q.send("D0"))}else va(b);a.getPosition()>=a.getEnd()&&(""!=K&&wa(K),c=!1)}});V.setHandler(A);this.addSurface=function(a){C=a;Ia&&a.setPlayerMode();I.setContext(C.context);k=I.getContext();a.setAutoScale(0<g.mode);a.setSize(v+y,x+y);
a.setController(ea);a.setFastCopy(ca(p.fastCopy));a.setTouchpad(ca(p.touchpad));a.setClipboard(ca(p.mapClipboard));a.run(99997);a.onclipdata=Ya};A=new Uint8Array(6);A[0]=5;A=new Uint8Array(8);A[0]=4;this.writeRawInput=function(a){if(fa){var c=parseInt(a.substring(0,2),16);a=a.substring(2).split("\t");var d=0,e=!1;switch(c){case 128:c=a[2];2==c&&Za();return;case 129:return;case 130:return;case 131:return;case 132:0==a[0]?(d=parseInt(a[1]),e=0==a[0],U(e,d,0)):42==a[1]?U(0,42,2):29==a[1]&&U(0,29,2);
return;case 139:0==a[0]&&(d=parseInt(a[1]),e=0==a[0],U(e,d,1));return;case 134:d=a[0].charCodeAt(0);47==d?U(!0,191,1):U(0,a[0],3);return}svGlobal.logger.warn("Unknowncode: "+a[1]+" type:"+c)}}};
